Repository line/armeria, pull requests merged in 2018-12, with the labels that each got.

#1470 Rename `EventLoopGroups.serverChannelClass()` to `serverChannelType()`
  core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java
  core/src/main/java/com/linecorp/armeria/internal/TransportType.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
Labels: cleanup

#1472 Allow disabling default ClientFactory shutdown hook
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
Labels: new-feature

#1474 Fix endpoint group health check metrics register different tag problem.
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupMetrics.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: defect

#1458 Make armeria support retrofit 2.5
  dependencies.yml
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java
Labels: dependencies

#1466 Fix to add exampleHttpHeaders to the DocService debug page
  docs-client/package.json
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/lib/specification.tsx
  docs-client/yarn.lock
  licenses/web-licenses.txt
Labels: defect

#1478 Exception handlers handle an exception raised from a decorator
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceExceptionHandlerTest.java
Labels: improvement

#1483 Remove the usage of Retrofit `Java8CallAdapterFactory`
  benchmarks/build.gradle
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/downstream/DownstreamSimpleBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/upstream/UpstreamSimpleBenchmark.java
  dependencies.yml
  retrofit2/build.gradle
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryLargeStreamTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
  site/src/sphinx/client-retrofit.rst
Labels: cleanup, dependencies

#1481 Respect MAX_CONCURRENT_STREAMS on the client side
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSession.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
Labels: defect

#1488 Allow users to set additional trailers using ServiceRequestContext.
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
Labels: new-feature

#1484 Simplify decorator builder methods
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientDecorationBuilder.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClient.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
  site/src/sphinx/client-custom-http-headers.rst
  site/src/sphinx/client-decorator.rst
  site/src/sphinx/client-grpc.rst
  site/src/sphinx/client-retry.rst
  site/src/sphinx/client-thrift.rst
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpHeaderTest.java
  zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
Labels: deprecation, new-feature

#1486 Do not write a false log message from AnnotatedValueResolver
  core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java
Labels: defect

#1489 Respect HTTP/2 connection window size
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSession.java
  core/src/main/java/com/linecorp/armeria/internal/ChannelUtil.java
  core/src/main/java/com/linecorp/armeria/internal/InboundTrafficController.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
Labels: defect

#1480 Support Spring validation on annotated HTTP services
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java
  examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/HelloAnnotatedService.java
  examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/HelloConfiguration.java
  examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/ValidationExceptionHandler.java
  examples/spring-boot-webflux/src/test/java/example/springframework/boot/webflux/HelloApplicationIntegrationTest.java
Labels: defect

#1467 Determine a client address from Forwarded, X-Forwarded-For headers an…
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/server/ClientAddressSource.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogFormats.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogType.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpHeaderUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
  logback/src/main/java/com/linecorp/armeria/common/logback/BuiltInProperties.java
  logback/src/main/java/com/linecorp/armeria/common/logback/BuiltInProperty.java
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporter.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  site/src/sphinx/server-access-log.rst
Labels: new-feature

#1491 Update dependencies
  dependencies.yml
  spring/boot1-autoconfigure/build.gradle
Labels: dependencies

#1493 Fix an inaccessible link on doc
  site/src/sphinx/advanced-spring-webflux-integration.rst
Labels: documentation

#1492 Support Tomcat 9.0.14
  dependencies.yml
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/ConfigFileLoaderInitializer.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/ManagedTomcatService.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90ProtocolHandler.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
  tomcat8.0/build.gradle
  tomcat8.5/build.gradle
Labels: dependencies

#1494 Add CIDR based Predicate<InetAddress>
  core/src/main/java/com/linecorp/armeria/server/misc/Inet4AddressBlock.java
  core/src/main/java/com/linecorp/armeria/server/misc/Inet6AddressBlock.java
  core/src/main/java/com/linecorp/armeria/server/misc/InetAddressPredicates.java
  core/src/main/java/com/linecorp/armeria/server/misc/package-info.java
  core/src/test/java/com/linecorp/armeria/server/misc/InetAddressPredicatesTest.java
Labels: improvement

#1498 Move InetAddressPredicates and related classes to common package
  core/src/main/java/com/linecorp/armeria/common/util/Inet4AddressBlock.java
  core/src/main/java/com/linecorp/armeria/common/util/Inet6AddressBlock.java
  core/src/main/java/com/linecorp/armeria/common/util/InetAddressPredicates.java
  core/src/main/java/com/linecorp/armeria/server/misc/package-info.java
  core/src/test/java/com/linecorp/armeria/common/util/InetAddressPredicatesTest.java
Labels: cleanup

#1497 Fix a bug where a decorator chain is broken when using AnnotatedServi…
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
Labels: defect

#1496 Fix invalid annotations
  site/src/sphinx/server-annotated-service.rst
Labels: documentation

#1495 Add docs about getting an IP address of a client who initiated a request
  site/src/sphinx/server-basics.rst
Labels: documentation

#1499 Send 'content-length' header for an empty PUT/POST/PATCH request
  core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/client/Http1EmptyRequestTest.java
Labels: defect

#1500 Revert 'null' to 'Function.identity()' which was fixed by #1478
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceElement.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java
Labels: improvement

#1503 Update the outdated site document
  site/src/sphinx/client-circuit-breaker.rst
Labels: documentation

#1504 Marshall Status.cause between server and client for more structured e…
  grpc/src/main/java/com/linecorp/armeria/common/grpc/StatusCauseException.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcHeaderNames.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/proto/com/linecorp/armeria/grpc/debug.proto
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcStatusCauseTest.java
  site/src/sphinx/client-grpc.rst
  site/src/sphinx/server-grpc.rst
Labels: new-feature

#1508 Add ServerConfig.verboseResponses()
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Labels: new-feature
