Repository line/armeria, pull requests merged in 2018-09, with the labels that each got.

#1350 Abort a response stream immediately when a client aborts the stream
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerAbortingInfiniteStreamTest.java
  testing/src/main/java/com/linecorp/armeria/testing/server/ServerRule.java
Labels: defect

#1354 Handle `%26` and `%3D` in a query string correctly
  core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java
  core/src/test/java/com/linecorp/armeria/internal/PathAndQueryTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
Labels: defect

#1356 Add decodedPath() and decodedMappedPath() / Decode path params
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java
  core/src/main/java/com/linecorp/armeria/server/DefaultPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/PathMappingResult.java
  core/src/main/java/com/linecorp/armeria/server/PathMappingResultBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java
  core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/GlobPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/RegexPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/composition/CompositeServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java
  core/src/test/resources/com/linecorp/armeria/server/file/bar/¢.txt
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Labels: breaking-change, defect, new-feature

#1355 Use thread local when creating scopes off of the request context thread.
  zipkin/src/main/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContext.java
  zipkin/src/test/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContextTest.java
  zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
Labels: defect

#1358 Fix an assertion error caused by simultaneous `StartStopSupport.start()` or `stop()`
  core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
Labels: defect

#1357 Add AsyncMethodCallbacks which bridges the gap between CompletionStage and AsyncMethodCallback
  thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientInvocationHandler.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/AsyncMethodCallbacks.java
  thrift/src/test/java/com/linecorp/armeria/common/thrift/AsyncMethodCallbacksTest.java
Labels: new-feature

#1359 Update dependencies
  dependencies.yml
  it/spring/boot-tomcat8.5/build.gradle
  jetty/src/main/java/com/linecorp/armeria/server/jetty/ArmeriaConnector.java
Labels: dependencies

#1360 Ignore flaky test (HttpServerAbortingInfiniteStreamTest.shouldCancelI…
  core/src/test/java/com/linecorp/armeria/server/HttpServerAbortingInfiniteStreamTest.java
Labels: cleanup

#1362 Allow TAB, CR and LF in a query string
  core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java
  core/src/test/java/com/linecorp/armeria/internal/PathAndQueryTest.java
Labels: defect

#1364 Add missing notice about OpenSAML
  NOTICE.txt
Labels: documentation

#1365 Update dependencies
  core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogFormats.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedValueResolverTest.java
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  it/spring/boot-tomcat8.5/build.gradle
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporterBuilder.java
  thrift/src/main/java/com/linecorp/armeria/internal/thrift/ThriftFunction.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/ManagedConnectorFactory.java
  tomcat8.5/build.gradle
Labels: dependencies

#1363 Customize client options of HttpClient used in HttpHealthCheckedEndpointGroup
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupBuilder.java
Labels: new-feature

#1367 Fix wrong assert condition in AremriaCallFactoryTest
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
Labels: cleanup

#1369 Fix NPE in HttpRequestSubscriber.onSubscribe()
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
Labels: defect

#1371 Fix ByteBuf leaks in gRPC client and server
  build.gradle
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
Labels: defect

#1366 Add a ResponseConverterFunction for Publisher and RxJava Observable
  core/src/main/java/com/linecorp/armeria/internal/PublisherToHttpResponseConverter.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunctionProvider.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceResponseConverterTest.java
  rxjava/src/main/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunction.java
  rxjava/src/main/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionProvider.java
  rxjava/src/main/java/com/linecorp/armeria/server/rxjava/package-info.java
  rxjava/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.ResponseConverterFunctionProvider
  rxjava/src/test/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionProviderTest.java
  rxjava/src/test/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionTest.java
Labels: new-feature

#1373 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  spring/boot1-autoconfigure/build.gradle
Labels: dependencies
