Repository line/armeria, pull requests merged in 2018-07, with the labels that each got.

#1274 Upgrade gradle to 4.8.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#1277 Fix build errors on JDK 10
  .appveyor.yml
  .gitignore
  .travis.yml
  .travis/install-jdk.sh
  build.gradle
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/MetricCollectingCircuitBreakerListener.java
  dependencies.yml
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceUtils.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaMeterBindersConfigurationTest.java
Labels: defect, dependencies

#1280 Update dependencies
  dependencies.yml
  tomcat8.0/build.gradle
Labels: dependencies

#1281 Fix a bug where a RST frame for a non-existent stream can be sent
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/Http2ObjectEncoder.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: defect

#1285 Do not add HTTP port if TLS was enabled and no port was specified
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Labels: breaking-change, defect

#1284 Do not fail but warn when Optional and Default are used redundantly
  core/src/main/java/com/linecorp/armeria/server/AnnotatedElementNameUtil.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedValueResolverTest.java
Labels: improvement

#1287 Update Netty from 4.1.26 to 4.1.27
  dependencies.yml
Labels: dependencies

#1286 Fix a StackOverflowError when stopping a starting server or starting a stopping server
  core/src/main/java/com/linecorp/armeria/server/Server.java
Labels: defect

#1289 Do not use framed version of Javadoc
  site/src/sphinx/_extensions/api.py
  site/src/sphinx/client-grpc.rst
  site/src/sphinx/client-thrift.rst
  site/src/sphinx/server-access-log.rst
Labels: documentation

#1293 Remove Java6Assertions (use org.assertj.core.api.Assertions instead)
  core/src/test/java/com/linecorp/armeria/internal/metric/MicrometerUtilTest.java
  settings/checkstyle/checkstyle.xml
Labels: cleanup

#1291 Add the git checkout action to post-release-msg
  .post-release-msg
Labels: cleanup

#1290 Allow to register duplicated endpoints under HealthCheckedEndpointGroup
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: defect

#1295 Use OpenJDK 10 instead of Oracle JDK 10 for build stability
  .travis.yml
Labels: cleanup

#1297 Clean up logging related with TLS handshake failures
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
Labels: defect

#1299 Fix a bug where Endpoint.toString() does not include IP address
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Labels: defect

#1298 Add RejectedPathMappingHandler
  core/src/main/java/com/linecorp/armeria/server/RejectedPathMappingHandler.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
Labels: new-feature

#1303 Add Authorizer.orElse() / Use composition for HttpAuthService
  core/src/main/java/com/linecorp/armeria/server/auth/AuthFailureHandler.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthSuccessHandler.java
  core/src/main/java/com/linecorp/armeria/server/auth/Authorizer.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthorizerUtil.java
  core/src/main/java/com/linecorp/armeria/server/auth/HttpAuthService.java
  core/src/main/java/com/linecorp/armeria/server/auth/HttpAuthServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/auth/HttpAuthServiceImpl.java
  core/src/test/java/com/linecorp/armeria/server/auth/AuthorizerTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/HttpAuthServiceTest.java
Labels: breaking-change, new-feature

#1306 Add the first example project
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
  dependencies.yml
  examples/README.md
  examples/spring-boot-tomcat/build.gradle
  examples/spring-boot-tomcat/src/main/java/example/springframework/boot/tomcat/HelloConfiguration.java
  examples/spring-boot-tomcat/src/main/java/example/springframework/boot/tomcat/HelloController.java
  examples/spring-boot-tomcat/src/main/java/example/springframework/boot/tomcat/Main.java
  examples/spring-boot-tomcat/src/main/resources/config/application.yml
  examples/spring-boot-tomcat/src/main/resources/static/.gitkeep
  examples/spring-boot-tomcat/src/main/resources/templates/.gitkeep
  examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloControllerTest.java
  examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloIntegrationTest.java
  examples/spring-boot-tomcat/src/test/resources/application-testbed.yml
  settings.gradle
  settings/checkstyle/checkstyle-suppressions.xml
  settings/checkstyle/checkstyle.xml
Labels: documentation

#1305 issue 1252, GRPC exception status code to HTTP status code could be i…
  core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
  dependencies.yml
  grpc/build.gradle
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcStatusTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
Labels: defect

#1307 Expose context-aware Executor for easier tests
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
Labels: new-feature

#1310 Update dependencies
  build.gradle
  dependencies.yml
Labels: dependencies

#1309 add numMaxConnections Flag
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
Labels: new-feature

#1296 Make Armeria Retrofit subscriber not buffer response
  core/src/main/java/com/linecorp/armeria/common/CommonPools.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/BlockingCallSubscriber.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/PipeBuffer.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriber.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/SubscriberFactory.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryLargeStreamTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/BlockingCallSubscriberTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriberTest.java
Labels: improvement
