Repository line/armeria, pull requests merged in 2018-05, with the labels that each got.

#1177 Update dependencies
  dependencies.yml
Labels: dependencies

#1164 Support `List<String>` type for `@Header` annotation
  core/src/main/java/com/linecorp/armeria/internal/AnnotatedHttpServiceParamUtil.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java
  core/src/main/java/com/linecorp/armeria/server/annotation/BeanRequestConverterFunction.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
Labels: new-feature

#1179 Add 'apiplural' directive for referring to a type in plural form
  site/src/sphinx/_extensions/api.py
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/advanced-zookeeper.rst
Labels: documentation

#1181 Add PrometheusMeterRegistries.defaultRegistry
  core/src/main/java/com/linecorp/armeria/common/metric/PrometheusMeterRegistries.java
Labels: new-feature

#1180 Add documentation about client-side load balancing and service discovery
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/client-service-discovery.rst
  site/src/sphinx/client.rst
Labels: documentation

#1182 Fetches thrift service names using reflection not to access armeria-thrift package
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceUtils.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ThriftServiceUtilsTest.java
Labels: defect

#1184 Add gRPC example to DocService documentation
  site/src/sphinx/server-docservice.rst
Labels: documentation

#1187 Use Highlight.js instead of Pygments for syntax highlighting
  site/src/sphinx/_extensions/highlightjs.py
  site/src/sphinx/_extensions/parsed_literal_highlight.py
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/_templates/layout.html
  site/src/sphinx/conf.py
Labels: documentation

#1186 Make CorsService response headers compatible with IE
  core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
Labels: improvement

#1176 Add ability to config Timer and DistributionSummary with user defined…
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
  core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java
Labels: deprecation, new-feature

#1172 Split ActiveRequestMetrics from RequestMetric to support better metri…
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
Labels: breaking-change, new-feature

#1173 Provides a way to specify exception/request/response handlers in AnnotatedServiceRegitrationBean
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
Labels: new-feature

#1174 Register multiple decorators in service registration beans
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/HttpServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
Labels: deprecation, new-feature

#1190 Do not export '*.percentile' and '*.histogram' gauges to Dropwizard MetricRegistry
  core/src/main/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistries.java
  core/src/test/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistriesTest.java
Labels: defect

#1197 Update IntelliJ IDEA code style and inspection profile
  settings/intellij_idea/settings.jar
Labels: miscellaneous

#1196 Skip pending request counting at health check service
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/TransientService.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
Labels: defect, new-feature

#1192 Add CircuitBreakerStrategy
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreaker.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerConfig.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerStrategy.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/HttpStatusBasedCircuitBreakerStrategy.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
  core/src/main/java/com/linecorp/armeria/server/throttling/CircuitBreakerBasedThrottlingStrategy.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClientTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
  core/src/test/java/com/linecorp/armeria/server/throttling/CircuitBreakerBasedThrottlingStrategyTest.java
Labels: breaking-change, new-feature

#1199 Fix flakiness in DropwizardMetricsIntegrationTest
  thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
Labels: cleanup

#1203 Fix Javadoc links for Jetty and Dropwizard Metrics
  dependencies.yml
Labels: cleanup

#1204 Add unsafe gRPC buffer wrap option to client.
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: new-feature

#1194 Add RequestContext scope for RxJava operators
  dependencies.yml
  rxjava/build.gradle
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextAssembly.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableCompletable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableMaybe.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableObservable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableSingle.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCompletable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCompletableObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextConditionalSubscriber.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextConnectableFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextConnectableObservable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextMaybe.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextMaybeObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextObservable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextParallelFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableCompletable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableMaybe.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableObservable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableSingle.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextSingle.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextSingleObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextSubscriber.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/package-info.java
  rxjava/src/test/java/com/linecorp/armeria/common/rxjava/RequestContextAssemblyTest.java
  settings.gradle
Labels: new-feature

#1205 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  spring/boot1-autoconfigure/build.gradle
  tomcat8.0/build.gradle
  tomcat8.5/build.gradle
Labels: dependencies

#1209 Remove CircuitBreakerBasedThrottlingStrategy completely
  core/src/main/java/com/linecorp/armeria/server/throttling/CircuitBreakerBasedThrottlingStrategy.java
  core/src/test/java/com/linecorp/armeria/server/throttling/CircuitBreakerBasedThrottlingStrategyTest.java
Labels: breaking-change

#1212 Publish Tomcat8.5 project
  settings.gradle
Labels: dependencies

#1208 Add documentation about CircuitBreaker
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java
  site/src/sphinx/client-circuit-breaker.rst
  site/src/sphinx/client-retry.rst
Labels: documentation

#1214 Add more convenience methods to HttpData
  core/src/main/java/com/linecorp/armeria/common/HttpData.java
  core/src/test/java/com/linecorp/armeria/common/HttpDataTest.java
Labels: new-feature

#1217 Removes old dependencies via Brave 5
  dependencies.yml
  zipkin/build.gradle
  zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java
  zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java
Labels: dependencies

#1218 Fix a packaging issue where armeria-tomcat8.5 JAR contains no classes
  tomcat8.5/build.gradle
Labels: defect

#1191 Refactor annotated HTTP service
  core/src/main/java/com/linecorp/armeria/internal/AnnotatedHttpServiceParamUtil.java
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedBeanFactory.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedElementNameUtil.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceTypeUtil.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/annotation/BeanRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Default.java
  core/src/main/java/com/linecorp/armeria/server/annotation/RequestObject.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedBeanFactoryTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedElementNameUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactoryTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceRequestConverterTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedValueResolverTest.java
  core/src/test/java/com/linecorp/armeria/server/PrefixAddingPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/TestConverters.java
  core/src/test/java/com/linecorp/armeria/server/other/AnnotatedHttpServiceAccessModifierTest.java
  site/src/sphinx/server-annotated-service.rst
Labels: new-feature

#1220 Have DynamicEndpointGroup ignore updates that do not change the list …
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: defect

#1219 Rename the `status` tag to `httpStatus` in `MeterIdPrefixFunction.ofDefault()`
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
Labels: breaking-change

#1222 Inject `Cookie` header automatically
  core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Cookies.java
  core/src/main/java/com/linecorp/armeria/server/annotation/DefaultCookies.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedValueResolverTest.java
  site/src/sphinx/server-annotated-service.rst
Labels: new-feature

#1189 Provide a way to specify Netty ChannelOptions for Server
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Labels: new-feature

#1227 Add an example using CorsService in Grpc documentation
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  site/src/sphinx/server-grpc.rst
Labels: documentation

#1226 More sensible default DistributionStatisticConfig for Timer and Distr…
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
Labels: improvement

#1228 Add documentation - production checklist / Deprecate ClientFactoryBuilder.socketOption() over channelOption()
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  site/src/sphinx/advanced-production-checklist.rst
  site/src/sphinx/advanced.rst
  site/src/sphinx/client-circuit-breaker.rst
Labels: deprecation, documentation

#1229 Update dependencies
  build.gradle
  dependencies.yml
Labels: dependencies

#1230 Fix bugs where a resolved Endpoint is not handled correctly
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientDelegateTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientSniTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMappingTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: defect

#1232 Add more methods related with accessing IP addresses to Endpoint
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Labels: new-feature

#1233 More robust host name extraction in HttpClientDelegate
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientDelegateTest.java
Labels: improvement

#1234 Change to propagate the last Response while retry in some condition
  core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryGiveUpException.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
  site/src/sphinx/client-retry.rst
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: breaking-change, defect
