Repository line/armeria, pull requests merged in 2018-10, with the labels that each got.

#1377 Use MIME type base64 decoder for SAML messages
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java
  saml/src/main/java/com/linecorp/armeria/server/saml/HttpPostBindingUtil.java
  saml/src/main/java/com/linecorp/armeria/server/saml/HttpRedirectBindingUtil.java
  saml/src/main/java/com/linecorp/armeria/server/saml/KeyStoreCredentialResolverBuilder.java
Labels: defect

#1379 Allow specifying the `Executor` used for invoking `Server` start/stop callbacks
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Labels: new-feature

#1380 Update dependencies
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  dependencies.yml
Labels: dependencies

#1382 Add a flag `com.linecorp.armeria.annotatedServiceExceptionVerbosity`
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/annotation/DefaultExceptionHandler.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionHandlerFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionVerbosity.java
Labels: new-feature

#1384 Add JVM and Gradle options to gradle.properties
  .appveyor.yml
  .travis.yml
  gradle.properties
Labels: cleanup

#1385 Make gRPC downstream / upstream more consistent by disabling somewhat time-con…
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/downstream/DownstreamSimpleBenchmark.java
Labels: performance

#1391 Remove unnecessary firstFrame optimization.
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java
Labels: cleanup

#1390 Special-case marshalling of empty protos.
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java
Labels: performance

#1389 Allow configuring HTTP2 SETTINGS frame.
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
Labels: new-feature

#1387 `EmptyFixedStreamMessage.completionFuture()` should be succeeded afte…
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestSubscriberTest.java
Labels: defect

#1392 Handle GOAWAY frames correctly
  core/src/main/java/com/linecorp/armeria/client/ClosedClientFactoryException.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/ResponseTimeoutException.java
  core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java
  core/src/main/java/com/linecorp/armeria/client/WriteTimeoutException.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/HttpStatusBasedCircuitBreakerStrategy.java
  core/src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
  core/src/main/java/com/linecorp/armeria/common/ClosedSessionException.java
  core/src/main/java/com/linecorp/armeria/common/ContentTooLargeException.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbortedStreamException.java
  core/src/main/java/com/linecorp/armeria/common/stream/CancelledSubscriptionException.java
  core/src/main/java/com/linecorp/armeria/common/stream/ClosedPublisherException.java
  core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/Http2GoAwayListener.java
  core/src/main/java/com/linecorp/armeria/internal/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/GracefulShutdownSupport.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/RequestTimeoutException.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/client/Http2ClientSettingsTest.java
  core/src/test/java/com/linecorp/armeria/client/Http2GoAwayTest.java
  core/src/test/java/com/linecorp/armeria/internal/ConnectionLimitingHandlerIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/server/GracefulShutdownSupportTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Labels: defect, new-feature

#1393 Make more HTTP/2 settings configurable and make them consistent
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/client/Http2ClientSettingsTest.java
  core/src/test/java/com/linecorp/armeria/client/Http2GoAwayTest.java
Labels: breaking-change, defect, new-feature

#1394 Update dependencies / Make sure /dev/epoll and OpenSSL are used durin…
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
  dependencies.yml
  spring/boot1-autoconfigure/build.gradle
Labels: dependencies, new-feature

#1402 Do not treat a class as automatically-convertible bean if it has a me…
  core/src/main/java/com/linecorp/armeria/server/AnnotatedValueResolver.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedBeanFactoryTest.java
Labels: defect

#1403 Overall cleanup of HTTP/2 handlers / Do not send GOAWAY to a closed connection
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/Http2GoAwayHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  testing-internal/src/main/resources/logback-test.xml
Labels: cleanup, defect

#1400 Allow specifying injected docs scripts per request.
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServiceTest.java
Labels: new-feature

#1406 Fail with UnprocessedRequestException when writing first request head…
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
Labels: defect

#1404 Invalidate the cached if there is new file in HttpVfs
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java
Labels: defect

#1411 Add README for benchmarks / Add async-profiler support
  benchmarks/README.md
  benchmarks/build.gradle
  dependencies.yml
Labels: performance

#1414 Fix failures in HttpFileServiceTest
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java
Labels: cleanup

#1415 Fix a bug where RequestLog is not complete under certain circumstances
  core/src/main/java/com/linecorp/armeria/client/DefaultHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java
  thrift/src/main/java/com/linecorp/armeria/client/thrift/DefaultTHttpClient.java
Labels: defect

#1417 Don't rewrite the user's path if it is valid since it may be escaped.
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
Labels: defect

#1419 Upgrade spring-boot dependency to 2.1.0
  dependencies.yml
Labels: dependencies
