Repository line/armeria, pull requests merged in 2018-11, with the labels that each got.

#1422 Make Armeria builds on Java 11
  core/build.gradle
  gradle.properties
  settings.gradle
Labels: cleanup

#1425 Update dependencies
  dependencies.yml
  docs-client/build.gradle
  docs-client/package.json
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/lib/json-prettify.ts
  docs-client/webpack.config.ts
  docs-client/yarn.lock
Labels: dependencies

#1424 Reduce unnecessary event loop task queueing
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
Labels: performance

#1429 Reduce memory copies in `Http2ResponseDecoder` and gRPC
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageFramer.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframerTest.java
Labels: performance

#1427 Set RequestLog wall time in micros and use RequestLog timestamps for s…
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
  zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanContextUtil.java
  zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java
Labels: new-feature

#1430 Fix a build error on Windows
  dependencies.yml
  docs-client/build.gradle
Labels: cleanup

#1431 Make HttpHealthcheckEndpointGroup port customizable
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupBuilder.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: new-feature

#1434 Check for empty remote service name which isn't allowed.
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
Labels: defect

#1436 Do not use UnpooledByteBufAllocator
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
Labels: performance

#1440 Avoid using CompletableFuture.whenCompleteAsync()
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java
  core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java
  jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Labels: performance

#1439 Throw FileNotFoundException when KeyStoreCredentialResolverBuilder ca…
  saml/src/main/java/com/linecorp/armeria/server/saml/KeyStoreCredentialResolverBuilder.java
  saml/src/test/java/com/linecorp/armeria/server/saml/KeyStoreCredentialResolverBuilderTest.java
  saml/src/test/resources/keystore/test.jks
Labels: defect

#1444 Even less usage of CompletableFuture.whenComplete()
  benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/RpcResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/AsyncMethodCallbacks.java
Labels: cleanup

#1445 Add public methods for users to determine the channel type of an even…
  core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java
  core/src/main/java/com/linecorp/armeria/internal/TransportType.java
Labels: new-feature

#1449 Fix NPE in AbstractStreamMessageDuplicator
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
Labels: defect

#1423 Add logging of when the first bytes are written / read from a transpo…
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/NoopRequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogAvailability.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
  zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanContextUtil.java
  zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java
  zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java
  zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java
  zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
  zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
Labels: new-feature

#1452 Run TestNG and streaming tests with shaded classes
  core/build.gradle
Labels: cleanup

#1453 Update the project setup guide
  site/src/sphinx/setup-common.rst
  site/src/sphinx/setup-gradle.rst
  site/src/sphinx/setup-maven.rst
  site/src/sphinx/setup.rst
Labels: documentation

#1454 Update dependencies
  dependencies.yml
  it/spring/boot-tomcat8.5/build.gradle
  tomcat8.5/build.gradle
Labels: dependencies

#1455 Make one-way Thrift call responses sent early
  thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftCallService.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
Labels: defect

#1451 Add docs about SAML module
  core/src/main/java/com/linecorp/armeria/server/Server.java
  examples/README.md
  examples/saml-service-provider/build.gradle
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/Main.java
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/MyAuthHandler.java
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/MyService.java
  examples/saml-service-provider/src/main/resources/localhost.crt
  examples/saml-service-provider/src/main/resources/localhost.key
  examples/saml-service-provider/src/main/resources/sample.jks
  examples/saml-service-provider/src/test/java/example/armeria/server/saml/sp/.gitkeep
  examples/saml-service-provider/src/test/resources/.gitkeep
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlSingleSignOnHandler.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlUtil.java
  settings.gradle
  site/src/sphinx/advanced-saml.rst
  site/src/sphinx/server-annotated-service.rst
Labels: documentation

#1457 Update sphinx-gradle-plugin to 2.3.1
  dependencies.yml
Labels: documentation

#1459 Allow `reactor-netty` and `armeria-spring-boot-webflux-autoconfigure` to coexist
  examples/README.md
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/InjectionService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/ServerFactory.java
  examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedHttpServiceTest.java
  examples/spring-boot-tomcat/build.gradle
  examples/spring-boot-webflux/build.gradle
  examples/spring-boot-webflux/src/test/resources/logback-test.xml
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryAutoConfiguration.java
  spring/boot-webflux-autoconfigure/src/test/resources/logback-test.xml
Labels: improvement

#1461 Unescape grpc message description in client.
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: defect

#1463 Fix the wrong unit of response time
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
Labels: defect

#1465 Correct documentation on GrpcService's Protobuf-JSON support
  site/src/sphinx/server-grpc.rst
Labels: documentation
