Repository line/armeria, pull requests merged in 2018-02, with the labels that each got.

#1006 Remove ZooKeeperEndpointGroup#Mode
  site/src/sphinx/advanced-zookeeper.rst
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroup.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java
Labels: breaking-change

#998 Unwrap Future of RpcResponse to encode service response correctly
  core/src/main/java/com/linecorp/armeria/common/RpcResponse.java
  core/src/test/java/com/linecorp/armeria/common/RpcResponseTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThrottlingRpcServiceTest.java
Labels: defect

#1020 Don't notify the server listener of client closure if it will be noti…
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
Labels: defect

#1019 Set previously health-checked endpoints that don't exist anymore to f…
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupMetrics.java
Labels: defect

#1021 Add Nullable to RequestContext.mapCurrent
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
Labels: defect

#1012 Subscribe to pooled objects for client requests.
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
Labels: improvement, performance

#1015 Upgrade micrometer to 1.0.0
  core/src/main/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistries.java
  core/src/main/java/com/linecorp/armeria/common/metric/NoopMeterRegistry.java
  core/src/main/java/com/linecorp/armeria/common/metric/PrometheusMeterRegistries.java
  dependencies.yml
  spring-boot/autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaMeterBindersConfigurationTest.java
Labels: dependencies

#1018 Allow session protocol to be specified for HttpHealthCheckedEndpointG…
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupBuilder.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
  testing/src/main/java/com/linecorp/armeria/testing/server/ServerRule.java
Labels: new-feature

#1017 Allow overriding ':authority' header
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
Labels: improvement

#1024 Handle split headers in ArmeriaCallSubscriber
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallSubscriber.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallSubscriberTest.java
Labels: defect
