Repository line/armeria, pull requests merged in 2018-03, with the labels that each got.

#1027 Handle split headers in Http(Request|Response).aggregate()
  core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestAggregator.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseAggregator.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java
Labels: defect

#1004 Implement ServerListenerBuilder
  core/src/main/java/com/linecorp/armeria/server/ServerListenerBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServerListenerTest.java
Labels: new-feature

#1032 Migrate remaining usage of hamcrest to assertj
  NOTICE.txt
  build.gradle
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultAttributeMapTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceDecorationTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/SniServerTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/HttpAuthServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckServiceTest.java
  dependencies.yml
  gradle/scripts/lib/common-git.gradle
  jetty/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java
  licenses/LICENSE.hamcrest.bsd.txt
  spring-boot/autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/endpoint/StaticEndpointGroupIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocStringExtractorTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp1Test.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
  tomcat/src/test/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatServiceTest.java
Labels: cleanup

#1036 Make closeSpan method static
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
  zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanContextUtil.java
  zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java
Labels: improvement

#1033 [TRIVIAL] EndpointGroupTest#[disconnectZk, setNodeChild] does not throw Throwable anymore
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java
Labels: cleanup

#1034 [TRIVIAL] Remove unused 'throws Exception's from DeferredStreamMessageTest
  core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
Labels: cleanup

#1031 Make sure RPC information is set to metrics for unframed requests.
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServicePluginTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
Labels: defect

#1011 Add docs for annotated HTTP service
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Decorator.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceDecorationTest.java
  site/src/sphinx/server-annotated-service.rst
  site/src/sphinx/server-rest.rst
  site/src/sphinx/server.rst
Labels: documentation

#1038 Better document / test reference counting of stream duplication.
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
Labels: cleanup

#1030 Close in-progress responses when channel is closed.
  core/src/main/java/com/linecorp/armeria/client/DecodedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriter.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriterTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/EventLoopStreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
  jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Labels: defect

#1045 Fix ConcurrentModificationException in DefaultKeyedChannelPool.doClose()
  core/src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java
Labels: defect

#1046 Update dependencies
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistries.java
  dependencies.yml
  tomcat8.0/build.gradle
Labels: dependencies

#1047 Cancel gRPC stream when client cancels.
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
  testing/src/main/java/com/linecorp/armeria/testing/server/ServerRule.java
Labels: defect

#1043 Do not use deprecated methods in documentation
  site/src/sphinx/server-basics.rst
Labels: documentation

#1052 Fix typo in `logback.xml` example
  site/src/sphinx/server-access-log.rst
Labels: documentation

#1053 Client Thrift example should wait until a call is finished
  site/src/sphinx/client-thrift.rst
Labels: documentation

#1051 More concise port and TLS configuration
  benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/downstream/DownstreamSimpleBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/downstream/LargePayloadBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/thrift/PooledResponseBufferBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerPort.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientSniTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/internal/ConnectionLimitingHandlerIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/RedirectServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/SniServerTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  it/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
  jetty/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java
  jetty/src/test/java/com/linecorp/armeria/server/jetty/UnmanagedJettyServiceTest.java
  site/src/sphinx/server-basics.rst
  site/src/sphinx/server-docservice.rst
  spring-boot/autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
  tomcat/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceTest.java
  zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: deprecation, new-feature

#1055 Update dependencies
  dependencies.yml
Labels: dependencies

#1057 [TRIVIAL] Remove unthrown Exceptions from HttpHealthCheckService
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
Labels: cleanup

#1054 Update the introductory part of the web site
  site/src/sphinx/index.rst
Labels: documentation

#1058 Add server side connections, pending responses metrics
  core/src/main/java/com/linecorp/armeria/server/GracefulShutdownSupport.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
Labels: new-feature

#1060 Ignore flaky test (GrpcClientTest.halfDuplexCallShouldSucceed) in CI
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: cleanup

#1062 Make sure stub code handlers run on the event loop.
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcTestUtil.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
Labels: defect

#1056 Fix to retry for HttpStatusBasedRetryStrategy when it gets exceptions…
  core/src/main/java/com/linecorp/armeria/client/retry/HttpStatusBasedRetryStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/internal/HttpHeaderSubscriber.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: breaking-change, new-feature

#1065 Fix to propegate the Exception in the StreamMessageDuplicator to the …
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
Labels: defect

#1064 Implement flow control of gRPC stream writes.
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcFlowControlTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/flow.proto
Labels: defect

#1068 Always call .join() on Server start futures in examples
  site/src/sphinx/server-basics.rst
Labels: documentation

#1069 Fix automatic retry documentation
  site/src/sphinx/advanced-retry.rst
Labels: documentation

#1085 Add ServerBuilder.tlsSelfSigned()
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  jetty/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java
  jetty/src/test/java/com/linecorp/armeria/server/jetty/UnmanagedJettyServiceTest.java
  testing-internal/src/main/java/com/linecorp/armeria/testing/internal/webapp/WebAppContainerTest.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp1Test.java
  tomcat/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceTest.java
Labels: new-feature

#1089 Add Endpoint.ipAddr
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/pool/PoolKey.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/endpoint/StaticEndpointGroupIntegrationTest.java
  zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/DefaultNodeValueCodec.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/TestBase.java
  zookeeper/src/test/java/com/linecorp/armeria/common/zookeeper/NodeValueCodecTest.java
Labels: new-feature

#1090 Add MoreNamingConventions.configure()
  core/src/main/java/com/linecorp/armeria/common/metric/MoreNamingConventions.java
  core/src/test/java/com/linecorp/armeria/common/metric/MoreNamingConventionsTest.java
Labels: new-feature

#1091 Fix potential buffer leaks due to empty ByteBufHttpData
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
  core/src/main/java/com/linecorp/armeria/unsafe/ByteBufHttpData.java
  core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriterTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshallerTest.java
Labels: defect

#1093 Reduce the amount of static memory required for testing :grpc
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcFlowControlTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Labels: cleanup

#1097 Fix a bug where resources are not cleaned up after calling duplicator.close()
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
Labels: defect

#1098 Add CODEOWNERS
  .github/CODEOWNERS
Labels: miscellaneous

#1049 Restructure spring-boot package to support both spring-boot 1 and 2
  dependencies.yml
  settings.gradle
  spring-boot/starter/build.gradle
  spring/boot-autoconfigure/build.gradle
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1MeterBindersConfiguration.java
  spring/boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring/boot-starter/build.gradle
  spring/boot2-autoconfigure/build.gradle
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerConfigurator.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/HttpServiceRegistrationBean.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/MeterIdPrefixFunctionFactory.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/package-info.java
  spring/boot2-autoconfigure/src/main/resources/META-INF/spring.factories
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaMeterBindersConfigurationTest.java
  spring/boot2-autoconfigure/src/test/resources/config/application-autoConfTest.yml
  spring/boot2-autoconfigure/src/test/thrift/main.thrift
  spring/boot2-starter/build.gradle
Labels: new-feature

#1102 Remove unthrown Exceptions from ArmeriaGrpcServerInteropTest
  it/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
Labels: cleanup

#1096 New Feature: Default "RequestConverterFunction" for Java beans
  core/src/main/java/com/linecorp/armeria/internal/AnnotatedHttpServiceParamUtil.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServices.java
  core/src/main/java/com/linecorp/armeria/server/annotation/BeanRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Header.java
  core/src/main/java/com/linecorp/armeria/server/annotation/MutableValueHolder.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Param.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceRequestConverterTest.java
Labels: new-feature

#1108 Update dependencies
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/shared/SimpleBenchmarkBase.java
  core/build.gradle
  dependencies.yml
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Labels: dependencies

#1107 Update Tomcat to 9.0.6 / Replace TomcatHandler with MethodHandles
  dependencies.yml
  settings.gradle
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/JarSubsetResourceSet.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/ManagedConnectorFactory.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat85Handler.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90InputBuffer.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90OutputBuffer.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90ProtocolHandler.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatHandler.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatUtil.java
  tomcat/src/test/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatServiceTest.java
  tomcat8.0/build.gradle
  tomcat8.0/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat80Handler.java
  tomcat8.5/build.gradle
Labels: dependencies

#1110 Use HTTP/2 preface upgrade by default
  core/src/main/java/com/linecorp/armeria/common/Flags.java
Labels: breaking-change

#1111 Rename 'armeria.server.numConnections` to `armeria.server.connections`
  core/src/main/java/com/linecorp/armeria/server/Server.java
Labels: defect
