Repository line/armeria, pull requests merged in 2018-06, with the labels that each got.

#1237 Mitigate to return CompletionStage instead of CompletableFuture where…
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerStrategy.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/HttpStatusBasedCircuitBreakerStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/HttpStatusBasedRetryStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/throttling/RateLimitingThrottlingStrategy.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingStrategy.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
  core/src/test/java/com/linecorp/armeria/server/throttling/RateLimitingThrottlingStrategyTest.java
  core/src/test/java/com/linecorp/armeria/server/throttling/ThrottlingStrategyTest.java
  site/src/sphinx/client-circuit-breaker.rst
  site/src/sphinx/client-retry.rst
Labels: improvement

#1235 Fill all necessary pseudo headers in RequestLog headers / Deprecate RequestLog.host() in favor of authority()
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeaders.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaders.java
  core/src/main/java/com/linecorp/armeria/common/HttpMethod.java
  core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/NoopRequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporter.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
  zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java
  zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java
  zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
Labels: defect, deprecation

#1236 Fix a bug where RetryingClient does not stop when ClientFactory is closed
  core/src/main/java/com/linecorp/armeria/client/ClosedClientFactoryException.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: defect

#1239 Use gRPC shaded in benchmarks to avoid needing classpath workarounds …
  benchmarks/build.gradle
  dependencies.yml
Labels: cleanup

#1240 Only enable verbose exceptions for tests.
  build.gradle
Labels: cleanup

#1238 Add a simple benchmark to check retrofit performance.
  benchmarks/build.gradle
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/downstream/DownstreamSimpleBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkBase.java
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkClient.java
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/upstream/UpstreamSimpleBenchmark.java
Labels: performance

#1242 Fix a bug where RetryingClient does not stop when StreamMessage is ab…
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: defect

#1244 Log request when response is failed and request wasn't logged.
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/logging/LoggingDecorators.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: improvement

#1245 Use non-suffixed content-type for default gRPC proto encoding.
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormatProvider.java
Labels: improvement

#1246 Only compute advertised encodings header once since it doesn't change.
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
Labels: performance

#1247 Reject most duplicate path mappings
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/CatchAllPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
Labels: defect

#1250 Don't allocate / copy when constructing retrofit url with no query an…
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
Labels: performance

#1251 Fix a bug where HttpClient connects to a wrong host when custom authority is used
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionChannelFactory.java
  core/src/main/java/com/linecorp/armeria/client/pool/PoolKey.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
Labels: defect

#1248 Optimize complexity of client endpoint WeightedRoundRobinStrategy
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/endpoint/StaticEndpointGroupIntegrationTest.java
Labels: improvement

#1249 Refactor TomcatService into ManagedTomcatService & UnmanagedTomcatSer…
  it/server/build.gradle
  it/server/src/test/java/com/linecorp/armeria/it/hbase/HBaseClientCompatibilityTest.java
  it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
  it/spring/boot-tomcat/build.gradle
  it/spring/boot-tomcat/src/main/java/com/linecorp/armeria/spring/tomcat/demo/Greeting.java
  it/spring/boot-tomcat/src/main/java/com/linecorp/armeria/spring/tomcat/demo/GreetingController.java
  it/spring/boot-tomcat/src/main/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplication.java
  it/spring/boot-tomcat/src/main/java/com/linecorp/armeria/spring/tomcat/demo/package-info.java
  it/spring/boot-tomcat/src/main/resources/application.properties
  it/spring/boot-tomcat/src/main/resources/config/application.yml
  it/spring/boot-tomcat/src/test/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplicationItTest.java
  it/spring/boot-tomcat8.5/build.gradle
  it/spring/boot-tomcat8.5/src/test/resources/application.properties
  settings.gradle
  settings/checkstyle/checkstyle-suppressions.xml
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot-tomcat-sample/src/main/resources/application.properties
  tomcat/src/main/java/com/linecorp/armeria/internal/tomcat/TomcatVersion.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/ManagedTomcatService.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatService.java
  tomcat/src/test/java/com/linecorp/armeria/server/tomcat/ManagedTomcatServiceTest.java
  tomcat/src/test/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatServiceTest.java
Labels: breaking-change, improvement

#1257 Allow more memory to tests, except streaming tests
  .appveyor.yml
  .travis.yml
  build.gradle
  core/build.gradle
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  it/spring/boot-tomcat/src/test/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplicationItTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaMeterBindersConfigurationTest.java
Labels: cleanup

#1260 Add a dedicated factory method for active request gauges to MeterIdPrefixFunction
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java
  core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java
Labels: defect, new-feature

#1259 Reproduce Tomcat 9.0 Issue w/o predefined ports.
  it/spring/boot-tomcat/src/main/resources/config/application.yml
  it/spring/boot-tomcat/src/test/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplicationItTest.java
Labels: cleanup

#1268 Do not confuse an IDE by having a source directory with two output directories
  it/spring/boot-tomcat/build.gradle
  it/spring/boot-tomcat8.5/build.gradle
  spring/boot1-autoconfigure/build.gradle
  thrift0.9/build.gradle
  tomcat8.0/build.gradle
  tomcat8.5/build.gradle
Labels: cleanup

#1270 Use the reference to the dedicated page about service discovery in th…
  site/src/sphinx/index.rst
Labels: documentation

#1272 Use getServiceDescriptor to get stub methods instead of removed API. …
  dependencies.yml
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java
Labels: dependencies

#1271 Update dependencies
  dependencies.yml
  it/spring/boot-tomcat/build.gradle
  it/spring/boot-tomcat8.5/build.gradle
  spring/boot1-autoconfigure/build.gradle
  tomcat/src/test/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatServiceTest.java
  tomcat8.5/build.gradle
Labels: dependencies

#1273 Remove Javassist from dependencies
  NOTICE.txt
  core/build.gradle
  dependencies.yml
  licenses/LICENSE.javassist.mpl11.html
Labels: defect, dependencies
