Repository line/armeria, pull requests merged in 2018-08, with the labels that each got.

#1315 Ensure SSLParameters.endpointIdentificationAlgorithm is 'HTTPS'
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/internal/ChannelUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
Labels: defect

#1318 Revert HttpServerPipelineConfigurator TLS Hostname verification chang…
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/internal/ChannelUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
Labels: defect

#1320 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1316 Update dependencies
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpService.java
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  spring/boot1-autoconfigure/build.gradle
Labels: dependencies

#1292 Add SAML configurator in order to easily enable SAML authentication o…
  dependencies.yml
  licenses/LICENSE.java-jwt.mit.txt
  licenses/LICENSE.java-support.al20.txt
  licenses/LICENSE.jsoup.mit.txt
  licenses/LICENSE.opensaml.al20.txt
  saml/build.gradle
  saml/src/main/java/com/linecorp/armeria/server/saml/HttpPostBindingUtil.java
  saml/src/main/java/com/linecorp/armeria/server/saml/HttpRedirectBindingUtil.java
  saml/src/main/java/com/linecorp/armeria/server/saml/JwtBasedSamlRequestIdManager.java
  saml/src/main/java/com/linecorp/armeria/server/saml/KeyStoreCredentialResolverBuilder.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerConfig.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerConfigBuilder.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlBindingProtocol.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlDecorator.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlEndpoint.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlException.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlHttpParameterNames.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlIdentityProviderConfig.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlIdentityProviderConfigBuilder.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlIdentityProviderConfigSelector.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlInitializer.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlMessageUtil.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlMetadataServiceFunction.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlNameIdFormat.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlNameIdPolicy.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlPortConfig.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlPortConfigAutoFiller.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlPortConfigBuilder.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlRequestIdManager.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlService.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceFunction.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceProvider.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceProviderBuilder.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlSingleLogoutFunction.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlSingleLogoutHandler.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlSingleSignOnHandler.java
  saml/src/main/java/com/linecorp/armeria/server/saml/package-info.java
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlRequestIdManagerTest.java
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlServiceProviderTest.java
  settings.gradle
  site/src/sphinx/advanced-saml.rst
  site/src/sphinx/advanced.rst
Labels: new-feature

#1321 Add Copy and Clear buttons to docs client
  docs-client/src/containers/MethodPage/index.tsx
Labels: new-feature

#1327 Add a new flag: 'com.linecorp.armeria.verboseResponses'
  build.gradle
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
  core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
Labels: new-feature

#1329 More strict path validation
  core/src/main/java/com/linecorp/armeria/internal/PathAndQuery.java
  core/src/test/java/com/linecorp/armeria/internal/PathAndQueryTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
Labels: defect

#1331 Update dependencies
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  dependencies.yml
Labels: dependencies

#1330 Add examples of annotated HTTP service
  examples/README.md
  examples/annotated-http-service/build.gradle
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/ExceptionHandlerService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/InjectionService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/PathPatternService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/ServerFactory.java
  examples/annotated-http-service/src/main/resources/.gitkeep
  examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedHttpServiceTest.java
  examples/annotated-http-service/src/test/resources/.gitkeep
  settings.gradle
Labels: documentation

#1335 Add one more example which returns a future from annotated service me…
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/PathPatternService.java
  examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedHttpServiceTest.java
Labels: documentation

#1334 Update post release msg
  .post-release-msg
Labels: cleanup

#1336 Fix broken link
  site/src/sphinx/server-basics.rst
Labels: documentation

#1340 Generate config metadata for Spring
  spring/boot-autoconfigure/build.gradle
  spring/boot1-autoconfigure/build.gradle
Labels: new-feature

#1338 Push ClientRequestContext when initiating gRPC HTTP request and calli…
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
Labels: defect

#1328 Allows trace scope decoration such as Log4J trace ID correlation
  dependencies.yml
  zipkin/src/main/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContext.java
  zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java
  zipkin/src/test/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContextTest.java
  zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
  zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
Labels: deprecation, new-feature

#1341 Drops main compile dependency on io.zipkin.zipkin2:zipkin
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
Labels: dependencies

#1344 Add StartStopSupport
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java
  core/src/test/java/com/linecorp/armeria/common/util/StartStopSupportTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
Labels: new-feature

#1345 Apply collapse to side menu
  docs-client/src/containers/App/index.tsx
Labels: new-feature

#1347 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextConditionalSubscriber.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextSubscriber.java
  site/src/sphinx/_static/overrides.css
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90ProtocolHandler.java
  tomcat8.5/build.gradle
Labels: dependencies

#1349 Completes stopFuture immediately if Server does not start server serverChannels yet
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Labels: defect

#1352 Fix advanced logging document not consistent
  site/src/sphinx/advanced-logging.rst
Labels: documentation
