Repository line/armeria, pull requests merged in 2018-04, with the labels that each got.

#1115 Allow empty lambdas in the check style
  settings/checkstyle/checkstyle.xml
Labels: cleanup

#1114 Allow caching header values to avoid creating new Strings for the sam…
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/downstream/DownstreamSimpleBenchmark.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
Labels: performance

#1116 Add documentation for BeanRequestConverterFunction
  site/src/sphinx/server-annotated-service.rst
Labels: documentation

#1122 Update dependencies
  dependencies.yml
Labels: dependencies

#1121 Throw ClosedPublisherException when StreamWriter.write() fails
  core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
  core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriterTest.java
Labels: breaking-change

#1119 Improve the cleanup of streaming responses
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
  tomcat/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceTest.java
Labels: defect

#1118 Allow aggregating pooled objects.
  core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestAggregator.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseAggregator.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Labels: new-feature

#1124 Reuse spring-boot2 integration at spring-boot1-autoconfigure correctly
  spring/boot-autoconfigure/build.gradle
Labels: defect

#1123 Remove unthrown Exceptions from anonymous ServerListenerAdapter classes
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLoggingService.java
  it/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
Labels: cleanup

#1126 Rename spring-boot-* to spring-boot1-* and spring-boot2-* to spring-b…
  settings.gradle
  spring/boot-autoconfigure/build.gradle
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerConfigurator.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/HttpServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/MeterIdPrefixFunctionFactory.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/package-info.java
  spring/boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaMeterBindersConfigurationTest.java
  spring/boot-autoconfigure/src/test/resources/config/application-autoConfTest.yml
  spring/boot-autoconfigure/src/test/thrift/main.thrift
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1MeterBindersConfiguration.java
  spring/boot1-autoconfigure/src/main/resources/META-INF/spring.factories
  spring/boot1-starter/build.gradle
  spring/boot2-autoconfigure/build.gradle
  spring/boot2-autoconfigure/src/main/resources/META-INF/spring.factories
  spring/boot2-starter/build.gradle
Labels: breaking-change, cleanup

#1127 Update dependencies
  build.gradle
  dependencies.yml
Labels: dependencies

#1125 Fix a bug where contentType is not reset
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeaders.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersTest.java
Labels: defect

#1044 Use Curator framework for ZooKeeper service registration and discovery
  dependencies.yml
  site/src/sphinx/advanced-zookeeper.rst
  zookeeper/build.gradle
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroup.java
  zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/ZooKeeperConnector.java
  zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/ZooKeeperException.java
  zookeeper/src/main/java/com/linecorp/armeria/internal/zookeeper/ZooKeeperDefaults.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistration.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListenerBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/package-info.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/TestBase.java
  zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: breaking-change, new-feature

#1129 Update protobuf-jackson dependency
  dependencies.yml
Labels: dependencies

#1131 Remove unthrown Exceptions from JettyService
  jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
Labels: cleanup

#1132 Add more flexibility in adding token-based authentication to HttpAuth…
  core/src/main/java/com/linecorp/armeria/server/auth/AuthTokenExtractors.java
  core/src/main/java/com/linecorp/armeria/server/auth/BasicTokenExtractor.java
  core/src/main/java/com/linecorp/armeria/server/auth/HttpAuthServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/auth/OAuth1aTokenExtractor.java
  core/src/main/java/com/linecorp/armeria/server/auth/OAuth2TokenExtractor.java
  core/src/test/java/com/linecorp/armeria/server/auth/HttpAuthServiceTest.java
Labels: new-feature

#1135 Use ServerBuilder.service() instead of serviceUnder() in gRPC server …
  site/src/sphinx/server-grpc.rst
Labels: documentation

#1138 Fix a bug where a GrpcDocServicePlugin does not handle exact path map…
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocServicePlugin.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServicePluginTest.java
Labels: defect

#1145 Clean up ZooKeeper EndpointGroupTest / Reduce flakiness
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/EndpointGroupTest.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupTest.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/ZooKeeperTestBase.java
  zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: cleanup

#1144 Support SSLeay PKCS#5 private key format
  NOTICE.txt
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/internal/crypto/BouncyCastleKeyFactoryProvider.java
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/crypto/BouncyCastleKeyFactoryProviderTest.java
  core/src/test/resources/com/linecorp/armeria/internal/crypto/pkcs5.key
  core/src/test/resources/com/linecorp/armeria/internal/crypto/pkcs8.key
  core/src/test/resources/com/linecorp/armeria/internal/crypto/test.crt
  dependencies.yml
  licenses/LICENSE.bouncycastle.mit.html
Labels: new-feature

#1142 Add more concise variants of HttpResponse.of()
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/test/java/com/linecorp/armeria/common/HttpResponseTest.java
  site/src/sphinx/server-basics.rst
Labels: new-feature

#1150 Update sphinx-gradle-plugin to 2.0.2
  .appveyor.yml
  .travis.yml
  dependencies.yml
  site/src/sphinx/_static/jquery.js
  site/src/sphinx/_templates/breadcrumbs.html
  site/src/sphinx/_themes/sphinx_rtd_theme/__init__.py
  site/src/sphinx/_themes/sphinx_rtd_theme/breadcrumbs.html
  site/src/sphinx/_themes/sphinx_rtd_theme/footer.html
  site/src/sphinx/_themes/sphinx_rtd_theme/layout.html
  site/src/sphinx/_themes/sphinx_rtd_theme/search.html
  site/src/sphinx/_themes/sphinx_rtd_theme/searchbox.html
  site/src/sphinx/_themes/sphinx_rtd_theme/static/css/badge_only.css
  site/src/sphinx/_themes/sphinx_rtd_theme/static/css/theme.css
  site/src/sphinx/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.eot
  site/src/sphinx/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg
  site/src/sphinx/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.ttf
  site/src/sphinx/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff
  site/src/sphinx/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff2
  site/src/sphinx/_themes/sphinx_rtd_theme/static/js/modernizr.min.js
  site/src/sphinx/_themes/sphinx_rtd_theme/static/js/theme.js
  site/src/sphinx/_themes/sphinx_rtd_theme/theme.conf
  site/src/sphinx/_themes/sphinx_rtd_theme/versions.html
  site/src/sphinx/conf.py
Labels: dependencies

#1154 Update dependencies
  dependencies.yml
  spring/boot1-autoconfigure/build.gradle
  tomcat8.0/build.gradle
  tomcat8.5/build.gradle
Labels: dependencies

#1147 Get `@Param` or `@Header` annotation value from a variable if the val…
  core/src/main/java/com/linecorp/armeria/internal/AnnotatedHttpServiceParamUtil.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java
  core/src/main/java/com/linecorp/armeria/server/annotation/BeanRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Header.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Param.java
  core/src/test/java/com/linecorp/armeria/internal/AnnotatedHttpServiceParamUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceRequestConverterTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
  site/src/sphinx/server-annotated-service.rst
Labels: new-feature

#1156 Fix broken links in advanced-zookeeper.rst
  site/src/sphinx/advanced-zookeeper.rst
Labels: documentation

#1157 Write rpc method name to access log
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
Labels: new-feature

#1159 Add access log writer as a listener of RequestLog
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
Labels: defect

#1162 Move 'automatic retry' and 'circuit breaker' to 'client' section
  site/src/sphinx/advanced.rst
  site/src/sphinx/client-circuit-breaker.rst
  site/src/sphinx/client-retry.rst
  site/src/sphinx/client.rst
  site/src/sphinx/setup-common.rst
Labels: documentation

#1163 Add a Sphinx extension that simplifies Javadoc linking
  site/build.gradle
  site/src/sphinx/_extensions/api.py
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/advanced-logging.rst
  site/src/sphinx/advanced-structured-logging-kafka.rst
  site/src/sphinx/advanced-structured-logging.rst
  site/src/sphinx/advanced-zipkin.rst
  site/src/sphinx/advanced-zookeeper.rst
  site/src/sphinx/client-circuit-breaker.rst
  site/src/sphinx/client-decorator.rst
  site/src/sphinx/client-grpc.rst
  site/src/sphinx/client-retrofit.rst
  site/src/sphinx/client-retry.rst
  site/src/sphinx/client-thrift.rst
  site/src/sphinx/conf.py
  site/src/sphinx/index.rst
  site/src/sphinx/server-access-log.rst
  site/src/sphinx/server-annotated-service.rst
  site/src/sphinx/server-basics.rst
  site/src/sphinx/server-decorator.rst
  site/src/sphinx/server-docservice.rst
  site/src/sphinx/server-grpc.rst
  site/src/sphinx/server-http-file.rst
  site/src/sphinx/server-servlet.rst
  site/src/sphinx/server-thrift.rst
Labels: documentation

#1166 Return `204 No Content` if there is no response converter for 'null' …
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceMethod.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedHttpServiceTest.java
Labels: defect

#1167 Only create composite bytebufs if there is more than one incoming gRPC frame.
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java
Labels: improvement, performance
