Repository line/armeria, pull requests merged in 2019-10, with the labels that each got.

#2129 Remove initial authority check in RetryingHttpClient
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestDuplicator.java
Labels: cleanup

#2123 Add a JMH benchmark for `ThriftMessageClassFinder`
  benchmarks/src/jmh/java/com/linecorp/armeria/common/thrift/text/StackTracingBenchmark.java
Labels: performance

#2127 Separate RequestContextAwareFuture version overrides into mrjar…
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/JavaVersionSpecific.java
  core/src/main/java/com/linecorp/armeria/internal/RequestContextAwareCompletableFuture.java
  core/src/main/java9/com/linecorp/armeria/internal/Java9RequestContextAwareCompletableFuture.java
  core/src/main/java9/com/linecorp/armeria/internal/Java9RequestContextAwareMinimalStage.java
  core/src/main/java9/com/linecorp/armeria/internal/Java9VersionSpecific.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/internal/RequestContextAwareCompletableFutureTest.java
  core/src/test/java9/com/linecorp/armeria/internal/RequestContextAwareCompletableFutureTest.java
Labels: cleanup

#2040 Provide a way to decorate multiple services by `Route`
  brave/src/test/java/com/linecorp/armeria/server/brave/ServerRequestContextAdapterTest.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/CompositeRouter.java
  core/src/main/java/com/linecorp/armeria/server/DecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RouteCache.java
  core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/RoutePathType.java
  core/src/main/java/com/linecorp/armeria/server/Router.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostDecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
  core/src/main/java/com/linecorp/armeria/server/composition/CompositeServiceEntry.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServicePluginTest.java
  core/src/test/java/com/linecorp/armeria/server/AbstractBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/PathWithPrefixTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteTest.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingTrieTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceConfigBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilderTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServicePluginTest.java
  site/src/sphinx/server-basics.rst
  site/src/sphinx/server-decorator.rst
Labels: new-feature

#2120 Split `RequestContext.request()` into `request()` and `rpcReque…
  brave/src/main/java/com/linecorp/armeria/client/brave/ArmeriaHttpClientParser.java
  brave/src/main/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapter.java
  brave/src/main/java/com/linecorp/armeria/internal/brave/SpanContextUtil.java
  brave/src/main/java/com/linecorp/armeria/internal/brave/SpanTags.java
  brave/src/main/java/com/linecorp/armeria/server/brave/ArmeriaHttpServerParser.java
  brave/src/main/java/com/linecorp/armeria/server/brave/ServiceRequestContextAdapter.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientTest.java
  brave/src/test/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapterTest.java
  brave/src/test/java/com/linecorp/armeria/internal/brave/SpanTagsTest.java
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/ServerRequestContextAdapterTest.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporter.java
  settings.gradle
  thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
  zipkin/build.gradle
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/package-info.java
  zipkin/src/main/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContext.java
  zipkin/src/main/java/com/linecorp/armeria/common/tracing/package-info.java
  zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java
  zipkin/src/main/java/com/linecorp/armeria/server/tracing/package-info.java
  zipkin/src/test/java/com/linecorp/armeria/client/tracing/TracingClientTest.java
  zipkin/src/test/java/com/linecorp/armeria/common/tracing/RequestContextCurrentTraceContextTest.java
  zipkin/src/test/java/com/linecorp/armeria/common/tracing/SpanCollectingReporter.java
  zipkin/src/test/java/com/linecorp/armeria/it/tracing/HttpTracingIntegrationTest.java
  zipkin/src/test/java/com/linecorp/armeria/server/tracing/TracingServiceTest.java
  zipkin/src/test/thrift/HelloService.thrift
Labels: breaking-change, new-feature

#2100 Provide a way to set an example headers for each registration b…
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ExampleHeaders.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcExampleHeaders.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/HttpServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot-webflux-autoconfigure/build.gradle
Labels: new-feature

#2131 Adding log for DefaultExceptionHandler when JSON parse error ha…
  core/src/main/java/com/linecorp/armeria/internal/annotation/DefaultExceptionHandler.java
Labels: defect

#2134 Fix a bug where long-lived request is not fully sent when retry…
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestDuplicatorTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
Labels: breaking-change, cleanup, defect

#2135 Update dependencies
  dependencies.yml
  settings/checkstyle/checkstyle.xml
Labels: dependencies

#2138 Do not notify `ResponseTimeoutException` twice
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java
Labels: defect

#2140 Call duplicator.abort() where necessary
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
Labels: defect

#2126 Run tests on older JVMs to check version-specific logic.
  .travis.install_jdk.sh
  .travis.yml
  build.gradle
  core/build.gradle
  core/src/test/java9/com/linecorp/armeria/internal/RequestContextAwareCompletableFutureTest.java
Labels: cleanup

#2145 Use TreeMap in Version Class to Sort the Versions
  core/src/main/java/com/linecorp/armeria/common/util/Version.java
Labels: defect

#2146 Fix EndpointGroup.of(Iterable) type
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupTest.java
Labels: defect

#2144 Fix a 404 error while retrieving Dropwizard Metrics Javadoc links
  dependencies.yml
Labels: cleanup

#2151 Switch default build JDK to Java 12.
  .appveyor.yml
  .travis.install_jdk.sh
  .travis.yml
  CONTRIBUTING.md
  README.md
  build.gradle
Labels: cleanup

#2153 Initialize path params map lazily to optimize routing that does not u…
  benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/RoutingResult.java
  core/src/main/java/com/linecorp/armeria/server/RoutingResultBuilder.java
Labels: performance

#2157 Switch from Travis CI to AppVeyor BYOC
  .appveyor.sh
  .appveyor.yml
  .travis.install_jdk.sh
  .travis.yml
  it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
Labels: cleanup

#2162 Fix typo in build message
  .appveyor.sh
Labels: cleanup

#2154 Enable FinalLocalVariable checkstyle check
  core/src/main/java/com/linecorp/armeria/client/retry/ExponentialBackoff.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocStringExtractor.java
  settings/checkstyle/checkstyle-suppressions.xml
  settings/checkstyle/checkstyle.xml
  testing/junit/src/main/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServerExtension.java
Labels: cleanup

#2152 Use singleton headers where possible in gRPC calls.
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/GrpcServiceBenchmark.java
  benchmarks/src/jmh/resources/logback-test.xml
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
Labels: performance

#2163 Add default tags in order.
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/metric/RequestMetricSupportBenchmark.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefix.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java
Labels: performance

#2168 Upload test reports to file.io
  .appveyor.build.sh
  .appveyor.report.sh
  .appveyor.yml
Labels: cleanup

#2166 Use StackOverflow for accepting questions
  CONTRIBUTING.md
  README.md
  site/src/sphinx/index.rst
Labels: documentation

#2159 Fix where access log is not written when the method of a reques…
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerHandlerTest.java
Labels: defect

#2172 Enable parallel build in CI jobs / Run only essential tasks on Windows
  .appveyor.build.sh
  .appveyor.yml
  build.gradle
  core/build.gradle
  docs-client/build.gradle
  it/spring/boot-tomcat8.5/build.gradle
  spring/boot1-autoconfigure/build.gradle
  thrift0.11/build.gradle
  thrift0.9/build.gradle
Labels: cleanup

#2124 Add `SslContext` validation
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServerTlsValidationTest.java
  core/src/test/resources/com/linecorp/armeria/server/keystore.jks
  core/src/test/resources/com/linecorp/armeria/server/keystore.p12
Labels: breaking-change, defect

#2175 Drop `armeria-zipkin` artifact from setup.html
  site/src/sphinx/setup.rst
Labels: documentation

#2142 Provide a way to configure a CacheSpec for HttpFileService
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileServiceConfig.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java
  site/src/sphinx/server-http-file.rst
Labels: new-feature

#2183 Fix a bug where disables all check style
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/encoding/AbstractStreamDecoderTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/common/MediaTypeTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultAttributeMapTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/AbstractUnaryGrpcServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  it/spring/boot-tomcat/src/main/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplication.java
  it/spring/boot-tomcat/src/test/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplicationItTest.java
  settings/checkstyle/checkstyle-suppressions.xml
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java
Labels: defect

#2139 Migrate debug page to hooks.
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/HomePage/index.tsx
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/EndpointPath.tsx
  docs-client/src/containers/MethodPage/HttpHeaders.tsx
  docs-client/src/containers/MethodPage/HttpQueryString.tsx
  docs-client/src/containers/MethodPage/RequestBody.tsx
  docs-client/src/lib/transports/grpc-unframed.ts
Labels: cleanup

#2193 Fix `ClassCastException` when calling `*HeadersBuilder.build()`…
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultResponseHeadersBuilder.java
  core/src/test/java/com/linecorp/armeria/common/DefaultHttpHeadersBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultResponseHeadersBuilderTest.java
Labels: defect

#2186 Add favicon to DocService
  docs-client/package.json
  docs-client/src/images/logo.png
  docs-client/webpack.config.ts
  site/src/sphinx/_static/logo.png
  site/src/sphinx/conf.py
Labels: improvement

#2179 Add Armeria version metric
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Labels: new-feature

#2188 Add `Server` and `Date` header by default
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpResponseSubscriberTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerDefaultHeadersTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/ProxyProtocolEnabledServerTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/streaming/JsonTextSequencesTest.java
  examples/server-sent-events/src/main/java/example/armeria/server/sse/Main.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Labels: new-feature

#2196 Add optimized supplier of current HTTP timestamp
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/HttpTimestampSupplierBenchmark.java
  core/src/main/java/com/linecorp/armeria/internal/HttpTimestampSupplier.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
  core/src/test/java/com/linecorp/armeria/internal/HttpTimestampSupplierTest.java
Labels: performance

#2182 Allow configuring a thread name pattern to treat as non-request threads.
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextBuilder.java
  brave/src/main/java/com/linecorp/armeria/internal/brave/TraceContextUtil.java
  brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
  brave/src/test/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextTest.java
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
Labels: defect

#2187 Some annotated service methods are run from blocking task executors
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpService.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Blocking.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceBlockingTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceTest.java
Labels: breaking-change, defect, new-feature

#2208 Implement ArmeriaServerHttpRequest.getRemoteAddress()
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerAutoConfigurationTest.java
Labels: defect

#2212 Have yarn task default to frozen lockfile to not update yarn file with unrelated work
  docs-client/build.gradle
  docs-client/yarn.lock
Labels: cleanup

#2211 Make sure spring configuration runs if serverbuilder consumers are pr…
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithConsumerTest.java
Labels: defect

#2213 Fix document
  site/src/sphinx/server-annotated-service.rst
Labels: documentation

#2206 Fix a wrong usage in documentation
  site/src/sphinx/advanced-production-checklist.rst
Labels: cleanup

#2207 Add hamcrest 2.2 dependency and upgrade json-unit 2.8.1 to 2.10.0
  build.gradle
  dependencies.yml
Labels: dependencies

#2184 Set useOpenSsl in Flags lazily to reduce server startup time
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/util/OsType.java
  core/src/main/java/com/linecorp/armeria/common/util/SystemInfo.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Labels: improvement
