Repository line/armeria, pull requests merged in 2019-06, with the labels that each got.

#1806 Migrate from Parameterized to JUnit 5.
  core/src/test/java/com/linecorp/armeria/client/HttpResponseDecoderTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestSubscriberTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriterTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/FixedStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerAbortingInfiniteStreamTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/PortUnificationServerTest.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerAutoConfigurationTest.java
  testing-internal/build.gradle
  testing-internal/src/main/java/com/linecorp/armeria/testing/internal/UniqueProtocolsProvider.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Labels: cleanup

#1809 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cleanup

#1818 Update Yarn and Node.js
  docs-client/build.gradle
Labels: dependencies

#1814 Allow configuring an already created DropwizardMeterRegistry with arm…
  core/src/main/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistries.java
Labels: new-feature

#1816 Move `Client/ServerCacheControl` to `common`
  core/src/main/java/com/linecorp/armeria/common/CacheControl.java
  core/src/main/java/com/linecorp/armeria/common/CacheControlBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ClientCacheControl.java
  core/src/main/java/com/linecorp/armeria/common/ClientCacheControlBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ServerCacheControl.java
  core/src/main/java/com/linecorp/armeria/common/ServerCacheControlBuilder.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
  core/src/test/java/com/linecorp/armeria/common/ClientCacheControlTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersTest.java
  core/src/test/java/com/linecorp/armeria/common/ServerCacheControlTest.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceAdditionalHeadersTest.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileTest.java
  examples/proxy-server/src/main/java/example/armeria/proxy/Main.java
  site/src/sphinx/server-http-file.rst
Labels: breaking-change, cleanup

#1819 Update frontend dependencies
  docs-client/package.json
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/index.tsx
  docs-client/webpack.config.ts
  docs-client/yarn.lock
  licenses/web-licenses.txt
Labels: dependencies

#1811 Automatically enable MockitoExtension in JUnit 5 tests.
  core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClientTest.java
  dependencies.yml
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerTest.java
  testing-internal/build.gradle
  testing-internal/src/main/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  testing-internal/src/main/resources/junit-platform.properties
Labels: cleanup

#1820 Add `PrometheusMeterRegistries.configureRegistry()`
  core/src/main/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistries.java
  core/src/main/java/com/linecorp/armeria/common/metric/PrometheusMeterRegistries.java
Labels: new-feature

#1821 Update dependencies
  dependencies.yml
  it/spring/boot-tomcat8.5/build.gradle
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
  tomcat8.5/build.gradle
Labels: dependencies

#1807 Update clinet-retry.rst
  site/src/sphinx/client-retry.rst
Labels: documentation

#1787 Reload PropertiesEndpointGroup if the watched properties file is updated
  core/src/main/java/com/linecorp/armeria/client/endpoint/FileWatcherRegistry.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/FileWatcherRunnable.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/RestartableThread.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/FileWatcherRegistryTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/FileWatcherRunnableTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/RestartableThreadTest.java
Labels: new-feature

#1815 Implement the go-to form for DocService debug page
  docs-client/package.json
  docs-client/src/components/GotoSelect/index.tsx
  docs-client/src/containers/App/index.tsx
  docs-client/yarn.lock
  licenses/web-licenses.txt
Labels: new-feature

#1808 Add SubscriptionOption
  benchmarks/src/jmh/java/com/linecorp/armeria/thrift/PooledResponseBufferBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/common/FilteredHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HeaderOverridingHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java
  core/src/main/java/com/linecorp/armeria/common/stream/SubscriptionOption.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/encoding/HttpDecodedResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/common/stream/FilteredStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDrainerTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/SubscriptionOptionTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/TwoElementFixedStreamMessageTest.java
  examples/proxy-server/src/main/java/example/armeria/proxy/ProxyService.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  site/src/sphinx/client-thrift.rst
  site/src/sphinx/server-annotated-service.rst
Labels: breaking-change, new-feature

#1826 Update dependencies
  dependencies.yml
  docs-client/yarn.lock
  it/spring/boot-tomcat8.5/build.gradle
  licenses/web-licenses.txt
  tomcat8.5/build.gradle
Labels: dependencies

#1828 Add unit test that uses gRPC Context.
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
Labels: cleanup

#1829 Add a main class to `:examples:annotated-http-service`
  examples/annotated-http-service/build.gradle
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/Main.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/ServerFactory.java
  examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedHttpServiceTest.java
Labels: cleanup

#1833 Hide `CacheControlBuilder` from the public API
  core/src/main/java/com/linecorp/armeria/common/CacheControl.java
  core/src/main/java/com/linecorp/armeria/common/CacheControlBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ClientCacheControl.java
  core/src/main/java/com/linecorp/armeria/common/ClientCacheControlBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ServerCacheControl.java
  core/src/main/java/com/linecorp/armeria/common/ServerCacheControlBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/common/CacheControlTest.java
  core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java
Labels: cleanup

#1831 Update dependencies
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  dependencies.yml
Labels: dependencies

#1832 Remove exactPath, triePath, prefix and regex method in Route api
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServicePlugin.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServiceUtil.java
  core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/CatchAllPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/ExactPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/PathMapping.java
  core/src/main/java/com/linecorp/armeria/server/PrefixPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMappingWithPrefix.java
  core/src/main/java/com/linecorp/armeria/server/Route.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RoutePathType.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/Service.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
  core/src/test/java/com/linecorp/armeria/server/GlobPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/ParameterizedPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/PathWithPrefixTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/composition/CompositeServiceTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocServicePlugin.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlService.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftDocServicePlugin.java
Labels: improvement

#1841 Export blocking task executor metrics
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
Labels: new-feature

#1850 Update protobuf-jackson to 1.0.0
  dependencies.yml
Labels: dependencies

#1853 Add 'requirements' to README.md and web site
  CONTRIBUTING.md
  README.md
  site/src/sphinx/setup.rst
Labels: documentation

#1846 Make health check client retry interval more configurable to ba…
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupBuilder.java
Labels: deprecation, new-feature

#1848 Make sure all safely retriable exceptions are wrapped by UnprocessedR…
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/GoAwayReceivedException.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java
  core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java
  core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java
  core/src/main/java/com/linecorp/armeria/internal/InboundTrafficController.java
  core/src/test/java/com/linecorp/armeria/client/Http2GoAwayTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java
Labels: improvement

#1859 Ignore `CancelledSubscriptionException` and `AbortedStreamException`
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerLoadBalancerInteropTest.java
  spring/boot-webflux-autoconfigure/src/test/resources/config/application-test_loadbalancer.yml
Labels: defect

#1857 Ensure a user set the endpoint path in DocService when the path is not…
  docs-client/README.md
  docs-client/scripts/serve.ts
  docs-client/src/containers/MethodPage/DebugPage.tsx
Labels: defect

#1863 Add missing dependency for `javax.annotation.Generated`
  dependencies.yml
  grpc/build.gradle
  thrift/build.gradle
  thrift0.11/build.gradle
  thrift0.9/build.gradle
Labels: dependencies

#1845 Provide MeterIdPrefixFunction for Retrofit
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/InvocationUtil.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunction.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/metric/RetrofitMeterIdPrefixFunctionTest.java
Labels: new-feature

#1864 Handle the case where `@Default` annotation is specified withou…
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedValueResolver.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceTest.java
Labels: defect

#1860 Fall back to the service with less constraint when content nego…
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingContextTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingTest.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
  spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
Labels: defect, improvement

#1867 Handle `HttpStatus/ResponseException` in `THttpService`
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpErrorResponseTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThrottlingRpcServiceTest.java
Labels: new-feature
