Repository line/armeria, pull requests merged in 2019-08, with the labels that each got.

#1940 Wait for delegate endpoints before beginning health check.
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/StaticEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: defect

#1937 Enable DeferredHttpResponse to have a defaultSubscriberExecutor
  core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseUtil.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java
Labels: improvement

#1945 Restore deleted method.
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java
Labels: cleanup

#1942 Don't add a second translated header when it already exists.
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
Labels: defect

#1935 Add a MockWebServerExtension, inspired by okhttp, which can allow tes…
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  testing/junit/src/main/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServerExtension.java
  testing/junit/src/main/java/com/linecorp/armeria/testing/junit/server/mock/RecordedRequest.java
  testing/junit/src/main/java/com/linecorp/armeria/testing/junit/server/mock/package-info.java
  testing/junit/src/test/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServiceExtensionTest.java
Labels: new-feature

#1965 Fix to contain te header in gRPC request
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: defect

#1962 Fix not to raise ClosedPublisherException when the HttpResponse is ab…
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
Labels: defect

#1974 Make `RetryingClient` respect the `Endpoint` selection order
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientLoadBalancingTest.java
Labels: defect

#1970 Remove the self-type parameters from abstract builders
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFileBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileBuilder.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientTest.java
Labels: deprecation, improvement

#1948 Revamp `HealthCheckedEndpointGroup`
  benchmarks/build.gradle
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupMetrics.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/package-info.java
  core/src/main/java/com/linecorp/armeria/common/util/AsyncCloseable.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
  examples/proxy-server/src/main/java/example/armeria/proxy/ProxyService.java
  site/src/sphinx/client-service-discovery.rst
Labels: breaking-change, defect, deprecation, new-feature

#1971 Allows tracing of threads without a request context available using a…
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java
  brave/src/test/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextTest.java
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
Labels: new-feature

#1977 Implement long polling for `HealthCheckedEndpointGroup`
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: defect, new-feature

#1978 Update dependencies
  dependencies.yml
  spring/boot1-autoconfigure/build.gradle
Labels: dependencies

#1961 Provide a way to request from an absolute URL with HttpClient
  core/src/main/java/com/linecorp/armeria/client/DefaultHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/HttpClient.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientRequestPathTest.java
  core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java
Labels: new-feature

#1975 Update docs-client dependencies, including migrating across breaking changes.
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServiceTest.java
  docs-client/package.json
  docs-client/src/components/GotoSelect/index.tsx
  docs-client/src/components/Section/index.tsx
  docs-client/src/components/VariableList/index.tsx
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/EnumPage/index.tsx
  docs-client/src/containers/HomePage/index.tsx
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/EndpointPath.tsx
  docs-client/src/containers/MethodPage/Endpoints.tsx
  docs-client/src/containers/MethodPage/Exceptions.tsx
  docs-client/src/containers/MethodPage/HttpHeaders.tsx
  docs-client/src/containers/MethodPage/HttpQueryString.tsx
  docs-client/src/containers/MethodPage/RequestBody.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/containers/StructPage/index.tsx
  docs-client/src/lib/specification.tsx
  docs-client/webpack.config.ts
  docs-client/yarn.lock
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServiceTest.java
  licenses/web-licenses.txt
  testing-internal/src/main/java/com/linecorp/armeria/testing/internal/TestUtil.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServiceTest.java
Labels: dependencies

#1982 Various improvements in health checking code
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupAuthorityTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: defect, new-feature

#1980 RequestContextCurrentTraceContext.setCurrentThreadNotRequestThread code
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java
Labels: documentation

#1990 Fix not to raise ConcurrentModificationException in HealthCheckedEndp…
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
Labels: defect

#1986 Disable TLS v1.3 when using JdkSslContext
  CONTRIBUTING.md
  core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java
  core/src/test/java/com/linecorp/armeria/internal/SslContextUtilTest.java
Labels: defect

#1993 Add Google Analytics tracker to the web site
  site/src/sphinx/_templates/footer.html
  site/src/sphinx/_templates/layout.html
Labels: documentation

#1992 Add a test for HealthCheckedEndpointGroup raising ConcurrentModificat…
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
Labels: cleanup

#1994 Add documentation for `-parameters` javac option
  CONTRIBUTING.md
  examples/README.md
  site/src/sphinx/_images/intellij_javac_parameters.png
  site/src/sphinx/server-annotated-service.rst
  site/src/sphinx/setup.rst
Labels: documentation

#1967 Add a shortcut methods for Server::activeLocalPort()
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckServiceTest.java
  examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedHttpServiceTest.java
  examples/grpc-service/src/test/java/example/armeria/grpc/HelloServiceTest.java
  examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
  examples/spring-boot-minimal/src/test/java/example/springframework/boot/minimal/HelloApplicationIntegrationTest.java
  examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloIntegrationTest.java
  examples/static-files/src/test/java/example/armeria/server/files/MainTest.java
  spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java
Labels: new-feature

#1983 Precompute exponential backoff.
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/BackoffBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/retry/ExponentialBackoff.java
  core/src/test/java/com/linecorp/armeria/client/retry/ExponentialBackoffTest.java
Labels: improvement

#1979 implemented Fibonacci backoff
  core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
  core/src/main/java/com/linecorp/armeria/client/retry/BackoffSpec.java
  core/src/main/java/com/linecorp/armeria/client/retry/FibonacciBackoff.java
  core/src/test/java/com/linecorp/armeria/client/retry/BackoffSpecTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/BackoffTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/FibonacciBackoffTest.java
Labels: new-feature

#1996 Update dependencies
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  dependencies.yml
Labels: dependencies

#1988 Add guide for how to run examples
  examples/README.md
  examples/annotated-http-service/build.gradle
  examples/grpc-service/build.gradle
  examples/saml-service-provider/build.gradle
  examples/server-sent-events/build.gradle
  examples/spring-boot-minimal/build.gradle
  examples/static-files/build.gradle
Labels: cleanup, documentation

#1998 Handles gRPC status when deferred to trailers
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClientTest.java
Labels: defect

#2004 Keep an endpoint's healthiness if long-poll health check returns NOT_…
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java
Labels: defect

#2005 Fix `byte[]` and `HttpData` conversion
  core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java
Labels: defect

#2007 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#2009 Update Tomcat from 9.0.22 to 9.0.24
  dependencies.yml
Labels: dependencies

#2013 Make Sphinx site generation not fail on `boms` section
  site/src/sphinx/conf.py
Labels: documentation

#2016 Fix flaky `HttpHealthCheckedEndpointGroupLongPollingTest`
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java
Labels: cleanup

#2012 Moves brave, jackson and netty version management to bom (Bill of Materials)
  dependencies.yml
  site/src/sphinx/advanced-spring-webflux-integration.rst
  site/src/sphinx/conf.py
Labels: dependencies

#1744 Show armeria version in doc service #685
  core/src/main/java/com/linecorp/armeria/common/util/Version.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
  docs-client/package.json
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/HomePage/index.tsx
  docs-client/src/lib/versions.tsx
  docs-client/webpack.config.ts
  docs-client/yarn.lock
  licenses/web-licenses.txt
Labels: new-feature

#2020 Add `ArmeriaRetrofitBuilder.clientOptions()`
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactory.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/metric/RetrofitMeterIdPrefixFunctionTest.java
Labels: new-feature

#2018 Add `as()` to `Client`
  core/src/main/java/com/linecorp/armeria/client/Client.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClient.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsBuilderTest.java
Labels: new-feature

#2027 because not found page, changed to add mailto
  CONTRIBUTING.md
Labels: documentation

#2019 Add `HealthCheckedEndpointGroupBuilder.clientOptions()`
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
Labels: new-feature

#2032 Remove unnecessary ignore of brave client integration test
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
Labels: cleanup

#2021 Call channel.remoteAddress before the connection is closed
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/logging/LoggingUtil.java
Labels: defect

#2029 Add `Unwrappable` and `ClientFactory.unwrap()`
  core/src/main/java/com/linecorp/armeria/client/Client.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClient.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClient.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
  core/src/main/java/com/linecorp/armeria/client/retry/BackoffWrapper.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractUnwrappable.java
  core/src/main/java/com/linecorp/armeria/common/util/Unwrappable.java
  core/src/main/java/com/linecorp/armeria/server/DecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/Service.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientUnwrapTest.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientFactory.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientUnwrapTest.java
  thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClient.java
  thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientDelegate.java
  thrift/src/main/java/com/linecorp/armeria/client/thrift/THttpClientInvocationHandler.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/THttpClientUnwrapTest.java
Labels: new-feature

#2036 Fix typo
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/BinaryContentPreviewer.java
  core/src/main/java/com/linecorp/armeria/common/util/SystemInfo.java
  core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/client/retry/FibonacciBackoffTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/TransportStatusListener.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriberTest.java
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlServiceProviderTest.java
Labels: documentation

#2034 Fix resource leak in `DefaultHttpClient.execute()`
  core/src/main/java/com/linecorp/armeria/client/DefaultHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounter.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClientTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounterTest.java
Labels: defect
