Repository line/armeria, pull requests merged in 2019-12, with the labels that each got.

#2288 Make sure boss `EventLoopGroup`s are terminated on startup fail…
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Labels: defect

#2237 Allow `LoggingClient/Service` to use a non-default `Logger`
  core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: new-feature

#2277 Fix outdated documentation in `client-custom-http-headers.rst`
  site/src/sphinx/client-custom-http-headers.rst
Labels: documentation

#2289 Deprecate `Sampler.rateLimited()` in favor of `rateLimiting()`
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/util/Sampler.java
  core/src/main/java/com/linecorp/armeria/common/util/Samplers.java
  core/src/test/java/com/linecorp/armeria/common/util/SamplerTest.java
Labels: cleanup

#2284 Respect gRPC stub deadline.
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
  it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
Labels: defect

#2293 Implement RoutingContextWrapper equals / hashCode / toString
  benchmarks/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
Labels: defect

#2295 Optimize RoutingContext by removing summary generation and othe…
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
Labels: improvement

#2242 Add more ways to add annotated service extensions
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedHttpServiceExtensions.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactoryTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
Labels: deprecation, new-feature

#2292 Automatic redirection with a trailing slash
  core/src/main/java/com/linecorp/armeria/server/CompositeRouter.java
  core/src/main/java/com/linecorp/armeria/server/RouteCache.java
  core/src/main/java/com/linecorp/armeria/server/Router.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java
  core/src/main/java/com/linecorp/armeria/server/RoutingTrieBuilder.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerAutoRedirectTest.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingTrieTest.java
Labels: breaking-change, defect

#2294 Provide a way to specify client IP from proxied addresses
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ProxiedAddresses.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/server/HttpHeaderUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/ProxyProtocolEnabledServerTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Labels: breaking-change, new-feature

#2286 Add immutable HTTP cookie API
  core/src/main/java/com/linecorp/armeria/common/ClientCookieDecoder.java
  core/src/main/java/com/linecorp/armeria/common/ClientCookieEncoder.java
  core/src/main/java/com/linecorp/armeria/common/Cookie.java
  core/src/main/java/com/linecorp/armeria/common/CookieBuilder.java
  core/src/main/java/com/linecorp/armeria/common/CookieUtil.java
  core/src/main/java/com/linecorp/armeria/common/Cookies.java
  core/src/main/java/com/linecorp/armeria/common/DefaultCookie.java
  core/src/main/java/com/linecorp/armeria/common/DefaultCookies.java
  core/src/main/java/com/linecorp/armeria/common/ServerCookieDecoder.java
  core/src/main/java/com/linecorp/armeria/common/ServerCookieEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedValueResolver.java
  core/src/test/java/com/linecorp/armeria/common/ClientCookieDecoderTest.java
  core/src/test/java/com/linecorp/armeria/common/ClientCookieEncoderTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultCookieTest.java
  core/src/test/java/com/linecorp/armeria/common/ServerCookieDecoderTest.java
  core/src/test/java/com/linecorp/armeria/common/ServerCookieEncoderTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedValueResolverTest.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/InjectionService.java
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/MyAuthHandler.java
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/MyService.java
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlServiceProviderTest.java
  site/src/sphinx/advanced-saml.rst
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
Labels: breaking-change, defect, deprecation, new-feature

#2296 Fix noisy `WARN` logs on client disconnection
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
Labels: defect

#2298 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  it/spring/boot-tomcat/build.gradle
  it/spring/boot-tomcat8.5/build.gradle
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationHttpService.java
  spring/boot1-autoconfigure/build.gradle
  thrift0.11/build.gradle
  thrift0.9/build.gradle
  tomcat8.0/build.gradle
  tomcat8.5/build.gradle
Labels: cleanup, dependencies

#2297 Fix flaky tests
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerHeaderValidationTest.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java
Labels: cleanup

#2300 Slim down docs client
  docs-client/package.json
  docs-client/src/index.html
  docs-client/src/index.tsx
  docs-client/webpack.config.ts
  docs-client/yarn.lock
  licenses/web-licenses.txt
Labels: cleanup

#2285 Multiple thrift services
  core/src/main/java/com/linecorp/armeria/common/util/AbstractUnwrappable.java
  thrift/src/main/java/com/linecorp/armeria/internal/thrift/ThriftFunction.java
  thrift/src/main/java/com/linecorp/armeria/internal/thrift/ThriftServiceMetadata.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpServiceBuilder.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftCallService.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceEntry.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/THttpServiceBuilderTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Labels: breaking-change, deprecation, new-feature

#2302 Update frontend dependencies
  docs-client/build.gradle
  docs-client/package.json
  docs-client/src/components/GotoSelect/index.tsx
  docs-client/yarn.lock
  licenses/web-licenses.txt
Labels: dependencies

#2305 Use `HttpRequest.of()` instead of `AggregatedHttpRequest.of()`…
  core/src/main/java/com/linecorp/armeria/client/WebClient.java
Labels: cleanup

#2301 Reduce bit operations for header validation
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
Labels: cleanup

#2303 Add flag to control header validation.
  benchmarks/src/jmh/java/com/linecorp/armeria/common/HttpHeadersBenchmark.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
Labels: performance

#2309 Fix a bug where query params disappear when `WebClient` executes
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java
Labels: defect

#2312 Move `examples/grpc-service` to `examples/grpc`
  examples/README.md
  examples/grpc/build.gradle
  examples/grpc/src/main/java/example/armeria/grpc/HelloServiceImpl.java
  examples/grpc/src/main/java/example/armeria/grpc/Main.java
  examples/grpc/src/main/proto/hello.proto
  examples/grpc/src/main/resources/.gitkeep
  examples/grpc/src/test/java/example/armeria/grpc/HelloServiceTest.java
  examples/grpc/src/test/resources/.gitkeep
  settings.gradle
Labels: cleanup

#2275 Return a CompletableFuture from API methods that checks whether…
  build.gradle
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageDrainer.java
  core/src/main/java/com/linecorp/armeria/internal/eventloop/EventLoopCheckingCompletableFuture.java
  core/src/main/java/com/linecorp/armeria/server/file/StreamingHttpFile.java
  core/src/test/java/com/linecorp/armeria/internal/eventloop/EventLoopCheckingCompletableFutureTest.java
Labels: new-feature

#2313 Fix flaky `HealthCheckServiceTest`
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
Labels: cleanup

#2310 Add grpc-service-reactor example
  NOTICE.txt
  dependencies.yml
  examples/README.md
  examples/grpc-reactor/build.gradle
  examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/HelloServiceImpl.java
  examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/Main.java
  examples/grpc-reactor/src/main/proto/hello.proto
  examples/grpc-reactor/src/main/resources/.gitkeep
  examples/grpc-reactor/src/test/java/example/armeria/grpc/reactor/HelloServiceTest.java
  examples/grpc-reactor/src/test/resources/.gitkeep
  licenses/LICENSE.reactive-grpc.bsd.txt
  settings.gradle
Labels: documentation

#2326 Small gRPC cleanups
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocServicePlugin.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
Labels: cleanup

#2330 Delegate to log.context() instead of implementing client connec…
  core/src/main/java/com/linecorp/armeria/client/ClientConnectionTimings.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/InvocationUtil.java
  site/src/sphinx/advanced-custom-attributes.rst
Labels: cleanup, deprecation

#2332 Improve exception message of `UnknownHostException`
  core/src/main/java/com/linecorp/armeria/internal/dns/DefaultDnsNameResolver.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java
Labels: cleanup, improvement

#2333 Improve the performance of query string encoding/decoding
  core/src/main/java/com/linecorp/armeria/common/QueryStringDecoder.java
  core/src/main/java/com/linecorp/armeria/common/QueryStringEncoder.java
Labels: improvement, performance

#2314 Make `RequestContextExporter` a part of public API
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperties.java
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilderTest.java
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExporterBuilder.java
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExporterBuilderTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/UnionMapTest.java
Labels: cleanup, new-feature

#2327 Allow customizing DocService when integrating with Spring Boot
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/DocServiceConfigurator.java
Labels: new-feature

#2337 Update Thrift from 0.12.0 to 0.13.0
  dependencies.yml
  thrift0.12/build.gradle
  thrift0.12/src/test/thrift/RpcDebugTest.thrift
  thrift0.12/src/test/thrift/TTextProtocolTest.thrift
  thrift0.12/src/test/thrift/cassandra.thrift
  thrift0.12/src/test/thrift/hbase.thrift
  thrift0.12/src/test/thrift/main.thrift
  thrift0.9/build.gradle
Labels: dependencies

#2336 Make `QueryString{Encoder,Decoder}` even faster
  core/src/main/java/com/linecorp/armeria/common/QueryStringDecoder.java
  core/src/main/java/com/linecorp/armeria/common/QueryStringEncoder.java
Labels: improvement, performance

#2316 Add more ways to add global annotated service extensions
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceExtensions.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactoryTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceHandlersOrderTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java
Labels: new-feature

#2236 Add Dropwizard module
  dependencies.yml
  dropwizard/build.gradle
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaBundle.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaServerConfigurator.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaServerFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/ManagedArmeriaServer.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/ArmeriaHttpConnectorFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/ArmeriaHttpsConnectorFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/ArmeriaServerDecorator.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/package-info.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/proxy/ArmeriaProxyConnectorFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/proxy/package-info.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/AccessLogWriterFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/CombinedAccessLogWriterFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/CommonAccessLogWriterFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/CustomAccessLogWriterFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/package-info.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/package-info.java
  dropwizard/src/main/resources/META-INF/services/com.linecorp.armeria.dropwizard.logging.AccessLogWriterFactory
  dropwizard/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable
  dropwizard/src/main/resources/META-INF/services/io.dropwizard.jetty.ConnectorFactory
  dropwizard/src/main/resources/META-INF/services/io.dropwizard.server.ServerFactory
  dropwizard/src/test/java/com/linecorp/armeria/dropwizard/ArmeriaConnectorFactoryTest.java
  dropwizard/src/test/java/com/linecorp/armeria/dropwizard/ArmeriaServerFactoryTest.java
  dropwizard/src/test/java/com/linecorp/armeria/dropwizard/connector/ArmeriaServerDecoratorTest.java
  dropwizard/src/test/java/com/linecorp/armeria/dropwizard/logging/AccessLogWriterFactoryTest.java
  dropwizard/src/test/resources/f.crt
  dropwizard/src/test/resources/f.jks
  dropwizard/src/test/resources/yaml/accessLogWriter/combined.yaml
  dropwizard/src/test/resources/yaml/accessLogWriter/common.yaml
  dropwizard/src/test/resources/yaml/accessLogWriter/custom-bad-format.yaml
  dropwizard/src/test/resources/yaml/accessLogWriter/custom.yaml
  dropwizard/src/test/resources/yaml/connector/http-minimal.yaml
  dropwizard/src/test/resources/yaml/connector/https-keystore.yaml
  dropwizard/src/test/resources/yaml/connector/https-minimal.yaml
  dropwizard/src/test/resources/yaml/server/http-server-minimal.yaml
  dropwizard/src/test/resources/yaml/server/https-server-minimal.yaml
  examples/README.md
  examples/dropwizard/build.gradle
  examples/dropwizard/server.yaml
  examples/dropwizard/src/main/java/example/dropwizard/DropwizardArmeriaApplication.java
  examples/dropwizard/src/main/java/example/dropwizard/DropwizardArmeriaConfiguration.java
  examples/dropwizard/src/main/java/example/dropwizard/armeria/services/http/HelloService.java
  examples/dropwizard/src/main/java/example/dropwizard/health/PingCheck.java
  examples/dropwizard/src/main/java/example/dropwizard/resources/JerseyResource.java
  examples/dropwizard/src/test/java/example/dropwizard/DropwizardArmeriaApplicationTest.java
  examples/dropwizard/src/test/java/example/dropwizard/armeria/services/http/HelloServiceTest.java
  examples/dropwizard/src/test/resources/test-server.yaml
  examples/dropwizard/test-endpoints.sh
  jetty/src/main/java/com/linecorp/armeria/server/jetty/ArmeriaConnector.java
  jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  settings.gradle
  site/src/sphinx/advanced-dropwizard-integration.rst
  site/src/sphinx/advanced.rst
  site/src/sphinx/server-access-log.rst
  site/src/sphinx/setup.rst
Labels: new-feature

#2340 Add and clean up TLS configuration methods
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/downstream/DownstreamSimpleBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/SslContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientSniTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerHeaderValidationTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/PortUnificationServerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTlsValidationTest.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/ArmeriaHttpsConnectorFactory.java
  examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/HelloConfiguration.java
  it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
  it/server/src/test/java/com/linecorp/armeria/server/http/ClientAuthIntegrationTest.java
  site/src/sphinx/advanced-spring-webflux-integration.rst
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSslConfigurationTest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/AbstractReactiveWebServerCustomKeyAliasTest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaWebClientTest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerAutoConfigurationTest.java
  testing-internal/src/main/java/com/linecorp/armeria/testing/internal/webapp/WebAppContainerTest.java
  testing/junit/src/test/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServiceExtensionTest.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
Labels: breaking-change, deprecation, new-feature

#2335 Add example:spring-boot-minimal-kotlin
  dependencies.yml
  examples/README.md
  examples/spring-boot-minimal-kotlin/build.gradle.kts
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/HelloAnnotatedService.kt
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/HelloConfiguration.kt
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/Main.kt
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/ValidationExceptionHandler.kt
  examples/spring-boot-minimal-kotlin/src/main/resources/config/application.yml
  examples/spring-boot-minimal-kotlin/src/test/kotlin/example/springframework/boot/minimal/kotlin/HelloApplicationIntegrationTest.kt
  examples/spring-boot-minimal-kotlin/src/test/resources/application-testbed.yml
  settings.gradle
Labels: documentation

#2341 Remove per-service loggers
  benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextAwareLogger.java
  core/src/main/java/com/linecorp/armeria/common/logging/LogLevel.java
  core/src/main/java/com/linecorp/armeria/internal/logging/LoggingDecorators.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: breaking-change, improvement, new-feature

#2322 Provide our own attribute mapping APIs for RequestContext
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/PathParsingBenchmark.java
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java
  brave/src/main/java/com/linecorp/armeria/internal/brave/TraceContextUtil.java
  brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapterTest.java
  brave/src/test/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/ServerRequestContextAdapterTest.java
  core/src/main/java/com/linecorp/armeria/client/ClientConnectionTimings.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/metric/AbstractMetricCollectingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/DefaultAttributeMap.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/internal/DefaultAttributeMap.java
  core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
  core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingService.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAttributeMapTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultAttributeMapTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedServiceAnnotationAliasTest.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
  examples/dropwizard/src/test/java/example/dropwizard/DropwizardArmeriaApplicationTest.java
  examples/spring-boot-minimal/src/test/java/example/springframework/boot/minimal/HelloApplicationIntegrationTest.java
  examples/spring-boot-webflux/src/test/java/example/springframework/boot/webflux/HelloApplicationIntegrationTest.java
  grpc/src/main/java/com/linecorp/armeria/unsafe/grpc/GrpcUnsafeBufferUtil.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/InvocationUtil.java
  site/src/sphinx/advanced-custom-attributes.rst
  site/src/sphinx/advanced-logging.rst
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThrottlingRpcServiceTest.java
Labels: breaking-change, new-feature

#2350 Remove Tomcat 8.0 support
  settings.gradle
  tomcat8.0/build.gradle
  tomcat8.0/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat80InputBuffer.java
  tomcat8.0/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat80OutputBuffer.java
  tomcat8.0/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat80ProtocolHandler.java
Labels: breaking-change, dependencies

#2348 Deprecates builder classes' constructors over builder methods
  core/src/main/java/com/linecorp/armeria/server/ServerListener.java
  core/src/main/java/com/linecorp/armeria/server/ServerListenerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeRpcService.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeRpcServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeService.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorsFactoryFunction.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocServiceFilter.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedDocServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerListenerTest.java
  examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/Main.java
  examples/grpc/src/main/java/example/armeria/grpc/Main.java
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/Main.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocServiceTest.java
  jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyServiceBuilder.java
  jetty/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceProvider.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceProviderBuilder.java
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlServiceProviderTest.java
  site/src/sphinx/advanced-saml.rst
  site/src/sphinx/server-annotated-service.rst
  site/src/sphinx/server-cors.rst
  site/src/sphinx/server-docservice.rst
  site/src/sphinx/server-servlet.rst
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServiceTest.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListenerBuilder.java
Labels: cleanup

#2351 Add missing Javadocs
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/util/Version.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/auth/BasicToken.java
  core/src/main/java/com/linecorp/armeria/server/auth/OAuth1aToken.java
  core/src/main/java/com/linecorp/armeria/server/auth/OAuth2Token.java
  dependencies.yml
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/ArmeriaHttpConnectorFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/ArmeriaHttpsConnectorFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/connector/proxy/ArmeriaProxyConnectorFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/AccessLogWriterFactory.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/logging/CustomAccessLogWriterFactory.java
  dropwizard/src/test/java/com/linecorp/armeria/dropwizard/ArmeriaConnectorFactoryTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/Compressor.java
  grpc/src/main/java/com/linecorp/armeria/unsafe/grpc/GrpcUnsafeBufferUtil.java
  rxjava/src/main/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionProvider.java
  settings/checkstyle/checkstyle-suppressions.xml
  settings/checkstyle/checkstyle.xml
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90ProtocolHandler.java
Labels: cleanup, documentation

#2344 Add `Clients.newContextCaptor()`
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextCaptor.java
  core/src/main/java/com/linecorp/armeria/client/ClientThreadLocalState.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextInitFailureTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientContextCaptorTest.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
Labels: defect, new-feature

#2349 Migrate all tests in examples to JUnit 5
  examples/annotated-http-service/build.gradle
  examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedServiceTest.java
  examples/grpc-reactor/build.gradle
  examples/grpc-reactor/src/test/java/example/armeria/grpc/reactor/HelloServiceTest.java
  examples/grpc/build.gradle
  examples/grpc/src/test/java/example/armeria/grpc/HelloServiceTest.java
  examples/saml-service-provider/build.gradle
  examples/server-sent-events/build.gradle
  examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
  examples/spring-boot-minimal-kotlin/build.gradle.kts
  examples/spring-boot-minimal/build.gradle
  examples/spring-boot-minimal/src/test/java/example/springframework/boot/minimal/HelloApplicationIntegrationTest.java
  examples/spring-boot-tomcat/build.gradle
  examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloControllerTest.java
  examples/spring-boot-tomcat/src/test/java/example/springframework/boot/tomcat/HelloIntegrationTest.java
  examples/spring-boot-webflux/build.gradle
  examples/spring-boot-webflux/src/test/java/example/springframework/boot/webflux/HelloApplicationIntegrationTest.java
  examples/spring-boot-webflux/src/test/java/example/springframework/boot/webflux/HelloControllerTest.java
  examples/static-files/build.gradle
  examples/static-files/src/test/java/example/armeria/server/files/MainTest.java
Labels: documentation

#2354 Integrate push and pushIfAbsent in RequestContext
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/FileWatcherRegistry.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/internal/RequestContextThreadLocal.java
  core/src/main/java/com/linecorp/armeria/internal/RequestContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
  core/src/main/java9/com/linecorp/armeria/internal/Java9RequestContextAwareCompletableFuture.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientWithContextAwareTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableCompletable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableMaybe.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableObservable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCallableSingle.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCompletable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextCompletableObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextConditionalSubscriber.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextConnectableFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextConnectableObservable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextMaybe.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextMaybeObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextObservable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextParallelFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableCompletable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableFlowable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableMaybe.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableObservable.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextScalarCallableSingle.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextSingle.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextSingleObserver.java
  rxjava/src/main/java/com/linecorp/armeria/common/rxjava/RequestContextSubscriber.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlMessageUtil.java
Labels: breaking-change, defect, deprecation

#2357 Fix annoying docs issue with empty request body
  docs-client/src/containers/MethodPage/DebugPage.tsx
Labels: defect

#2102 HTTP header/parameter-based path mapping
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/Route.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RouteCache.java
  core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/RoutingPredicate.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/annotation/MatchesHeader.java
  core/src/main/java/com/linecorp/armeria/server/annotation/MatchesHeaders.java
  core/src/main/java/com/linecorp/armeria/server/annotation/MatchesParam.java
  core/src/main/java/com/linecorp/armeria/server/annotation/MatchesParams.java
  core/src/test/java/com/linecorp/armeria/server/CachingRoutingContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerHeaderPredicatesMatchingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerParamPredicatesMatchingTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingContextTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingPredicateTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/MatchesHeaderTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/MatchesParamTest.java
  site/src/sphinx/server-annotated-service.rst
  site/src/sphinx/server-basics.rst
Labels: new-feature

#2355 Overall cleanup and deprecation
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/DefaultAddressResolverGroupFactory.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/EventCount.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounter.java
  core/src/main/java/com/linecorp/armeria/common/ClientCacheControlBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ServerCacheControlBuilder.java
  core/src/main/java/com/linecorp/armeria/common/metric/PrometheusMeterRegistries.java
  core/src/main/java/com/linecorp/armeria/common/util/Version.java
  core/src/main/java/com/linecorp/armeria/server/DecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RedirectService.java
  core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostDecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/annotation/PathPrefix.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthTokenExtractors.java
  core/src/main/java/com/linecorp/armeria/server/auth/HttpAuthService.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeRpcService.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeRpcServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeService.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/EventCountTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/MetricCollectingCircuitBreakerListenerTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/SlidingWindowCounterTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/Main.java
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/HelloConfiguration.kt
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDocStringExtractorTest.java
  saml/src/main/java/com/linecorp/armeria/server/saml/KeyStoreCredentialResolverBuilder.java
  site/src/sphinx/advanced-saml.rst
  testing/junit/src/main/java/com/linecorp/armeria/testing/junit/common/EventLoopGroupExtension.java
  testing/junit4/src/main/java/com/linecorp/armeria/testing/junit4/common/EventLoopGroupRule.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListenerBuilder.java
  zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: breaking-change, cleanup, deprecation
