Repository line/armeria, pull requests merged in 2019-11, with the labels that each got.

#2203 Add UUID From RequestContext
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequestTest.java
Labels: new-feature

#2225 Update the introductary slides to the latest one
  site/src/sphinx/_static/slides.html
  site/src/sphinx/_static/slides.pdf
  site/src/sphinx/index.rst
Labels: documentation

#2217 Add RefreshingAddressResolver
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/internal/dns/DefaultDnsNameResolver.java
  core/src/main/java/com/linecorp/armeria/internal/dns/DnsQuestionWithoutTrailingDot.java
  core/src/main/java/com/linecorp/armeria/internal/dns/DnsUtil.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestDnsServer.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
Labels: breaking-change, new-feature

#2214 Deactivate HttpSession in separate handler from codecs.
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/internal/AbstractHttp2ConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/Http1ClientCodec.java
  core/src/main/java/com/linecorp/armeria/internal/ReadSuppressingHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
Labels: cleanup

#2222 Add service level settings to annotated services
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceElement.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
Labels: defect, new-feature

#2229 Update SLF4J and Logback Javadoc URL
  dependencies.yml
Labels: cleanup

#2228 Increase the request/response timeout in `ArmeriaSpringActuator…
  spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
Labels: cleanup

#2234 Fix auto-configuration to support GrpcServiceRegistrationBeans…
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
Labels: defect

#2231 Fix not to cache DNS failure when timed out
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestDnsServer.java
Labels: defect

#2227 Fix not to push context multiple times when notifying multiple…
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogListenerInvoker.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestLogListenerInvokerTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
Labels: defect, performance

#2224 Replace `UUID` with `RequestId` and make its generation configu…
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestId.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/RequestId.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOptions.java
  core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/ThreadLocalByteArray.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
  core/src/main/java/com/linecorp/armeria/server/file/DefaultEntityTagFunction.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogType.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultRequestIdTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/internal/ThreadLocalByteArrayTest.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/StatusMessageEscaper.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  saml/src/main/java/com/linecorp/armeria/server/saml/JwtBasedSamlRequestIdManager.java
  site/src/sphinx/server-access-log.rst
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequestTest.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/TTextProtocol.java
Labels: breaking-change, new-feature

#2197 Add some missing Javadoc comments
  benchmarks/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/BackoffBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/RetryingHttpClientBase.java
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/shared/ClientType.java
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/shared/GithubApiService.java
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/shared/SimpleBenchmarkBase.java
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/PathParsingBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkBase.java
  benchmarks/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkClient.java
  settings/checkstyle/checkstyle.xml
Labels: documentation

#2240 Make `DynamicEndpointGroup` respect a weight change
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroupTest.java
Labels: defect

#2246 Remove host-level fields in `ServerBuilder`
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostDecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceConfigBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
Labels: cleanup, deprecation

#2249 Don't use exact match when checking UnknownHostException in test
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
Labels: cleanup

#2241 Make 'none+' serialization format as optional.
  core/src/main/java/com/linecorp/armeria/client/AbstractClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Scheme.java
  core/src/test/java/com/linecorp/armeria/client/ClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/SchemeTest.java
Labels: breaking-change, improvement

#2252 Set event loop for delayed responses in test.
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
Labels: cleanup

#2257 Upgrade to Gradle 6.0
  dependencies.yml
  docs-client/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#2253 Allow `HttpStatusException` to have a cause
  core/src/main/java/com/linecorp/armeria/server/HttpStatusException.java
  core/src/test/java/com/linecorp/armeria/server/HttpStatusExceptionTest.java
Labels: defect, new-feature

#2255 Make route decorators handle the requests for non-existent mapp…
  benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/CompositeRouter.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/FallbackService.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/Route.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/CompositeServiceEntry.java
  core/src/test/java/com/linecorp/armeria/server/CatchAllPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutedTest.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
Labels: new-feature

#2260 Fix flaky test in ServerTest
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
  thrift/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
Labels: cleanup

#2259 Always use `ServiceRequestContext` on the server side
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Labels: defect

#2248 Allow handling response timeout with specific cause on the clie…
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultHttpClient.java
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingHttpClient.java
  core/src/main/java/com/linecorp/armeria/common/HeaderOverridingHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/logging/NoopRequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbortingSubscriber.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java
  core/src/main/java/com/linecorp/armeria/internal/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/internal/Http2GoAwayHandler.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/client/DefaultHttpClientTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutHandlerTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/AbortCauseArgumentProvider.java
  core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultHttpRequestTest.java
  dependencies.yml
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Labels: deprecation, new-feature

#2263 Make sure a CORS preflight request doesn't go to a wrong service
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/Routed.java
  core/src/main/java/com/linecorp/armeria/server/RoutingResult.java
  core/src/main/java/com/linecorp/armeria/server/RoutingResultBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RoutingResultType.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
Labels: defect

#2265 Add `rel=nofollow` to the site badge links
  site/src/sphinx/_static/add_badges.js
Labels: miscellaneous

#2261 Allow configuring DefaultAddressResolverGroup by flag
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
Labels: defect

#2258 Allow adjusting a request/response log level
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/logging/LoggingDecorators.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: new-feature

#2230 Introduce ClientFactoryOptions
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptionValue.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
Labels: new-feature

#2266 Update dependencies
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/package-info.java
  core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupRegistryTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupAuthorityTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthCheckedEndpointGroupLongPollingTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/AuthorizerTest.java
  dependencies.yml
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/Tomcat90InputBuffer.java
Labels: dependencies

#2267 Fix to set the proper default value when creating default DefaultEven…
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
Labels: cleanup

#2281 Revert netty-tcnative-boringssl-static version to `2.0.26.Final`
  dependencies.yml
Labels: dependencies

#2063 Support CORS options for actuator.
  core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
  docs-client/build.gradle
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/CorsEndpointProperties.java
  spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
  spring/boot-actuator-autoconfigure/src/test/resources/application-autoConfTestCors.yml
Labels: new-feature

#2273 Add connection timing annotations to client spans.
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
Labels: new-feature

#2269 Change blockingTaskExecutor from Executor to ScheduledExecutorS…
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/CommonPools.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextAwareScheduledExecutorService.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/UnstoppableScheduledExecutorService.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceBlockingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunctionTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunctionTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunctionTest.java
  jetty/src/main/java/com/linecorp/armeria/server/jetty/ArmeriaThreadPool.java
  jetty/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  site/src/sphinx/advanced-production-checklist.rst
Labels: breaking-change, improvement

#2283 Clean up the factory methods in `Http{Request,Response}`
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/encoding/HttpDecodingClient.java
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HeaderOverridingHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpService.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckService.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestDuplicatorTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodedResponseTest.java
  examples/proxy-server/src/main/java/example/armeria/proxy/ProxyService.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/UnaryGrpcClient.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  testing/junit/src/main/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServerExtension.java
  testing/junit/src/test/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServiceExtensionTest.java
Labels: cleanup, deprecation, improvement
