Repository line/armeria, pull requests merged in 2019-04, with the labels that each got.

#1695 Fix `IllegalReferenceCountException` in `TwoElementFixedStreamMessage`
  core/src/main/java/com/linecorp/armeria/common/stream/EventLoopStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/TwoElementFixedStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/TwoElementFixedStreamMessageTest.java
Labels: defect

#1697 Fix a bug where `DnsEndpointGroup` does not respect search domains
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsQuestionWithoutTrailingDot.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroup.java
Labels: defect

#1699 Make CORS policy to be applied to the specific paths
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/CatchAllPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/DefaultPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/ExactPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/HttpHeaderPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/PathMapping.java
  core/src/main/java/com/linecorp/armeria/server/PrefixPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/annotation/decorator/CorsDecorator.java
  core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
  site/src/sphinx/server-cors.rst
Labels: documentation, new-feature

#1706 Don't use address for service name
  zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java
  zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java
Labels: defect

#1692 Provide a way to get the duration that was taken to get a connection
  core/src/main/java/com/linecorp/armeria/client/ClientConnectionTimings.java
  core/src/main/java/com/linecorp/armeria/client/ClientConnectionTimingsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/common/util/TextFormatter.java
  core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java
  core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLog.java
  core/src/test/java/com/linecorp/armeria/client/ClientConnectionTimingsTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/common/util/TextFormatterTest.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
  site/src/sphinx/advanced-custom-attributes.rst
  site/src/sphinx/advanced-logging.rst
  site/src/sphinx/advanced-structured-logging.rst
  site/src/sphinx/advanced-unit-testing.rst
  site/src/sphinx/advanced.rst
  site/src/sphinx/client-decorator.rst
  site/src/sphinx/server-decorator.rst
  thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftStructuredLog.java
Labels: deprecation, documentation, new-feature

#1712 Clean up RetryStrategy and RetryStrategyWithContent Javadoc
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategyWithContent.java
  site/src/sphinx/client-retry.rst
Labels: documentation

#1715 Fix NPE while DocService scans gRPC services
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDocServicePlugin.java
Labels: defect

#1713 Support disabling OpenSSL in Spring
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/Ssl.java
Labels: defect

#1716 Add HTTP content encoding property to ArmeriaSettings
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaCompressionConfigurationTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSslConfigurationTest.java
  spring/boot-autoconfigure/src/test/resources/config/application-compressionTest.yml
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Labels: new-feature

#1717 Support SslContextBuilder customizer when configuring TLS with Server…
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
Labels: defect, new-feature

#1720 Extract gRPC wire protocol core classes to a protocol package.
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaStatusException.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/protocol/Compressor.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/protocol/Decompressor.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/protocol/StatusCodes.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/protocol/package-info.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/ForwardingCompressor.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/ForwardingDecompressor.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshaller.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/StatusExceptionConverter.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/GrpcMessageMarshallerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/TestServiceImpl.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
Labels: new-feature

#1723 UnframedGrpcService now sends a response even there is no content to …
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
Labels: defect

#1714 Allow SettableHealthChecker to have chained invocation.
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/SettableHealthChecker.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/SettableHealthCheckerTest.java
Labels: breaking-change, new-feature

#1726 Make `RedirectService` preserve the query string by default
  core/src/main/java/com/linecorp/armeria/server/RedirectService.java
  core/src/test/java/com/linecorp/armeria/server/RedirectServiceTest.java
Labels: breaking-change, new-feature

#1729 Use `Class.getDeclaredField()` instead of `getField()` when fetching Thrift metadata.
  thrift/src/main/java/com/linecorp/armeria/internal/thrift/ThriftFunction.java
Labels: defect

#1707 Add `boolean shutdownOnStop` parameter to `ServerBuilder.blockingTaskExecutor()`
  core/src/main/java/com/linecorp/armeria/server/InterminableExecutorService.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
Labels: deprecation, new-feature

#1724 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  it/spring/boot-tomcat8.5/build.gradle
  spring/boot1-autoconfigure/build.gradle
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/package-info.java
  tomcat8.5/build.gradle
  zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/NodeValueCodec.java
Labels: dependencies

#1734 allow for repeated method declarations
  core/src/main/java/com/linecorp/armeria/internal/Types.java
  thrift/src/main/java/com/linecorp/armeria/internal/thrift/ThriftServiceMetadata.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
  thrift/src/test/thrift/RpcDebugTest.thrift
  thrift0.11/src/test/thrift/RpcDebugTest.thrift
  thrift0.9/src/test/thrift/RpcDebugTest.thrift
Labels: defect

#1735 DefaultPathMapping now generates the correct regex pattern for a path…
  core/src/main/java/com/linecorp/armeria/server/DefaultPathMapping.java
  core/src/test/java/com/linecorp/armeria/server/DefaultPathMappingTest.java
Labels: defect

#1727 Extract grpc protocol to separate artifact and add AbstractUnaryGrpcService.
  grpc-protocol/build.gradle
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/AbstractUnaryGrpcService.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaStatusException.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/Compressor.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/Decompressor.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/GrpcHeaderNames.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/GrpcTrailersUtil.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/StatusCodes.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/StatusMessageEscaper.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/package-info.java
  grpc/build.gradle
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/AbstractUnaryGrpcServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/StatusMessageEscaperTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  settings.gradle
Labels: new-feature

#1740 Prevent double `CorsService` decoration
  core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorFactoryFunction.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorsFactoryFunction.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
Labels: defect

#1741 `RoutingTrie` can now handle a trailing slash correctly
  core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
Labels: defect

#1746 Improve the overall look of the web site
  dependencies.yml
  site/src/sphinx/_static/add_badges.js
  site/src/sphinx/_static/center_page.js
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/_templates/layout.html
  site/src/sphinx/conf.py
  site/src/sphinx/index.rst
  site/src/sphinx/setup.rst
Labels: cleanup, documentation
