Repository line/armeria, pull requests merged in 2019-01, with the labels that each got.

#1506 Make services in DocService collapsible
  docs-client/build.gradle
  docs-client/package.json
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/yarn.lock
  licenses/web-licenses.txt
Labels: new-feature

#1513 Do not return a connection to the pool if it's scheduled for disconnection
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSession.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/Http2GoAwayHandler.java
  core/src/test/java/com/linecorp/armeria/client/Http1ConnectionCloseHeaderTest.java
  core/src/test/java/com/linecorp/armeria/client/Http1EmptyRequestTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
Labels: defect

#1516 Make HttpHeaderNames.of() accept CharSequence in lieu of String
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpHeaderUtil.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/ClientAddressSource.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogFormats.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeaderNamesTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersJsonDeserializerTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersJsonSerializerTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpDocServiceTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceRequestConverterTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedValueResolverTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpHeaderUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckServiceTest.java
  examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedHttpServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpRequest.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpResponseTest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpHeaderTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftDocServiceTest.java
  zipkin/src/main/java/com/linecorp/armeria/internal/tracing/AsciiStringKeyFactory.java
Labels: improvement

#1509 Provide a way to return a successful response with alternative status…
  core/src/main/java/com/linecorp/armeria/internal/PublisherToHttpResponseConverter.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpService.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/DefaultHttpResult.java
  core/src/main/java/com/linecorp/armeria/server/annotation/HttpResult.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/NullToNoContentResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StatusCode.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceHandlersOrderTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/ProxyProtocolEnabledServerTest.java
  core/src/test/java/com/linecorp/armeria/server/TestConverters.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java
  rxjava/src/main/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunction.java
  rxjava/src/main/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionProvider.java
  rxjava/src/test/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionProviderTest.java
  site/src/sphinx/server-access-log.rst
  site/src/sphinx/server-annotated-service.rst
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
Labels: breaking-change, new-feature

#1519 Add an example which uses Armeria with the minimal Spring Boot depend…
  examples/README.md
  examples/spring-boot-minimal/build.gradle
  examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloAnnotatedService.java
  examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloConfiguration.java
  examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/Main.java
  examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/ValidationExceptionHandler.java
  examples/spring-boot-minimal/src/main/resources/config/application.yml
  examples/spring-boot-minimal/src/test/java/example/springframework/boot/minimal/HelloApplicationIntegrationTest.java
  examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/HelloConfiguration.java
  examples/spring-boot-webflux/src/test/java/example/springframework/boot/webflux/HelloApplicationIntegrationTest.java
  settings.gradle
Labels: documentation

#1520 Additional description in README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#1517 Support different access log files for different virtual hosts.
  core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogger.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
  site/src/sphinx/server-access-log.rst
Labels: new-feature

#1527 Don't synchronize CountingSampler.
  core/src/main/java/com/linecorp/armeria/internal/logging/CountingSampler.java
Labels: performance

#1529 Less verbose error logging / Fix incorrect behavior when 'verboseExceptions' is set.
  core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
  core/src/main/java/com/linecorp/armeria/internal/Http2GoAwayHandler.java
  core/src/test/java/com/linecorp/armeria/common/util/ExceptionsTest.java
  core/src/test/java/com/linecorp/armeria/internal/Http2GoAwayHandlerTest.java
Labels: defect, improvement

#1505 Provide a way to stream an individual file
  core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFileBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/AggregatedHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/CachingHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpVfs.java
  core/src/main/java/com/linecorp/armeria/server/file/DefaultEntityTagFunction.java
  core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpVfs.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpDataFile.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileAttributes.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileService.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpVfs.java
  core/src/main/java/com/linecorp/armeria/server/file/MimeTypeUtil.java
  core/src/main/java/com/linecorp/armeria/server/file/NonExistentHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/StreamingHttpFile.java
  core/src/test/java/com/linecorp/armeria/server/file/CachingHttpFileTest.java
  core/src/test/java/com/linecorp/armeria/server/file/DefaultEntityTagFunctionTest.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/file/MimeTypeUtilTest.java
  site/src/sphinx/server-annotated-service.rst
  site/src/sphinx/server-http-file.rst
Labels: breaking-change, defect, new-feature

#1525 Add option to run gRPC callbacks in blocking executor.
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  site/src/sphinx/server-grpc.rst
Labels: new-feature

#1532 Deprecate `ClosedClientFactoryException` and use `IllegalStateException`
  core/src/main/java/com/linecorp/armeria/client/ClosedClientFactoryException.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: breaking-change, defect, deprecation

#1526 Support different CORS policy for different origins.
  core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
Labels: breaking-change, new-feature

#1535 Make Armeria(Client|Server)Configurator extend Spring's Ordered inter…
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerConfigurator.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaServerConfiguratorTest.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientAutoConfiguration.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientConfigurator.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpConnector.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientConfiguratorTest.java
Labels: breaking-change, improvement

#1543 Remove deprecated methods in CircuitBreakerListener
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerListener.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
Labels: breaking-change

#1541 Make javax.validation compileOnly
  spring/boot-autoconfigure/build.gradle
  spring/boot-webflux-autoconfigure/build.gradle
  spring/boot1-autoconfigure/build.gradle
Labels: dependencies

#1544 Update dependencies
  build.gradle
  dependencies.yml
  it/spring/boot-tomcat8.5/build.gradle
  spring/boot1-autoconfigure/build.gradle
  tomcat8.5/build.gradle
Labels: dependencies

#1540 Added a document about CORS Service.
  site/src/sphinx/server-cors.rst
  site/src/sphinx/server-grpc.rst
  site/src/sphinx/server.rst
Labels: documentation

#1546 Add the missing dependency in example
  examples/spring-boot-minimal/build.gradle
  site/src/sphinx/server-cors.rst
Labels: documentation

#1549 Make sure server max request length of 0 or Long.MAX_VALUE doesn't ca…
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/ArmeriaMessageDeframer.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Labels: defect

#1547 Add annotation-based CORS Decorator
  core/src/main/java/com/linecorp/armeria/common/HttpHeaders.java
  core/src/main/java/com/linecorp/armeria/common/ImmutableHttpHeaders.java
  core/src/main/java/com/linecorp/armeria/server/annotation/AdditionalHeader.java
  core/src/main/java/com/linecorp/armeria/server/annotation/decorator/CorsDecorator.java
  core/src/main/java/com/linecorp/armeria/server/annotation/decorator/CorsDecorators.java
  core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorFactoryFunction.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorsFactoryFunction.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
  site/src/sphinx/server-cors.rst
Labels: new-feature

#1548 Add `ClientRequestContextBuilder` and `ServiceRequestContextBuilder`
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/NoopRequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java
  core/src/main/java/com/linecorp/armeria/internal/ChannelUtil.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientDelegateTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerHttpClientTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClientTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMappingTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingHttpClientTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedValueResolverTest.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/AuthorizerTest.java
  core/src/test/java/com/linecorp/armeria/server/file/CachingHttpFileTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HttpHealthCheckServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/ManagedHttpHealthCheckServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  site/src/sphinx/advanced-unit-testing.rst
  site/src/sphinx/advanced.rst
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequestTest.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
  zipkin/src/test/java/com/linecorp/armeria/client/tracing/HttpTracingClientTest.java
  zipkin/src/test/java/com/linecorp/armeria/server/tracing/HttpTracingServiceTest.java
Labels: new-feature

#1558 Only initialize json marshaller when needed.
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcService.java
Labels: defect

#1562 Fix deprecated API usages
  core/src/main/java/com/linecorp/armeria/client/DecoratingClient.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClientFunction.java
  core/src/main/java/com/linecorp/armeria/client/FunctionalDecoratingClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogAvailability.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/crypto/BouncyCastleKeyFactoryProvider.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
Labels: cleanup

#1561 Update dependencies
  .appveyor.yml
  .travis.yml
  build.gradle
  dependencies.yml
  docs-client/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  grpc/build.gradle
  settings.gradle
Labels: dependencies

#1565 Provide a way to add multiple BindableService instances to GrpcServic…
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
Labels: new-feature

#1560 Support an alias for a bunch of annotations
  NOTICE.txt
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/AnnotationUtil.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceAnnotationAliasTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotatedHttpServiceResponseConverterTest.java
  core/src/test/java/com/linecorp/armeria/internal/annotation/AnnotationUtilTest.java
  dependencies.yml
  licenses/LICENSE.cglib.al20.txt
Labels: new-feature

#1566 Do not set Content-length header when trailing headers exists
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpMessage.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpMessageTest.java
  core/src/test/java/com/linecorp/armeria/internal/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/internal/DefaultHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunctionTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java
Labels: defect
