Repository line/armeria, pull requests merged in 2020-08, with the labels that each got.

#2958 Convert REQ_SERVICE_NAME builtInProperty to snake_case
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Labels: breaking change, defect

#2959 Remove BiFunction from HttpStreamReader
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReader.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReaderTest.java
Labels: cleanup

#2962 Fix not to raise an exception from `(Service|Client)RequestContext.cu…
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java
Labels: defect

#2961 Update dependencies
  dependencies.yml
  docs-client/package-lock.json
  docs-client/package.json
  site/package-lock.json
  site/package.json
Labels: dependencies

#2954 Add String-to-Duration converter on Spring Boot 1
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1ConversionServiceConfiguration.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1FormatterRegistrar.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/DurationStyle.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/StringToDurationConverter.java
  spring/boot1-autoconfigure/src/main/resources/META-INF/spring.factories
  spring/boot1-autoconfigure/src/test/java/com/linecorp/armeria/spring/DurationStyleTests.java
Labels: defect

#2950 Fix a bug where gRPC message deframer is closed before writing respon…
  examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
  examples/grpc-kotlin/gen-src/main/java/example/armeria/grpc/kotlin/Hello.java
  examples/grpc-kotlin/gen-src/main/kotlinGrpc/example/armeria/grpc/kotlin/HelloGrpcKt.kt
  examples/grpc-kotlin/gen-src/main/resources/META-INF/armeria/grpc/armeria-main.dsc
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/HelloServiceImpl.kt
  examples/grpc-kotlin/src/main/proto/hello.proto
  examples/grpc-kotlin/src/test/kotlin/example/armeria/grpc/kotlin/HelloServiceTest.kt
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReader.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
Labels: defect

#2964 Support compressed and base64 encoded trailers in GrpcWebUtil
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/Base64Decoder.java
  grpc-protocol/src/test/java/com/linecorp/armeria/common/grpc/protocol/Base64DecoderTest.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcWebUtil.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebRetryTest.java
Labels: improvement

#2960 Add DocServiceConfigurator into boot2-webflux-autoconfigure
  spring/boot2-webflux-autoconfigure/build.gradle
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java
Labels: defect

#2963 Add the release note for 0.99.9
  site/src/pages/news/20200514-newsletter-0.mdx
  site/src/pages/news/20200703-newsletter-1.mdx
  site/src/pages/release-notes/0.80.0.mdx
  site/src/pages/release-notes/0.81.0.mdx
  site/src/pages/release-notes/0.81.1.mdx
  site/src/pages/release-notes/0.82.0.mdx
  site/src/pages/release-notes/0.83.0.mdx
  site/src/pages/release-notes/0.84.0.mdx
  site/src/pages/release-notes/0.85.0.mdx
  site/src/pages/release-notes/0.86.0.mdx
  site/src/pages/release-notes/0.87.0.mdx
  site/src/pages/release-notes/0.88.0.mdx
  site/src/pages/release-notes/0.89.0.mdx
  site/src/pages/release-notes/0.89.1.mdx
  site/src/pages/release-notes/0.90.0.mdx
  site/src/pages/release-notes/0.90.1.mdx
  site/src/pages/release-notes/0.90.2.mdx
  site/src/pages/release-notes/0.90.3.mdx
  site/src/pages/release-notes/0.91.0.mdx
  site/src/pages/release-notes/0.92.0.mdx
  site/src/pages/release-notes/0.93.0.mdx
  site/src/pages/release-notes/0.94.0.mdx
  site/src/pages/release-notes/0.95.0.mdx
  site/src/pages/release-notes/0.96.0.mdx
  site/src/pages/release-notes/0.97.0.mdx
  site/src/pages/release-notes/0.98.0.mdx
  site/src/pages/release-notes/0.98.1.mdx
  site/src/pages/release-notes/0.98.2.mdx
  site/src/pages/release-notes/0.98.3.mdx
  site/src/pages/release-notes/0.98.4.mdx
  site/src/pages/release-notes/0.98.5.mdx
  site/src/pages/release-notes/0.98.6.mdx
  site/src/pages/release-notes/0.98.7.mdx
  site/src/pages/release-notes/0.99.0.mdx
  site/src/pages/release-notes/0.99.1.mdx
  site/src/pages/release-notes/0.99.2.mdx
  site/src/pages/release-notes/0.99.3.mdx
  site/src/pages/release-notes/0.99.4.mdx
  site/src/pages/release-notes/0.99.5.mdx
  site/src/pages/release-notes/0.99.6.mdx
  site/src/pages/release-notes/0.99.7.mdx
  site/src/pages/release-notes/0.99.8.mdx
  site/src/pages/release-notes/0.99.9.mdx
  site/src/plugins/gatsby-remark-table-of-contents-patched.js
Labels: documentation

#2966 Add the new slides by @matsumana
  site/src/components/article.tsx
  site/src/pages/community/articles.mdx
Labels: documentation

#2968 Fix a bug where `TimeoutMode.SET_FROM_START` schedules a wrong timeout
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
  core/src/test/java/com/linecorp/armeria/internal/common/TimeoutSchedulerTest.java
Labels: defect

#2969 Fix to set content-type correctly for gRPC Trailers-Only
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/GrpcTrailersUtil.java
  grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebRetryTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebTextTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramerTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/FramedGrpcServiceTest.java
Labels: defect

#2965 Ignore CancelledSubscription when handling HTTP HEAD
  core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ReactiveWebServerLoadBalancerInteropTest.java
Labels: defect

#2977 Fix a bug where different tags of WebClient are registered to Prometh…
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestOnlyLog.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithMetricsTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/HttpServiceLogNameTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceLogNameTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceLogNameTest.java
Labels: defect

#2985 Fix a bug where HAProxy server handler throws `NPE` if an address fam…
  core/src/main/java/com/linecorp/armeria/client/HAProxyHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/test/java/com/linecorp/armeria/server/ProxyProtocolEnabledServerTest.java
Labels: defect

#2982 Fix syntax in documentation example
  site/src/pages/docs/client-decorator.mdx
  site/src/pages/docs/server-decorator.mdx
Labels: documentation

#2988 Fix invalid docs for CircuitBreakerStrategy
  site/src/pages/docs/advanced-spring-webflux-integration.mdx
  site/src/pages/docs/client-retry.mdx
Labels: documentation

#2979 Add `defaultServiceName()` and `defaultLogName()` to service binding builders
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ServiceName.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestLogNameTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: breaking change, new feature

#2980 WebFlux app can't start if management.server.port is customized
  spring/boot2-webflux-autoconfigure/build.gradle
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryAutoConfiguration.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java
Labels: defect

#2993 Fix leaks in tests of DynamicBehaviorHandler and others
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientPipeliningTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/client/proxy/HAProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/ProxyProtocolEnabledServerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/HttpServiceLogNameTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  it/server/src/test/java/com/linecorp/armeria/server/http/ClientAuthIntegrationTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunctionTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSslConfigurationTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortHttpsTest.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/SimpleChannelHandler.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/SimpleChannelHandlerFactory.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
Labels: cleanup

#2971 Add `GrpcMeterIdPrefixFunction`
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilderParams.java
  core/src/main/java/com/linecorp/armeria/client/ClientDecoration.java
  core/src/main/java/com/linecorp/armeria/client/ClientDecorationBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/DefaultMeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsBuilderTest.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/GrpcTrailersUtil.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcWebUtil.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunction.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormats.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcWebTrailers.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientUtil.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcWebTrailersExtractor.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/InternalGrpcWebUtil.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebRetryTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunctionTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunction.java
  site/src/pages/docs/client-grpc.mdx
Labels: new feature

#2992 Add slf4j-simple to examples
  examples/context-propagation/dagger/build.gradle
  examples/context-propagation/kotlin/build.gradle.kts
  examples/context-propagation/manual/build.gradle
  examples/context-propagation/rxjava/build.gradle
Labels: cleanup

#2994 Fix a bug where gRPC and Thrift service name is not overriden by defa…
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceLogNameTest.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
  thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceLogNameTest.java
Labels: defect

#2995 Remove Guava dependency from examples
  examples/context-propagation/manual/build.gradle
  examples/context-propagation/manual/src/main/java/example/armeria/contextpropagation/manual/MainService.java
  examples/context-propagation/rxjava/src/main/java/example/armeria/contextpropagation/rxjava/MainService.java
Labels: cleanup

#2999 Support `RequestContext` propagation during Reactor operations
  dependencies.yml
  reactor3/build.gradle
  reactor3/src/main/java/com/linecorp/armeria/common/reactor3/RequestContextHooks.java
  reactor3/src/main/java/com/linecorp/armeria/common/reactor3/package-info.java
  reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareFluxTest.java
  reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareMonoTest.java
  settings.gradle
Labels: dependencies, new feature

#3004 Make `RequestContext.setAttr()` return an old value / Remove `*AttrIf…
  core/src/main/java/com/linecorp/armeria/common/DefaultAttributeMap.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAttributeMapTest.java
Labels: breaking change, improvement

#3001 Upgrade gRPC-Kotlin to 0.1.5
  dependencies.yml
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/HelloServiceImpl.kt
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/Main.kt
  examples/grpc-kotlin/src/test/kotlin/example/armeria/grpc/kotlin/HelloServiceTest.kt
  grpc/build.gradle
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaCoroutineContextInterceptor.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
Labels: new feature

#2983 Support Kotlin suspending functions for annotated services
  build.gradle
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/KotlinUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/KotlinUtilTest.java
  examples/annotated-http-service-kotlin/build.gradle.kts
  examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/ArmeriaRequestContext.kt
  examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/ContextAwareService.kt
  examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/DecoratingService.kt
  examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/Main.kt
  examples/annotated-http-service-kotlin/src/test/kotlin/example/armeria/server/annotated/kotlin/AnnotatedServiceTest.kt
  kotlin/build.gradle.kts
  kotlin/src/main/java/com/linecorp/armeria/common/kotlin/CoroutineContextProvider.java
  kotlin/src/main/java/com/linecorp/armeria/common/kotlin/CoroutineContexts.java
  kotlin/src/main/java/com/linecorp/armeria/common/kotlin/package-info.java
  kotlin/src/main/java/com/linecorp/armeria/server/kotlin/CoroutineContextService.java
  kotlin/src/main/java/com/linecorp/armeria/server/kotlin/package-info.java
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/CoroutineUtil.kt
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/KotlinUtil.kt
  kotlin/src/test/java/com/linecorp/armeria/internal/server/annotation/KotlinUtilWithKotlinDependenciesTest.java
  kotlin/src/test/kotlin/com/linecorp/armeria/server/ExampleService.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/SuspendingAnnotatedServiceTest.kt
  settings.gradle
Labels: new feature

#3003 Abide by Reactive Streams spec 3.6 in FixedStreamMessage
  core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/FixedStreamMessageTest.java
Labels: defect

#3008 Fix a bug where retrofit response is not completed
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriber.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilderTest.java
Labels: defect

#3005 Add Reactor context-propagation example
  examples/README.md
  examples/context-propagation/dagger/src/main/java/example/armeria/contextpropagation/dagger/MainGraph.java
  examples/context-propagation/manual/src/main/java/example/armeria/contextpropagation/manual/MainService.java
  examples/context-propagation/reactor/build.gradle
  examples/context-propagation/reactor/src/main/java/example/armeria/contextpropagation/reactor/Main.java
  examples/context-propagation/reactor/src/main/java/example/armeria/contextpropagation/reactor/MainService.java
  examples/context-propagation/rxjava/src/main/java/example/armeria/contextpropagation/rxjava/MainService.java
  kotlin/src/test/kotlin/com/linecorp/armeria/server/SuspendingAnnotatedServiceTest.kt
  settings.gradle
Labels: documentation

#3011 Add internal modifier to kotlin utility functions
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/KotlinUtil.java
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaCoroutineUtil.kt
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaKotlinUtil.kt
Labels: cleanup

#3009 Add Thrift example
  examples/README.md
  examples/thrift/build.gradle
  examples/thrift/src/main/java/example/armeria/thrift/HelloServiceImpl.java
  examples/thrift/src/main/java/example/armeria/thrift/Main.java
  examples/thrift/src/main/resources/.gitkeep
  examples/thrift/src/main/thrift/hello.thrift
  examples/thrift/src/test/java/example/armeria/thrift/HelloServiceTest.java
  examples/thrift/src/test/resources/.gitkeep
  settings.gradle
Labels: documentation

#3010 Add documentation for Kotlin coroutines
  examples/README.md
  examples/annotated-http-service-kotlin/build.gradle.kts
  examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/ContextAwareService.kt
  site/src/pages/docs/server-annotated-service.mdx
  site/src/pages/docs/setup.mdx
Labels: documentation

#3012 Rename `toHeaderValue()` to `asHeaderValue()`
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/common/auth/BasicToken.java
  core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aToken.java
  core/src/main/java/com/linecorp/armeria/common/auth/OAuth2Token.java
Labels: breaking change, cleanup

#3013 Update dependencies
  dependencies.yml
  docs-client/package-lock.json
  docs-client/package.json
  docs-client/src/components/GotoSelect/index.tsx
  examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  it/micrometer1.3/build.gradle
  site/package-lock.json
  site/package.json
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-starter/build.gradle
Labels: dependencies

#3014 Add `RequestContext.hasAttr()` and `hasOwnAttr()`
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
Labels: new feature

#3023 Use `ArmeriaHttp(Client|Server)Parser` by default in Brave decorators
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientTest.java
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceTest.java
Labels: improvement
