Repository line/armeria, pull requests merged in 2020-11, with the labels that each got.

#3112 Support prefix option for Logback integration
  core/src/main/java/com/linecorp/armeria/common/logging/ExportGroup.java
  core/src/main/java/com/linecorp/armeria/common/logging/ExportGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
  logback/src/main/java/com/linecorp/armeria/common/logback/ExportGroupConfig.java
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
  logback/src/test/java/com/linecorp/armeria/common/logback/CustomObject.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  logback/src/test/resources/com/linecorp/armeria/common/logback/testXmlConfig.xml
  site/src/pages/docs/advanced-logging.mdx
Labels: new feature

#3126 Add a release note for 1.2.0
  site/src/components/api-link.tsx
  site/src/pages/release-notes/1.2.0.mdx
  site/src/plugins/gatsby-remark-api-links.js
Labels: documentation

#3143 Add arbitrary param parsers
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtilTest.java
Labels: new feature

#3149 Reduce docs-client JS bundle size
  docs-client/src/components/GotoSelect/index.tsx
  docs-client/src/containers/MethodPage/DebugPage.tsx
Labels: cleanup

#3151 Fix silly mistake in `ProxyService` example
  examples/proxy-server/build.gradle
  examples/proxy-server/src/main/java/example/armeria/proxy/ProxyService.java
  examples/proxy-server/src/test/java/example/armeria/proxy/ProxyServiceTest.java
Labels: cleanup

#3135 Expanding CircuitBreakerMapping to include request path as a key
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerFactory.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerMapping.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerMappingBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java
Labels: new feature

#3154 Allow colon character in first segment of absolute path
  core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientContextCaptorTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
Labels: defect

#3150 Replace react-dropdown with Material-UI's Select
  docs-client/package-lock.json
  docs-client/package.json
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/EndpointPath.tsx
  docs-client/src/containers/MethodPage/HttpHeaders.tsx
  docs-client/src/containers/MethodPage/HttpQueryString.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/containers/MethodPage/style-dropdown.css
  docs-client/src/lib/types.ts
  licenses/web-licenses.txt
Labels: improvement

#3152 Fix a bug where preflight request is handled by the irrelevant routeD…
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/Route.java
  core/src/main/java/com/linecorp/armeria/server/RouteCache.java
  core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/RouteDecoratorRoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/RoutingResult.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
  core/src/test/java/com/linecorp/armeria/server/CachingRoutingContextTest.java
  core/src/test/java/com/linecorp/armeria/server/GlobPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteDecoratingServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteTest.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
Labels: defect, deprecation

#3153 Fix a bug where a gRPC ServerCall is invoked after a stream is closed
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTimeoutTest.java
Labels: defect

#3007 Use Caffeine in `RefresingAddressResolver`
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
Labels: improvement

#3164 Add documentation for annotated arbitrary types
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtilTest.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: documentation

#3163 Use javax-annotation-api instead of jakarta-annotation-api
  NOTICE.txt
  dependencies.yml
  examples/grpc-kotlin/build.gradle.kts
  examples/grpc-reactor/build.gradle
  examples/grpc/build.gradle
  grpc/build.gradle
  licenses/LICENSE.jakarta-annotation.epl20.txt
  licenses/LICENSE.javax-annotation.cddl11.txt
  thrift0.13/build.gradle
  thrift0.9/build.gradle
Labels: dependencies

#3165 Clean up cacheSpec and backoffSpec documentation
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/server/file/FileServiceBuilder.java
Labels: cleanup

#3161 Use disallowed list instead of blacklist and allow list instead of whitelist
  core/src/main/java/com/linecorp/armeria/client/IgnoreHostsTrustManager.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpHeadersUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientAdditionalHeadersTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerAdditionalHeadersTest.java
  javadoc/build.gradle
Labels: cleanup

#3167 Replace react-select with Material-UI's Autocomplete
  docs-client/package-lock.json
  docs-client/package.json
  docs-client/src/components/GotoSelect/index.tsx
  licenses/web-licenses.txt
Labels: improvement

#3038 Provide a way to consume headers and data separately from HttpResponse
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/SplitHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultSplitHttpResponse.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/NoopSubscription.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/package-info.java
  core/src/test/java/com/linecorp/armeria/common/DefaultSplitHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultSplitHttpResponseVerification.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpConnector.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpResponse.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpClientResponseSubscriber.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpResponseBodyStream.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpResponseTest.java
Labels: new feature

#3178 Strip the IPv6 scope ID in `Endpoint.withIpAddr()`
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Labels: defect

#3145 Mapping retry config by context/request parameters
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/KeyedRetryConfigMapping.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryConfig.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryConfigMapping.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClientBuilder.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/KeyedRetryConfigMappingTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: new feature

#3172 Provide a way to allow bad HTTP2 cipher suites for client
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/SslContextUtilTest.java
Labels: new feature

#3181 Fix a bug where HealthCheckedEndpointGroup.endpoints() is not set
  core/src/main/java/com/linecorp/armeria/client/endpoint/CompositeEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/LazyList.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckEndpointGroupRaceTest.java
Labels: defect

#2981 Add HttpDeframer for decoding `HttpObject`s on top of Reactive Streams
  core/src/main/java/com/linecorp/armeria/common/stream/ByteBufDeframerInput.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframer.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerHandler.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerInput.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerOutput.java
  core/src/test/java/com/linecorp/armeria/common/stream/ByteBufDeframerInputTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/HttpDeframerTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerHandler.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/DeframedMessage.java
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/HttpDeframerUtil.java
  grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
  grpc/build.gradle
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcWebTrailersExtractor.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/InternalGrpcWebUtil.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshaller.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerHandler.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReader.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebTextTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerHandlerTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshallerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpDeframerTckTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReaderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  it/grpcweb/src/test/java/com/linecorp/armeria/server/grpc/GrpcWebServiceTest.java
Labels: improvement, new feature

#3187 Fix flaky test: DefaultSplitHttpResponseTest.cancelResponse
  core/src/test/java/com/linecorp/armeria/common/DefaultSplitHttpResponseTest.java
Labels: cleanup

#3185 nit: {@code
  core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java
Labels: cleanup

#3124 Provide a way to encode and decode Protobuf in annotated services
  .scalafmt.conf
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/CompositeRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/CompositeResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ConsumesProtobuf.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ProducesProtobuf.java
  core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunctionProvider.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
  dependencies.yml
  examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/Main.kt
  examples/context-propagation/kotlin/src/main/kotlin/example/armeria/contextpropagation/kotlin/Main.kt
  gradle.properties
  protobuf/build.gradle
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionProvider.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/package-info.java
  protobuf/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.RequestConverterFunctionProvider
  protobuf/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.ResponseConverterFunctionProvider
  protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufRequestAnnotatedServiceTest.java
  protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionTest.java
  protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufResponseAnnotatedServiceTest.java
  protobuf/src/test/proto/messages.proto
  reactor3/build.gradle
  rxjava2/src/main/java/com/linecorp/armeria/internal/server/rxjava2/ObservableResponseConverterFunctionProvider.java
  rxjava3/src/main/java/com/linecorp/armeria/internal/server/rxjava3/ObservableResponseConverterFunctionProvider.java
  scalapb/scalapb_2.12/build.gradle
  scalapb/scalapb_2.13/build.gradle
  scalapb/scalapb_2.13/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.RequestConverterFunctionProvider
  scalapb/scalapb_2.13/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.ResponseConverterFunctionProvider
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionProvider.scala
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunctionProvider.scala
  scalapb/scalapb_2.13/src/test/proto/messages.proto
  scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestAnnotatedServiceTest.scala
  scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionTest.scala
  scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseAnnotatedServiceTest.scala
  settings.gradle
  site/src/pages/docs/setup.mdx
  spring/boot2-actuator-autoconfigure/build.gradle
  spring/boot2-webflux-autoconfigure/build.gradle
  testing-internal/build.gradle
Labels: new feature

#3188 Fix positioning of copy/clear response buttons in DocService
  docs-client/src/containers/MethodPage/DebugPage.tsx
Labels: cleanup

#3174 Update docs to reflect current grpc-web support
  site/src/pages/docs/server-grpc.mdx
Labels: documentation

#3166 Fix route decorator evaluation order
  core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestLogNameTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
Labels: defect

#3081 Do not collect metrics of the requests to `TransientService` by default
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/server/TransientServiceOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/TransientService.java
  core/src/main/java/com/linecorp/armeria/server/TransientServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/TransientServiceOption.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingService.java
  core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java
  core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceTest.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/PrometheusSupport.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
Labels: deprecation, new feature

#3193 Update dependencies
  build.gradle
  core/src/main/java/com/linecorp/armeria/internal/common/util/BouncyCastleKeyFactoryProvider.java
  core/src/test/java/com/linecorp/armeria/client/Http2ClientSettingsTest.java
  dependencies.yml
  examples/spring-boot-minimal-kotlin/src/test/resources/application-testbed.yml
  examples/spring-boot-minimal/src/test/resources/application-testbed.yml
  examples/spring-boot-tomcat/src/test/resources/application-testbed.yml
  examples/spring-boot-webflux/src/test/resources/application-testbed.yml
  gradle/wrapper/gradle-wrapper.properties
  grpc/build.gradle
  spring/boot1-autoconfigure/build.gradle
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationSecureTest.java
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/PrometheusMetricExposureTest.java
  spring/boot2-actuator-autoconfigure/src/test/resources/application-secureTest.yml
  spring/boot2-actuator-starter/build.gradle
  spring/boot2-autoconfigure/build.gradle
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationWithoutMeterTest.java
  spring/boot2-starter/build.gradle
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/AbstractServerHttpRequest.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpRequest.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaWebClientWithRetryingClientTest.java
Labels: defect, dependencies

#3110 Add HttpRequestBuilder
  core/src/main/java/com/linecorp/armeria/client/WebClient.java
  core/src/main/java/com/linecorp/armeria/client/WebClientRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestBuilder.java
  core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java
Labels: new feature

#3182 Support io_uring
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java
  core/src/main/java/com/linecorp/armeria/common/util/TransportType.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ChannelUtil.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestDnsServer.java
  core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
  dependencies.yml
Labels: new feature

#3194 Make ServletRequest.getProtocol() return a correct value
  jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java
  testing-internal/src/main/webapp/index.jsp
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Labels: defect

#3192 Add documentation for ScalaPB
  site/src/components/code-block.tsx
  site/src/pages/docs/advanced-scalapb.mdx
  site/src/pages/docs/toc.json
Labels: documentation

#3199 Fix a bug where a `CacheEntry` is failed to clear in `RefreshingAddre…
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
Labels: defect

#3183 Support Thrift custom protocol
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/ThriftProtocolFactories.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/ThriftProtocolFactoryProvider.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/ThriftSerializationFormats.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/DefaultThriftProtocolFactoryProvider.java
  thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpServiceBuilder.java
  thrift0.13/src/main/resources/META-INF/services/com.linecorp.armeria.common.thrift.ThriftProtocolFactoryProvider
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientRequestContextInitFailureTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
  thrift0.13/src/test/resources/META-INF/services/com.linecorp.armeria.common.SerializationFormatProvider
  thrift0.13/src/test/resources/META-INF/services/com.linecorp.armeria.common.thrift.ThriftProtocolFactoryProvider
Labels: new feature

#2935 Add facility to capture dns metrics
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultDnsQueryLifecycleObserver.java
  core/src/main/java/com/linecorp/armeria/client/DefaultDnsQueryLifecycleObserverFactory.java
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsNameEncoder.java
Labels: new feature

#3118 Handle cookies on client
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/client/PublicSuffixBenchmark.java
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/client/cookie/AcceptOriginCookiePolicy.java
  core/src/main/java/com/linecorp/armeria/client/cookie/CookieClient.java
  core/src/main/java/com/linecorp/armeria/client/cookie/CookieJar.java
  core/src/main/java/com/linecorp/armeria/client/cookie/CookiePolicy.java
  core/src/main/java/com/linecorp/armeria/client/cookie/CookieState.java
  core/src/main/java/com/linecorp/armeria/client/cookie/DefaultCookieJar.java
  core/src/main/java/com/linecorp/armeria/client/cookie/SetCookieResponse.java
  core/src/main/java/com/linecorp/armeria/client/cookie/package-info.java
  core/src/main/java/com/linecorp/armeria/common/Cookie.java
  core/src/main/java/com/linecorp/armeria/common/CookieBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultCookie.java
  core/src/main/java/com/linecorp/armeria/internal/client/PublicSuffix.java
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  core/src/test/java/com/linecorp/armeria/client/cookie/AcceptOriginCookiePolicyTest.java
  core/src/test/java/com/linecorp/armeria/client/cookie/CookieClientTest.java
  core/src/test/java/com/linecorp/armeria/client/cookie/DefaultCookieJarTest.java
  core/src/test/java/com/linecorp/armeria/client/cookie/SetCookieResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/ClientCookieDecoderTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultCookieTest.java
  core/src/test/java/com/linecorp/armeria/common/ServerCookieEncoderTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/PublicSuffixTest.java
Labels: new feature

#3201 Fix a leak in `ByteBufDeframerInput`
  core/src/main/java/com/linecorp/armeria/common/stream/ByteBufDeframerInput.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframer.java
  core/src/test/java/com/linecorp/armeria/common/stream/ByteBufDeframerInputTest.java
Labels: defect

#3171 Add advanced-metrics docs to web site
  site/src/pages/docs/advanced-metrics.mdx
  site/src/pages/docs/toc.json
Labels: documentation

#3200 Update developer-guide.mdx
  site/src/pages/community/developer-guide.mdx
Labels: documentation

#3203 Clean up `HttpDeframer` and gRPC
  core/src/main/java/com/linecorp/armeria/client/DefaultDnsQueryLifecycleObserver.java
  core/src/main/java/com/linecorp/armeria/common/stream/ByteBufDeframerInput.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultHttpDeframer.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframer.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerHandler.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerInput.java
  core/src/main/java/com/linecorp/armeria/common/stream/HttpDeframerOutput.java
  core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/HttpDeframerTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/HttpDeframerUtil.java
  grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerHandler.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerHandlerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpDeframerTckTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerTest.java
Labels: cleanup

#3202 Use `ClassValue` for the map whose key is `Class`
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOption.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java
Labels: defect

#3204 Cache frontend packages
  .appveyor.build.sh
  docs-client/.npmrc
  docs-client/build.gradle
  site/.npmrc
  site/build.gradle
Labels: cleanup

#3177 Add Accept-Language parsing and prioritizing
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeaders.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
  core/src/test/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilderTest.java
Labels: new feature

#3205 Update dependencies
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpRequest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpRequestTest.java
  dependencies.yml
Labels: dependencies

#3206 Clean up `RetryingClient`
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/KeyedRetryConfigMapping.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryConfig.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryConfigMapping.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: cleanup

#3197 Provide a way to customize gRPC Status mapping rule
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcStatusFunction.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerHandler.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpDeframerTckTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcStatusMappingTest.java
Labels: defect, new feature
