Repository line/armeria, pull requests merged in 2020-03, with the labels that each got.

#2550 Migrate deprecated or removed API on documentations
  site/src/sphinx/advanced-unit-testing.rst
  site/src/sphinx/advanced-zookeeper.rst
  site/src/sphinx/client-circuit-breaker.rst
  site/src/sphinx/client-custom-http-headers.rst
  site/src/sphinx/client-service-discovery.rst
  site/src/sphinx/server-decorator.rst
Labels: documentation

#2549 Add documentation creating WebClient using HealthCheckedEndpointGroup
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  site/src/sphinx/client-service-discovery.rst
Labels: cleanup

#2555 Upgrade to Dropwizard 1.3.20
  dependencies.yml
Labels: dependencies

#2557 Do not leak ping tasks in `HealthCheckService`
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
Labels: defect

#2558 Update dependencies
  build.gradle
  dependencies.yml
  docs-client/yarn.lock
  gradle/wrapper/gradle-wrapper.properties
  licenses/web-licenses.txt
Labels: dependencies

#2559 Increase timeout for BraveClientIntegrationTest
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
Labels: cleanup

#2503 Make `Throttling*Service` responses configurable
  core/src/main/java/com/linecorp/armeria/server/throttling/AbstractThrottlingService.java
  core/src/main/java/com/linecorp/armeria/server/throttling/AbstractThrottlingServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingAcceptHandler.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingRejectHandler.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingRpcService.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingRpcServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingService.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/throttling/ThrottlingServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/throttling/ThrottlingStrategyTest.java
Labels: new feature

#2409 Send an HTTP/2 PING frame on an idle connection
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/IdleTimeoutHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandlerTest.java
Labels: new feature

#2552 Revamp ZooKeeper{EndpointGroupBuilder, UpdatingListenerBuilder}
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/AbstractCuratorFrameworkBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/internal/common/zookeeper/ZooKeeperDefaults.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListenerBuilder.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupTest.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/ZooKeeperTestBase.java
  zookeeper/src/test/java/com/linecorp/armeria/common/zookeeper/ZooKeeperExtension.java
  zookeeper/src/test/java/com/linecorp/armeria/common/zookeeper/ZooKeeperTestUtil.java
  zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: cleanup

#2563 Fix naming mistakes in HTTP/2 ping options
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Labels: cleanup

#2565 Fix Javadoc errors in `QueryParams`
  core/src/main/java/com/linecorp/armeria/common/QueryParams.java
Labels: documentation

#2564 Do not warn blocking future operations when done
  core/src/main/java/com/linecorp/armeria/common/CompletableRpcResponse.java
  core/src/main/java/com/linecorp/armeria/common/util/EventLoopCheckingFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractRequestContextAwareFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/EventLoopCheckingUtil.java
  core/src/test/java/com/linecorp/armeria/common/util/EventLoopCheckingFutureTest.java
Labels: defect

#2548 Do not add additionalTrailers to ResponseHeaders
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java
  core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientAdditionalHeadersTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientDelegateTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithMetricsTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerAdditionalHeadersTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteDecoratingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/TestServiceImpl.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  site/src/sphinx/server-decorator.rst
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpHeaderTest.java
Labels: defect

#2546 Allow setting example paths and queries for DocService
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/docs/MethodInfo.java
  core/src/main/java/com/linecorp/armeria/server/docs/ServiceInfo.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/docs/MethodInfoTest.java
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/EndpointPath.tsx
  docs-client/src/containers/MethodPage/HttpQueryString.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/lib/specification.tsx
  docs-client/src/lib/transports/annotated-http.ts
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java
Labels: new feature

#2553 Handle exceptions from Subscribers
  NOTICE.txt
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/OneElementFixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/RegularFixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/TwoElementFixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java
  core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
  core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
  core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/SubscriberThrowingExceptionTest.java
  licenses/LICENSE.rxjava.al20.txt
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
Labels: defect

#2556 Add support for Dropwizard 2.0.x
  dependencies.yml
  dropwizard/build.gradle
  dropwizard/src/test/resources/dropwizard-armeria-app.yaml
  dropwizard1/build.gradle
  settings.gradle
Labels: dependencies, new feature

#2567 Deduplicate timeout code in RequestContext implementations
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
Labels: cleanup

#2569 Require using Assert4J for test case assertions
  CONTRIBUTING.md
Labels: documentation

#2568 Add documentation for the order of client decoration
  core/src/main/java/com/linecorp/armeria/client/ClientDecoration.java
  core/src/main/java/com/linecorp/armeria/client/ClientDecorationBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/ContentPreviewerTest.java
  site/src/sphinx/advanced-structured-logging.rst
  site/src/sphinx/client-decorator.rst
Labels: documentation

#2570 Add all HTTP methods to route when the method is empty
  core/src/main/java/com/linecorp/armeria/common/HttpMethod.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/Route.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
Labels: defect

#2572 Do not warn on unexpected exceptions in annotated services
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/DefaultExceptionHandler.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionVerbosity.java
Labels: cleanup

#2560 Copy RequestLog properties to child in RetryingClient
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestOnlyLog.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
Labels: defect

#2580 Specify why on `Closed{Session,Stream}Exception`
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/common/ClosedSessionException.java
  core/src/main/java/com/linecorp/armeria/common/stream/ClosedStreamException.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/StreamingCallSubscriberTest.java
Labels: improvement

#2581 Handle the exception raised by `RetryStrategy`
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: defect

#2582 Remove unnecessary header copies when deriving a context
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
Labels: defect

#2579 Fix a bug where `ConcurrencyLimitingClient` fails with…
  core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
Labels: defect

#2584 Make `RetryingClient` handle negative nano time properly
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
Labels: defect

#2577 Allow `UUID` to be bound to annotated service parameters
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java
  site/src/sphinx/server-annotated-service.rst
Labels: new feature

#2583 Warn if context is pushed illegally
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractRequestContextAwareFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
  core/src/test/java/com/linecorp/armeria/internal/common/RequestContextAwareFutureTest.java
  core/src/test/java9/com/linecorp/armeria/internal/common/Java9RequestContextAwareFutureTest.java
Labels: cleanup

#2586 Update dependencies
  dependencies.yml
  docs-client/build.gradle
  docs-client/yarn.lock
Labels: dependencies

#2587 Make `RequestContextAwareLogger` push context
  core/src/main/java/com/linecorp/armeria/common/RequestContextAwareLogger.java
Labels: defect

#2496 Client-side proxy support
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/client/proxy/ConnectProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/DirectProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/ProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/ProxyType.java
  core/src/main/java/com/linecorp/armeria/client/proxy/Socks4ProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/Socks5ProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/package-info.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/DynamicBehaviorHandler.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/NettyServerExtension.java
Labels: new feature

#2590 Fix a bug where response is not closed with an exception
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
Labels: defect

#2591 Reimplement `RequestContext.toString()`
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/util/TextFormatter.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/TemporaryThreadLocals.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/common/util/TextFormatterTest.java
Labels: improvement, new feature

#2592 Change CountingSampler to accept float instead of double
  core/src/main/java/com/linecorp/armeria/common/util/CountingSampler.java
  core/src/main/java/com/linecorp/armeria/common/util/Sampler.java
  core/src/main/java/com/linecorp/armeria/common/util/Samplers.java
  core/src/test/java/com/linecorp/armeria/common/util/CountingSamplerTest.java
  core/src/test/java/com/linecorp/armeria/common/util/SamplerTest.java
Labels: defect

#2594 Wrap the exception with UnprocessedRequestException when fails to wri…
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
Labels: improvement

#2372 Streamline HTTP header/trailer validation and conversion
  benchmarks/src/jmh/java/com/linecorp/armeria/common/HttpRequestHeaderConversionBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/common/HttpResponseHeaderConversionBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/client/HttpHeaderUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/server/ServerHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
Labels: cleanup, improvement, performance

#2571 Revamp `RequestContext.set{Request,Response}Timeout()`
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/util/TimeoutMode.java
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultTimeoutControllerTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java
Labels: breaking change, cleanup, new feature

#2562 Fix AuthSuccessHandler to use HttpRequest and HttpResponse
  core/src/main/java/com/linecorp/armeria/server/auth/AuthFailureHandler.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthSuccessHandler.java
Labels: breaking change, defect

#2599 Provide a way to access a parent log from a child log
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogAccess.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
Labels: new feature

#2597 Assign stream ID right before writing RequestHeaders
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSession.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
Labels: defect

#2604 Switch from TSLint to ESLint
  docs-client/.eslintrc.js
  docs-client/.prettierrc.js
  docs-client/package.json
  docs-client/src/components/GotoSelect/index.tsx
  docs-client/src/components/VariableList/index.tsx
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/EnumPage/index.tsx
  docs-client/src/containers/HomePage/index.tsx
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/EndpointPath.tsx
  docs-client/src/containers/MethodPage/Endpoints.tsx
  docs-client/src/containers/MethodPage/Exceptions.tsx
  docs-client/src/containers/MethodPage/HttpHeaders.tsx
  docs-client/src/containers/MethodPage/HttpQueryString.tsx
  docs-client/src/containers/MethodPage/RequestBody.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/lib/json-prettify.ts
  docs-client/src/lib/specification.tsx
  docs-client/src/lib/transports/index.ts
  docs-client/src/lib/transports/transport.ts
  docs-client/src/lib/versions.tsx
  docs-client/webpack.config.ts
  docs-client/yarn.lock
  licenses/web-licenses.txt
  settings/eslint/eslintrc.js
  settings/prettier/prettierrc.js
Labels: cleanup

#2613 Fix `IllegalStateException` while building a WebFlux response
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
Labels: defect

#2614 Fix intermittent test failure in SubscriberThrowingExceptionTest
  core/src/test/java/com/linecorp/armeria/common/stream/SubscriberThrowingExceptionTest.java
Labels: cleanup

#2609 Wrap ProxyConnectException with UnprocessedRequestException
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
Labels: defect

#2612 Allow monitoring `Executor` and Reactor `Scheduler` together with Prometheus
  NOTICE.txt
  core/src/main/java/com/linecorp/armeria/internal/common/metric/ExecutorServiceMetrics.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedCallable.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedExecutor.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedExecutorService.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedRunnable.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedScheduledExecutorService.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/common/metric/DropwizardMeterRegistriesTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/ExecutorServiceMetricsTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
Labels: breaking change, improvement

#2566 Added `armeria-bucket4j` to throttle based on token buckets
  NOTICE.txt
  bucket4j/build.gradle
  bucket4j/src/main/java/com/linecorp/armeria/common/throttling/ThrottlingHeaders.java
  bucket4j/src/main/java/com/linecorp/armeria/common/throttling/ThrottlingHeadersImpl.java
  bucket4j/src/main/java/com/linecorp/armeria/common/throttling/package-info.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/BandwidthLimit.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucket.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketBuilder.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketSpec.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketThrottlingStrategy.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketThrottlingStrategyBuilder.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/package-info.java
  bucket4j/src/test/java/com/linecorp/armeria/server/throttling/bucket4j/BandwidthLimitTest.java
  bucket4j/src/test/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketTest.java
  bucket4j/src/test/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketThrottlingStrategyTest.java
  dependencies.yml
  licenses/LICENSE.bucket4j.al20.txt
  settings.gradle
Labels: new feature

#2610 Provide a way to customize context propagation using its own storage
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextStorage.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextStorageProvider.java
  core/src/main/java/com/linecorp/armeria/common/ThreadLocalRequestContextStorage.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextThreadLocal.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  it/context-storage/build.gradle
  it/context-storage/src/test/java/com/linecorp/armeria/common/CustomRequestContextStorageProvider.java
  it/context-storage/src/test/java/com/linecorp/armeria/common/RequestContextStorageCustomizingTest.java
  it/context-storage/src/test/resources/META-INF/services/com.linecorp.armeria.common.RequestContextStorageProvider
  settings.gradle
Labels: new feature

#2622 Add support for gRPC CallCredentials.
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/CallCredentialsDecoratingClient.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: new feature

#2620 Fix the ResponseHeaders log to contain additional headers
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientHttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpHeadersUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/server/ServerHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/server/ServerHttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerAdditionalHeadersTest.java
Labels: defect

#2623 Fix a bug where DNS resolution is not timed out
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DnsTimeoutException.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
Labels: defect

#2624 Fix a bug where `Single<HttpResponse>` is not serialized properly in annotated service
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  rxjava/src/test/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionTest.java
  rxjava2/src/test/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunctionTest.java
Labels: defect

#2616 Make `ClosedSessionException` extend `ClosedStreamException`
  core/src/main/java/com/linecorp/armeria/common/ClosedSessionException.java
  core/src/main/java/com/linecorp/armeria/common/stream/ClosedStreamException.java
  core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
Labels: breaking change, cleanup

#2625 Update dependencies
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  build.gradle
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  it/spring/boot-tomcat8.5/build.gradle
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-starter/build.gradle
  tomcat8.5/build.gradle
  zookeeper/build.gradle
Labels: dependencies

#2626 Add `ServiceConfig.defaultLogName()`
  benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  brave/src/main/java/com/linecorp/armeria/server/brave/ServiceRequestContextAdapter.java
  brave/src/test/java/com/linecorp/armeria/server/brave/ServerRequestContextAdapterTest.java
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/FallbackService.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostDecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
  core/src/main/java/com/linecorp/armeria/server/file/CachingHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogger.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestLogNameTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/HelloServiceImpl.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlDecorator.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlService.java
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
Labels: defect, dependencies, new feature

#2631 Do not encode response when the status indicates empty content
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
  core/src/test/java/com/linecorp/armeria/server/HttpResponseSubscriberTest.java
  core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodedResponseTest.java
  dependencies.yml
Labels: defect

#2630 Log which health checkers are not listenable
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
Labels: improvement

#2638 fix typo : res -> req
  site/src/sphinx/server-basics.rst
Labels: cleanup

#2642 Downgrade ZooKeeper
  dependencies.yml
Labels: dependencies

#2641 Fix a bug where `useEffect()` has wrong dependencies in DebugPage
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/MethodPage/DebugPage.tsx
Labels: defect
