Repository line/armeria, pull requests merged in 2020-07, with the labels that each got.

#2855 Use the default settings for `Logging{Client,Service}`'s default fact…
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: breaking change, cleanup

#2857 Parameterize `PooledHttpStreamMessage`
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/unsafe/PooledStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/unsafe/PooledStreamMessageTest.java
Labels: cleanup

#2858 Change the return type of `PooledHttpData` methods inherited from `By…
  core/src/main/java/com/linecorp/armeria/common/unsafe/ByteBufHttpData.java
  core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpData.java
Labels: cleanup

#2834 Return `ContextAwareEventLoop` from `RequestContext.eventLoop()`
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareEventLoop.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareExecutorService.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareFuture.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareFutureListener.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareLogger.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareProgressiveFutureListener.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareProgressivePromise.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwarePromise.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareScheduledExecutorService.java
  core/src/main/java/com/linecorp/armeria/common/ContextHolder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultContextAwareEventLoop.java
  core/src/main/java/com/linecorp/armeria/common/DefaultContextAwareExecutorService.java
  core/src/main/java/com/linecorp/armeria/common/DefaultContextAwareScheduledExecutorService.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextUtil.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbortedStreamException.java
  core/src/main/java/com/linecorp/armeria/common/stream/CancelledSubscriptionException.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractContextAwareFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/ContextAwareFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/JavaVersionSpecific.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java
  core/src/main/java/com/linecorp/armeria/server/auth/Authorizer.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/throttling/AbstractThrottlingService.java
  core/src/main/java9/com/linecorp/armeria/internal/common/Java9ContextAwareFuture.java
  core/src/main/java9/com/linecorp/armeria/internal/common/Java9ContextAwareMinimalStage.java
  core/src/main/java9/com/linecorp/armeria/internal/common/Java9VersionSpecific.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/ContextAwareFutureTest.java
  core/src/test/java9/com/linecorp/armeria/internal/common/Java9ContextAwareFutureTest.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
  examples/context-propagation/dagger/src/main/java/example/armeria/contextpropagation/dagger/Main.java
  examples/context-propagation/kotlin/src/main/kotlin/example/armeria/contextpropagation/kotlin/MainService.kt
  examples/context-propagation/manual/src/main/java/example/armeria/contextpropagation/manual/MainService.java
  examples/context-propagation/rxjava/src/main/java/example/armeria/contextpropagation/rxjava/MainService.java
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/HelloServiceImpl.kt
  examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/HelloServiceImpl.java
  examples/grpc-scala/src/main/scala/example/armeria/grpc/scala/HelloServiceImpl.scala
  examples/grpc/src/main/java/example/armeria/grpc/HelloServiceImpl.java
  grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcStatusCauseTest.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaWebClientTest.java
Labels: breaking change, deprecation

#2848 Provide a utility that parses gRPC-Web trailers from a response content
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcWebUtil.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/InternalGrpcWebUtil.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebRetryTest.java
Labels: new feature

#2839 Add MeterIdPrefixFunction.andThen to customize MeterIdPrefix using RequestLog
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionCustomizer.java
  core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java
Labels: deprecation, new feature

#2865 Update dependencies
  dependencies.yml
  docs-client/package-lock.json
  docs-client/package.json
  examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
  gradle/wrapper/gradle-wrapper.properties
  site/package-lock.json
  site/package.json
Labels: dependencies

#2861 Separate `HttpFile` and `AggregateHttpFile` from each other
  core/src/main/java/com/linecorp/armeria/common/unsafe/PooledAggregatedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpResponse.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFileBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/AggregatedHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/AggregatedHttpFileBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/CachingHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/FileService.java
  core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpDataFile.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/NonExistentAggregatedHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/NonExistentHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/StreamingHttpFile.java
  core/src/test/java/com/linecorp/armeria/server/file/CachingHttpFileTest.java
  core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
  site/src/pages/docs/server-http-file.mdx
Labels: breaking change, cleanup

#2864 Allow a request to schedule timeout in nanoseconds precision
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultTimeoutController.java
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutController.java
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultTimeoutControllerTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
Labels: breaking change, defect

#2866 Add 0.99.8 release note
  site/src/pages/release-notes/0.99.8.mdx
Labels: documentation

#2867 Fix flaky test `BraveServiceIntegrationTest.childCompletesBeforeServer`
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
Labels: cleanup

#2868 Fix the URLs of diagrams in the web site
  site/src/plugins/gatsby-remark-draw-patched.js
Labels: documentation

#2870 Add the newsletter vol. 1 / Update the article list
  site/src/components/article-list.module.less
  site/src/pages/community/articles.json
  site/src/pages/news/20200703-newsletter-1.mdx
Labels: documentation

#2874 Fix artifact-id missing
  site/src/pages/docs/advanced-spring-webflux-integration.mdx
Labels: documentation

#2872 Improve mobile navigation
  site/src/layouts/base.tsx
  site/src/layouts/header.module.less
  site/src/layouts/header.tsx
  site/src/layouts/mdx.module.less
  site/src/layouts/mdx.tsx
Labels: documentation

#2879 Do not show floating hamburger for dual-column view
  site/src/layouts/header.module.less
Labels: documentation

#2853 Allow binding an annotated service method without a path
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceNullablePathTest.java
Labels: new feature

#2876 Use annotations in errorprone
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  build.gradle
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpData.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractContextAwareFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/server/TestConverters.java
  dependencies.yml
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/TestServiceImpl.java
  rxjava2/src/main/java/com/linecorp/armeria/common/rxjava2/RequestContextAssembly.java
  rxjava3/src/main/java/com/linecorp/armeria/common/rxjava3/RequestContextAssembly.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
Labels: improvement

#2883 Fix `ArmeriaEurekaClientTest` not to hang
  eureka/src/test/java/com/linecorp/armeria/client/eureka/ArmeriaEurekaClientTest.java
Labels: cleanup

#2878 Do not fill `:authority` header if `Host` header exists in HTTP/2
  core/src/main/java/com/linecorp/armeria/client/ClientHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/server/ProxyServerAuthorityHeaderTest.java
Labels: breaking change, defect

#2884 Update GrpcServiceRegistrationBean migration guide
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcServiceRegistrationBean.java
Labels: documentation

#2875 Hide over-exposed public APIs
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/EventCount.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointSelectionStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java
  core/src/main/java/com/linecorp/armeria/client/logging/ConnectionPoolLoggingListener.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageDrainer.java
  core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutController.java
  core/src/main/java/com/linecorp/armeria/internal/logging/package-info.java
  core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java
  core/src/main/java/com/linecorp/armeria/server/ExecutorBasedExecutorService.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/RoutingPredicate.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFileAttributes.java
  examples/spring-boot-webflux/src/main/java/example/springframework/boot/webflux/HelloController.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcJsonMarshallerBuilder.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcJsonUtil.java
  rxjava2/src/main/java/com/linecorp/armeria/common/rxjava2/RequestContextCallableCompletable.java
  rxjava2/src/main/java/com/linecorp/armeria/common/rxjava2/RequestContextCallableObservable.java
  rxjava2/src/main/java/com/linecorp/armeria/common/rxjava2/RequestContextScalarCallableCompletable.java
  rxjava2/src/main/java/com/linecorp/armeria/common/rxjava2/RequestContextScalarCallableFlowable.java
  rxjava2/src/main/java/com/linecorp/armeria/common/rxjava2/RequestContextScalarCallableMaybe.java
  rxjava2/src/main/java/com/linecorp/armeria/common/rxjava2/RequestContextScalarCallableSingle.java
  rxjava3/src/main/java/com/linecorp/armeria/common/rxjava3/RequestContextScalarSupplierFlowable.java
  rxjava3/src/main/java/com/linecorp/armeria/common/rxjava3/RequestContextScalarSupplierMaybe.java
  rxjava3/src/main/java/com/linecorp/armeria/common/rxjava3/RequestContextScalarSupplierSingle.java
  rxjava3/src/main/java/com/linecorp/armeria/common/rxjava3/RequestContextSupplierObservable.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerConfigBuilder.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/ArmeriaWebServer.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpConnector.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/text/SequenceContext.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/text/TTextProtocol.java
Labels: cleanup, deprecation

#2881 Use JUnit 5 in documentation
  site/src/pages/docs/advanced-custom-attributes.mdx
  site/src/pages/docs/advanced-dropwizard-integration.mdx
  site/src/pages/docs/advanced-logging.mdx
  site/src/pages/docs/advanced-unit-testing.mdx
  site/src/pages/docs/client-circuit-breaker.mdx
  site/src/pages/docs/client-custom-http-headers.mdx
  site/src/pages/docs/client-retry.mdx
  site/src/pages/docs/client-service-discovery.mdx
  site/src/pages/docs/client-thrift.mdx
  site/src/pages/docs/server-access-log.mdx
  site/src/pages/docs/server-annotated-service.mdx
  site/src/pages/docs/server-basics.mdx
  site/src/pages/docs/server-cors.mdx
  site/src/pages/docs/server-decorator.mdx
  site/src/pages/docs/server-grpc.mdx
  site/src/pages/docs/server-http-file.mdx
Labels: cleanup

#2886 Fix flaky tests
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebRetryTest.java
  it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
Labels: cleanup

#2888 Fix flaky test `ArmeriaReactiveWebServerFactoryTest.shouldRunOnSpecif…
  dependencies.yml
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java
Labels: cleanup

#2887 Successful events for proxy ssl should be ignored
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
Labels: defect

#2885 Remove anuraaga from owners
  .github/CODEOWNERS
Labels: miscellaneous

#2891 Fix a buffer leak in Thrift client
  thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientBuilderTest.java
Labels: defect

#2752 Introduce ProxyConfigSelector
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/client/proxy/ConnectProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/DirectProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/ProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/ProxyConfigSelector.java
  core/src/main/java/com/linecorp/armeria/client/proxy/Socks4ProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/Socks5ProxyConfig.java
  core/src/main/java/com/linecorp/armeria/client/proxy/StaticProxyConfigSelector.java
  core/src/main/java/com/linecorp/armeria/client/proxy/WrappingProxyConfigSelector.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyConfigTest.java
  core/src/test/java/com/linecorp/armeria/client/proxy/WrappingProxyConfigSelectorTest.java
Labels: breaking change, new feature

#2889 Add `decorators` method for passing multiple decorators to ServiceConfigSetters
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingTest.java
Labels: new feature

#2893 Ignore userInfo when parsing Endpoint
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Labels: defect

#2905 Fix a bug where ContentPreviewer unexpectly releases an HttpData
  core/src/main/java/com/linecorp/armeria/common/logging/ContentPreviewerFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/LengthLimitingContentPreviewer.java
  core/src/test/java/com/linecorp/armeria/common/logging/ContentPreviewerFactoryTest.java
Labels: defect

#2909 Update frontend dependencies
  docs-client/package-lock.json
  docs-client/package.json
  site/package-lock.json
  site/package.json
Labels: dependencies

#2910 Use simpler return type for `ServerConfig.requestIdGenerator()`
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
Labels: cleanup

#2901 Add more information to `ProtocolViolationException`
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
Labels: cleanup

#2912 Update dependencies
  dependencies.yml
  dropwizard1/build.gradle
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/Main.kt
  examples/grpc-kotlin/src/test/kotlin/example/armeria/grpc/kotlin/HelloServiceTest.kt
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/HelloAnnotatedService.kt
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/HelloConfiguration.kt
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/ValidationExceptionHandler.kt
  examples/spring-boot-minimal-kotlin/src/test/kotlin/example/springframework/boot/minimal/kotlin/HelloApplicationIntegrationTest.kt
  it/micrometer1.3/build.gradle
  it/spring/boot2-tomcat8/build.gradle
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-starter/build.gradle
  tomcat8/build.gradle
Labels: dependencies

#2908 Add `CheckReturnValue` annotation on streaming output
  core/src/main/java/com/linecorp/armeria/client/HttpClient.java
  core/src/main/java/com/linecorp/armeria/client/WebClient.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/server/HttpService.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionHandlerFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthFailureHandler.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaWebClient.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceFunction.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlSingleSignOnHandler.java
Labels: improvement

#2913 API cleanup
  annotation-processor/src/main/java/com/linecorp/armeria/server/annotation/processor/DocumentationProcessor.java
  bucket4j/src/main/java/com/linecorp/armeria/common/throttling/ThrottlingHeaders.java
  bucket4j/src/main/java/com/linecorp/armeria/common/throttling/package-info.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/BandwidthLimit.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucket.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketBuilder.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketThrottlingStrategy.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketThrottlingStrategyBuilder.java
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/package-info.java
  core/src/main/java/com/linecorp/armeria/client/AbstractEventLoopEntry.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListenerWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/main/java/com/linecorp/armeria/common/Cookie.java
  core/src/main/java/com/linecorp/armeria/common/Cookies.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextInitFailureTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultEventLoopSchedulerTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithEmptyEndpointGroupTest.java
  grpc/src/main/java/com/linecorp/armeria/unsafe/grpc/GrpcUnsafeBufferUtil.java
  grpc/src/main/java/com/linecorp/armeria/unsafe/grpc/package-info.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientRequestContextInitFailureTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientRequestContextInitFailureTest.java
Labels: cleanup

#2906 Use thread-local buffer in `Endpoint.toString()`
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
Labels: improvement

#2916 Make `ProxyConfigSelector` a functional interface
  core/src/main/java/com/linecorp/armeria/client/proxy/ProxyConfigSelector.java
  core/src/main/java/com/linecorp/armeria/client/proxy/StaticProxyConfigSelector.java
Labels: cleanup

#2915 Allow `@Blocking` annotation to be used at the class level
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Blocking.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBlockingTest.java
Labels: new feature

#2914 Fix flaky `ServiceBindingTest`
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingTest.java
Labels: cleanup

#2919 Add 'Effective gRPC' by @viktortnk
  site/src/pages/community/articles.json
Labels: documentation

#2898 Decorate all services with MetricCollectingService when integrates with Spring Boot
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Labels: defect

#2927 Add a bunch of `final` keywords
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/RetryingClientBase.java
  core/src/main/java/com/linecorp/armeria/client/AbstractEventLoopState.java
  core/src/main/java/com/linecorp/armeria/client/AbstractWebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/PooledChannel.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/AbstractCircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/AbstractCircuitBreakerClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerConfig.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/metric/AbstractMetricCollectingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/AbstractAggregatedHttpMessage.java
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultContextAwareExecutorService.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/QueryParamsBase.java
  core/src/main/java/com/linecorp/armeria/common/StringMultimap.java
  core/src/main/java/com/linecorp/armeria/common/logging/LengthLimitingContentPreviewer.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriter.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/RegularFixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOption.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOptionValue.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOptions.java
  core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractContextAwareFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractHttp2ConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractHttp2ConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/ReadSuppressingHandler.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/server/Http1ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java
  core/src/main/java/com/linecorp/armeria/server/throttling/AbstractThrottlingService.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingStrategy.java
  core/src/main/java9/com/linecorp/armeria/internal/common/Java9VersionSpecific.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit5/server/mock/MockWebServerExtension.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/PipeBuffer.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/DynamicBehaviorHandler.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/TemporaryFolder.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/text/PairContext.java
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatService.java
  zookeeper3/src/main/java/com/linecorp/armeria/common/zookeeper/AbstractCuratorFrameworkBuilder.java
Labels: breaking change, cleanup

#2929 Use hard links for build caches
  .appveyor.build.sh
Labels: cleanup

#2925 Add `useBlockingTaskExecutor()` to annotated service binding builders
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBlockingTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java
Labels: new feature

#2928 Move `Client(Factory)Option.CONSTANT` to `Client(Factory)Options`
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaClientUtil.java
  grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  junit5/src/test/java/com/linecorp/armeria/testing/junit5/server/mock/MockWebServiceExtensionTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilderTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
Labels: cleanup, deprecation

#2922 Fix more flaky tests in `armeria-zookeeper3`
  zookeeper3/src/test/java/com/linecorp/armeria/common/zookeeper/ZooKeeperTestUtil.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceDiscoveryCompatibilityTest.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ServerSetRegistrationTest.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: cleanup

#2931 Improve newsletter sign-up forms
  site/src/components/mailchimp.module.less
  site/src/components/mailchimp.tsx
  site/src/layouts/footer.module.less
  site/src/layouts/footer.tsx
  site/src/layouts/header.module.less
  site/src/layouts/header.tsx
  site/src/layouts/mdx.module.less
  site/src/layouts/mdx.tsx
  site/src/pages/community/index.mdx
  site/src/pages/news/sign-up.mdx
Labels: documentation

#2930 Fix a bug where grpc-web trailers not compressed
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/GrpcTrailersUtil.java
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/GrpcTrailersUtil.java
  grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcWebUtil.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshaller.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebRetryTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/GrpcTestUtil.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Labels: defect

#2933 Add human-readable route string for Route
  brave/src/main/java/com/linecorp/armeria/server/brave/ServiceRequestContextAdapter.java
  brave/src/test/java/com/linecorp/armeria/server/brave/ServerRequestContextAdapterTest.java
  core/src/main/java/com/linecorp/armeria/server/CatchAllPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/ExactPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/PathMapping.java
  core/src/main/java/com/linecorp/armeria/server/PrefixPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMappingWithPrefix.java
  core/src/main/java/com/linecorp/armeria/server/Route.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/file/FileService.java
  core/src/test/java/com/linecorp/armeria/server/CatchAllPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/ExactPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/ParameterizedPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/PathWithPrefixTest.java
  core/src/test/java/com/linecorp/armeria/server/PrefixPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/RegexPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteTest.java
Labels: deprecation, new feature

#2934 Revamp community article list
  site/src/components/article-list.module.less
  site/src/components/article-list.tsx
  site/src/components/article.module.less
  site/src/components/article.tsx
  site/src/components/thank-you.tsx
  site/src/layouts/header.module.less
  site/src/layouts/header.tsx
  site/src/layouts/list-all.tsx
  site/src/layouts/mdx.module.less
  site/src/layouts/mdx.tsx
  site/src/layouts/release-notes.tsx
  site/src/pages/community/articles.json
  site/src/pages/community/articles.mdx
  site/src/pages/release-notes/list.tsx
Labels: documentation

#2936 Fix wrong artifact versions in documentation
  site/src/pages/docs/advanced-dropwizard-integration.mdx
  site/src/pages/docs/advanced-saml.mdx
  site/src/pages/docs/advanced-spring-webflux-integration.mdx
  site/src/pages/docs/setup.mdx
Labels: documentation

#2686 Support servlet API
  examples/servlet-adapter/build.gradle
  examples/servlet-adapter/src/main/java/example/armeria/server/servlet/HomeServlet.java
  examples/servlet-adapter/src/main/java/example/armeria/server/servlet/Main.java
  examples/servlet-adapter/src/test/java/example/armeria/server/servlet/MainTest.java
  servlet4/build.gradle
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/DefaultServletContext.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/DefaultServletHttpRequest.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/DefaultServletHttpResponse.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/DefaultServletOutputStream.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/DefaultServletRegistration.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/DefaultServletService.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/ServletBuilder.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/ServletFilterChain.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/ServletRequestDispatcher.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/ServletUrlMapper.java
  servlet4/src/main/java/com/linecorp/armeria/server/servlet/package-info.java
  servlet4/src/test/java/com/linecorp/armeria/server/servlet/ServletContextPathTest.java
  servlet4/src/test/java/com/linecorp/armeria/server/servlet/ServletEmptyContextPathTest.java
  servlet4/src/test/java/com/linecorp/armeria/server/servlet/ServletServiceTest.java
  servlet4/src/test/java/com/linecorp/armeria/server/servlet/ServletUrlMapperTest.java
  settings.gradle
Labels: new feature

#2941 Chooses the first `EventLoop` to send a request randomly
  core/src/main/java/com/linecorp/armeria/client/DefaultEventLoopScheduler.java
  core/src/test/java/com/linecorp/armeria/client/DefaultEventLoopSchedulerTest.java
  core/src/test/java/com/linecorp/armeria/client/MaxNumEventLoopsPerEndpointTest.java
Labels: improvement

#2944 Reduce the minimum allowed ping interval
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
Labels: improvement

#2938 Support grpc-web-text
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/GrpcServiceBenchmark.java
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/downstream/LargePayloadBenchmark.java
  dependencies.yml
  grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/Base64Decoder.java
  grpc-protocol/src/main/java/com/linecorp/armeria/server/grpc/protocol/AbstractUnsafeUnaryGrpcService.java
  grpc-protocol/src/test/java/com/linecorp/armeria/common/grpc/protocol/Base64DecoderTest.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcWebUtil.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormats.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshaller.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcSerializationFormatProvider.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/unsafe/grpc/GrpcUnsafeBufferUtil.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebRetryTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcWebTextTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcSerializationFormatsTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshallerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  it/grpcweb/build.gradle
  it/grpcweb/src/test/java/com/example/helloworld/GreeterServiceImpl.java
  it/grpcweb/src/test/java/com/linecorp/armeria/server/grpc/GrpcWebServiceTest.java
  it/grpcweb/src/test/proto/helloworld.proto
  settings.gradle
  site/src/pages/docs/client-grpc.mdx
  site/src/pages/docs/server-grpc.mdx
Labels: new feature

#2942 Add Open Graph metadata to the web site pages
  site/gatsby-config.js
  site/src/layouts/base.tsx
  site/src/layouts/community.tsx
  site/src/layouts/docs.tsx
  site/src/layouts/mdx.tsx
  site/src/pages/index.tsx
  site/static/og-image.png
Labels: documentation

#2948 Add a new community video from @okue
  site/src/pages/community/articles.mdx
Labels: documentation

#2945 Update dependencies
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  dependencies.yml
  docs-client/package-lock.json
  docs-client/package.json
  examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
  it/micrometer1.3/build.gradle
  it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
  it/spring/boot2-tomcat8/build.gradle
  settings.gradle
  site/package-lock.json
  site/package.json
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-starter/build.gradle
Labels: dependencies

#2946 Fix a bug where grpc-web-text add line-feed when base64 encoding
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageFramer.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/Base64Decoder.java
  grpc-protocol/src/test/java/com/linecorp/armeria/common/grpc/protocol/Base64DecoderTest.java
Labels: cleanup

#2939 Add `when*TimingOut` and `when*TimedOut` to `{Service,Client}RequestContext`
  brave/src/test/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextTest.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultTimeoutController.java
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutController.java
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutHandlerTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultTimeoutControllerTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/TimeoutSchedulerTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
Labels: deprecation, new feature

#2951 Fix buffer leak on DNS query timeout
  build.gradle
  core/src/main/java/com/linecorp/armeria/common/ByteArrayHttpData.java
  core/src/main/java/com/linecorp/armeria/common/ByteBufHttpData.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestDnsServer.java
  core/src/test/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolverTest.java
Labels: defect

#2955 Fix a leak in `ArmeriaClientCall`
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
Labels: defect

#2956 Run with aggressive leak detection during CI build
  .appveyor.build.sh
  .appveyor.yml
Labels: cleanup

#2957 Remove a parameter from `UnmodifiableFuture.doCancel()`
  core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java
Labels: cleanup
