Repository line/armeria, pull requests merged in 2020-05, with the labels that each got.

#2687 Fix a bug where two threads access MPSC queue
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
Labels: defect

#2679 Use IP address to register service information in ZooKeeper discovery…
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/util/InetAddressPredicates.java
  core/src/main/java/com/linecorp/armeria/common/util/SystemInfo.java
  core/src/test/java/com/linecorp/armeria/common/util/InetAddressPredicatesTest.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
Labels: improvement, new feature

#2685 Fix a bug where `HttpStreamReader` calls deframer multiple times with…
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReader.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReaderTest.java
Labels: defect

#2692 Fix a bug where ClassLoader blocks thread when using TTEXT
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/common/CacheableClassLoader.java
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/common/ClassLoadBenchmark.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java
Labels: defect

#2640 Create properties files based on Doc Comments for Rest APIs
  annotation-processor/build.gradle
  annotation-processor/src/main/java/com/linecorp/armeria/server/annotation/processor/DocumentationProcessor.java
  annotation-processor/src/main/java/com/linecorp/armeria/server/annotation/processor/package-info.java
  annotation-processor/src/main/resources/META-INF.services/javax.annotation.processing.Processor
  annotation-processor/src/test/java/com/linecorp/armeria/server/annotation/processor/DocumentationProcessorTest.java
  annotation-processor/src/test/resources/DocumentationProcessor/NoJavaDoc.java.txt
  annotation-processor/src/test/resources/DocumentationProcessor/WithJavaDoc.java.txt
  dependencies.yml
  examples/spring-boot-minimal-kotlin/build.gradle.kts
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/HelloAnnotatedService.kt
  examples/spring-boot-minimal/build.gradle
  settings.gradle
Labels: new feature

#2689 Update to Micrometer 1.5.1 LTS
  NOTICE.txt
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/ExecutorServiceMetrics.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedCallable.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedExecutor.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedExecutorService.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedRunnable.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/TimedScheduledExecutorService.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/ExecutorServiceMetricsTest.java
  dependencies.yml
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-starter/build.gradle
Labels: dependencies

#2684 Support `@LocalArmeriaPort`, `@LocalArmeriaPorts`
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaBeanPostProcessor.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaBeanPostProcessor.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaBeanPostProcessorConfiguration.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/LocalArmeriaPort.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/LocalArmeriaPorts.java
  spring/boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortHttpsTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortTest.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortsTest.java
  spring/boot-webflux-autoconfigure/build.gradle
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/ArmeriaWebServer.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/LocalArmeriaPortTest.java
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1BeanPostProcessor.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1BeanPostProcessorConfiguration.java
  spring/boot1-autoconfigure/src/main/resources/META-INF/spring.factories
Labels: new feature

#2691 Fix for issue #2688 (armeria-jetty: ArmeriaConnector - NPE when DEBUG logging enabled)
  jetty/src/main/java/com/linecorp/armeria/server/jetty/ArmeriaConnector.java
  jetty/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceStartupTest.java
Labels: defect

#2702 Allow PING scheduling with no idle timeout
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
Labels: defect

#2699 Fix a bug where a connection is not closed immediatley when HTTP/2 PING write fails
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
Labels: defect

#2700 Reduce the overhead of piggybacked connection attempts in `HttpChanne…
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSession.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
Labels: performance

#2704 Fix code example for MetricCollectingRpcClient
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingRpcClient.java
Labels: cleanup

#2703 Fix flaky test `HttpServerKeepAliveHandlerTest.clientShouldSendPingWi…
  core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
Labels: cleanup

#2661 Provide a way to build `RetryRule` and `RetryRuleWithContent`
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/WithDuplicator.java
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/WithoutDuplicator.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryDecision.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleUtil.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContent.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategyWithContent.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Cookie.java
  core/src/main/java/com/linecorp/armeria/common/HttpMethod.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedElementNameUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/docs/FieldInfoBuilder.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientUnwrapTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseDecoderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryStrategyBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryStrategyBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientAuthorityHeaderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientLoadBalancingTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithMetricsTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingHttpClientWithContextAwareTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultHttpRequestDuplicatorTest.java
  core/src/test/java/com/linecorp/armeria/server/AbstractBindingBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/client/grpc/GrpcClientUnwrapTest.java
  site/src/sphinx/client-retry.rst
  thrift/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java
  thrift/src/test/java/com/linecorp/armeria/internal/client/thrift/THttpClientUnwrapTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListenerBuilder.java
Labels: breaking change, dependencies, new feature

#2707 Update dependencies
  build.gradle
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersTest.java
  core/src/test/java/com/linecorp/armeria/common/QueryParamsTest.java
  dependencies.yml
  docs-client/build.gradle
  docs-client/yarn.lock
  dropwizard1/build.gradle
  examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  it/spring/boot-tomcat8.5/build.gradle
  licenses/web-licenses.txt
  site/build.gradle
  tomcat8.5/build.gradle
  zookeeper/build.gradle
Labels: dependencies

#2705 Handle h1c retry failure correctly for proxy requests
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/NettyServerExtension.java
Labels: defect

#2701 Support Eureka service discovery
  NOTICE.txt
  core/src/main/java/com/linecorp/armeria/client/AbstractWebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
  dependencies.yml
  eureka/build.gradle
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/package-info.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/Application.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/Applications.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/ApplicationsDeserializer.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/DataCenterInfo.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/DataCenterInfoSerializer.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaClientUtil.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaWebClient.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/InstanceInfo.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/LeaseInfo.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/package-info.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/InstanceInfoBuilder.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/package-info.java
  eureka/src/test/java/com/linecorp/armeria/client/eureka/ArmeriaEurekaClientTest.java
  eureka/src/test/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupTest.java
  eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
  licenses/LICENSE.eureka.al20.txt
  settings.gradle
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupBuilder.java
Labels: new feature

#2706 Implement TTEXT_NAMED_ENUM serialization format
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftJacksonModule.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftJacksonSerializers.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftProtocolFactories.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftSerializationFormats.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/TTextProtocol.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/TTextProtocolFactory.java
  thrift/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftSerializationFormatProvider.java
  thrift/src/test/java/com/linecorp/armeria/common/thrift/text/TTextProtocolTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
  thrift/src/test/resources/com/linecorp/armeria/common/thrift/text/TTextNamedEnumProtocol_TestData.txt
  thrift/src/test/resources/com/linecorp/armeria/common/thrift/text/TTextNamedEnumProtocol_TestData_Serialized.txt
  thrift/src/test/thrift/TTextProtocolTest.thrift
  thrift0.12/src/test/thrift/TTextProtocolTest.thrift
  thrift0.9/src/test/thrift/TTextProtocolTest.thrift
Labels: new feature

#2709 Fix a bug where a response cause is not propagated when retrying a fa…
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/retry/WithDuplicator.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleUtil.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContent.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithMetricsTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: defect

#2710 Add the release notes for 0.99.5 and update the newsletter
  site/src/layouts/mdx.module.less
  site/src/pages/index.tsx
  site/src/pages/news/20200429-newsletter-0.mdx
  site/src/pages/news/20200514-newsletter-0.mdx
  site/src/pages/release-notes/0.99.5.mdx
Labels: documentation

#2711 Fix flaky test `HttpServerKeepAliveHandlerTest.shouldCloseConnectionW…
  core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
Labels: cleanup

#2714 Remove excessive margin between a paragraph and sublist
  site/src/layouts/mdx.module.less
Labels: documentation

#2695 Updates to Brave 5.12.1
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
  dependencies.yml
Labels: dependencies

#2725 Updates to Brave 5.12.3
  dependencies.yml
Labels: dependencies

#2716 Fix ClassNotFoundException for Spring Boot 2.3.0
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/SimpleHttpCodeStatusMapper.java
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
  spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/SimpleHttpCodeStatusMapperTest.java
Labels: defect

#2723 Add `RequestContextStorage.hook()`
  core/src/main/java/com/linecorp/armeria/common/RequestContextStorage.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextStorageWrapper.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
  it/context-storage/src/test/java/com/linecorp/armeria/common/CustomRequestContextStorageProvider.java
  it/context-storage/src/test/java/com/linecorp/armeria/common/RequestContextStorageCustomizingTest.java
Labels: new feature

#2724 Add `RequestScopedMdc` for request-scoped MDC properties
  core/src/main/java/com/linecorp/armeria/common/logging/RequestScopedMdc.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestScopedMdcTest.java
Labels: new feature

#2727 Pull up `root` and `ownAttr(s)` access methods
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestScopedMdc.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
Labels: improvement

#2729 Make `RequestScopedMdc` properties are inherited
  core/src/main/java/com/linecorp/armeria/common/logging/RequestScopedMdc.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestScopedMdcTest.java
Labels: improvement

#2697 Enable using generated documentation properties files in DocService
  annotation-processor/src/main/java/com/linecorp/armeria/server/annotation/processor/DocumentationProcessor.java
  annotation-processor/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  annotation-processor/src/test/java/com/linecorp/armeria/server/annotation/processor/DocumentationProcessorTest.java
  core/src/main/java/com/linecorp/armeria/internal/annotation/package-info.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/ProcessedDocumentationHelper.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java
  core/src/test/resources/com.linecorp.armeria.docstrings.annotated.com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactoryTest.DescriptionAnnotatedTestClass.properties
  examples/spring-boot-minimal-kotlin/build.gradle.kts
  examples/spring-boot-minimal/build.gradle
  examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloAnnotatedService.java
  settings.gradle
  site/src/pages/docs/server-docservice.mdx
Labels: new feature

#2730 Fix a bug where a WebClient created without URI does not respect auth…
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
Labels: defect

#2734 Fix flaky test `WebClientBuilderTest.authorityHeader()`
  core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
Labels: cleanup

#2732 Do not use HTML entities for zero-length response
  docs-client/src/lib/transports/annotated-http.ts
Labels: defect

#2736 Allow retrying when an `EndpointGroup` is empty.
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
  brave/src/main/java/com/linecorp/armeria/server/brave/ServiceRequestContextAdapter.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultEventLoopScheduler.java
  core/src/main/java/com/linecorp/armeria/client/EventLoopScheduler.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointSelector.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/StaticEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/test/java/com/linecorp/armeria/client/DefaultEventLoopSchedulerTest.java
  core/src/test/java/com/linecorp/armeria/client/MaxNumEventLoopsPerEndpointTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithContextAwareTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithEmptyEndpointGroupTest.java
Labels: breaking change, defect

#2735 Fix a bug where ArmeriaHttpUtil throws NPE when failing to read versi…
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
Labels: defect

#2721 Regex based sanitizer implementation for logging client and service
  core/src/main/java/com/linecorp/armeria/common/logging/RegexBasedSanitizer.java
  core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: new feature

#2742 Guarantee backward compatibility with Micrometer 1.3.x
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
  it/micrometer1.3/build.gradle
  settings.gradle
Labels: defect

#2733 Update dependencies
  dependencies.yml
  examples/grpc-kotlin/src/test/kotlin/example/armeria/grpc/kotlin/HelloServiceTest.kt
  gradle/wrapper/gradle-wrapper.properties
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
Labels: dependencies

#2744 Set missing serviceLevelObjectives in Micrometer 1.3
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
Labels: cleanup

#2745 Add the release notes for 0.99.6
  site/src/pages/release-notes/0.99.5.mdx
  site/src/pages/release-notes/0.99.6.mdx
Labels: documentation

#2748 Switch from Yarn to NPM
  docs-client/README.md
  docs-client/build.gradle
  docs-client/package-lock.json
  docs-client/package.json
  docs-client/src/components/GotoSelect/index.tsx
  docs-client/src/components/VariableList/index.tsx
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/EnumPage/index.tsx
  docs-client/src/containers/HomePage/index.tsx
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/EndpointPath.tsx
  docs-client/src/containers/MethodPage/Endpoints.tsx
  docs-client/src/containers/MethodPage/Exceptions.tsx
  docs-client/src/containers/MethodPage/HttpHeaders.tsx
  docs-client/src/containers/MethodPage/HttpQueryString.tsx
  docs-client/src/containers/MethodPage/RequestBody.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/lib/specification.tsx
  docs-client/src/lib/transports/index.ts
  docs-client/src/lib/transports/transport.ts
  docs-client/src/lib/versions.tsx
  docs-client/tslint.json
  docs-client/webpack.config.ts
  docs-client/yarn.lock
  licenses/web-licenses.txt
  site/README.md
  site/build.gradle
  site/gatsby-node.js
  site/gatsby-ssr.js
  site/package-lock.json
  site/package.json
  site/src/components/alert.tsx
  site/src/components/api-link.tsx
  site/src/components/article-list.tsx
  site/src/components/aspect-ratio.tsx
  site/src/components/blockquote.tsx
  site/src/components/code-block.tsx
  site/src/components/emoji.tsx
  site/src/components/logo.tsx
  site/src/components/mailchimp.tsx
  site/src/components/marketing.tsx
  site/src/components/max-width.tsx
  site/src/components/project-badge.tsx
  site/src/components/thank-you.tsx
  site/src/layouts/base.tsx
  site/src/layouts/community.tsx
  site/src/layouts/docs.tsx
  site/src/layouts/header.tsx
  site/src/layouts/list-all.tsx
  site/src/layouts/mdx.tsx
  site/src/layouts/news.tsx
  site/src/layouts/release-notes.tsx
  site/src/layouts/short-url.tsx
  site/src/pages/404.tsx
  site/src/pages/index.tsx
  site/src/pages/news/list.tsx
  site/src/pages/release-notes/list.tsx
  site/src/plugins/gatsby-remark-api-links.js
  site/src/plugins/gatsby-remark-table-of-contents-patched.js
  site/yarn.lock
Labels: cleanup
