Repository line/armeria, pull requests merged in 2020-04, with the labels that each got.

#2644 Fix a bug where `toQueryString()` with empty `QueryParams`
  core/src/main/java/com/linecorp/armeria/common/QueryStringEncoder.java
  core/src/test/java/com/linecorp/armeria/common/QueryParamsTest.java
Labels: defect

#2643 Compute grpc-timeout header after processing grpc deadline instead of…
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: defect

#2650 Fix stale java version requirement at homepage
  site/src/sphinx/setup.rst
Labels: cleanup

#2648 Add gRPC-web to client documentation
  site/src/sphinx/client-grpc.rst
Labels: documentation

#2647 Fix `ConcurrentModificationException` in `HealthCheckedEndpointGroup`
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
Labels: defect

#2652 Add `RetryStrategy.onException()`
  core/src/main/java/com/linecorp/armeria/client/retry/HttpStatusBasedRetryStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
Labels: new feature

#2653 Publish all-in-one Javadoc JAR to Maven Central
  javadoc/build.gradle
  settings.gradle
Labels: documentation

#2654 Fix a bug where a recursive union struct failed to decode in TTEXT protocol
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java
  thrift/src/main/java/com/linecorp/armeria/internal/common/thrift/TByteBufTransport.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftTreeStructureTest.java
  thrift/src/test/thrift/TreeStructTest.thrift
  thrift0.12/src/test/thrift/TreeStructTest.thrift
  thrift0.9/src/test/thrift/TreeStructTest.thrift
Labels: defect

#2646 Add seconds suffix to LONG_TASK_TIMER for legacy convention
  core/src/main/java/com/linecorp/armeria/common/metric/MoreNamingConventions.java
Labels: defect

#2618 Updates to Brave 5.11.2 and backfills tests
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
  dependencies.yml
Labels: cleanup, dependencies

#2657 Fix a bug where `DocService` sends a wrong HTTP method if a method ha…
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
  docs-client/src/containers/MethodPage/index.tsx
Labels: defect

#2635 Prettify output of REST calls in DocService if JSON
  docs-client/src/lib/transports/annotated-http.ts
Labels: improvement

#2658 Fix incorrect Logback settings in documentation
  site/src/sphinx/advanced-logging.rst
Labels: cleanup

#2660 Remove Google Analytics from references
  gradle.properties
  site/build.gradle
Labels: cleanup

#2636 Add HTTP/1 PING(`OPTIONS *`)
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/IdleTimeoutHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http1ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttpObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIdleTimeoutHandlerTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerIdleTimeoutHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
Labels: breaking change, new feature

#2667 Do not limit ConcurrencyLimitingClient when maxConcurrency is MAX_VALUE
  core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
Labels: defect

#2666 Fix a leak in `HttpResponseSubscriber`
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
Labels: defect

#2665 Make DNS resolver handle timeout correctly when querying AAAA & A…
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolver.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
Labels: defect

#2671 Use tryFailure in HttpChannelPool
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
Labels: cleanup

#2659 Add `Server.blockUntilShutdown()`
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
Labels: new feature

#2675 Distinguish initialization and state changes of circuit breaker
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerListener.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerListenerAdapter.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreaker.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
Labels: improvement
