Repository line/armeria, pull requests merged in 2020-06, with the labels that each got.

#2754 Clean up build tasks
  .appveyor.build.sh
  .appveyor.yml
  docs-client/README.md
  docs-client/build.gradle
  docs-client/package.json
  site/README.md
  site/build.gradle
  site/src/pages/community/developer-guide.mdx
  spring/boot1-autoconfigure/build.gradle
Labels: cleanup

#2755 Use LF line ending for all OSes
  .appveyor.yml
  .gitattributes
Labels: cleanup

#2718 Specific headers such as :status, grpc-message, etc. in gRPC should not be duplicate
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/MetadataUtil.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/MetadataUtilTest.java
Labels: defect

#2759 Fix incorrect ToC margin and 404 rendering
  site/package-lock.json
  site/package.json
  site/src/layouts/mdx.module.less
  site/src/pages/404.module.less
Labels: cleanup

#2751 Improve the exception message for the case of unexpected type
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
Labels: improvement

#2749 Support Curator Service Discovery and Spring Cloud ZooKeeper
  core/src/main/java/com/linecorp/armeria/server/Server.java
  dependencies.yml
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
  zookeeper/build.gradle
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/CuratorDiscoverySpec.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/CuratorDiscoverySpecBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/LegacyZookeeperDiscoverySpec.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroup.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZookeeperDiscoverySpec.java
  zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/AbstractCuratorFrameworkBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/NodeValueCodec.java
  zookeeper/src/main/java/com/linecorp/armeria/internal/common/zookeeper/CuratorXNodeValueCodec.java
  zookeeper/src/main/java/com/linecorp/armeria/internal/common/zookeeper/LegacyNodeValueCodec.java
  zookeeper/src/main/java/com/linecorp/armeria/internal/common/zookeeper/ZookeeperPathUtil.java
  zookeeper/src/main/java/com/linecorp/armeria/internal/common/zookeeper/package-info.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/CuratorRegistrationSpec.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/CuratorRegistrationSpecBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/LegacyZookeeperRegistrationSpec.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListenerBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZookeeperRegistrationSpec.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/CuratorDiscoverySpecTest.java
  zookeeper/src/test/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupTest.java
  zookeeper/src/test/java/com/linecorp/armeria/common/zookeeper/NodeValueCodecTest.java
  zookeeper/src/test/java/com/linecorp/armeria/common/zookeeper/ZooKeeperTestUtil.java
  zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceDiscoveryCompatibilityTest.java
  zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: breaking change, new feature

#2764 Fix NPE in HttpSessionHandler
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/Http2ClientSettingsTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpSessionHandlerTest.java
Labels: defect

#2757 Make the requests go to the URI that is specified when `WebClient` is…
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientRequestPathTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
Labels: breaking change, defect

#2740 Provide a way to trigger a timeout without scheduler
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultTimeoutController.java
  core/src/main/java/com/linecorp/armeria/internal/common/TimeoutScheduler.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeService.java
  core/src/main/java/com/linecorp/armeria/server/composition/AbstractCompositeServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/CompositeServiceEntry.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeRpcService.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeRpcServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeService.java
  core/src/main/java/com/linecorp/armeria/server/composition/SimpleCompositeServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextBuilderTest.java
Labels: deprecation, new feature

#2765 Return HTTP/1.1 connection to the pool after request is complete
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/Http1ConnectionReuseTest.java
Labels: defect

#2771 Add missing selectionStrategy setter for `EurekaEndpointGroup`
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
Labels: cleanup

#2502 Add not to bind on the specific port(s) from Spring Boot (Actuator)
  spring/boot-actuator-autoconfigure/build.gradle
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
  spring/boot-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
  spring/boot-actuator-autoconfigure/src/test/resources/application-secureTest.yml
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationNetUtil.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-webflux-autoconfigure/build.gradle
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Labels: new feature

#2747 Provide a way to close a connection when exceeding the maximum age on server-side
  core/src/main/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http1ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
Labels: new feature

#2775 Fix typo: </exports> -> </export>
  site/src/pages/docs/advanced-logging.mdx
Labels: cleanup

#2777 Use npm ci instead npm install
  docs-client/build.gradle
  site/build.gradle
Labels: cleanup

#2773 Allow injecting `null` into annotated service methods if annotated wi…
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePluginTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceNullableParamTest.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: new feature

#2778 Fix flaky test `ServerMaxConnectionAgeTest.http1MaxConnectionAge`
  core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
Labels: cleanup

#2772 Apply errorprone
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
  build.gradle
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java
  core/src/main/java/com/linecorp/armeria/common/logging/ContentPreviewerFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/SubscriptionOptionTest.java
  core/src/test/java/com/linecorp/armeria/server/TestConverters.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
  dependencies.yml
  docs-client/package-lock.json
  examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitClassAwareMeterIdPrefixFunction.java
  rxjava/src/test/java/com/linecorp/armeria/common/rxjava/RequestContextAssemblyTest.java
  rxjava2/src/test/java/com/linecorp/armeria/common/rxjava2/RequestContextAssemblyTest.java
Labels: improvement

#2774 Validate a boolean parameter strictly in annotated services
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
Labels: defect

#2770 Add builder for OAuth1aToken
  core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aToken.java
  core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aTokenBuilder.java
  core/src/main/java/com/linecorp/armeria/server/auth/OAuth1aTokenExtractor.java
  core/src/test/java/com/linecorp/armeria/common/auth/OAuth1aTokenTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
Labels: new feature

#2783 Support java.time.Period type for `@Param` annotation
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: new feature

#2776 Fix the errors reported by NullAway
  build.gradle
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultTimeoutController.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
Labels: cleanup

#2781 Logback <exports> tag does not work
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  logback/src/test/resources/com/linecorp/armeria/common/logback/testXmlConfig.xml
Labels: defect

#2795 Rename @ConditionalHeader in documentation
  site/src/pages/docs/server-annotated-service.mdx
Labels: cleanup

#2800 Add Gitpod links for armeria-examples
  examples/README.md
Labels: documentation

#2779 Provide type parameter information to `RequestConverterFunction`
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunction.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceAnnotationAliasTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceGenericsTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceHandlersOrderTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunctionTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunctionTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunctionTest.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: breaking change, defect

#2794 Fix flaky test in PublisherBasedStreamMessageTest
  core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTest.java
Labels: cleanup

#2801 Complete session after SessionProtocol and ProxyConnectionEvent are t…
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
Labels: defect

#2796 Add connection lifespan metrics
  core/src/main/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http1ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/test/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
Labels: new feature

#2803 Provide `RequestContext` to `RequestLog` sanitizers
  core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RegexBasedSanitizer.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestOnlyLog.java
  core/src/main/java/com/linecorp/armeria/common/util/Functions.java
  core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: new feature

#2780 Add `RequestLog.serviceName()`
  benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/Backoff.java
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperties.java
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogProperty.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestOnlyLog.java
  core/src/main/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunction.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractUnwrappable.java
  core/src/main/java/com/linecorp/armeria/common/util/Unwrappable.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/Service.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
  core/src/test/java/com/linecorp/armeria/client/retry/BackoffTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
  core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java
  core/src/test/java/com/linecorp/armeria/common/util/AbstractUnwrappableTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/UnwrappingServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLogFormatsTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/HttpServiceLogNameTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceLogNameTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/InvocationUtil.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitClassAwareMeterIdPrefixFunction.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunction.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunctionBuilder.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/RetrofitClassAwareMeterIdPrefixFunctionTest.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/RetrofitMeterIdPrefixFunctionTest.java
  site/src/pages/docs/advanced-structured-logging.mdx
  thrift/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceLogNameTest.java
Labels: breaking change, deprecation, new feature

#2799 Support classes in `java.time` for `@Param` annotation
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTypeUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestConverterTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: improvement

#2805 Fail immediately on proxy connect exception
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
Labels: defect

#2802 Support shutdown property of spring boot
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaGracefulShutdownConfigurationTest.java
  spring/boot-autoconfigure/src/test/resources/config/application-gracefulShutdownTest.yml
Labels: new feature

#2804 Update documentation for ZooKeeper service discovery
  site/build.gradle
  site/src/components/api-link.tsx
  site/src/pages/docs/advanced-production-checklist.mdx
  site/src/pages/docs/advanced-zookeeper.mdx
Labels: documentation

#2808 Fix flaky test in `ServerMaxConnectionAgeTest.http1MaxConnectionAge`
  core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
Labels: cleanup

#2813 Fix flaky test in ProxyClientIntegrationTest.testProxyWithH2C
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
Labels: cleanup

#2807 Fix broken links in the documentation
  dependencies.yml
  site/src/pages/docs/advanced-dropwizard-integration.mdx
  site/src/pages/docs/client-decorator.mdx
Labels: cleanup

#2814 Update gRPC-Java to 1.30.0
  benchmarks/build.gradle
  dependencies.yml
  examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
  examples/grpc-kotlin/gen-src/main/java/example/armeria/grpc/kotlin/Hello.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ProtoReflectionServiceInterceptor.java
  it/server/build.gradle
Labels: dependencies

#2815 Abide by the rule Reactive Streams 2.3
  core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/common/PublisherBasedHttpResponseTest.java
Labels: defect

#2816 Add `onResponseTrailers()` to circuit breaker and retry rule builders
  core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/AbstractRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRule.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleUtil.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContent.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleUtil.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContent.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientRuleTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderTest.java
Labels: new feature

#2789 Fix lack of service context when annotated service method has request…
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  rxjava2/src/test/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunctionTest.java
Labels: defect

#2818 Move the web site to https://armeria.dev/
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  NOTICE.txt
  README.md
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
  examples/README.md
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/ExceptionHandlerService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/InjectionService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/MessageConverterService.java
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/PathPatternService.java
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/HelloServiceImpl.kt
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/Main.kt
  examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/HelloServiceImpl.java
  examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/Main.java
  examples/grpc/src/main/java/example/armeria/grpc/HelloServiceImpl.java
  examples/grpc/src/main/java/example/armeria/grpc/Main.java
  examples/proxy-server/README.md
  examples/proxy-server/src/main/java/example/armeria/proxy/ProxyService.java
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/HelloAnnotatedService.kt
  examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloAnnotatedService.java
  gradle.properties
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
  logback/src/main/java/com/linecorp/armeria/common/logback/package-info.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceProvider.java
  site/gatsby-config.js
  site/package.json
  site/src/layouts/base.tsx
  site/src/pages/community/developer-guide.mdx
  site/src/pages/news/20200514-newsletter-0.mdx
  site/src/pages/release-notes/0.82.0.mdx
  site/src/pages/release-notes/0.94.0.mdx
  site/src/pages/release-notes/0.98.0.mdx
  site/src/pages/release-notes/0.99.0.mdx
Labels: miscellaneous

#2819 Fix a bug where `PATCH` method could not use request body in DocService
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
  docs-client/src/containers/MethodPage/index.tsx
Labels: defect

#2822 Add missing parentheses in client-service-discovery.mdx
  site/src/pages/docs/client-service-discovery.mdx
Labels: cleanup

#2820 Add `@ServiceName` annotation for annotated service
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ServiceName.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceRequestLogNameTest.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: new feature

#2824 Update dependencies
  dependencies.yml
Labels: dependencies

#2823 Add release notes for 0.99.7 / Do not lazy-load but redirect
  site/src/layouts/redirect.tsx
  site/src/layouts/short-url.tsx
  site/src/pages/news/index.tsx
  site/src/pages/release-notes/0.99.7.mdx
  site/src/pages/release-notes/index.tsx
Labels: documentation

#2825 Add `.nojekyll` and `CNAME`
  .post-release-msg
  site/gatsby-config.js
  site/package-lock.json
  site/package.json
  site/static/.nojekyll
Labels: documentation

#2826 Respect the specified port when registering service discovery instance
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
  eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper/src/test/java/com/linecorp/armeria/server/zookeeper/ServerSetRegistrationTest.java
Labels: defect

#2827 Remove StreamMessage.drainAll()
  benchmarks/src/jmh/java/com/linecorp/armeria/grpc/GrpcServiceBenchmark.java
  core/src/main/java/com/linecorp/armeria/common/HeaderOverridingHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java
  core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java
  core/src/test/java/com/linecorp/armeria/client/Http1ConnectionReuseTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java
  core/src/test/java/com/linecorp/armeria/client/encoding/HttpDecodedResponseTest.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDrainerTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/server/DecodedHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodedResponseTest.java
  examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
  spring/boot-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/AbstractReactiveWebServerCustomKeyAliasTest.java
Labels: breaking change

#2829 Rename `armeria-testing-junit` module to `armeria-junit5`
  junit4/build.gradle
  junit4/src/main/java/com/linecorp/armeria/testing/junit4/common/AbstractEventLoopGroupRule.java
  junit4/src/main/java/com/linecorp/armeria/testing/junit4/common/EventLoopGroupRule.java
  junit4/src/main/java/com/linecorp/armeria/testing/junit4/common/EventLoopRule.java
  junit4/src/main/java/com/linecorp/armeria/testing/junit4/common/package-info.java
  junit4/src/main/java/com/linecorp/armeria/testing/junit4/server/SelfSignedCertificateRule.java
  junit4/src/main/java/com/linecorp/armeria/testing/junit4/server/ServerRule.java
  junit4/src/main/java/com/linecorp/armeria/testing/junit4/server/package-info.java
  junit5/build.gradle
  junit5/src/main/java/com/linecorp/armeria/internal/testing/EventLoopGroupRuleDelegate.java
  junit5/src/main/java/com/linecorp/armeria/internal/testing/SelfSignedCertificateRuleDelegate.java
  junit5/src/main/java/com/linecorp/armeria/internal/testing/ServerRuleDelegate.java
  junit5/src/main/java/com/linecorp/armeria/internal/testing/package-info.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/common/AbstractAllOrEachExtension.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/common/AbstractEventLoopGroupExtension.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/common/EventLoopExtension.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/common/EventLoopGroupExtension.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/common/package-info.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/server/SelfSignedCertificateExtension.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/server/ServerExtension.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServerExtension.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/server/mock/RecordedRequest.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/server/mock/package-info.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit/server/package-info.java
  junit5/src/test/java/com/linecorp/armeria/testing/junit/common/AbstractAllOrEachExtensionTest.java
  junit5/src/test/java/com/linecorp/armeria/testing/junit/server/mock/MockWebServiceExtensionTest.java
  settings.gradle
  testing-internal/build.gradle
  testing/common/build.gradle
  testing/junit4/build.gradle
Labels: breaking change

#2828 Add a documentation link of example requests for DebugPage
  docs-client/package-lock.json
  docs-client/package.json
  docs-client/src/containers/MethodPage/DebugPage.tsx
Labels: cleanup

#2831 Fix indent in HttpStatus.java
  core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
Labels: cleanup

#2842 Update Kafka to 2.5.0
  dependencies.yml
  kafka/src/main/java/com/linecorp/armeria/server/logging/kafka/KafkaAccessLogWriter.java
  kafka/src/test/java/com/linecorp/armeria/server/logging/kafka/KafkaAccessLogWriterTest.java
Labels: dependencies

#2835 Fix a bug where a non-base WebClient does not respect the scheme of URI.
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientRequestPathTest.java
  thrift/src/main/java/com/linecorp/armeria/internal/client/thrift/DefaultTHttpClient.java
Labels: defect

#2841 Add gauges for circuit breakers
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerMetrics.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/MetricCollectingCircuitBreakerListenerTest.java
Labels: new feature

#2838 Deprecate Spring registration beans
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedExampleRequest.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/AnnotatedServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerConfigurator.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ExampleHeaders.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcExampleHeaders.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcExampleRequest.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/GrpcServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/HttpServiceRegistrationBean.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/MeterIdPrefixFunctionFactory.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ThriftServiceRegistrationBean.java
Labels: deprecation

#2832 Publish stream events before calling `RequestLogBuilder`
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogAccess.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/internal/logging/ContentPreviewingUtil.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  thrift/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
Labels: defect, deprecation, improvement

#2836 Wrap `DnsTimeoutException` with `UnprocessedRequestException`
  core/src/main/java/com/linecorp/armeria/client/ClientHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/client/UnprocessedRequestException.java
  core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilderTest.java
Labels: breaking change, defect, deprecation

#2847 Add leak detection to `DefaultClientFactory`
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
Labels: improvement

#2837 Asynchronous endpoint selection
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/CompositeEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointSelector.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/OrElseEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/StaticEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractListenable.java
  core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/IdentityHashStrategy.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextDelayedInitTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelectorTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategyTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  licenses/web-licenses.txt
  thrift/src/main/java/com/linecorp/armeria/internal/client/thrift/DefaultTHttpClient.java
Labels: breaking change, new feature

#2850 Return the Host header value from `RequestHeaders.authority()` if `:a…
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
Labels: defect

#2852 Close the connection with failed HTTP/2 upgrade request early
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
Labels: improvement

#2849 Make the build not fail when `defaultUseHttp2Preface=false`
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/test/java/com/linecorp/armeria/client/HttpSessionHandlerTest.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerKeepAliveHandlerTest.java
  eureka/src/test/java/com/linecorp/armeria/client/eureka/ArmeriaEurekaClientTest.java
Labels: defect, documentation

#2854 Fix an example in `PooledHttpData` Javadoc
  core/src/main/java/com/linecorp/armeria/common/unsafe/PooledHttpData.java
Labels: documentation

#2845 Asynchronous metadata access in `HttpFile` and `FileService`
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractBlockingHttpVfs.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpVfs.java
  core/src/main/java/com/linecorp/armeria/server/file/AggregatedHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/CachingHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/ClassPathHttpVfs.java
  core/src/main/java/com/linecorp/armeria/server/file/DeferredHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/FileService.java
  core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/FileSystemHttpVfs.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpDataFile.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/HttpVfs.java
  core/src/main/java/com/linecorp/armeria/server/file/NonExistentHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/StreamingHttpFile.java
  core/src/test/java/com/linecorp/armeria/server/file/CachingHttpFileTest.java
  core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileTest.java
  core/src/test/resources/com/linecorp/armeria/server/file/foo/foo_alone.txt
Labels: breaking change, defect, new feature

#2851 Add `ClientRequestContext` to the filters of RetryRule and CircuitBre…
  core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/AbstractRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRule.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContent.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContent.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/BiPredicateUtil.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientRuleTest.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java
Labels: deprecation, new feature
