Repository line/armeria, pull requests merged in 2020-02, with the labels that each got.

#2437 Fix typo in JavaDoc
  core/src/main/java/com/linecorp/armeria/server/Route.java
Labels: documentation

#2436 Make requestStartTime set before a connection attempt
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/metric/RequestMetricSupportBenchmark.java
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/ClientConnectionTimings.java
  core/src/main/java/com/linecorp/armeria/common/logging/ClientConnectionTimingsBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogProperty.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestOnlyLog.java
  core/src/main/java/com/linecorp/armeria/internal/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/internal/metric/RequestMetricSupport.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientWithRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/ClientConnectionTimingsTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/internal/metric/RequestMetricSupportTest.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/ArmeriaChannel.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java
Labels: defect, improvement

#2439 Public API clean up
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/ExceptionFilter.java
  core/src/main/java/com/linecorp/armeria/client/encoding/DecodingClient.java
  core/src/main/java/com/linecorp/armeria/client/encoding/HttpDecodingClient.java
  core/src/main/java/com/linecorp/armeria/client/encoding/StreamDecoderFactories.java
  core/src/main/java/com/linecorp/armeria/client/encoding/StreamDecoderFactory.java
  core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
  core/src/main/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClient.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLog.java
  core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLogBuilder.java
  core/src/main/java/com/linecorp/armeria/server/logging/structured/StructuredLoggingService.java
  core/src/main/java/com/linecorp/armeria/server/logging/structured/package-info.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/encoding/HttpDecodedResponseTest.java
  kafka/src/main/java/com/linecorp/armeria/server/logging/structured/kafka/KafkaStructuredLoggingService.java
  kafka/src/main/java/com/linecorp/armeria/server/logging/structured/kafka/StructuredLogJsonKafkaSerializer.java
  kafka/src/main/java/com/linecorp/armeria/server/logging/structured/kafka/package-info.java
  kafka/src/test/java/com/linecorp/armeria/server/logging/structured/kafka/KafkaStructuredLoggingServiceTest.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/DefaultMeterIdPrefixFunctionFactory.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/MeterIdPrefixFunctionFactory.java
  spring/boot-autoconfigure/src/test/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtilTest.java
  spring/boot-webflux-autoconfigure/build.gradle
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/DataBufferFactoryWrapper.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftCall.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftJacksonModule.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftJacksonSerializers.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftReply.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftStructuredLog.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftStructuredLogJsonFormat.java
  thrift/src/test/java/com/linecorp/armeria/common/thrift/ThriftJacksonTest.java
  thrift/src/test/java/com/linecorp/armeria/it/thrift/ThriftStructuredLoggingTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftStructuredLogJsonFormatTest.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroup.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/package-info.java
  zookeeper/src/main/java/com/linecorp/armeria/common/zookeeper/package-info.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/package-info.java
Labels: breaking change, cleanup, deprecation

#2441 Rename debug.proto to more internal-sounding type
  grpc/build.gradle
  grpc/src/main/proto/com/linecorp/armeria/grpc/internal_exception_messages.proto
Labels: cleanup

#2443 Hide all Jackson Ser/deserializers from public API
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersJsonDeserializer.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersJsonSerializer.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeJsonDeserializer.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeJsonSerializer.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeadersJsonDeserializer.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeadersJsonDeserializer.java
  core/src/main/java/com/linecorp/armeria/server/docs/TypeSignatureJsonSerializer.java
Labels: cleanup

#2442 Make most public classes final
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptionValue.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/InvalidResponseHeadersException.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/KeyedCircuitBreakerMapping.java
  core/src/main/java/com/linecorp/armeria/client/encoding/ZlibStreamDecoder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/ConnectionPoolLoggingListener.java
  core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/common/ProtocolViolationException.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogAvailabilityException.java
  core/src/main/java/com/linecorp/armeria/common/sse/ServerSentEventBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java
  core/src/main/java/com/linecorp/armeria/server/RedirectService.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ServerSentEventResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/docs/DocService.java
  core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java
  core/src/main/java/com/linecorp/armeria/server/streaming/ServerSentEvents.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingRpcService.java
  core/src/main/java/com/linecorp/armeria/server/throttling/ThrottlingService.java
  core/src/main/java/com/linecorp/armeria/unsafe/ByteBufHttpData.java
  core/src/test/java/com/linecorp/armeria/client/encoding/AbstractStreamDecoderTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/ServerSentEventResponseConverterFunctionTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc/src/main/java/com/linecorp/armeria/internal/grpc/HttpStreamReader.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/grpc/HttpStreamReaderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceTest.java
  logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
  rxjava/src/main/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunction.java
  rxjava/src/main/java/com/linecorp/armeria/server/rxjava/ObservableResponseConverterFunctionProvider.java
  saml/src/main/java/com/linecorp/armeria/server/saml/InvalidSamlRequestException.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlMetadataServiceFunction.java
  testing-internal/src/main/java/com/linecorp/armeria/testing/internal/AnticipatedException.java
  testing-internal/src/main/java/com/linecorp/armeria/testing/internal/UniqueProtocolsProvider.java
  testing/common/src/main/java/com/linecorp/armeria/testing/internal/EventLoopGroupRuleDelegate.java
  testing/common/src/main/java/com/linecorp/armeria/testing/internal/SelfSignedCertificateRuleDelegate.java
  testing/junit4/src/main/java/com/linecorp/armeria/testing/junit4/common/EventLoopGroupRule.java
  testing/junit4/src/main/java/com/linecorp/armeria/testing/junit4/common/EventLoopRule.java
  testing/junit4/src/main/java/com/linecorp/armeria/testing/junit4/server/SelfSignedCertificateRule.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftJacksonSerializers.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/ThriftProtocolFactories.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/MapContext.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/SequenceContext.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/TTextProtocol.java
  thrift/src/main/java/com/linecorp/armeria/common/thrift/text/TTextProtocolFactory.java
  thrift/src/main/java/com/linecorp/armeria/server/thrift/ThriftDocServicePlugin.java
  tomcat/src/main/java/com/linecorp/armeria/server/tomcat/TomcatServiceException.java
  zookeeper/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupBuilder.java
  zookeeper/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
Labels: cleanup

#2420 Use modern features of Gradle instead of custom scripts where possible.
  CONTRIBUTING.md
  README.md
  benchmarks/build.gradle
  brave/build.gradle
  build.gradle
  core/build.gradle
  dependencies.yml
  dropwizard/build.gradle
  examples/annotated-http-service/build.gradle
  examples/context-propagation/dagger/build.gradle
  examples/context-propagation/manual/build.gradle
  examples/context-propagation/rxjava/build.gradle
  examples/dropwizard/build.gradle
  examples/grpc-reactor/build.gradle
  examples/grpc/build.gradle
  examples/proxy-server/build.gradle
  examples/saml-service-provider/build.gradle
  examples/server-sent-events/build.gradle
  examples/spring-boot-minimal/build.gradle
  examples/spring-boot-tomcat/build.gradle
  examples/spring-boot-webflux/build.gradle
  examples/static-files/build.gradle
  grpc/build.gradle
  it/server/build.gradle
  it/spring/boot-tomcat/build.gradle
  it/spring/boot-tomcat8.5/build.gradle
  jetty/build.gradle
  kafka/build.gradle
  logback/build.gradle
  retrofit2/build.gradle
  rxjava/build.gradle
  saml/build.gradle
  settings.gradle
  spring/boot-actuator-autoconfigure/build.gradle
  spring/boot-actuator-starter/build.gradle
  spring/boot-autoconfigure/build.gradle
  spring/boot-starter/build.gradle
  spring/boot-webflux-autoconfigure/build.gradle
  spring/boot-webflux-starter/build.gradle
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-starter/build.gradle
  testing-internal/build.gradle
  testing-internal/src/main/java/com/linecorp/armeria/testing/internal/webapp/WebAppContainerTest.java
  testing/junit/build.gradle
  testing/junit4/build.gradle
  thrift/build.gradle
  thrift0.12/build.gradle
  thrift0.9/build.gradle
  tomcat/build.gradle
  tomcat8.5/build.gradle
  zookeeper/build.gradle
Labels: cleanup, dependencies

#2429 Fix 'cannot start a new stream with a DATA frame' error under load
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/internal/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  thrift/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
Labels: defect

#2450 Replace ConvertUtils to guava Ints
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ConvertUtils.java
Labels: cleanup

#2446 Make FailFastException public
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/FailFastException.java
Labels: new feature

#2438 Add MediaTypeNames
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ConsumesBinary.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ConsumesJson.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ConsumesOctetStream.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ConsumesText.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ProducesBinary.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ProducesEventStream.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ProducesJson.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ProducesJsonSequences.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ProducesOctetStream.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ProducesText.java
  core/src/test/java/com/linecorp/armeria/common/MediaTypeNamesTest.java
  core/src/test/java/com/linecorp/armeria/common/MediaTypeTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceAnnotationAliasTest.java
  site/src/sphinx/server-basics.rst
  spring/boot-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
Labels: new feature

#2458 Update dependencies
  benchmarks/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostDecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpDataTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  dependencies.yml
  examples/proxy-server/src/main/java/example/armeria/proxy/Main.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  it/spring/boot-tomcat8.5/build.gradle
  saml/src/test/java/com/linecorp/armeria/server/saml/KeyStoreCredentialResolverBuilderTest.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpHandlerAdapter.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
  tomcat8.5/build.gradle
Labels: dependencies

#2435 Add HttpStatus.isSuccess() and other boolean getters
  core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
  core/src/test/java/com/linecorp/armeria/common/HttpStatusTest.java
Labels: new feature

#2454 Do not use type parameter for builder self type in public API
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaConfigurationUtil.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
Labels: cleanup

#2459 Clean up `HttpStatus.is*()` and their tests
  core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
  core/src/test/java/com/linecorp/armeria/common/HttpStatusTest.java
Labels: cleanup

#2462 Use `HttpStatus.is*()` for brevity
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerStrategy.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryStrategy.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupLongPollingPingTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpClientResponseSubscriber.java
Labels: cleanup

#2465 Fix flaky tests
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
  gradle.properties
  thrift/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
Labels: cleanup

#2466 Fix a bug where `pendingResponses` meter is not updated
  core/src/main/java/com/linecorp/armeria/server/GracefulShutdownSupport.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/server/GracefulShutdownSupportTest.java
Labels: defect, performance

#2456 Add EncodingServiceBuilder
  core/src/main/java/com/linecorp/armeria/server/Service.java
  core/src/main/java/com/linecorp/armeria/server/encoding/EncodingService.java
  core/src/main/java/com/linecorp/armeria/server/encoding/EncodingServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
  core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodingService.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/logging/ContentPreviewingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
  dropwizard/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaConfigurationUtil.java
  site/src/sphinx/server-decorator.rst
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Labels: breaking change

#2457 Apply gradle-versions-plugin to dependencyManagement project
  gradle.properties
  gradle/scripts/README.md
  gradle/scripts/lib/common-dependencies.gradle
  site/build.gradle
  spring/boot1-autoconfigure/build.gradle
Labels: cleanup

#2467 Update frontend dependencies
  docs-client/build.gradle
  docs-client/package.json
  docs-client/yarn.lock
  licenses/web-licenses.txt
Labels: dependencies

#2464 Fix a bug where making IPv6 DnsQuestion when it's not supported
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/internal/client/DnsUtil.java
Labels: defect

#2469 Update dependencies
  dependencies.yml
Labels: dependencies

#2470 Fix overlap in DocService sidebar
  docs-client/src/containers/App/index.tsx
Labels: cleanup

#2471 Preserve service binding order when building routers
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRoutingTest.java
Labels: defect

#2474 Fix `HealthCheckedEndpointGroup` compatibility with old servers
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupCompatibilityTest.java
Labels: defect

#2476 Update dependencies
  dependencies.yml
Labels: dependencies

#2478 Fix blocking operation warnings from `FileService`
  core/src/main/java/com/linecorp/armeria/server/file/CachingHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/file/FileService.java
Labels: defect

#2479 Potentially fix flakiness in `FileServiceTest`
  core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
Labels: cleanup

#2485 Fix `InvalidKeySpecException` when using `PKCS#5` keys
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/BouncyCastleKeyFactoryProvider.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/BouncyCastleKeyFactoryProviderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/resources/cert.pem
  core/src/test/resources/com/linecorp/armeria/internal/common/util/pkcs5.key
  core/src/test/resources/com/linecorp/armeria/internal/common/util/pkcs8.key
  core/src/test/resources/com/linecorp/armeria/internal/common/util/test.crt
  core/src/test/resources/pkcs5.pem
  core/src/test/resources/pkcs8.pem
Labels: defect

#2490 Fix DefaultTimeoutControllerTest.resetTimeout_withoutInit()
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultTimeoutControllerTest.java
Labels: cleanup

#2488 Replace Http1ClientCodec to Netty HttpClientCodec
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/internal/client/Http1ClientCodec.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/THttp2Client.java
Labels: cleanup

#2484 Added maven configuration for DocService
  site/src/sphinx/server-docservice.rst
Labels: documentation

#2492 Do not export `null` values in `RequestContextExporter`
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Labels: defect

#2494 Fix `ReflectionsException` while scanning docstrings
  core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java
Labels: defect

#2495 Make `FallthroughException` a part of public API
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionHandlerFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/FallthroughException.java
  core/src/main/java/com/linecorp/armeria/server/annotation/RequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunctionTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunctionTest.java
  core/src/test/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunctionTest.java
Labels: defect

#2483 Allow `ArmeriaRetrofitBuilder` to configure `ClientOption`
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientDecoration.java
  core/src/main/java/com/linecorp/armeria/client/ClientDecorationBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOptions.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsBuilderTest.java
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/Main.kt
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilderTest.java
Labels: defect, new feature

#2497 Fix buffer leak in `HttpRequest.of()`
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestTest.java
Labels: defect

#2374 Fix `MAX_CONCURRENT_STREAMS` violation on client side
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/common/logging/ClientConnectionTimingsBuilder.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
Labels: defect

#2498 Fix a leak in `HttpResponse.of()`
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/test/java/com/linecorp/armeria/common/EmptyReferenceCountedHttpData.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpResponseTest.java
Labels: defect

#2499 Always abort a failed client request
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
Labels: cleanup

#2500 Clean up `ClientUtil`
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
Labels: cleanup

#2504 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  it/spring/boot-tomcat8.5/build.gradle
  tomcat8.5/build.gradle
Labels: dependencies

#2506 Rename `armeria.server.pendingResponses` to follow meter naming conve…
  core/src/main/java/com/linecorp/armeria/server/Server.java
Labels: defect

#2508 Abort with `ClosedStreamException` on `RST_STREAM`
  core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Labels: cleanup

#2515 Make `RequestContextExporter` capable of exporting request ID
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Labels: new feature

#2519 Downgrade Reflections from 0.9.12 to 0.9.11
  core/src/main/java/com/linecorp/armeria/server/docs/DocStringExtractor.java
  dependencies.yml
Labels: defect, dependencies

#2517 Do not propagate the first child's `requestCause()` for nested logs
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithLoggingTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithMetricsTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
Labels: defect

#2516 Exclude default options when merging two `Client*Options`
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOptions.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
Labels: breaking change, defect

#2526 Fix flaky HttpClientMaxConcurrentStreamTest
  core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
Labels: cleanup

#2521 Allow `RequestContextExporter` to export an `AttributeKey` with diffe…
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/CustomObject.java
  logback/src/test/java/com/linecorp/armeria/common/logback/CustomObjectNameStringifier.java
  logback/src/test/java/com/linecorp/armeria/common/logback/CustomObjectValueStringifier.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  logback/src/test/resources/com/linecorp/armeria/common/logback/testXmlConfig.xml
Labels: defect

#2520 Fix a bug where `RequestContextExporter` exports wrong properties
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultAttributeMap.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/main/java/com/linecorp/armeria/server/RouteDecoratingService.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
Labels: defect

#2528 Push the current context when logging requests and responses
  core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
  core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/logging/LoggingTestUtil.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: defect

#2523 Revamp the options API
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptionValue.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientOption.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptionValue.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/StringMultimapBuilder.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOption.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOptionValue.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractOptions.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcFlowControlTest.java
Labels: breaking change, new feature

#2530 Make `HttpTimestampSupplier` work with negative clock value
  core/src/main/java/com/linecorp/armeria/internal/common/util/HttpTimestampSupplier.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/HttpTimestampSupplierTest.java
Labels: defect

#2529 Update dependencies
  dependencies.yml
  docs-client/yarn.lock
Labels: cleanup

#2532 Add `LogLevel.OFF` and `log()` method with varargs
  core/src/main/java/com/linecorp/armeria/common/logging/LogLevel.java
Labels: new feature

#2533 Fix Subscriber not to throw an exception
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/main/java/com/linecorp/armeria/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/ArmeriaMessageDeframer.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamReader.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpClientResponseSubscriber.java
Labels: defect

#2537 Fix a bug where `ctx.set*Timeout()` does not schedule a timeout
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
Labels: defect

#2540 Fix: Dropwizard example reference
  site/src/sphinx/advanced-dropwizard-integration.rst
Labels: documentation

#2536 Update Brave from 5.9.5 to 5.10.1
  brave/src/main/java/com/linecorp/armeria/client/brave/ArmeriaHttpClientParser.java
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  brave/src/main/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapter.java
  brave/src/main/java/com/linecorp/armeria/server/brave/ArmeriaHttpServerParser.java
  brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
  brave/src/main/java/com/linecorp/armeria/server/brave/ServiceRequestContextAdapter.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientTest.java
  brave/src/test/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapterTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/ServerRequestContextAdapterTest.java
  dependencies.yml
Labels: dependencies

#2538 Require request path when building a client
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/WebClient.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/test/java/com/linecorp/armeria/client/ClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofit.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
  thrift/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientBuilderTest.java
  thrift/src/test/java/com/linecorp/armeria/it/client/endpoint/StaticEndpointGroupIntegrationTest.java
  thrift/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
Labels: breaking change, new feature

#2541 Implement new rawStatusCode methods in ServerHttpResponse
  dependencies.yml
  spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
Labels: dependencies

#2539 Fix StreamMessage to handle abort() correctly
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
Labels: defect

#2542 Add documentation for adding doc string to annotated services
  site/src/sphinx/server-docservice.rst
Labels: cleanup

#2531 More ways to customize export keys for `RequestContextExporter`
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperties.java
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  site/src/sphinx/advanced-logging.rst
Labels: breaking change, new feature
