Repository line/armeria, pull requests merged in 2021-08, with the labels that each got.

#3714 Make HttpHeaders more cacheable
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/ContentTooLargeExceptionBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeaders.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeaders.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultResponseHeaders.java
  core/src/main/java/com/linecorp/armeria/common/DefaultResponseHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeaders.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeaders.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/StringMultimap.java
  core/src/main/java/com/linecorp/armeria/common/StringValueConverter.java
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/StringUtil.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/RoutingResult.java
  core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
  core/src/main/java/com/linecorp/armeria/server/file/AbstractHttpFile.java
  core/src/main/java/com/linecorp/armeria/server/streaming/JsonLines.java
  core/src/main/java/com/linecorp/armeria/server/streaming/JsonTextSequences.java
  core/src/main/java/com/linecorp/armeria/server/streaming/ServerSentEvents.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeaderCachedValuesTest.java
  core/src/test/java/com/linecorp/armeria/common/StringMultimapDerivedApiConsistencyTest.java
  examples/proxy-server/src/main/java/example/armeria/proxy/AnimationService.java
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/MyAuthHandler.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  oauth2/src/main/java/com/linecorp/armeria/internal/common/auth/oauth2/AbstractOAuth2Request.java
  resteasy/src/main/java/com/linecorp/armeria/server/resteasy/ResteasyService.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/AbstractSubscriber.java
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Labels: improvement

#3430 Propagate Brave's Scope when a RequestContext is pushed
  brave/build.gradle
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextBuilder.java
  brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
  brave/src/test/java/com/linecorp/armeria/server/brave/SpanPropagationTest.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ServerSetRegistrationTest.java
Labels: defect, new feature

#3738 Re-indent gRPC example
  examples/grpc/src/main/java/example/armeria/grpc/Main.java
Labels: cleanup

#3674 Provide a way to recover a failed `StreamMessage`
  core/src/main/java/com/linecorp/armeria/common/AbortedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/stream/ConcatArrayStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/ConcatPublisherStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/AbortedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/SubscriptionArbiter.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceElement.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/DefaultExceptionHandler.java
  core/src/main/java/com/linecorp/armeria/server/DefaultExceptionHandler.java
  core/src/main/java/com/linecorp/armeria/server/ExceptionHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseException.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ExceptionVerbosity.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunctionProvider.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceExceptionHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ExceptionHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingFailureTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
  rxjava2/src/main/java/com/linecorp/armeria/internal/server/rxjava2/ObservableResponseConverterFunctionProvider.java
  rxjava2/src/main/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunction.java
  rxjava2/src/test/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunctionProviderTest.java
  rxjava3/src/main/java/com/linecorp/armeria/internal/server/rxjava3/ObservableResponseConverterFunctionProvider.java
  rxjava3/src/main/java/com/linecorp/armeria/server/rxjava3/ObservableResponseConverterFunction.java
  rxjava3/src/test/java/com/linecorp/armeria/server/rxjava3/ObservableResponseConverterFunctionProviderTest.java
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunctionProvider.scala
Labels: breaking change, defect, deprecation, improvement, new feature

#3715 Add a way for a user to initiate connection shutdown.
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractHttp2ConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/GracefulConnectionShutdownHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/InitiateConnectionShutdown.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/common/KeepAliveMaxNumRequestsTest.java
  core/src/test/java/com/linecorp/armeria/server/InitiateConnectionShutdownTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
Labels: new feature

#3728 Add `JacksonObjectMapperProvider`
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/JacksonObjectMapperProvider.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultJacksonObjectMapperProvider.java
  core/src/main/java/com/linecorp/armeria/internal/common/JacksonUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/JacksonUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/streaming/JsonLines.java
  core/src/main/java/com/linecorp/armeria/server/streaming/JsonTextSequences.java
  graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java
  it/jackson-provider/build.gradle
  it/jackson-provider/src/test/java/com/linecorp/armeria/common/CustomJacksonObjectMapperProvider.java
  it/jackson-provider/src/test/java/com/linecorp/armeria/common/JacksonObjectMapperProviderTest.java
  it/jackson-provider/src/test/resources/META-INF/services/com.linecorp.armeria.common.JacksonModuleProvider
  it/jackson-provider/src/test/resources/META-INF/services/com.linecorp.armeria.common.JacksonObjectMapperProvider
  kotlin/src/test/kotlin/com/linecorp/armeria/server/DataClassDocServiceTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/JacksonModuleAnnotatedServiceTest.kt
  sangria/sangria_2.13/src/main/scala/com/linecorp/armeria/server/sangria/SangriaGraphqlService.scala
  sangria/sangria_2.13/src/test/scala/com/linecorp/armeria/server/sangria/GraphqlTestUtil.scala
  scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/JacksonModuleAnnotatedServiceTest.scala
Labels: breaking change, defect, new feature

#3736 Fix buffer leak in the UnaryGrpcClient
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java
  grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/DeframedMessage.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcWebTrailersExtractor.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClientTest.java
Labels: defect

#3744 Reduce the resource consumption of flaky tests
  .github/workflows/actions_build.yml
  gradle.properties
Labels: cleanup

#3748 Fix a bug where `Server.stop/close()` never finishes
  core/src/main/java/com/linecorp/armeria/internal/common/GracefulConnectionShutdownHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
Labels: defect

#3747 Fix `NullPointerException` in `HttpResponseDecoder`
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
Labels: defect

#3749 Fix a bug that request start time is not set properly for child logs
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientWithMetricsTest.java
Labels: defect

#3752 Add virtual office hours to the web site
  site/build.gradle
  site/package-lock.json
  site/src/design/office_hours.png
  site/src/pages/community/index.mdx
  site/src/pages/community/office-hours.mdx
  site/src/pages/community/toc.json
Labels: documentation

#3750 Ignore `CancelledSubscriptionException` when WebFlux's WebClient cancels the upstream
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultSplitHttpResponse.java
  dependencies.yml
  it/spring/boot2-kotlin/build.gradle.kts
  it/spring/boot2-kotlin/src/test/kotlin/com/linecorp/armeria/spring/kotlin/AbnormalController.kt
  it/spring/boot2-kotlin/src/test/kotlin/com/linecorp/armeria/spring/kotlin/ClientCoroutineTest.kt
  it/spring/boot2-kotlin/src/test/kotlin/com/linecorp/armeria/spring/kotlin/KotlinWebFluxApp.kt
  settings.gradle
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpResponseBodyStream.java
Labels: defect

#3755 Add `GrpcServiceBuilder.intercept()` to inject interceptor fluently
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServerInterceptorTest.java
Labels: new feature

#3766 Add a flag that disables the Netty version warning
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
Labels: new feature

#3691 Fix `HttpResponse` not propagating cancellation signal to upstream
  core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ObjectCollectingUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/ResponseConversionUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/common/DeferredHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
  kotlin/src/test/kotlin/com/linecorp/armeria/server/SuspendingAnnotatedServiceTest.kt
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
Labels: defect

#3758 Invalidate `RequestLog.toString*()` cache when sanitizer functions are different
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: defect

#3762 Use ArmeriaServerGracefulShutdownLifecycle to start Server with Spring integration
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerGracefulShutdownLifecycle.java
Labels: defect

#3732 Add `ArmeriaProcessor` to provide `ActionHook`
  it/spring/boot2-tomcat9/src/main/java/com/linecorp/armeria/spring/tomcat/demo/ErrorHandlingController.java
  it/spring/boot2-tomcat9/src/main/java/com/linecorp/armeria/spring/tomcat/demo/GlobalBaseException.java
  it/spring/boot2-tomcat9/src/main/java/com/linecorp/armeria/spring/tomcat/demo/GlobalExceptionHandler.java
  it/spring/boot2-tomcat9/src/main/resources/config/application.yml
  it/spring/boot2-tomcat9/src/test/java/com/linecorp/armeria/spring/tomcat/demo/ErrorHandlingTest.java
  it/spring/boot2-tomcat9/src/test/java/com/linecorp/armeria/spring/tomcat/demo/SpringTomcatApplicationItTest.java
  tomcat8/build.gradle
  tomcat8/src/main/java/com/linecorp/armeria/server/tomcat/ArmeriaEndpoint.java
  tomcat8/src/main/java/com/linecorp/armeria/server/tomcat/ArmeriaProcessor.java
  tomcat8/src/main/java/com/linecorp/armeria/server/tomcat/package-info.java
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/ArmeriaProcessor.java
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/LogWrapper.java
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Labels: defect

#3773 Add client factory and provider for UnaryGrpcClient.
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/client/grpc/protocol/UnaryGrpcClientFactory.java
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/client/grpc/protocol/UnaryGrpcClientFactoryProvider.java
  grpc-protocol/src/main/resources/META-INF/services/com.linecorp.armeria.client.ClientFactoryProvider
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClientTest.java
Labels: new feature

#3778 Relax overly-strict request path validation for HTTP/1
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerPathTest.java
Labels: defect

#3763 Update dependencies
  NOTICE.txt
  build.gradle
  core/build.gradle
  core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
  dependencies.yml
  examples/grpc-reactor/build.gradle
  gradle/scripts/lib/java-rpc-proto.gradle
  gradle/wrapper/gradle-wrapper.properties
  it/spring/boot2-tomcat8/build.gradle
  licenses/LICENSE.brotli4j.al20.txt
  tomcat8/build.gradle
Labels: dependencies

#3779 Fix a bug that ErrorWebExceptionHandler is not applied properly
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ByteBufLeakTest.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ErrorWebExceptionHandlerTest.java
Labels: defect

#3641 Provide automatic redirection
  .github/workflows/actions_build.yml
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestDuplicatorWrapper.java
  core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/redirect/CyclicRedirectsException.java
  core/src/main/java/com/linecorp/armeria/client/redirect/RedirectConfig.java
  core/src/main/java/com/linecorp/armeria/client/redirect/RedirectConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/client/redirect/RedirectsException.java
  core/src/main/java/com/linecorp/armeria/client/redirect/TooManyRedirectsException.java
  core/src/main/java/com/linecorp/armeria/client/redirect/UnexpectedDomainRedirectException.java
  core/src/main/java/com/linecorp/armeria/client/redirect/UnexpectedProtocolRedirectException.java
  core/src/main/java/com/linecorp/armeria/client/redirect/package-info.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryDecision.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpRequestDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/SessionProtocol.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/internal/client/RedirectingClientUtil.java
  core/src/test/java/com/linecorp/armeria/client/RedirectContextTest.java
  core/src/test/java/com/linecorp/armeria/client/RedirectingClientTest.java
  core/src/test/java/com/linecorp/armeria/client/redirect/RedirectConfigBuilderTest.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
Labels: new feature

#3771 Add a release note for 1.10.0
  site/build.gradle
  site/src/components/api-link.tsx
  site/src/pages/release-notes/1.10.0.mdx
  site/src/plugins/gatsby-remark-api-links.js
Labels: documentation

#3790 Fix a typo of link in the REST tutorials
  site/src/pages/tutorials/rest/blog/add-services-to-server.mdx
  site/src/pages/tutorials/rest/blog/implement-create.mdx
  site/src/pages/tutorials/rest/blog/implement-read.mdx
  site/src/pages/tutorials/rest/blog/implement-update.mdx
Labels: cleanup

#3784 Add `SystemInfo.hasIpV6()`
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/common/util/SystemInfo.java
  core/src/main/java/com/linecorp/armeria/internal/client/DnsUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServerEphemeralLocalPortTest.java
Labels: new feature
