Repository line/armeria, pull requests merged in 2021-06, with the labels that each got.

#3592 Wait to close stream before proceeding in DefaultStreamMessage.noExecutor benchmark
  benchmarks/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageBenchmark.java
Labels: cleanup

#3607 Do not log verbosely when Socket.initialize() fails (second).
  core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
Labels: cleanup

#3504 Add a 'Client interoperability' page to 'Advanced' section
  site/README.md
  site/src/components/code-block.tsx
  site/src/pages/docs/advanced-client-interoperability.mdx
  site/src/pages/docs/server-annotated-service.mdx
  site/src/pages/docs/toc.json
Labels: documentation

#3389 Add BlockingTaskExecutorBuilder
  core/src/main/java/com/linecorp/armeria/common/CommonPools.java
  core/src/main/java/com/linecorp/armeria/common/util/BlockingTaskExecutor.java
  core/src/main/java/com/linecorp/armeria/common/util/BlockingTaskExecutorBuilder.java
  core/src/main/java/com/linecorp/armeria/common/util/DefaultBlockingTaskExecutor.java
Labels: new feature

#3588 Peel RPC response exception
  core/src/main/java/com/linecorp/armeria/common/RpcResponse.java
  thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/THttpServiceBuilderTest.java
Labels: defect

#3590 Add a scheduled job that updates public suffix list periodically
  .gitattributes
  .github/workflows/public-suffixes.yml
  core/build.gradle
Labels: cleanup

#3611 Fix flaky ScheduledHealthCheckerTest.stopSchedulingAfterStop
  core/src/test/java/com/linecorp/armeria/server/healthcheck/ScheduledHealthCheckerTest.java
Labels: cleanup

#3622 Cancel duplicated GitHub Action workflows
  .github/workflows/actions_build.yml
Labels: miscellaneous

#3628 Do not run schedule task in fork repos
  .github/workflows/public-suffixes.yml
Labels: cleanup

#3632 Notify late subscriber signals on the late subscriber's event loop
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/DeferredStreamMessageTest.java
Labels: defect

#3631 Fix `CircuitBreakerClient` to return a `HttpResponse` immediately without waiting for headers or trailers
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientTest.java
Labels: defect

#3629 Add a reset method to MockWebServerExtension for use outside JUnit5.
  junit5/src/main/java/com/linecorp/armeria/testing/junit5/server/mock/MockWebServerExtension.java
Labels: improvement

#3626 Add Javadoc about path patterns
  core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
Labels: documentation

#3613 Add ClientFactory.numConnections()
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientFactoryTest.java
Labels: new feature

#3505 Make `TemporaryThreadLocals` `AutoClosable` to safely use shared resources
  benchmarks/src/jmh/java/com/linecorp/armeria/common/QueryStringEncoderBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientBuilderParams.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ByteArrayHttpData.java
  core/src/main/java/com/linecorp/armeria/common/ByteBufHttpData.java
  core/src/main/java/com/linecorp/armeria/common/ContentDisposition.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareLogger.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestId.java
  core/src/main/java/com/linecorp/armeria/common/QueryParamGetters.java
  core/src/main/java/com/linecorp/armeria/common/QueryParams.java
  core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aToken.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/multipart/MultipartEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/PercentDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/TargetLengthBasedClassNameAbbreviator.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/TemporaryThreadLocals.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/file/DefaultEntityTagFunction.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
  core/src/test/java/com/linecorp/armeria/common/QueryParamsTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/TemporaryThreadLocalsTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/StatusMessageEscaper.java
  resteasy/src/main/java/com/linecorp/armeria/client/resteasy/ArmeriaJaxrsClientEngine.java
  saml/src/main/java/com/linecorp/armeria/server/saml/JwtBasedSamlRequestIdManager.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/text/TTextProtocol.java
Labels: improvement

#3627 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
  site/src/pages/community/developer-guide.mdx
Labels: documentation

#3625 Use SPI for loading the Jackson modules automatically
  core/src/main/java/com/linecorp/armeria/common/JacksonModuleProvider.java
  core/src/main/java/com/linecorp/armeria/internal/server/JacksonUtil.java
  it/jackson-provider/build.gradle
  it/jackson-provider/src/test/java/com/linecorp/armeria/common/CustomJacksonModuleProvider.java
  it/jackson-provider/src/test/java/com/linecorp/armeria/common/JacksonModuleProviderTest.java
  it/jackson-provider/src/test/resources/META-INF/services/com.linecorp.armeria.common.JacksonModuleProvider
  settings.gradle
Labels: new feature

#3635 #3633 Handle errors when invoking a WebOperation
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
Labels: defect

#3645 Fix flaky `MultipartDecoderTckTest.required_completionFutureMustCompleteOnTermination0`
  core/src/test/java/com/linecorp/armeria/common/multipart/MultipartDecoderTckTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
Labels: cleanup

#3601 Add `ServerBuilder.localPort` shortcuts
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Labels: new feature

#3646 Add missing package-info.java for java12 package
  core/src/main/java12/com/linecorp/armeria/internal/common/package-info.java
Labels: cleanup

#3362 Dynamic reconfiguration of Server
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfigHolder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfigurator.java
  core/src/test/java/com/linecorp/armeria/client/ReconfigurableServerTest.java
Labels: new feature

#3602 Add shortcut methods that create event loops and blocking task executor thread pool
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/ConnectionLimitingHandlerIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: new feature

#3650 Disable incremental compile for Scala projects
  examples/grpc-scala/build.gradle
  it/grpc/scala/build.gradle
  scalapb/scalapb_2.12/build.gradle
Labels: cleanup

#3593 Add `RequestOptions` that allow configuring options at request level.
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/DefaultRequestOptions.java
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/RequestOptions.java
  core/src/main/java/com/linecorp/armeria/client/RequestOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/RequestOptionsSetters.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/client/WebClient.java
  core/src/main/java/com/linecorp/armeria/client/WebClientRequestPreparation.java
  core/src/test/java/com/linecorp/armeria/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java
  core/src/test/java/com/linecorp/armeria/client/RequestOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/WebClientRequestPreparationTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
Labels: new feature

#3509 Set TCP_USER_TIMEOUT by default
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ChannelUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/ChannelUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  it/nio/build.gradle
  it/nio/src/test/java/com/linecorp/armeria/server/http/NioServerTest.java
  settings.gradle
Labels: new feature

#3373 Support GraphQL
  NOTICE.txt
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/common/MediaTypeTest.java
  dependencies.yml
  examples/graphql/build.gradle
  examples/graphql/src/main/java/example/armeria/server/graphql/Main.java
  examples/graphql/src/main/java/example/armeria/server/graphql/UserDataFetcher.java
  examples/graphql/src/main/resources/schema.graphqls
  examples/graphql/src/test/java/example/armeria/server/graphql/GraphqlServiceTest.java
  examples/graphql/src/test/resources/.gitkeep
  graphql/build.gradle
  graphql/src/main/java/com/linecorp/armeria/server/graphql/DefaultGraphqlService.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlConfigurator.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlService.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilder.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/RuntimeWiringConfigurator.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/package-info.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceBlockingTest.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilderTest.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceSubscriptionTest.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java
  graphql/src/test/resources/subscription.graphqls
  graphql/src/test/resources/test.graphqls
  it/dgs/build.gradle
  it/dgs/src/test/java/com/linecorp/armeria/graphql/GraphQLTest.java
  it/dgs/src/test/resources/test.graphqls
  licenses/LICENSE.dgs.al20.txt
  licenses/LICENSE.graphql-java.mit.text
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
  settings.gradle
Labels: new feature

#3640 Update dependencies
  build.gradle
  core/build.gradle
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersBaseTest.java
  dependencies.yml
  gradle/scripts/lib/common-dependencies.gradle
  it/micrometer1.3/build.gradle
  it/spring/boot2-tomcat8/build.gradle
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
  scala/scala_2.12/build.gradle
  scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/ServerBuilderSuite.scala
  scalapb/scalapb_2.12/build.gradle
  spring/boot1-autoconfigure/build.gradle
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
  tomcat8/build.gradle
Labels: dependencies

#3642 A set of fixes and enhancements for multipart package
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  core/src/main/java/com/linecorp/armeria/common/multipart/DefaultMultipart.java
  core/src/main/java/com/linecorp/armeria/common/multipart/Multipart.java
  core/src/main/java/com/linecorp/armeria/common/multipart/Multiparts.java
  core/src/test/java/com/linecorp/armeria/common/multipart/MultipartIntegrationTest.java
Labels: new feature

#3652 Run checkstyle job independently
  .github/workflows/actions_build.yml
Labels: cleanup

#3582 Add documentation for setting a request timeout and attributes with `WebClient`
  site/src/pages/docs/advanced-custom-attributes.mdx
  site/src/pages/docs/client-timeouts.mdx
Labels: documentation

#3653 Split flaky tests from the main CI builds
  .github/workflows/actions_build.yml
  consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: cleanup

#3616 Allow specifying current / max content length when creating `ContentTooLargeException`
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/ContentTooLargeException.java
  core/src/main/java/com/linecorp/armeria/common/ContentTooLargeExceptionBuilder.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/test/java/com/linecorp/armeria/common/DefaultHttpResponseDuplicatorTest.java
Labels: improvement

#3355 Add example code for REST API tutorial
  examples/tutorials/rest-api-annotated-service/build.gradle
  examples/tutorials/rest-api-annotated-service/src/main/java/example/armeria/server/blog/BadRequestExceptionHandler.java
  examples/tutorials/rest-api-annotated-service/src/main/java/example/armeria/server/blog/BlogPost.java
  examples/tutorials/rest-api-annotated-service/src/main/java/example/armeria/server/blog/BlogPostRequestConverter.java
  examples/tutorials/rest-api-annotated-service/src/main/java/example/armeria/server/blog/BlogService.java
  examples/tutorials/rest-api-annotated-service/src/main/java/example/armeria/server/blog/Main.java
  examples/tutorials/rest-api-annotated-service/src/test/java/example/armeria/server/blog/BlogServiceTest.java
  settings.gradle
Labels: documentation

#3656 Make Spring integration compatible with Spring Boot 2.4
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationServiceUtil.java
Labels: defect

#3658 Use `ServerExtension` in examples
  examples/annotated-http-service-kotlin/build.gradle.kts
  examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/Main.kt
  examples/annotated-http-service-kotlin/src/test/kotlin/example/armeria/server/annotated/kotlin/AnnotatedServiceTest.kt
  examples/annotated-http-service/build.gradle
  examples/annotated-http-service/src/main/java/example/armeria/server/annotated/Main.java
  examples/annotated-http-service/src/test/java/example/armeria/server/annotated/AnnotatedServiceTest.java
  examples/graphql/build.gradle
  examples/graphql/src/main/java/example/armeria/server/graphql/Main.java
  examples/graphql/src/test/java/example/armeria/server/graphql/GraphqlServiceTest.java
  examples/grpc-kotlin/build.gradle.kts
  examples/grpc-reactor/build.gradle
  examples/grpc-reactor/src/main/java/example/armeria/grpc/reactor/Main.java
  examples/grpc-reactor/src/test/java/example/armeria/grpc/reactor/HelloServiceTest.java
  examples/grpc/build.gradle
  examples/grpc/src/main/java/example/armeria/grpc/Main.java
  examples/grpc/src/test/java/example/armeria/grpc/HelloServiceTest.java
  examples/server-sent-events/build.gradle
  examples/server-sent-events/src/main/java/example/armeria/server/sse/Main.java
  examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
  examples/static-files/build.gradle
  examples/static-files/src/main/java/example/armeria/server/files/Main.java
  examples/static-files/src/test/java/example/armeria/server/files/MainTest.java
  examples/thrift/build.gradle
  examples/thrift/src/main/java/example/armeria/thrift/Main.java
  examples/thrift/src/test/java/example/armeria/thrift/HelloServiceTest.java
Labels: cleanup

#3659 Fix type casting error when setting TCP_USER_TIMEOUT
  core/src/main/java/com/linecorp/armeria/internal/common/util/ChannelUtil.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/ChannelUtilTest.java
Labels: defect

#3657 Add release note for 1.9.1
  site/src/pages/release-notes/1.9.1.mdx
Labels: documentation

#3660 Convert `:authority` header to `host` header in `{Tomcat,Jetty}Service`
  core/src/main/java/com/linecorp/armeria/server/ServerPort.java
  jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  site/src/pages/release-notes/1.9.1.mdx
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java
  testing-internal/src/main/webapp/index.jsp
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Labels: defect

#3665 Add a blog post by @jupiny
  site/src/pages/community/articles.mdx
Labels: documentation

#3663 Require the minimum JDK version to 11 for examples only
  build.gradle
  core/build.gradle
  dependencies.yml
  examples/graphql/src/main/java/example/armeria/server/graphql/UserDataFetcher.java
  examples/tutorials/rest-api-annotated-service/src/test/java/example/armeria/server/blog/BlogServiceTest.java
  scalapb/scalapb_2.12/build.gradle
  scalapb/scalapb_2.13/build.gradle
  site/src/pages/release-notes/1.9.0.mdx
  spring/boot1-starter/build.gradle
Labels: cleanup
