Repository line/armeria, pull requests merged in 2021-11, with the labels that each got.

#3903 Fail if an empty string is specified for EurekaEndpointGroupBuilder
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
Labels: defect

#3905 Use CircuitBreakerListener.metricCollecting in side document
  site/src/pages/docs/client-circuit-breaker.mdx
Labels: documentation

#3902 Add SubjectAlternativeNames in SelfSignedCertificate.
  core/src/main/java/com/linecorp/armeria/internal/common/util/SelfSignedCertificate.java
  dependencies.yml
  it/okhttp/build.gradle
  it/okhttp/src/test/java/com/linecorp/armeria/it/okhttp/OkHttpTlsTest.java
  settings.gradle
Labels: defect

#3910 Update site doc client-retry.mdx
  site/src/pages/docs/client-retry.mdx
Labels: cleanup

#3912 Accept more file extensions from GrpcDocStringExtractor
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java
  site/src/pages/docs/server-docservice.mdx
Labels: defect

#3936 Update JDK version to 16 in the developer guide
  site/src/pages/community/developer-guide.mdx
Labels: documentation

#3931 Add @jrhee17 to the team
  .github/CODEOWNERS
Labels: improvement

#3934 DecodingClient - accept duplicated encoding values
  core/src/main/java/com/linecorp/armeria/client/encoding/DecodingClient.java
  core/src/test/java/com/linecorp/armeria/client/encoding/DecodingClientTest.java
Labels: defect

#3930 Correctly clear HTTP query string and headers in DocService
  docs-client/src/containers/MethodPage/DebugPage.tsx
Labels: defect

#3917 DocService shows multiline docString
  docs-client/src/components/VariableList/index.tsx
Labels: defect

#3920 Fix the case where `unfinishedResponses` isn't decremented on early abort
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientMaxConcurrentStreamTest.java
Labels: defect

#3898 Fix bug for accept wildcard case in `GraphqlService`
  graphql-protocol/src/main/java/com/linecorp/armeria/internal/server/graphql/protocol/GraphqlUtil.java
  graphql-protocol/src/test/java/com/linecorp/armeria/internal/server/graphql/protocol/GraphqlUtilTest.java
Labels: defect

#3914 Fix a bug where protocol violation errors trigger duplicate headers writes
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerProtocolViolationTest.java
Labels: defect

#3908 Address `maxConcurrentStreams` violation on write timeout
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java
Labels: defect

#3922 Add a new community article by @julnamoo
  site/src/pages/community/articles.mdx
Labels: documentation

#3943 Add the release note for 1.13.3
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocStringExtractor.java
  site/release-note.ts
  site/src/pages/release-notes/1.13.3.mdx
Labels: documentation

#3942 Allow empty request path in AbstractHttpRequestBuilder
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
Labels: defect
