Repository line/armeria, pull requests merged in 2021-04, with the labels that each got.

#3426 Make Armeria buildable with JDK 15
  .appveyor.build.sh
  .appveyor.yml
  build.gradle
  consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroupBuilder.java
  consul/src/main/java/com/linecorp/armeria/server/consul/ConsulUpdatingListenerBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ContentDispositionBuilder.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeaderGetters.java
  core/src/test/java/com/linecorp/armeria/client/cookie/DefaultCookieJarTest.java
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunction.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java
  resteasy/src/main/java/com/linecorp/armeria/client/resteasy/ArmeriaResteasyClientBuilder.java
  site/src/pages/community/developer-guide.mdx
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/HealthCheckServiceConfigurator.java
Labels: cleanup, dependencies

#3427 Make it clear that we introduced a breaking change in 1.3.0
  site/src/pages/news/20200703-newsletter-1.mdx
  site/src/pages/news/20210202-newsletter-2.mdx
  site/src/pages/release-notes/0.84.0.mdx
  site/src/pages/release-notes/0.85.0.mdx
  site/src/pages/release-notes/0.86.0.mdx
  site/src/pages/release-notes/0.88.0.mdx
  site/src/pages/release-notes/0.89.0.mdx
  site/src/pages/release-notes/0.90.0.mdx
  site/src/pages/release-notes/0.90.3.mdx
  site/src/pages/release-notes/0.91.0.mdx
  site/src/pages/release-notes/0.92.0.mdx
  site/src/pages/release-notes/0.93.0.mdx
  site/src/pages/release-notes/0.94.0.mdx
  site/src/pages/release-notes/0.95.0.mdx
  site/src/pages/release-notes/0.98.0.mdx
  site/src/pages/release-notes/0.98.5.mdx
  site/src/pages/release-notes/0.99.0.mdx
  site/src/pages/release-notes/0.99.3.mdx
  site/src/pages/release-notes/0.99.6.mdx
  site/src/pages/release-notes/0.99.9.mdx
  site/src/pages/release-notes/1.1.0.mdx
  site/src/pages/release-notes/1.2.0.mdx
  site/src/pages/release-notes/1.3.0.mdx
  site/src/pages/release-notes/1.4.0.mdx
Labels: documentation

#3391 Provide shortcut methods for add cookie in {Request, Response}Headers Builder
  core/src/main/java/com/linecorp/armeria/common/Cookie.java
  core/src/main/java/com/linecorp/armeria/common/CookieUtil.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeaders.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultResponseHeaders.java
  core/src/main/java/com/linecorp/armeria/common/DefaultResponseHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeadersBuilder.java
  core/src/test/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultResponseHeadersBuilderTest.java
  scala/scala_2.13/src/test/scala/com/linecorp/armeria/common/CookieSuite.scala
Labels: new feature

#3424 Fix a flaky test in `PathStreamMessageTckTest`
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
Labels: cleanup

#3340 Fix a bug where a request has failed to be routed when both a '/path' and a '/{var}' path mappings exist with different HTTP methods
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/Route.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/RoutingTrie.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerAutoRedirectTest.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingTrieTest.java
Labels: defect

#3432 Fix incorrect managed dependency names
  core/build.gradle
Labels: cleanup

#3410 Allow to customize success status for request metrics
  core/src/main/java/com/linecorp/armeria/client/metric/AbstractMetricCollectingClient.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClient.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/metric/AbstractMetricCollectingBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
  core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingService.java
  core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
  examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloConfiguration.java
Labels: new feature

#3413 Add ExceptionHandler to send a different response depending on the Ex…
  core/src/main/java/com/linecorp/armeria/server/ExceptionHandler.java
  core/src/main/java/com/linecorp/armeria/server/ExceptionHandlerUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/test/java/com/linecorp/armeria/server/ExceptionHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
Labels: new feature

#3433 Add new built-in MDC property `req.root_id`
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Labels: new feature

#3434 Update dependencies
  .appveyor.report.sh
  bucket4j/src/main/java/com/linecorp/armeria/server/throttling/bucket4j/TokenBucketThrottlingStrategy.java
  build.gradle
  core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
  dependencies.yml
  docs-client/build.gradle
  docs-client/package-lock.json
  docs-client/package.json
  docs-client/src/lib/transports/annotated-http.ts
  docs-client/src/lib/transports/grpc-unframed.ts
  docs-client/src/lib/transports/thrift.ts
  docs-client/src/lib/transports/transport.ts
  it/grpcweb/build.gradle
  it/micrometer1.3/build.gradle
  it/spring/boot2-tomcat8/build.gradle
  resteasy/src/main/java/com/linecorp/armeria/client/resteasy/ArmeriaResteasyClientBuilder.java
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala
  site/build.gradle
  site/package-lock.json
  site/package.json
  spring/boot1-autoconfigure/build.gradle
  tomcat8/build.gradle
  zookeeper3/build.gradle
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: cleanup, dependencies

#3366 Provide a way to customize default `serviceName` in RequestLog
  benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ServiceNamingUtil.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServiceNaming.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogComponent.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/common/metric/MeterIdPrefixFunctionTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/GrpcLogUtilTest.java
Labels: deprecation, new feature

#3436 Add the release note for 1.6.0
  site/src/pages/release-notes/1.6.0.mdx
Labels: documentation

#3443 Fix a bug where a Spring `SecurityContext` is not propagated to upstream
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  dependencies.yml
  it/spring/webflux-security/build.gradle
  it/spring/webflux-security/src/test/java/com/linecorp/armeria/spring/security/SecureApp.java
  it/spring/webflux-security/src/test/java/com/linecorp/armeria/spring/security/SecureConfiguration.java
  it/spring/webflux-security/src/test/java/com/linecorp/armeria/spring/security/SecureResource.java
  it/spring/webflux-security/src/test/java/com/linecorp/armeria/spring/security/SecureResourceTest.java
  settings.gradle
  site/src/pages/release-notes/1.6.0.mdx
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
Labels: defect

#3441 Fix a bug where a wrong context is pushed when `RequestContextHooks` is enabled
  reactor3/src/main/java/com/linecorp/armeria/common/reactor3/RequestContextHooks.java
  reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareFluxTest.java
  reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareMonoTest.java
  site/src/pages/release-notes/1.6.0.mdx
Labels: defect

#3459 Do not log `RequestTimeoutException` when timed out too early
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
Labels: defect

#3460 Do not throw `EofException` if attempted to write to a timed out resp…
  jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
Labels: defect

#3449 Fix a bug where an exception raised in `FilteredStreamMessage` is not…
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/FilteredStreamMessageTest.java
Labels: defect

#3450 Fix a bug where a `PathStreamMessage` raises an `IllegalStateExceptio…
  core/src/main/java/com/linecorp/armeria/common/stream/PathStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/PathStreamMessageTest.java
Labels: defect

#3462 Defer instantiation of a TimeoutException until a request actually is timed out
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/common/CancellationSchedulerTest.java
Labels: improvement

#3477 Remove invaild method name from the warn message in `RequestContextCurrentTraceContext`
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.java
Labels: defect

#3461 Fix a bug where duplicated parameter specifications of a data class i…
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java
  examples/README.md
  kotlin/build.gradle.kts
  kotlin/src/test/kotlin/com/linecorp/armeria/server/DataClassDocServiceTest.kt
Labels: defect

#3458 Support Kotlin's data class and Scala's case class in the default Jackson converter of annotated service
  core/src/main/java/com/linecorp/armeria/internal/server/JacksonUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonRequestConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/streaming/JsonTextSequences.java
  kotlin/build.gradle.kts
  kotlin/src/test/kotlin/com/linecorp/armeria/server/JacksonModuleAnnotatedServiceTest.kt
  scala/scala_2.12/build.gradle
  scala/scala_2.13/build.gradle
  scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/JacksonModuleAnnotatedServiceTest.scala
  scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/ServerSuite.scala
Labels: new feature

#3479 Fix incorrect path parameter substitutions in `AbstractHttpRequestBuilder`
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java
Labels: defect

#3485 Do not log verbosely when `Socket.initialize()` fails.
  core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
Labels: defect

#3486 Remove unused `javax.annotation:javax.annotation-api` dependencies
  grpc/build.gradle
  scala/scala_2.12/build.gradle
  scala/scala_2.13/build.gradle
Labels: dependencies

#3467 Use GitHub Actions
  .appveyor.build.sh
  .appveyor.report.sh
  .appveyor.yml
  .github/workflows/actions_build.yml
  build.gradle
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
  gradle/wrapper/gradle-wrapper.properties
  scalapb/scalapb_2.12/build.gradle
  scalapb/scalapb_2.13/build.gradle
Labels: cleanup

#3488 Fix flaky `PrometheusMetricExposureTest`
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/PrometheusMetricExposureTest.java
Labels: cleanup

#3487 Update dependencies
  build.gradle
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  dependencies.yml
  dropwizard2/build.gradle
  settings/checkstyle/checkstyle.xml
Labels: dependencies

#3482 Prepare to support WebSockets over HTTP/2
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/common/HttpMethod.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpService.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientRequestPathTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpMethodTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerConnectMethodTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTooLargeContentTest.java
Labels: new feature

#3468 Fix a bug where `ServiceNaming` produces a wrong serviceName for annotated services
  .gitignore
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ServiceNamingUtil.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceNaming.java
  core/src/main/java/com/linecorp/armeria/server/SimpleTypeServiceNaming.java
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AnnotatedServiceLogNameTest.java
Labels: defect

#3444 Add a benchmark for plaintext
  benchmarks/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
Labels: performance

#3490 Use self-hosted runner for GitHub Actions
  .github/workflows/actions_build.yml
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  gradle/wrapper/gradle-wrapper.properties
  site/build.gradle
Labels: cleanup

#3494 Fix a bug where a server-side `RequestLog` is not completed a request…
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRequestCancellationTest.java
Labels: defect

#3495 Add release note for 1.7.1
  site/src/pages/release-notes/1.7.1.mdx
Labels: documentation

#3497 Increase timeout to fix flaky test in BraveIntegrationTest
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
Labels: cleanup

#3060 Handle request timeout correctly for HTTP
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/client/Http1ResponseDecoderTest.java
Labels: defect

#3503 Add release note for 1.7.2
  site/src/pages/release-notes/1.7.2.mdx
Labels: documentation
