Repository line/armeria, pull requests merged in 2021-02, with the labels that each got.

#3316 Update frontend dependencies
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  docs-client/package-lock.json
  docs-client/package.json
  licenses/web-licenses.txt
  site/README.md
  site/package-lock.json
  site/package.json
Labels: dependencies

#3237 HttpResponse.of(ResponseHeaders,Publisher<HttpObject>)
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/PrependingPublisher.java
  core/src/test/java/com/linecorp/armeria/common/PublisherBasedHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/PrependingPublisherTckTest.java
Labels: new feature

#3317 Add release notes for 1.4.0
  site/src/pages/release-notes/1.4.0.mdx
Labels: documentation

#3319 Add documentation for Consul
  site/src/pages/docs/client-service-discovery.mdx
  site/src/pages/docs/server-service-registration.mdx
Labels: documentation

#3322 Correct DocService documentation
  site/src/pages/docs/server-docservice.mdx
Labels: documentation

#3324 Add Armeria newsletter vol. 2
  site/package-lock.json
  site/package.json
  site/src/pages/news/20210202-newsletter-2.mdx
  site/src/pages/release-notes/1.4.0.mdx
Labels: miscellaneous

#3326 Fix a typo in the structured logging site page
  site/src/pages/docs/advanced-structured-logging.mdx
Labels: cleanup

#3325 Add an explicit width for embedded tweet in newsletter
  site/src/pages/news/20210202-newsletter-2.mdx
  site/src/styles/antd-overrides.less
Labels: miscellaneous

#3331 Support async request handling in `JettyService`
  jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  jetty9/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java
Labels: new feature

#3339 Add `netty-resolver-dns-native-macos` as a transitive dependency
  core/build.gradle
Labels: dependencies

#3338 Fix a bug where an `IllegalStateException` is raised on a non-ready `EndpointGroup`
  consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/LazyDynamicEndpointGroupTest.java
Labels: defect

#3337 Fix not to release elements before subscribed in duplicator
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorCloseTest.java
Labels: defect

#3328 Fix a bug where trailers is not properly received by non-official gRPC client
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTrailersTest.java
Labels: defect

#3289 Add documentation for `ClientFactoryBuilder`
  site/src/pages/docs/client-factory.mdx
  site/src/pages/docs/toc.json
Labels: documentation

#3361 Add documentation for brief introduction of WebClient features
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  site/src/pages/docs/client-http.mdx
Labels: documentation

#3343 Provide a way to bulid an `HttpRequest` with a `Publisher`
  core/src/main/java/com/linecorp/armeria/client/WebClientRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestBuilder.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java
Labels: new feature

#3329 Let GrpcStatusFunction mutate Metadata
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/HelloServiceImpl.kt
  examples/grpc-kotlin/src/main/proto/hello.proto
  examples/grpc-kotlin/src/test/kotlin/example/armeria/grpc/kotlin/HelloServiceTest.kt
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcStatusFunction.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframer.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcStatusMappingTest.java
  it/grpc/kotlin/build.gradle.kts
  it/grpc/kotlin/src/test/kotlin/com/linecrop/armeria/grpc/kotlin/HelloServiceImpl.kt
  it/grpc/kotlin/src/test/kotlin/com/linecrop/armeria/grpc/kotlin/HelloServiceTest.kt
  it/grpc/kotlin/src/test/proto/hello.proto
  it/grpc/reactor/build.gradle
  it/grpc/reactor/src/test/java/com/linecorp/armeria/grpc/reactor/HelloServiceImpl.java
  it/grpc/reactor/src/test/java/com/linecorp/armeria/grpc/reactor/HelloServiceTest.java
  it/grpc/reactor/src/test/proto/hello.proto
  it/grpc/scala/build.gradle
  it/grpc/scala/src/test/proto/hello.proto
  it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceImpl.scala
  it/grpc/scala/src/test/scala/com/linecorp/armeria/grpc/scala/HelloServiceTest.scala
  settings.gradle
Labels: new feature

#3354 Add the release note for 1.5.0
  site/src/pages/release-notes/1.5.0.mdx
Labels: documentation

#3336 Use func.name() to build Thrift request header
  thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
Labels: defect
