Repository line/armeria, pull requests merged in 2021-12, with the labels that each got.

#3927 Make HealthCheckedEndpointGroup gracefully update new endpoints
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AllHealthCheckStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/PartialHealthCheckStrategy.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/AllHealthCheckStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupCompatibilityTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupLongPollingTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/PartialHealthCheckStrategyBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/PartialHealthCheckStrategyTest.java
Labels: defect, improvement

#3951 Make sure to start a gRPC client call after the initialization of an `Endpoint`
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/StaticEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/package-info.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/LazyDynamicEndpointGroupTest.java
Labels: defect

#3947 Abort server startup if `ServerListener.serverStarting` throws an exception
  core/src/main/java/com/linecorp/armeria/common/util/StartStopSupport.java
  core/src/test/java/com/linecorp/armeria/common/util/StartStopSupportTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerListenerTest.java
Labels: defect

#3960 Add `queryParams()` to `ServiceRequestContext`
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java
Labels: new feature

#3976 Fix flaky test in HealthCheckedEndpointGroupIntegrationTest
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupIntegrationTest.java
Labels: cleanup

#3970 Limit steps for composing a tutorial stepper
  site/src/components/steps.tsx
Labels: defect

#3929 Change Prometheus exporter's ByteArrayOutputStream to ByteBufOutputStream
  core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java
  core/src/test/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceTest.java
Labels: improvement

#3895 Add more shortcuts for `RetryRule` and `RetryRuleWithContent`
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRule.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContent.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: new feature

#3975 Provide a way to set a gRPC's ClientInterceptor using GrpcClientOptions
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
  grpc/src/test/java/com/linecorp/armeria/internal/client/grpc/CustomGrpcClientFactoryTest.java
Labels: new feature

#3939 Deprecate Cookie.builder and introduce Cookie.secureBuilder
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Cookie.java
  core/src/test/java/com/linecorp/armeria/client/cookie/AcceptOriginCookiePolicyTest.java
  core/src/test/java/com/linecorp/armeria/client/cookie/CookieClientTest.java
  core/src/test/java/com/linecorp/armeria/client/cookie/DefaultCookieJarTest.java
  core/src/test/java/com/linecorp/armeria/common/ClientCookieEncoderTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultCookieTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultResponseHeadersBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeaderCachedValuesTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/ServerCookieEncoderTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/MyAuthHandler.java
  resteasy/src/test/java/com/linecorp/armeria/server/resteasy/BookServiceServerTest.java
  resteasy/src/test/java/com/linecorp/armeria/server/resteasy/CalculatorServiceServerTest.java
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlServiceProviderTest.java
  scala/scala_2.13/src/test/scala/com/linecorp/armeria/common/CookieSuite.scala
  site/src/pages/docs/advanced-saml.mdx
Labels: new feature, deprecation

#3928 support other prometheus formats
  core/src/main/java/com/linecorp/armeria/server/metric/PrometheusExpositionService.java
  core/src/test/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceTest.java
Labels: new feature

#3921 Overloaded WebClient's methods to accept query parameters
  core/src/main/java/com/linecorp/armeria/client/WebClient.java
  core/src/main/java/com/linecorp/armeria/client/WebClientUtil.java
  core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java
  core/src/test/java/com/linecorp/armeria/client/WebClientUtilTest.java
Labels: new feature

#3946 Expose Actuator WebOperation to a port of internal services
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationInternalServiceTest.java
  spring/boot2-actuator-autoconfigure/src/test/resources/application-actuatorTest.yml
  spring/boot2-actuator-autoconfigure/src/test/resources/application-allInternalServices.yml
  spring/boot2-actuator-autoconfigure/src/test/resources/application-defaultInternalServices.yml
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/InternalServiceId.java
Labels: new feature

#3949 Add `StreamMessage.peek()`
  core/src/main/java/com/linecorp/armeria/client/cookie/CookieClient.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/ResponsePeekTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessagePeekTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpHeaderTest.java
Labels: new feature

#3941 Add HttpResponseBuilder to fluently build `HttpResponse`
  core/src/main/java/com/linecorp/armeria/client/WebClientRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpMessageBuilder.java
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseBuilder.java
  core/src/test/java/com/linecorp/armeria/common/HttpResponseBuilderTest.java
Labels: defect, new feature

#3991 Update GPG passphrase for the `Public Suffix List` job
  .github/workflows/public-suffixes.yml
Labels: miscellaneous

#3990 Add exception to warning log in FramedGrpcService.
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
Labels: cleanup

#3998 Add a new community podcast video
  site/src/pages/community/articles.mdx
Labels: documentation

#4000 Add a new japanese conference video
  site/src/pages/community/articles.mdx
Labels: documentation

#3984 Handle missing `SameSite` attribute in `ClientCookieDecoder`
  core/src/main/java/com/linecorp/armeria/common/ClientCookieDecoder.java
  core/src/test/java/com/linecorp/armeria/common/ClientCookieDecoderTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeaderCachedValuesTest.java
Labels: defect

#3962 Add mapAsync method to StreamMessage
  core/src/main/java/com/linecorp/armeria/common/stream/AsyncMapStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/AsyncMapStreamMessageTest.java
Labels: new feature

#3948 Provide a way to send a different HTTP status in an unframed gRPC service
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcStatusMappingFunction.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
Labels: new feature

#4004 Use GitHub managed runners to build site
  .github/workflows/actions_build.yml
  site/build.gradle
Labels: miscellaneous
