Repository line/armeria, pull requests merged in 2021-09, with the labels that each got.

#3795 Allow to sanitize request or response content preview
  core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/logging/ContentPreviewingUtil.java
  core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java
  core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/client/logging/ContentPreviewingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
Labels: new feature

#3811 Fix a bug where benchmark parameters aren't respected
  benchmarks/build.gradle
  dependencies.yml
Labels: dependencies

#3775 Support RCEA with independent states
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporter.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestContextExporterBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/RequestContextExporterTest.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  logback/src/test/resources/com/linecorp/armeria/common/logback/testXmlConfig.xml
Labels: new feature

#3754 Allow specifying different `blockingTaskExecutor` per route
  benchmarks/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceBlockingPerRouteTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
Labels: new feature

#3800 Fix a bug where a gRPC client call is closed twice
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  it/grpc/kotlin/src/test/kotlin/com/linecorp/armeria/grpc/kotlin/HelloServiceTest.kt
Labels: defect

#3782 Use a custom error response mapper for unframed requests
  examples/grpc/build.gradle
  examples/grpc/src/main/java/example/armeria/grpc/HelloServiceImpl.java
  examples/grpc/src/test/java/example/armeria/grpc/HelloServiceTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
Labels: new feature

#3768 Add support for Kotlin `Flow` in `AnnotatedService`
  benchmarks/build.gradle
  benchmarks/src/jmh/kotlin/com/linecorp/armeria/internal/common/kotlin/AnnotatedServiceFlowBenchmark.kt
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/KotlinUtil.java
  kotlin/build.gradle.kts
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaCoroutineUtil.kt
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaKotlinUtil.kt
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/FlowCollectingPublisher.kt
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/FlowResponseConverterFunction.kt
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/FlowResponseConverterFunctionProvider.kt
  kotlin/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.ResponseConverterFunctionProvider
  kotlin/src/test/java/com/linecorp/armeria/internal/server/annotation/KotlinUtilWithKotlinDependenciesTest.java
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/DataClassDocServiceTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/ExampleService.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/FlowAnnotatedServiceTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/FlowCollectingPublisherTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/JacksonModuleAnnotatedServiceTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/Jsr305StrictTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt
  settings.gradle
Labels: new feature

#3813 Specify `SamlEndpoint` when creating `SamlAssertionConsumerConfigBuil…
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerConfigBuilder.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceProviderBuilder.java
Labels: deprecation

#3735 Add more parameters to `ArmeriaSettings`
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1ConversionServiceConfiguration.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/NumberToDurationConverter.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationSettingsUtil.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationPriorityTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationTest.java
  spring/boot2-autoconfigure/src/test/resources/config/application-settings.yml
  spring/boot2-webflux-autoconfigure/build.gradle
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerSettingsTest.java
  spring/boot2-webflux-autoconfigure/src/test/resources/config/application-test_armeria_settings.yml
Labels: new feature

#3815 Add useful method to `GraphqlService`
  core/src/main/java/com/linecorp/armeria/internal/common/util/ResourceUtil.java
  dropwizard2/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaConfigurationUtil.java
  examples/graphql-kotlin/src/main/kotlin/example/armeria/server/graphql/kotlin/Main.kt
  examples/graphql-kotlin/src/main/resources/schema.graphqls
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilder.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilderTest.java
Labels: new feature

#3818 Fix that a failed response of transient service is not logged
  core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
  core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/TransientHttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/WrappingTransientHttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceTest.java
Labels: defect

#3809 Add `auth` builder method to `HealthCheckedEndpointGroupBuilder`
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/common/auth/AuthToken.java
  core/src/main/java/com/linecorp/armeria/common/auth/BasicToken.java
  core/src/main/java/com/linecorp/armeria/common/auth/OAuth1aToken.java
  core/src/main/java/com/linecorp/armeria/common/auth/OAuth2Token.java
  core/src/main/java/com/linecorp/armeria/server/auth/BasicTokenExtractor.java
  core/src/main/java/com/linecorp/armeria/server/auth/OAuth1aTokenExtractor.java
  core/src/main/java/com/linecorp/armeria/server/auth/OAuth2TokenExtractor.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/common/auth/OAuth1aTokenTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/BasicTokenTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/OAuth2TokenTest.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
  eureka/src/test/java/com/linecorp/armeria/client/eureka/ArmeriaEurekaClientTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
Labels: new feature

#3397 Add documentation about streaming response
  site/build.gradle
  site/src/pages/docs/advanced-streaming-backpressure.mdx
  site/src/pages/docs/toc.json
Labels: documentation

#3770 Utility for scheduling a task and retrieving its CompletableFuture
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/test/java/com/linecorp/armeria/common/HttpResponseTest.java
Labels: new feature

#3825 Fix a bug where a client sends requests using a closing connection.
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2GoAwayHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/test/java/com/linecorp/armeria/client/ClientGoAwayGracefulShutdownTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
Labels: defect

#3814 Add a benchmark that measures gRPC server performance with `ghz`
  benchmarks/ghz/README.md
  benchmarks/ghz/bench.sh
  benchmarks/ghz/build.gradle
  benchmarks/ghz/src/main/java/com/linecorp/armeria/grpc/ghz/GreeterServer.java
  benchmarks/ghz/src/main/proto/hello.proto
  benchmarks/ghz/src/main/resources/100B
  benchmarks/ghz/src/main/resources/10B
  benchmarks/ghz/src/main/resources/10kB
  benchmarks/ghz/src/main/resources/1kB
  benchmarks/jmh/README.md
  benchmarks/jmh/build.gradle
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/ExceptionSamplerBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/HttpHeadersBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/HttpRequestHeaderConversionBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/HttpResponseHeaderConversionBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/MediaTypesBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/QueryStringDecoderBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/QueryStringEncoderBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/stream/StreamMessageCollectorBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/common/thrift/text/StackTracingBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/core/HttpServerBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/core/client/endpoint/DnsEndpointGroupBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/core/client/endpoint/WeightedRoundRobinStrategyBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/core/client/retry/BackoffBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/core/client/retry/RetryingClientBase.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/core/client/retry/WithDuplicator.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/core/client/retry/WithoutDuplicator.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/grpc/GrpcServiceBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/grpc/downstream/DownstreamSimpleBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/grpc/downstream/LargePayloadBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/grpc/shared/ClientType.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/grpc/shared/GithubApiService.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/grpc/shared/SimpleBenchmarkBase.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/grpc/upstream/UpstreamSimpleBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/client/PublicSuffixBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/common/ByteBufDecoderInputBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/common/CacheableClassLoader.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/common/ClassLoadBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/common/PathParsingBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/common/util/HttpTimestampSupplierBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/common/util/IntegersBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/server/annotation/MethodInvokerBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/retrofit2/downstream/DownstreamSimpleBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkBase.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/retrofit2/shared/SimpleBenchmarkClient.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/retrofit2/upstream/UpstreamSimpleBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/shared/AsyncCounters.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/shared/EventLoopJmhExecutor.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/thrift/PooledResponseBufferBenchmark.java
  benchmarks/jmh/src/jmh/proto/com/linecorp/armeria/grpc/binary-proxy.proto
  benchmarks/jmh/src/jmh/proto/com/linecorp/armeria/grpc/github-api.proto
  benchmarks/jmh/src/jmh/resources/github_search_response.binarypb
  benchmarks/jmh/src/jmh/resources/logback-test.xml
  benchmarks/jmh/src/jmh/thrift/services.thrift
  settings.gradle
  settings/checkstyle/checkstyle-suppressions.xml
Labels: miscellaneous

#3836 Fix a bug where additional headers are not sent when a request is failed.
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerAdditionalHeadersTest.java
Labels: defect

#3841 Address flaky test KeepAliveHandlerTest.testIdle
  core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
Labels: cleanup
