Repository line/armeria, pull requests merged in 2021-01, with the labels that each got.

#3244 Allow using Armeria without epoll or io_uring JARs
  core/build.gradle
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/util/EventLoopGroups.java
  core/src/main/java/com/linecorp/armeria/common/util/TransportType.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ChannelUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/TransportTypeProvider.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/DefaultDnsNameResolverTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/ChannelUtilTest.java
Labels: dependencies, deprecation, new feature

#3245 Fix test for `@LocalArmeriaPort(s)`
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaBeanPostProcessor.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortsTest.java
Labels: cleanup

#3251 Fix a bug where NPE is raised when retrying a gRPC request
  core/src/main/java/com/linecorp/armeria/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientRetryTest.java
Labels: defect

#3250 Fix flaky test in Consul
  consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
Labels: cleanup

#3249 Deprecate CircuitBreakerRpcClient.newPerHostAndMethodDecorator()
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRpcClient.java
  site/src/pages/docs/client-circuit-breaker.mdx
  site/src/pages/release-notes/1.3.0.mdx
Labels: deprecation

#3256 Exclude `tomcat-embed-jasper` from exposed dependencies
  tomcat9/build.gradle
Labels: breaking change, defect

#3220 Fix invalid return types of overridden methods in builder classes
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  it/builders/build.gradle
  it/builders/src/test/java/com/linecorp/armeria/OverriddenBuilderMethodsReturnTypeTest.java
  settings.gradle
Labels: breaking change, defect

#3252 Fix flaky test in TomcatServiceDestroyedConnectorTest
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
  tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceDestroyedConnectorTest.java
Labels: cleanup

#3259 Add `Http1HeaderNaming` rule for WebClient
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Http1HeaderNaming.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/client/Http1HeaderNamingTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
Labels: new feature

#3265 Mark public_suffixes.txt as generated code for GitHub PR view
  .gitattributes
Labels: cleanup

#3261 Fix 'Go to' selection handling in docs-client
  docs-client/src/components/GotoSelect/index.tsx
Labels: defect

#3290 Correct FindBugs-JSR305 license
  NOTICE.txt
  licenses/LICENSE.jsr305.al20.txt
  licenses/LICENSE.jsr305.bsd.txt
Labels: miscellaneous

#3288 Support Jetty 9.3
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  jetty9.3/build.gradle
  jetty9/src/main/java/com/linecorp/armeria/server/jetty/ArmeriaEndPoint.java
  jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  settings.gradle
Labels: improvement

#3254 Add `ConcatArrayStreamMessage` which flattens an array of `StreamMessage`s (Multipart 2/4)
  NOTICE.txt
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/ConcatArrayStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageUtil.java
  core/src/main/java/com/linecorp/armeria/common/stream/SubscriberUtil.java
  core/src/main/java/com/linecorp/armeria/common/stream/SubscriptionArbiter.java
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  core/src/test/java/com/linecorp/armeria/common/stream/ConcatArrayStreamMessageTck1Test.java
  core/src/test/java/com/linecorp/armeria/common/stream/ConcatArrayStreamMessageTck2Test.java
  core/src/test/java/com/linecorp/armeria/common/stream/ConcatStreamTest.java
  licenses/LICENSE.heldion.al20.txt
Labels: new feature

#3275 Fix eureka registration
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
Labels: defect

#3274 Add 'A Bootiful Podcast: Netty and Armeria founder Trustin Lee'
  site/src/pages/community/articles.mdx
Labels: documentation

#3282 Override logger(String) on `LoggingServiceBuilder`
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
Labels: cleanup

#3257 Add the articles of Request Scoping and Writing a Java library with better experience
  site/src/pages/community/articles.mdx
Labels: documentation

#3253 Add `Content-Disposition` header codec (Multipart 1/4)
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ContentDisposition.java
  core/src/main/java/com/linecorp/armeria/common/ContentDispositionBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeaders.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaders.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  core/src/main/java/com/linecorp/armeria/common/QueryParams.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/StringValueConverter.java
  core/src/test/java/com/linecorp/armeria/common/ContentDispositionTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultHttpHeadersBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersBaseTest.java
  core/src/test/java/com/linecorp/armeria/common/StringMultimapDerivedApiConsistencyTest.java
  dropwizard2/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaServerFactory.java
Labels: new feature

#3295 Fix unknown API example in advanced-structured-logging document
  site/src/pages/docs/advanced-structured-logging.mdx
Labels: documentation

#3238 Attempt re-registration when Eureka heart beat fails with 404 Not Found
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
  eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
Labels: defect

#3281 Add support for datacenters, tags and filtering to Consul
  consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroup.java
  consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroupBuilder.java
  consul/src/main/java/com/linecorp/armeria/internal/consul/AgentServiceClient.java
  consul/src/main/java/com/linecorp/armeria/internal/consul/CatalogClient.java
  consul/src/main/java/com/linecorp/armeria/internal/consul/ConsulClient.java
  consul/src/main/java/com/linecorp/armeria/internal/consul/ConsulClientUtil.java
  consul/src/main/java/com/linecorp/armeria/internal/consul/HealthClient.java
  consul/src/main/java/com/linecorp/armeria/server/consul/ConsulUpdatingListener.java
  consul/src/main/java/com/linecorp/armeria/server/consul/ConsulUpdatingListenerBuilder.java
  consul/src/test/java/com/linecorp/armeria/client/consul/ConsulEndpointGroupTest.java
  consul/src/test/java/com/linecorp/armeria/server/consul/ConsulUpdatingListenerTest.java
Labels: new feature

#3301 Fix localArmerialPortMetadata cachekey
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaBeanPostProcessor.java
Labels: defect

#3267 Provide a way to limit max number of requests and max connection age for client
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandlerUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/NoopKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http1ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java
  core/src/test/java/com/linecorp/armeria/common/KeepAliveMaxNumRequestsTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/Http2KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
Labels: new feature

#3298 Wrap `ClosedStreamExeception` with `UnprocessedRequestException` when `REFUSED_STREAM` is received
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/test/java/com/linecorp/armeria/client/Http2ClientRefusedStreamTest.java
Labels: defect

#3305 Fix `IllegalStateException` error when the external client was already started
  zookeeper3/src/main/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroup.java
  zookeeper3/src/main/java/com/linecorp/armeria/server/zookeeper/ZooKeeperUpdatingListener.java
  zookeeper3/src/test/java/com/linecorp/armeria/client/zookeeper/ZooKeeperEndpointGroupTest.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceExternalClientUsageTest.java
Labels: defect

#3287 Add support for `HttpFile` auto-conversion in annotated services
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/server/annotation/HttpFileResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceResponseConverterTest.java
Labels: new feature

#3272 Fix bug that camel function name could not be found when thrift define is low underline style
  it/thrift-fullcamel/build.gradle
  it/thrift-fullcamel/src/test/java/server/thrift/CamelNameThriftServiceTest.java
  it/thrift-fullcamel/src/test/java/server/thrift/ThriftServiceMetadataTest.java
  it/thrift-fullcamel/src/test/thrift/main.thrift
  settings.gradle
  thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftServiceMetadata.java
Labels: defect

#3302 Use SourceVersion.latest for the annotation processor
  annotation-processor/src/main/java/com/linecorp/armeria/server/annotation/processor/DocumentationProcessor.java
Labels: cleanup

#3308 Add multiple ServerServiceDefinition to GrpcServiceBuilder
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
Labels: new feature

#3260 Add option to start `HealthCheckService` unhealthy and register listener
  core/src/main/java/com/linecorp/armeria/server/healthcheck/DefaultHealthCheckUpdateHandler.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckUpdateListener.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
Labels: new feature

#3311 Provide more ways to run with context
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextTest.java
Labels: new feature
