Repository line/armeria, pull requests merged in 2021-05, with the labels that each got.

#3506 Correctly sends "Connection: close" header on disallowed HTTP/1 requests
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerConnectMethodTest.java
Labels: defect

#3498 Fix flaky tests in `DnsMetricsTest`
  .github/workflows/actions_build.yml
  core/src/main/java/com/linecorp/armeria/client/DefaultDnsQueryLifecycleObserver.java
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java
  core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  gradle.properties
Labels: cleanup

#3515 Clean up flaky tests
  .github/workflows/actions_build.yml
  consul/src/test/java/com/linecorp/armeria/client/consul/ConsulEndpointGroupTest.java
  consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
  consul/src/test/java/com/linecorp/armeria/server/consul/ConsulUpdatingListenerTest.java
  core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
  core/src/test/java/com/linecorp/armeria/client/DnsTimeoutUtil.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceDiscoveryCompatibilityTest.java
Labels: cleanup

#3525 Clean up flaky tests (3rd round)
  .github/workflows/actions_build.yml
  consul/src/test/java/com/linecorp/armeria/internal/consul/ConsulTestBase.java
  core/src/test/java/com/linecorp/armeria/client/ClientMaxConnectionAgeTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/management/ManagementServiceTest.java
  examples/server-sent-events/src/main/java/example/armeria/server/sse/Main.java
  examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java
  gradle/scripts/lib/common-git.gradle
  thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceExternalClientUsageTest.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/ZooKeeperRegistrationTest.java
Labels: cleanup

#3534 Avoid unnesssary put operations for `PathAndQuery`
  core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
Labels: improvement, performance

#3507 Add code completion for armeria.ssl
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
Labels: improvement

#3531 Propagate the response tailers of a child log to the parent log
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcRetryWithCircuitBreakerTest.java
Labels: defect

#3524 Fix a leak when `ContentTooLargeException` is raised by a `DefaultMessageDuplicator`
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/test/java/com/linecorp/armeria/common/DefaultHttpResponseDuplicatorTest.java
Labels: defect

#3500 Fix spring boot test using wrong TestConfiguration class for loading ApplicationContext
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationSecureTest.java
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
  spring/boot2-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/PrometheusMetricExposureTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationDisabledTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaGracefulShutdownConfigurationTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSslConfigurationTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortHttpsTest.java
Labels: cleanup

#3406 Provide a way to implement a HealthChecker with periodic polling
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckStatus.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthChecker.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/ScheduledHealthChecker.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/ScheduledHealthCheckerTest.java
Labels: new feature

#3537 Use a precomputed serviceName and method name instead of splitting a full method name on demand
  core/src/main/java/com/linecorp/armeria/common/DefaultRpcRequest.java
  core/src/main/java/com/linecorp/armeria/common/RpcRequest.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ServiceNamingUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServiceNaming.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcLogUtil.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HandlerRegistry.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
Labels: new feature

#3538 Skip to check wildcard domains when no virtual host is used.
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
Labels: improvement

#3530 Fix a recursive update with a `ConcurrentHashMap` in `RefreshingAddre…
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
Labels: defect

#3543 Compute readableByte on read and write operations to avoid additional…
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/common/ByteBufDecoderInputBenchmark.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/ByteBufDecoderInput.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/ByteBufDecoderInputTest.java
  dependencies.yml
Labels: improvement

#3539 Add a constant String pool for efficient conversion from String to int
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/common/util/IntegersBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/DefaultDnsQueryLifecycleObserver.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/common/HttpStatus.java
  core/src/main/java/com/linecorp/armeria/common/StringMultimap.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/StringUtil.java
  core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/StringUtilTest.java
  dependencies.yml
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/common/grpc/protocol/GrpcTrailersUtil.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcMeterIdPrefixFunction.java
Labels: improvement

#3456 Changes to introduce JSON lines encoder
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  core/src/main/java/com/linecorp/armeria/server/streaming/JsonLines.java
  core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
  core/src/test/java/com/linecorp/armeria/server/streaming/JsonLinesTest.java
Labels: new feature

#3502 Allow to add and set HTTP headers using `java.util.Map`
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/QueryParamsBuilder.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeadersBuilder.java
  core/src/test/java/com/linecorp/armeria/common/DefaultHttpHeadersBuilderTest.java
  scala/scala_2.13/src/test/scala/com/linecorp/armeria/common/HttpHeaderSuite.scala
Labels: new feature

#3552 Provide a way to disable `DnsQueryLifecycleObserverFactory`
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
Labels: new feature

#3548 AnnotatedService to use MethodHandle in place of java.lang.reflect.Method
  benchmarks/src/jmh/java/com/linecorp/armeria/internal/server/annotation/MethodInvokerBenchmark.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
Labels: improvement

#3563 Fix flaky GracefulShutdownIntegrationTest
  thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
Labels: cleanup

#3536 Allow users to specify metric success function with ArmeriaAutoConfiguration
  examples/spring-boot-minimal/src/main/java/example/springframework/boot/minimal/HelloConfiguration.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/MetricCollectingServiceConfigurator.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot2-webflux-autoconfigure/build.gradle
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
Labels: new feature

#3532 Improve a DNS query exception matcher
  core/src/main/java/com/linecorp/armeria/client/DefaultDnsQueryLifecycleObserver.java
Labels: improvement, performance

#3564 Fix `NullPointerException` in `CancellationScheduler`
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
  core/src/test/java/com/linecorp/armeria/internal/common/CancellationSchedulerTest.java
Labels: defect

#3558 Add `ElementType.TYPE_USE` to `NonNullByDefault`
  core/src/main/java/com/linecorp/armeria/common/annotation/NonNullByDefault.java
Labels: improvement

#3559 Do not swallow server errors of `TransientService`
  core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingDecorators.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/metric/PrometheusExpositionServiceTest.java
Labels: defect

#3508 Trim trailing dollar signs in `fullTypeName()` and `shorten()` of `ServiceNaming` for consistency
  core/src/main/java/com/linecorp/armeria/internal/common/util/ServiceNamingUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServiceNaming.java
  core/src/main/java/com/linecorp/armeria/server/SimpleTypeServiceNaming.java
  core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AnnotatedServiceLogNameTest.java
Labels: improvement

#3566 Update dependencies
  dependencies.yml
  docs-client/package-lock.json
  docs-client/package.json
  site/package-lock.json
  site/package.json
Labels: dependencies

#3567 Release note for 1.8.0
  core/src/test/java/com/linecorp/armeria/client/WebClientRequestPreparationTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
  site/src/pages/release-notes/1.8.0.mdx
Labels: documentation

#3574 Fix flaky `HttpServerRequestTimeoutTest`
  core/src/test/java/com/linecorp/armeria/server/HttpServerRequestTimeoutTest.java
Labels: cleanup

#3570 Cleanup CancellationScheduler to provide more accurate timeout nanos
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
Labels: defect

#3573 Fix flaky `ServiceRequestCancellationTest`
  core/src/test/java/com/linecorp/armeria/server/ServiceRequestCancellationTest.java
Labels: cleanup

#3581 HttpRequestSubscriber should update RequestLogBuilder with all sent request headers
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestSubscriberTest.java
Labels: defect

#3580 Add a notice for Micrometer 1.7.0 upgrade in 1.8.0
  site/src/pages/release-notes/1.8.0.mdx
Labels: documentation

#3568 Add get last method for HttpHeaders and QueryParams
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/QueryParamGetters.java
  core/src/main/java/com/linecorp/armeria/common/StringMultimap.java
  core/src/main/java/com/linecorp/armeria/common/StringMultimapBuilder.java
  core/src/main/java/com/linecorp/armeria/common/StringMultimapGetters.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersBaseTest.java
  core/src/test/java/com/linecorp/armeria/common/QueryParamsBaseTest.java
Labels: new feature

#3583 Fix a leak in the duplicator
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageDuplicatorTest.java
Labels: defect
