Repository line/armeria, pull requests merged in 2022-06, with the labels that each got.

#4259 Correctly throw `WriteTimeoutException` for requests without content
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
Labels: defect

#4240 Reuse armeria's WebClient instance when using the integration for Spring webflux's WebClient
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpConnector.java
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpRequest.java
Labels: defect

#4247 Update Dropwizard from 2.0.29 to 2.1.0
  dependencies.yml
  dropwizard2/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaServerFactory.java
Labels: dependencies

#4274 Fix javadoc of ArmeriaSettings.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
Labels: documentation

#4278 Skip a validation the reverse-lookup result of `127.0.0.1` for Windows
  jetty9/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTlsReverseDnsLookupTest.java
Labels: cleanup

#4225 Add Koltlin nullable type support to `AnnotatedService`
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/KotlinUtil.java
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaKotlinUtil.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/NullableTypeSupportTest.kt
Labels: new feature

#4245 Forward proxy requests shouldn't resolve hostnames
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/proxy/ProxyType.java
  core/src/test/java/com/linecorp/armeria/client/proxy/HttpProxyServerHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/IntermediaryProxyServerHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxySuccessEvent.java
  core/src/test/java/com/linecorp/armeria/client/proxy/Socks4ProxyServerHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/Socks5ProxyServerHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/UnknownHostProxyTest.java
Labels: defect

#4266 Provide an option to compress a grpc response automatically
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientCompressionTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ArmeriaServerCallTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceAutoCompressTest.java
Labels: new feature

#4291 Add max-age ServerCacheControl.DISABLED/REVALIDATE
  core/src/main/java/com/linecorp/armeria/common/HttpHeaders.java
  core/src/main/java/com/linecorp/armeria/common/QueryParams.java
  core/src/main/java/com/linecorp/armeria/common/ServerCacheControl.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersTest.java
  core/src/test/java/com/linecorp/armeria/common/QueryParamsTest.java
  core/src/test/java/com/linecorp/armeria/common/ServerCacheControlTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/file/FileServiceAdditionalHeadersTest.java
  graphql/src/test/java/com/linecorp/armeria/internal/server/graphql/GraphqlDocServiceTest.java
Labels: defect

#4296 Add document for gPRC metrics with armeria-spring-boot
  site/src/pages/docs/advanced-metrics.mdx
Labels: documentation

#4090 Fluently add expected exceptions to Logging{Service,Client}
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogLevelMapper.java
  core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
Labels: new feature

#4280 Chain the AccessLogWriter if another one is previously set
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ShutdownSupport.java
  core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  dropwizard2/src/main/java/com/linecorp/armeria/dropwizard/ArmeriaServerFactory.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
Labels: improvement, deprecation

#4226 Provide a way to limit a string and a container length for Thrift services and clients
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/grpc/downstream/LargePayloadBenchmark.java
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/thrift/PooledResponseBufferBenchmark.java
  brave/src/test/java/com/linecorp/armeria/it/brave/BraveIntegrationTest.java
  examples/thrift/src/test/java/example/armeria/thrift/HelloServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcProtoVersionTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcHealthCheckServiceTest.java
  it/grpc/reactor/src/test/java/com/linecorp/armeria/grpc/reactor/HelloServiceTest.java
  it/thrift-fullcamel/src/test/java/server/thrift/CamelNameThriftServiceTest.java
  site/src/pages/docs/advanced-metrics.mdx
  site/src/pages/docs/client-thrift.mdx
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  thrift0.13/src/main/java/com/linecorp/armeria/client/thrift/ThriftClientBuilder.java
  thrift0.13/src/main/java/com/linecorp/armeria/client/thrift/ThriftClientOptions.java
  thrift0.13/src/main/java/com/linecorp/armeria/client/thrift/ThriftClients.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/ThriftJacksonSerializers.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/ThriftProtocolFactories.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/ThriftProtocolFactoryProvider.java
  thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/ThriftSerializationFormats.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientFactory.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/DefaultThriftProtocolFactoryProvider.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftProtocolUtil.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePlugin.java
  thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpServiceBuilder.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ClientRequestContextPushedOnCallbackTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/THttpClientBadSeqIdTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientBuilderTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientLengthLimitTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientRequestContextInitFailureTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/common/thrift/ThriftMessageTestUtil.java
  thrift0.13/src/test/java/com/linecorp/armeria/internal/client/thrift/THttpClientUnwrapTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/client/endpoint/StaticEndpointGroupIntegrationTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/metric/DropwizardMetricsIntegrationTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/metric/PrometheusMetricsIntegrationTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/TMultiplexedProtocolIntegrationTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThriftDynamicTimeoutTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpErrorResponseTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpHeaderTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThrottlingRpcServiceTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/THttpServiceBuilderTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceLengthLimitTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceLogNameTest.java
  thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftTreeStructureTest.java
Labels: new feature, breaking change, deprecation

#4298 Fix Reactive Streams 3.3 violation in `PublisherBasedStreamMessage`
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessageTck.java
Labels: defect

#4042 Add a unit test which checks upstream media types
  core/src/test/java/com/linecorp/armeria/common/MediaTypeTest.java
Labels: cleanup
