Repository line/armeria, pull requests merged in 2022-10, with the labels that each got.

#4410 Provide a way to fluently configure a client TLS key and certificates
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/common/TlsSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  it/server/src/test/java/com/linecorp/armeria/server/http/MutualTlsTest.java
  site/src/pages/docs/client-factory.mdx
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerMutualTlsTest.java
Labels: new feature

#4428 Support camelcase for HttpJsonTranscodingService Query Parameters
  grpc/src/main/java/com/linecorp/armeria/server/grpc/DefaultHttpJsonTranscodingOptions.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingOptions.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingOptionsBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingQueryParamMatchRule.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingOptionsBuilderTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/transcoding.proto
Labels: defect, new feature

#4449 Return cached aggregated message for following withPooledObjects call
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/common/AggregationOptions.java
  core/src/main/java/com/linecorp/armeria/common/AggregationOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultAggregationOptions.java
  core/src/main/java/com/linecorp/armeria/common/HttpData.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/AggregationSupport.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/unsafe/PooledObjects.java
  core/src/test/java/com/linecorp/armeria/common/AggregationOptionsTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultHttpResponseTest.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
  grpc-protocol/src/main/java/com/linecorp/armeria/client/grpc/protocol/UnaryGrpcClient.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnaryServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceItTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceSupportHttpJsonTranscodingTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java
  thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
  thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
Labels: improvement, deprecation

#4435 Provide a way to handle GraphQL errors
  graphql/src/main/java/com/linecorp/armeria/server/graphql/DefaultGraphqlErrorHandler.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/DefaultGraphqlService.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlErrorHandler.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlService.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilder.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlErrorHandlerTest.java
Labels: new feature

#4460 Remove an invalid `content-length` in a gRPC streaming response.
  grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractServerCall.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/InvalidResponseLengthTest.java
Labels: defect

#4461 Add the release note for 1.20.0
  site/src/pages/release-notes/1.20.0.mdx
Labels: documentation

#4457 Update dependencies
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupLongPollingTest.java
  dependencies.toml
Labels: dependencies

#4474 Respond with application/json for httpjson transcoding endpoints
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
Labels: defect

#4475 Add release note for 1.20.1
  site/src/pages/release-notes/1.20.1.mdx
Labels: documentation

#4476 Provide a way to conveniently give star Armeria from the site
  site/package-lock.json
  site/package.json
  site/src/layouts/base.tsx
  site/src/layouts/star-begging.module.less
  site/src/layouts/star-begging.tsx
Labels: miscellaneous

#4483 Remove use of deprecated method RequestContextWrapper$delegate
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextWrapperTest.java
Labels: cleanup

#4494 Do not set request cause if request is aborted after response is complete
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClient.java
  core/src/main/java/com/linecorp/armeria/common/ResponseCompleteException.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/EmptyFixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseDecoderTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageCollectingTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/HttpRequestNotSubscribedTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
Labels: defect
