Repository line/armeria, pull requests merged in 2022-08, with the labels that each got.

#4372 Fix a bug where request duration is incorrectly recoded.
  core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
  core/src/test/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerRequestDurationTest.java
  core/src/test/java/com/linecorp/armeria/server/StreamingDecodedHttpRequestTest.java
Labels: defect

#4363 Remove a false postive warning for unknown `MethodType` in `ArmeriaChannel`
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
Labels: defect

#4378 Correctly handle cors preflight requests for paths with query params
  core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
Labels: defect

#4379 Add release notes for 1.17.2
  site/src/pages/release-notes/1.17.2.mdx
Labels: documentation

#4373 Fix file serving from OSGI bundle classloader
  core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileTest.java
Labels: defect

#4380 Use ClosedSessionException and ClosedStreamException correctly
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/stream/ClosedStreamException.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
Labels: defect

#4231 Unframed grpc service support richer error model
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlers.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ErrorDetailsMarshallerTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcStatusDetailsBinHeaderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlerTest.java
Labels: new feature

#4308 Introduce a way to unwrap `RequestContext`s
  brave/src/main/java/com/linecorp/armeria/client/brave/BraveClient.java
  brave/src/main/java/com/linecorp/armeria/server/brave/BraveService.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/UserClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientRequestContextExtension.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientThreadLocalState.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextExtension.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextInitFailureTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultConcurrentAttributesTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextWrapperTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/server/DefaultServiceRequestContextTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
Labels: improvement, breaking change

#4376 Upgrade dependencies
  core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtilTest.java
  dependencies.toml
  gradle/scripts/lib/scala.gradle
  gradle/wrapper/gradle-wrapper.properties
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java
  it/spring/boot2-tomcat8/build.gradle
  licenses/web-licenses.txt
  scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseAnnotatedServiceTest.scala
  spring/boot1-autoconfigure/build.gradle
  spring/boot2-autoconfigure/build.gradle
  tomcat8/build.gradle
Labels: dependencies

#4316 Provide a way to decorate a gRPC service using a builder method
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HandlerRegistry.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/HandlerRegistryTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
  site/src/pages/docs/server-grpc.mdx
Labels: new feature

#4383 Don't limit a max selection timeout to a response timeout in `EndpointSelector`
  core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/SelectionTimeoutTest.java
Labels: defect

#4375 Add release notes for 1.18.0
  site/release-note.ts
  site/src/pages/community/developer-guide.mdx
  site/src/pages/release-notes/1.17.2.mdx
  site/src/pages/release-notes/1.18.0.mdx
Labels: documentation

#4397 Fix the wrong Guava `failureaccess` version
  dependencies.toml
Labels: cleanup

#4386 Fix not to set chunked encoding header when 304 response is sent
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/client/Http1HeaderNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoderTest.java
Labels: defect
