Repository line/armeria, pull requests merged in 2022-04, with the labels that each got.

#4187 Enforce UTF-8 when running CI
  .github/workflows/actions_build.yml
  .github/workflows/public-suffixes.yml
  .github/workflows/publish-release.yml
Labels: miscellaneous

#4190 Remove unnecessary comment
  dependencies.yml
Labels: cleanup

#4179 Fix parsing error for BodyPart when an empty file
  core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java
  core/src/test/java/com/linecorp/armeria/common/multipart/MimeParserTest.java
  core/src/test/java/com/linecorp/armeria/common/multipart/MultipartTest.java
Labels: defect

#4176 Add Gradle(Kotlin) tab to RequiredDependencies component
  site/src/components/required-dependencies.tsx
  site/src/pages/docs/setup.mdx
Labels: documentation

#4173 Provide a way to add multiple QueryParams with a single key when using WebClient.prepare()
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestSetters.java
  core/src/test/java/com/linecorp/armeria/common/HttpRequestBuilderTest.java
Labels: defect

#4191 Add metrics for TLS handshakes / Reduce TLS certificate expiry metrics cardinality
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/CertificateUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/test/java/com/linecorp/armeria/server/ServerTlsCertificateMetricsTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTlsHandshakeMetricsTest.java
Labels: defect, new feature, breaking change

#4183 Add request start time to CoyoteRequest
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
  tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/TomcatServiceAccessLogTest.java
Labels: defect

#4196 Fix a bug where a DNS resolution is failed with a search domain starting with a dot
  core/src/main/java/com/linecorp/armeria/internal/client/dns/SearchDomainDnsResolver.java
  core/src/test/java/com/linecorp/armeria/internal/client/dns/SearchDomainDnsResolverTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/dns/SearchDomainTest.java
Labels: defect

#4200 Warn the initial failure of health checks for `HealthCheckedEndpointGroup`
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupInitialFailureTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
Labels: defect

#4171 Include a stacktrace in a response for unframed gRPC service when verboseResponse is enabled
  examples/grpc/src/test/java/example/armeria/grpc/HelloServiceTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcMetricsIntegrationTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlerTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
Labels: defect

#4174 Support for response_body option of gRPC-JSON transcoding
  grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
  grpc/src/test/proto/com/linecorp/armeria/grpc/testing/transcoding.proto
Labels: new feature

#4207 Add article of Hello Armeria, Bye Spring
  site/src/pages/community/articles.mdx
Labels: documentation

#4206 Fix eureka may stop schedule the fetching registry
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
  eureka/src/test/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupFailoverTest.java
Labels: defect

#4208 Add 'Introducing Armeria (or Three Principles of a Good Framework)' to the article list
  site/src/pages/community/articles.mdx
Labels: documentation

#4180 Fix a bug where a `HeaderListSizeException` is not propagated to a client
  core/src/main/java/com/linecorp/armeria/client/ClientHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/client/Http2HeadersLimitTest.java
  junit4/src/main/java/com/linecorp/armeria/testing/junit4/server/ServerRule.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit5/server/ServerExtension.java
Labels: defect, new feature

#4185 Add no-op subscribe
  core/src/main/java/com/linecorp/armeria/common/stream/NoopSubscriber.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageTest.java
Labels: new feature

#4060 Support comma-delimited multi `@Param` or `@Header`
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Delimiter.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: new feature

#4041 Make `GrpcService` handle the `@Decorator` annotations in a gRPC stub
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedObjectFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/DecoratorAnnotationUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/DecoratorAnnotationUtilTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/InternalReflectionUtils.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceSupportHttpJsonTranscodingTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcDecoratingServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
  grpc/src/test/proto/com/linecorp/armeria/server/grpc/InternalReflectionUtilsTest.java
Labels: new feature

#4214 Add 'Building an Authentication Microservice at LINE' to the community article list
  site/src/pages/community/articles.mdx
Labels: documentation

#4215 Make `RoutingResult.path()` correctly return the mapped path
  core/src/main/java/com/linecorp/armeria/server/AbstractPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/ExactPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/GlobPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/ParameterizedPathMapping.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMappingWithPrefix.java
  core/src/main/java/com/linecorp/armeria/server/RouteBuilder.java
  core/src/test/java/com/linecorp/armeria/server/AbstractPathMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/MappedPathTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcDecoratingServiceTest.java
Labels: defect

#4209 Update dependencies
  build.gradle
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  dependencies.yml
  docs-client/package-lock.json
  docs-client/package.json
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  it/spring/boot2-tomcat8/build.gradle
  site/package-lock.json
  site/package.json
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaMeterBindersConfigurationTest.java
  tomcat8/build.gradle
Labels: dependencies

#4212 Make `EurekaEndpointGroupFailoverTest` flaky
  eureka/src/test/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupFailoverTest.java
Labels: cleanup

#4218 Add the release note for 1.16.0
  site/src/pages/release-notes/1.16.0.mdx
Labels: documentation

#4219 Fix a bug where `WeightedRandomDistributionEndpointSelector` gets stuck in an infinite loop
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRandomDistributionEndpointSelector.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightedRandomDistributionEndpointSelectorTest.java
Labels: defect

#4204 generate metadata from throwable
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/GrpcHeaderNames.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcStatusDetailsBinHeaderTest.java
Labels: defect
