Repository line/armeria, pull requests merged in 2022-09, with the labels that each got.

#4405 Reject DATA Frames for invalid path requests
  core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
  core/src/test/java12/com/linecorp/armeria/server/InvalidPathWithDataTest.java
Labels: defect

#4406 Introduce a `BuiltInProperty` representing the request/response failure cause
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  logback/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Labels: new feature

#4394 Automatically publish the Armeria site using GitHub Actions
  .github/workflows/publish-site.yml
  .post-release-msg
Labels: miscellaneous

#4408 Fix that reactive health endpoint is not handled correctly
  spring/boot2-actuator-autoconfigure/build.gradle
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ReactiveHealthEndpointWebExtensionUtil.java
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
  spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationServiceUtil.java
  spring/boot2-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaSpringActuatorReactiveIndicatorTest.java
  spring/boot2-webflux-autoconfigure/src/test/resources/config/application-test_actuator.yml
Labels: defect

#4398 Fix `AnnotatedService` behavior with `void` return types
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/ClassUtil.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ByteArrayResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/HttpFileResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/JacksonResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ServerSentEventResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/server/annotation/StringResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/ClassUtilTest.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunction.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
  rxjava2/src/main/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunction.java
  rxjava3/src/main/java/com/linecorp/armeria/server/rxjava3/ObservableResponseConverterFunction.java
  scala/scala_2.13/src/test/scala/com/linecorp/armeria/server/ClassUtilTest.scala
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
  scalapb/scalapb_2.13/src/main/scala_2/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
  scalapb/scalapb_3/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunction.scala
Labels: defect

#4409 Fix the test failure of `SelectionTimeoutTest.select_timeout()`
  core/src/test/java/com/linecorp/armeria/client/endpoint/SelectionTimeoutTest.java
Labels: cleanup

#4336 Add delegating response converter function provider
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AggregatedResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/ResponseConverterFunctionUtil.java
  core/src/main/java/com/linecorp/armeria/server/annotation/DelegatingResponseConverterFunctionProvider.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunctionProvider.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/ResponseConverterFunctionUtilTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/TestDelegatingSpiConverterProvider.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/TestSpiConverterProvider.java
  core/src/test/resources/META-INF/services/com.linecorp.armeria.server.annotation.DelegatingResponseConverterFunctionProvider
  core/src/test/resources/META-INF/services/com.linecorp.armeria.server.annotation.ResponseConverterFunctionProvider
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/FlowResponseConverterFunctionProvider.kt
  kotlin/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.DelegatingResponseConverterFunctionProvider
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt
  kotlin/src/test/resources/META-INF/services/com.linecorp.armeria.server.annotation.DelegatingResponseConverterFunctionProvider
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
  protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufResponseAnnotatedServiceJsonArrayTest.java
  protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufResponseAnnotatedServiceTest.java
  protobuf/src/test/proto/messages.proto
  rxjava2/src/main/java/com/linecorp/armeria/internal/server/rxjava2/ObservableResponseConverterFunctionProvider.java
  rxjava2/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.DelegatingResponseConverterFunctionProvider
  rxjava2/src/test/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunctionProviderTest.java
  rxjava3/src/main/java/com/linecorp/armeria/internal/server/rxjava3/ObservableResponseConverterFunctionProvider.java
  rxjava3/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.DelegatingResponseConverterFunctionProvider
  rxjava3/src/test/java/com/linecorp/armeria/server/rxjava3/ObservableResponseConverterFunctionProviderTest.java
  scalapb/scalapb_2.13/src/main/resources/META-INF/services/com.linecorp.armeria.server.annotation.DelegatingResponseConverterFunctionProvider
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunctionProvider.scala
Labels: defect

#4364 Add support for alternative protobuf content types
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceResponseMediaTypeTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
Labels: defect

#4232 Add TraceAbleRequestContextStorage for ease of detect context leaks
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/internal/common/LeakTracingRequestContextStorageBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/ThreadLocalRequestContextStorage.java
  core/src/main/java/com/linecorp/armeria/common/util/Samplers.java
  core/src/main/java/com/linecorp/armeria/common/util/Unwrappable.java
  core/src/main/java/com/linecorp/armeria/internal/common/LeakTracingRequestContextStorage.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
  core/src/test/java/com/linecorp/armeria/common/util/SamplerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java
  it/trace-context-leak/build.gradle
  it/trace-context-leak/src/test/java/com/linecorp/armeria/internal/common/EnableLeakDetectionFlagsProvider.java
  it/trace-context-leak/src/test/java/com/linecorp/armeria/internal/common/TraceRequestContextLeakTest.java
  it/trace-context-leak/src/test/resources/META-INF/services/com.linecorp.armeria.common.FlagsProvider
  settings.gradle
Labels: new feature

#4413 Fix IndexOutOfBoundsException in build.gradle
  build.gradle
Labels: cleanup

#4415 Rename `newResponseConverterFunction` to `createResponseConverterFunction` in `ResponseConverterFunctionProvider`
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/ResponseConverterFunctionUtil.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunctionProvider.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/TestSpiConverterProvider.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
Labels: cleanup

#3987 Add the gRPC tutorial
  site/src/images/tutorial_blogservice_grpc_docservice_start.png
  site/src/images/tutorial_blogservice_grpc_reqex.png
  site/src/images/tutorial_blogservice_grpc_return.png
  site/src/pages/tutorials/grpc/blog/add-docservice.mdx
  site/src/pages/tutorials/grpc/blog/define-service.mdx
  site/src/pages/tutorials/grpc/blog/implement-create.mdx
  site/src/pages/tutorials/grpc/blog/implement-delete.mdx
  site/src/pages/tutorials/grpc/blog/implement-read.mdx
  site/src/pages/tutorials/grpc/blog/implement-update.mdx
  site/src/pages/tutorials/grpc/blog/index.mdx
  site/src/pages/tutorials/grpc/blog/run-service.mdx
  site/src/pages/tutorials/toc.json
Labels: documentation

#4199 Support file upload for GraphQL
  core/src/main/java/com/linecorp/armeria/internal/server/FileAggregatedMultipart.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  graphql-protocol/src/main/java/com/linecorp/armeria/internal/server/graphql/protocol/GraphqlUtil.java
  graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlService.java
  graphql-protocol/src/main/java/com/linecorp/armeria/server/graphql/protocol/MultipartVariableMapper.java
  graphql-protocol/src/test/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlServiceTest.java
  graphql/src/main/java/com/linecorp/armeria/common/graphql/scalar/MoreScalars.java
  graphql/src/main/java/com/linecorp/armeria/common/graphql/scalar/MultipartFileScalar.java
  graphql/src/main/java/com/linecorp/armeria/common/graphql/scalar/package-info.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceMultipartTest.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceTest.java
  graphql/src/test/resources/multipart.graphqls
  it/graphql-multipart/build.gradle
  it/graphql-multipart/src/test/java/com/linecorp/armeria/graphql/GraphqlTest.java
  it/graphql-multipart/src/test/resources/test.graphqls
  settings.gradle
Labels: new feature

#4416 Add Armeria Youtube videos
  site/src/pages/community/articles.mdx
Labels: documentation

#4366 Cache an aggregated result of a `StreamMessage` for non-pooled objects
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpMessage.java
  core/src/main/java/com/linecorp/armeria/common/AggregationOptions.java
  core/src/main/java/com/linecorp/armeria/common/AggregationOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultAggregationOptions.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpRequestDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpResponseDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/DeferredHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/FilteredHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/FilteredHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/FixedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/FixedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HeaderOverridingHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/StreamMessageBasedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/StreamMessageBasedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageAndWriter.java
  core/src/main/java/com/linecorp/armeria/common/stream/AggregationSupport.java
  core/src/main/java/com/linecorp/armeria/common/stream/CancellableStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/PublisherBasedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWrapper.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbortedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractSplitHttpMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultHttpRequest.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultHttpResponse.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/AbortedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessage.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/client/Http1ConnectionReuseTest.java
  core/src/test/java/com/linecorp/armeria/common/AggregationOptionsTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java
Labels: new feature

#4395 Retry when Spring tests fails to start a `Server` with a random port obtained in advance
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationPriorityTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortHttpsTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/RetryableArmeriaServerGracefulShutdownLifecycle.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/RetryableArmeriaServerGracefulShutdownLifecycleTest.java
Labels: cleanup

#4414 Update dependencies
  build.gradle
  dependencies.toml
  gradle/scripts/lib/common-dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
  it/spring/boot2-tomcat8/build.gradle
  site/build.gradle
Labels: dependencies

#4356 Show more stack trace of CompositeException
  core/src/main/java/com/linecorp/armeria/common/util/CompositeException.java
  core/src/test/java/com/linecorp/armeria/common/util/CompositeExceptionTest.java
Labels: improvement

#4422 Add EndpointGroup info to TimeoutException for DynamicEndpointGroup.whenReady() future
  consul/src/main/java/com/linecorp/armeria/client/consul/ConsulEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/PropertiesEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupInitialFailureTest.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
  thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ClientRequestContextPushedOnCallbackTest.java
Labels: cleanup

#4400 Allow customizing auto refresh behaviors for `AddressResolver`
  core/src/main/java/com/linecorp/armeria/client/DefaultDnsCache.java
  core/src/main/java/com/linecorp/armeria/client/DnsCacheBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DnsCacheListener.java
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/internal/client/dns/DnsUtil.java
  core/src/test/java/com/linecorp/armeria/client/DefaultDnsCacheTest.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
Labels: new feature, deprecation

#4419 Add release notes for 1.19.0
  site/src/pages/release-notes/1.19.0.mdx
Labels: documentation

#4434 Fix ScalaPbJsonMarshaller class name in doc
  site/src/pages/docs/advanced-scalapb.mdx
Labels: documentation

#4429 `Protobuf` converter providers don't attempt to illegally cast nested parameterized types
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionProvider.java
  protobuf/src/main/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionProvider.java
  protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufRequestConverterFunctionTest.java
  protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufResponseConverterFunctionTest.java
  scalapb/scalapb_2.13/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbConverterUtil.scala
  scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunctionTest.scala
  scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/ScalaPbResponseConverterFunctionTest.scala
Labels: defect

#4431 Revisit: Retry when Spring tests fails to start a Server with a random port obtained in advance
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerGracefulShutdownLifecycle.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaServerSmartLifecycle.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationPriorityTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/LocalArmeriaPortHttpsTest.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/RetryableArmeriaServerGracefulShutdownLifecycle.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/RetryableArmeriaServerGracefulShutdownLifecycleTest.java
Labels: cleanup

#4448 Fix a bug where `WeightRampingUpStrategy` raises a NPE when a `DynamicEndpointGroup` is not initialized
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategyTest.java
Labels: defect

#4430 Fix a bug where a dynamically proxied class name is exposed in `DocService`
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/ClassUtil.java
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/CgLibServiceNameTest.java
Labels: defect

#4451 Fix to return the proper media type in `GraphqlService`
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  graphql-protocol/src/main/java/com/linecorp/armeria/internal/server/graphql/protocol/GraphqlUtil.java
  graphql-protocol/src/test/java/com/linecorp/armeria/internal/server/graphql/protocol/GraphqlUtilTest.java
  graphql-protocol/src/test/java/com/linecorp/armeria/server/graphql/protocol/AbstractGraphqlServiceTest.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/DefaultGraphqlService.java
  sangria/sangria_2.13/src/main/scala/com/linecorp/armeria/server/sangria/SangriaGraphqlService.scala
Labels: new feature

#4402 Add `StreamMessage.fromOutputStream()`
  core/src/main/java/com/linecorp/armeria/common/stream/ByteStreamMessageOutputStream.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/ByteStreamMessageOutputStreamTest.java
Labels: new feature

#4425 Add `enable-auto-injection` prop in `spring-configuration-metadata.json`
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot2-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
Labels: defect

#4432 Fix Multipart not to raise an exception when closing boundary only
  core/src/main/java/com/linecorp/armeria/common/multipart/DefaultMultipart.java
  core/src/main/java/com/linecorp/armeria/common/multipart/MimeParser.java
  core/src/main/java/com/linecorp/armeria/common/multipart/Multipart.java
  core/src/main/java/com/linecorp/armeria/common/multipart/MultipartDecoder.java
  core/src/test/java/com/linecorp/armeria/common/multipart/MimeParserTest.java
  core/src/test/java/com/linecorp/armeria/common/multipart/MultipartTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceMultipartTest.java
Labels: defect

#4436 Protobuf docservice handles structs with empty children correctly
  core/src/main/java/com/linecorp/armeria/server/docs/FieldInfoBuilder.java
  protobuf/src/test/java/com/linecorp/armeria/server/protobuf/ProtobufNamedTypeInfoProviderTest.java
  protobuf/src/test/proto/messages.proto
  protobuf/src/test/resources/com/linecorp/armeria/server/protobuf/ProtobufNamedTypeInfoProviderTest_specification.json5
Labels: defect

#4441 Add AggregatedHttpRequest.toHttpRequest(headers)
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestUtil.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpRequestTest.java
Labels: new feature

#4456 Add `jackson-modules-java8` dependency to the core module
  benchmarks/jmh/build.gradle
  core/build.gradle
  core/src/test/java/com/linecorp/armeria/internal/common/JacksonUtilTest.java
  dependencies.toml
  gradle/scripts/version-catalog.gradle
Labels: dependencies
