Repository line/armeria, pull requests merged in 2022-05, with the labels that each got.

#3980 Add attributes to Endpoint
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultAttributeMap.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultAttributeMapTest.java
Labels: new feature

#4221 Fix a bug where duplicate healthy endpoints are set to `HealthCheckedEndpointGroup`
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
Labels: defect

#4242 Fix failing `DefaultMediaTypeResolverTest` tests
  core/src/test/java/com/linecorp/armeria/server/file/DefaultMediaTypeResolverTest.java
Labels: cleanup

#4249 Move a misplaced test file
  grpc/src/test/java/com/linecorp/armeria/server/grpc/InternalReflectionUtilsTest.java
Labels: cleanup

#4272 Use temurin instead of adopt
  .github/workflows/actions_build.yml
  .github/workflows/public-suffixes.yml
  .github/workflows/publish-release.yml
Labels: cleanup
