Repository line/armeria, pull requests merged in 2023-05, with the labels that each got.

#4856 Add newly-added method from logback 1.3 to support compatibility
  logback/src/main/java/com/linecorp/armeria/common/logback/LoggingEventWrapper.java
Labels: defect

#4823 Add current time to the invalid SAML request exception
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
Labels: cleanup

#4859 Fix `NullPointerException` in `FuseableStreamMessage`
  core/src/main/java/com/linecorp/armeria/common/stream/FuseableStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/FuseableStreamMessageTest.java
Labels: defect

#4854 Upgrade Gradle to 8.1.1
  .github/workflows/actions_build.yml
  benchmarks/jmh/build.gradle
  build.gradle
  core/build.gradle
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessageVerification.java
  gradle/scripts/.gitrepo
  gradle/scripts/lib/common-dependencies.gradle
  gradle/scripts/lib/common-git.gradle
  gradle/scripts/lib/java-alpn.gradle
  gradle/scripts/lib/java-coverage.gradle
  gradle/scripts/lib/java-rpc-proto.gradle
  gradle/scripts/lib/java-rpc-thrift.gradle
  gradle/scripts/lib/java-shade.gradle
  gradle/scripts/lib/java.gradle
  gradle/scripts/lib/kotlin.gradle
  gradle/scripts/lib/scala.gradle
  gradle/wrapper/gradle-wrapper.properties
  it/micrometer1.3/build.gradle
  it/thrift0.9.1/build.gradle
  junit4/build.gradle
  kotlin/build.gradle.kts
  settings.gradle
  spring/boot2-actuator-autoconfigure/build.gradle
  spring/boot2-autoconfigure/build.gradle
  spring/boot2-webflux-autoconfigure/build.gradle
  spring/boot3-actuator-autoconfigure/build.gradle
  spring/boot3-autoconfigure/build.gradle
  spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationTest.java
Labels: dependencies

#4884 Fix incorrectly overridden project groups by `JvmTestSuite`.
  core/build.gradle
  dependencies.toml
  examples/annotated-http-service-kotlin/src/main/kotlin/example/armeria/server/annotated/kotlin/MarkdownDescriptionService.kt
  examples/context-propagation/kotlin/src/main/kotlin/example/armeria/contextpropagation/kotlin/MainService.kt
  examples/spring-boot-minimal-kotlin/src/main/kotlin/example/springframework/boot/minimal/kotlin/ValidationExceptionHandler.kt
  kotlin/build.gradle.kts
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/DataClassDocServiceTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/FlowAnnotatedServiceTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/NullableTypeSupportTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt
Labels: miscellaneous

#4822 Introduce GrpcCallOptions
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcCallOptions.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: new feature

#4880 Enhance `boot3-actuator-autoconfigure`
  examples/spring-boot-minimal/src/main/resources/config/application.yml
  spring/boot3-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
  spring/boot3-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/MappingWebEndpointPathMapper.java
  spring/boot3-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ReactiveHealthEndpointWebExtensionUtil.java
  spring/boot3-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/SimpleHttpCodeStatusMapper.java
  spring/boot3-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java
  spring/boot3-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationServiceUtil.java
  spring/boot3-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationSecureTest.java
  spring/boot3-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationTest.java
  spring/boot3-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/SimpleHttpCodeStatusMapperTest.java
  spring/boot3-actuator-autoconfigure/src/test/resources/application-autoConfTest.yml
  spring/boot3-actuator-autoconfigure/src/test/resources/application-autoConfTestDisableDiscovery.yml
  spring/boot3-actuator-autoconfigure/src/test/resources/application-autoConfTestHealthStatus.yml
  spring/boot3-actuator-autoconfigure/src/test/resources/application-secureTest.yml
Labels: improvement

#4858 Fix `ThriftDocServicePlugin` maybe failed when thrift proto compile with fullcamel option
  it/thrift-fullcamel/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePluginTest.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePlugin.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/ThriftServiceEntry.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePluginTest.java
  thrift/thrift0.17/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePluginTest.java
Labels: defect

#4893 Backport #4494, #4508 and #4524 to 1.16
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/logging/ContentPreviewingClient.java
  core/src/main/java/com/linecorp/armeria/common/ResponseCompleteException.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/stream/CancelledSubscriptionException.java
  core/src/main/java/com/linecorp/armeria/common/util/UnmodifiableFuture.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/EmptyFixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseDecoderTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageCollectingTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageVerification.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/HttpRequestNotSubscribedTest.java
  core/src/test/java/com/linecorp/armeria/server/Http1KeepAliveTest.java
  core/src/test/java/com/linecorp/armeria/server/UnfinishedRequestTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingFailureTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
Labels: defect

#4897 Typo correction: add missing word
  site/src/pages/docs/client-retrofit.mdx
Labels: miscellaneous

#4851 Respect CallOptions.executor in the gRPC client
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
Labels: defect

#4860 Add documentation for timeout at the server side
  site/src/pages/docs/server-timeouts.mdx
  site/src/pages/docs/toc.json
Labels: documentation

#4834 Fix a bug when `ConcurrencyLimitingClient` is added after `RetryingClient`
  core/src/main/java/com/linecorp/armeria/client/limit/AbstractConcurrencyLimitingClient.java
  core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitWithRetryTest.java
  core/src/test/java/com/linecorp/armeria/client/limit/ConcurrencyLimitingClientTest.java
Labels: defect

#4877 Provide a way to customize GraphQL ExecutionId
  graphql/src/main/java/com/linecorp/armeria/server/graphql/ExecutionIdGenerator.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilder.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/ExecutionIdGeneratorTest.java
Labels: new feature

#4832 Propagate exceptions thrown from `RequestConverter` to `ExceptionHandler`
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactory.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceExceptionHandlerTest.java
Labels: defect

#4801 Add `KeyStoreUtil` to support `.jks` and `.p12` key store formats
  core/src/main/java/com/linecorp/armeria/internal/common/util/KeyStoreUtil.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/KeyStoreUtilTest.java
  core/src/test/resources/com/linecorp/armeria/internal/common/util/keystore-different-password.jks
  core/src/test/resources/com/linecorp/armeria/internal/common/util/keystore-two-keys.p12
  core/src/test/resources/com/linecorp/armeria/internal/common/util/keystore.jks
  core/src/test/resources/com/linecorp/armeria/internal/common/util/keystore.p12
  core/src/test/resources/com/linecorp/armeria/internal/common/util/not-keystore-empty.p12
  core/src/test/resources/com/linecorp/armeria/internal/common/util/not-keystore.p12
Labels: new feature

#4820 Update protobuf-java to resolve CVEs
  dependencies.toml
Labels: dependencies

#4707 Add RetryingClient metric
  core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
Labels: improvement, sprint

#4840 Fix to use a relative path for schemas.json in DocServcie client
  docs-client/src/containers/App/index.tsx
Labels: defect

#4267 Provide a way to customize a log format produced by Logging{Service,Client}
  core/src/main/java/com/linecorp/armeria/client/logging/AbstractLoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/AbstractLogFormatterBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/JsonLogFormatter.java
  core/src/main/java/com/linecorp/armeria/common/logging/JsonLogFormatterBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/LogFormatter.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogProperty.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestOnlyLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/TextLogFormatter.java
  core/src/main/java/com/linecorp/armeria/common/logging/TextLogFormatterBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/common/logging/LoggingUtils.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/JsonLogFormatterTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/TextLogFormatterTest.java
  core/src/test/java/com/linecorp/armeria/server/TransientHttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: new feature
