Repository line/armeria, pull requests merged in 2023-10, with the labels that each got.

#5148 Update "Setting up a project" docs
  site/src/pages/docs/setup.mdx
Labels: cleanup

#5128 Use `<Tabs>` for maven/gradle configuration in DocService docs
  site/src/pages/docs/server-docservice.mdx
Labels: documentation

#5143 Refactor bootstrap retrieval in `HttpChannelPool`
  core/src/main/java/com/linecorp/armeria/client/Bootstraps.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
Labels: cleanup

#5108 Migrate more JUnit 4 tests to JUnit 5
  core/src/test/java/com/linecorp/armeria/client/Http2GoAwayTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientPipeliningTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceAnnotationAliasTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceDecorationTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceResponseConverterTest.java
  core/src/test/java/com/linecorp/armeria/server/StreamingDecodedHttpRequestTest.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
  core/src/test/java/com/linecorp/armeria/server/file/FileServiceAdditionalHeadersTest.java
  core/src/test/java/com/linecorp/armeria/server/streaming/JsonTextSequencesTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcFlowControlTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcStatusCauseTest.java
  it/server/src/test/java/com/linecorp/armeria/server/grpc/interop/ArmeriaGrpcServerInteropTest.java
Labels: cleanup

#5173 Use the desired protocol to get a pending acquisition
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/test/java/com/linecorp/armeria/client/PendingAcquisitionTest.java
Labels: defect

#5179 Update jmh configuration for async profiler
  benchmarks/jmh/README.md
  benchmarks/jmh/build.gradle
  dependencies.toml
Labels: cleanup

#5235 Don't allocate a route with an empty prefix
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/test/java/com/linecorp/armeria/server/RouteTest.java
Labels: cleanup

#5037 Provide a way to add a context path to a subset of services
  core/src/main/java/com/linecorp/armeria/internal/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/AbstractAnnotatedServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/AbstractBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ContextPathAnnotatedServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ContextPathDecoratingBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ContextPathServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ContextPathServicesBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostDecoratingServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/server/AbstractBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/AbstractServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ContextPathTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
Labels: new feature

#5221 Fix a bug where `CookieClient` does not work with redirects
  core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/test/java/com/linecorp/armeria/client/retry/RedirectWithCookieClientTest.java
Labels: defect

#4802 Provide a way to set the root context path
  core/src/main/java/com/linecorp/armeria/internal/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/server/BaseContextPathTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteDecoratingServiceTest.java
Labels: new feature

#5196 Omit `dependencyManagement` module from direct dependency
  gradle/scripts/.gitrepo
  gradle/scripts/build-flags.gradle
  gradle/scripts/lib/common-dependencies-legacy.gradle
  gradle/scripts/lib/common-dependencies.gradle
  gradle/scripts/lib/java-publish.gradle
  gradle/scripts/lib/java-shade.gradle
  gradle/scripts/lib/java.gradle
  gradle/scripts/lib/kotlin.gradle
  gradle/scripts/version-catalog.gradle
Labels: cleanup

#5220 Introduce the `CancellationScheduler` interface
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultCancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/NoopCancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/test/java/com/linecorp/armeria/internal/client/DefaultClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/CancellationSchedulerTest.java
Labels: improvement

#5224 throw ISE when gRPC HTTP JSON transcoding is enabled but serialization format JSON is missing
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilderTest.java
Labels: defect

#5240 Fix failing public suffixes
  .github/workflows/public-suffixes.yml
Labels: cleanup

#5155 Add metrics for client certificates
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/common/CommonPools.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/metric/CertificateMetrics.java
  core/src/main/java/com/linecorp/armeria/common/metric/EventLoopMetrics.java
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeterBinders.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/CertificateUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/CertificateUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerSslContextUtil.java
  core/src/test/java/com/linecorp/armeria/client/ClientCertificateMetricsTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTlsCertificateMetricsTest.java
Labels: new feature

#5168 Provide a way to disable HTTP/2 for HTTP clients
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/NonWrappingRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/PreferHttp1Test.java
Labels: new feature

#5232 Limit max reset frames to mitigate HTTP/2 RST floods
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
  core/src/test/java/com/linecorp/armeria/server/MaxResetFramesTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  dependencies.toml
Labels: defect, dependencies

#5230 Fix that `WebSocketService` rejects headers that have multiple values
  core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java
  core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceTest.java
Labels: defect

#5249 Remove deprecated API usages
  core/src/main/java/com/linecorp/armeria/client/AbstractDnsResolverBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareBiConsumer.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareBiFunction.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareConsumer.java
  core/src/main/java/com/linecorp/armeria/common/ContextAwareFunction.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextDelayedInitTest.java
  core/src/test/java/com/linecorp/armeria/client/RedirectContextTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/ByteBufsInputStreamTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/RecoverableStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerHandlerTest.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaClientUtil.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilderTest.java
  it/jackson-provider/src/test/java/com/linecorp/armeria/common/CustomJacksonObjectMapperProvider.java
  jetty/jetty11/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceStartupTest.java
  jetty/jetty11/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/Jsr305StrictTest.kt
  logback/logback12/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
  oauth2/src/test/java/com/linecorp/armeria/client/auth/oauth2/OAuth2ClientCredentialsGrantTest.java
  oauth2/src/test/java/com/linecorp/armeria/client/auth/oauth2/OAuth2ResourceOwnerPasswordCredentialsGrantTest.java
  reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareMonoTest.java
  scala/scala_2.13/src/main/scala/com/linecorp/armeria/scala/CommonConversions.scala
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaWebClientTest.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientBuilderTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/observation/BraveIntegrationTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThriftHttpErrorResponseTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/thrift/ThrottlingRpcServiceTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp1Test.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftSerializationFormatsTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftServiceTest.java
  zookeeper3/src/test/java/com/linecorp/armeria/server/zookeeper/CuratorServiceDiscoveryCompatibilityTest.java
Labels: cleanup

#4827 Provide a way to determine circuit, and retry with response duration
  core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClient.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientRuleTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderTest.java
Labels: new feature

#5144 Disable request timeout if `grpc-timeout` is omitted while `useClientTimeoutHeader` is enabled.
  grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTimeoutTest.java
Labels: defect

#5048 fix debug page popping when URL params are set
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/index.tsx
Labels: defect

#4682 Add ArrayBasedEventLoopState(#4439)
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/client/EventLoopStateBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/AbstractEventLoopState.java
  core/src/main/java/com/linecorp/armeria/client/ArrayBasedEventLoopState.java
  core/src/main/java/com/linecorp/armeria/client/DefaultEventLoopScheduler.java
  core/src/main/java/com/linecorp/armeria/client/HeapBasedEventLoopState.java
  core/src/main/java/com/linecorp/armeria/client/OneEventLoopState.java
  core/src/test/java/com/linecorp/armeria/client/DefaultEventLoopSchedulerTest.java
  core/src/test/java/com/linecorp/armeria/client/MaxNumEventLoopsPerEndpointTest.java
Labels: improvement

#5255 Allow adding multiple `(Server|Service)ErrorHandler`s
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ErrorHandlerOrElseTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilder.java
Labels: cleanup

#5242 Fix a bug where responseCause is not propagated to `CircuitBreakerRule` from `RetryingClient`
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerWithRetryTest.java
Labels: defect

#5244 Update dependencies
  dependencies.toml
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  reactor3/src/test/java/com/linecorp/armeria/common/reactor3/ContextAwareFluxTest.java
  tomcat10/src/main/java/com/linecorp/armeria/internal/server/tomcat/Tomcat90ProtocolHandler.java
Labels: dependencies

#5107 Make RequestContextExtension.hook() public API
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextExtension.java
  core/src/main/java/com/linecorp/armeria/internal/common/RequestContextUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/AbstractAnnotatedServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ContextPathAnnotatedServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ContextPathServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostContextPathServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/client/WebClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/ContextPushHookTest.java
  core/src/test/java/com/linecorp/armeria/common/RequestContextWrapperTest.java
  core/src/test/java/com/linecorp/armeria/server/AbstractServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAndServiceConfigConsistencyTest.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/client/thrift/ThriftClientBuilder.java
Labels: new feature

#5260 Support context-path for Spring integration
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationSettingsUtil.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsBaseContextPathTest.java
  spring/boot3-autoconfigure/src/test/resources/config/application-baseContextPathTest.yml
Labels: new feature

#5174 Support for Snappy content compression
  core/src/main/java/com/linecorp/armeria/client/encoding/DecodingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/encoding/SnappyStreamDecoder.java
  core/src/main/java/com/linecorp/armeria/common/encoding/StreamDecoderFactories.java
  core/src/main/java/com/linecorp/armeria/common/encoding/StreamDecoderFactory.java
  core/src/main/java/com/linecorp/armeria/internal/common/encoding/SnappyFramedOutputStream.java
  core/src/main/java/com/linecorp/armeria/internal/common/encoding/StreamEncoderFactories.java
  core/src/main/java/com/linecorp/armeria/internal/common/encoding/StreamEncoderFactory.java
  core/src/main/java/com/linecorp/armeria/server/encoding/DecodingService.java
  core/src/main/java/com/linecorp/armeria/server/encoding/EncodingService.java
  core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncodedResponse.java
  core/src/main/java/com/linecorp/armeria/server/encoding/HttpEncoders.java
  core/src/main/java/com/linecorp/armeria/server/file/FileService.java
  core/src/test/java/com/linecorp/armeria/client/encoding/DecodingClientTest.java
  core/src/test/java/com/linecorp/armeria/server/encoding/DecoderLengthLimitTest.java
  core/src/test/java/com/linecorp/armeria/server/encoding/DecodingServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodedResponseTest.java
  core/src/test/java/com/linecorp/armeria/server/encoding/HttpEncodersTest.java
  core/src/test/java/com/linecorp/armeria/server/file/DefaultMediaTypeResolverTest.java
Labels: new feature

#5261 Fix missed overridden methods
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/DnsResolverGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/RestClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/websocket/WebSocketClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseBuilder.java
  it/builders/src/test/java/com/linecorp/armeria/OverriddenBuilderMethodsReturnTypeTest.java
Labels: defect

#5149 Resolve only platform dependencies when generating POM file
  gradle/scripts/.gitrepo
  gradle/scripts/README.md
  gradle/scripts/lib/java-publish.gradle
  gradle/scripts/lib/kotlin.gradle
  gradle/scripts/settings-flags.gradle
Labels: defect

#5198 Add `StreamMessage.endWith(finalizer)`
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/PublisherBasedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisher.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageEndWithTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisherTckTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/stream/SurroundingPublisherTest.java
Labels: new feature

#5256 Refine example explanation for RetryRule behavior
  site/src/pages/docs/client-retry.mdx
Labels: documentation

#4644 Preserve a user-defined content-length for HEAD request
  core/src/main/java/com/linecorp/armeria/common/AbstractHttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/DefaultHttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequestUtil.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/ResponseHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/WebSocketHttp1ResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/common/ContentLengthTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpResponseTest.java
  core/src/test/java/com/linecorp/armeria/common/StringMultimapDerivedApiConsistencyTest.java
  core/src/test/java12/com/linecorp/armeria/server/HeadRequestTest.java
Labels: defect

#5223 Start HTTP/2 requests when HTTP2-Settings is applied
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
Labels: defect

#5227 Fix byte buf leak when a `ContentTooLargeException` is raised
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultCancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/WebSocketServiceChannelHandler.java
  core/src/test/java/com/linecorp/armeria/server/ExceedingServiceMaxContentLengthTest.java
  core/src/test/java/com/linecorp/armeria/server/StreamingDecodedHttpRequestTest.java
  core/src/test/java12/com/linecorp/armeria/server/InvalidPathWithDataTest.java
  core/src/test/java12/com/linecorp/armeria/server/JavaHttpClientUpgradeTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcLargeRequestTest.java
Labels: defect

#5268 Publish `ProxyConnectionEvent` after `HAProxyMessage` is written
  core/src/main/java/com/linecorp/armeria/client/HAProxyHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
Labels: defect

#5154 Propagate pending exceptions when a session or a stream is closed
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/client/WebSocketHttp1ClientChannelHandler.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClosedStreamExceptionUtil.java
  core/src/main/java/com/linecorp/armeria/internal/client/PendingExceptionUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/client/PendingExceptionTest.java
Labels: defect

#5163 Fix a bug where a recursively added `EndpointGroup` listener is not invoked
  core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/RoundRobinStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/StickyEndpointSelectionStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
  core/src/main/java/com/linecorp/armeria/common/util/AbstractListenable.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextDelayedInitTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelectorTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/DynamicEndpointGroupTest.java
Labels: defect

#5252 Add the release note for 1.26.0
  dependencies.toml
  site/src/pages/release-notes/1.25.0.mdx
  site/src/pages/release-notes/1.26.0.mdx
Labels: documentation

#5272 Release a new version with GitHub Actions
  .github/workflows/gradle-enterprise-postjob.yml
  .github/workflows/tag-new-release.yml
Labels: miscellaneous

#5277 Disable RST_STREAM frame limitation for HTTP/2 clients
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
Labels: defect, breaking change

#5278 Add release notes for 1.26.1
  site/src/pages/release-notes/1.26.1.mdx
Labels: documentation

#5275 Fix not to send Armeria upgrade PR to Central Dogma when minor version up
  .github/actions/post-release.ts
Labels: cleanup
