Repository line/armeria, pull requests merged in 2023-03, with the labels that each got.

#4718 Remove `StreamMessageWriter` and replace it to `StreamWriter`
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractStreamMessageWriter.java
  core/src/main/java/com/linecorp/armeria/common/stream/ByteStreamMessageOutputStream.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessageWriter.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamWriter.java
  core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageTest.java
Labels: cleanup, breaking change

#4531 Allow sending `Connection: close` header
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/ClientHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSession.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/AbstractKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpHeadersUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/KeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/NoopKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/client/ClientOptionsTest.java
  core/src/test/java/com/linecorp/armeria/client/CountingConnectionPoolListener.java
  core/src/test/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientNoKeepAliveTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/KeepAliveHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/Http1ServerKeepAliveTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerNoKeepAliveTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerMaxConnectionAgeTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
Labels: defect, improvement

#4705 Handle overflow on `PathStreamMessage#range(offset, length)`
  core/src/main/java/com/linecorp/armeria/common/stream/PathStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/PathStreamMessageTest.java
Labels: defect

#4720 Upgrade to Apache HttpClient 5
  build.gradle
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/InitiateConnectionShutdownTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTest.java
  core/src/test/java/com/linecorp/armeria/server/SniServerTest.java
  core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
  dependencies.toml
  testing-internal/build.gradle
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/webapp/WebAppContainerTest.java
  thrift/thrift0.12/build.gradle
  thrift/thrift0.13/build.gradle
  thrift/thrift0.14/build.gradle
  thrift/thrift0.15/build.gradle
  thrift/thrift0.16/build.gradle
  thrift/thrift0.17/build.gradle
  thrift/thrift0.9/build.gradle
  tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/ManagedTomcatServiceTest.java
  tomcat9/src/test/java/com/linecorp/armeria/server/tomcat/UnmanagedTomcatServiceTest.java
Labels: dependencies

#4726 Allow serving an HTTP/1 request with absolute URI.
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/AbsoluteRequestUriTest.java
Labels: new feature

#4706 Add implicit request mapping to @Head when the service is mapped to @Get
  core/src/main/java/com/linecorp/armeria/server/FallbackService.java
  core/src/main/java/com/linecorp/armeria/server/RegexPathMappingWithPrefix.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceImplicitHeadTest.java
  core/src/test/java/com/linecorp/armeria/server/CachingRoutingContextTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingContextTest.java
Labels: improvement

#4715 Listens to the result of querying DnsRecords
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DefaultDnsQueryListener.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsQueryListener.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroupBuilder.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java
Labels: new feature

#4695 Fix a bug where a DNS resolution is timed out when IPv6 is enabled
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolverGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolver.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolverTest.java
Labels: defect

#4739 Update site/README.md to show a better way to install svgbob
  site/README.md
Labels: documentation

#4703 Add `StreamMessage.of(inputStream)`
  core/src/main/java/com/linecorp/armeria/common/stream/AbstractByteStreamMessageBuilder.java
  core/src/main/java/com/linecorp/armeria/common/stream/InputStreamStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/InputStreamStreamMessageBuilder.java
  core/src/main/java/com/linecorp/armeria/common/stream/PathStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/PathStreamMessageBuilder.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/InternalStreamMessageUtil.java
  core/src/test/java/com/linecorp/armeria/common/stream/InputStreamStreamMessageTckTest.java
  core/src/test/java/com/linecorp/armeria/common/stream/InputStreamStreamMessageTest.java
Labels: new feature

#4724 Add CoroutineServerInterceptor
  dependencies.toml
  grpc-kotlin/build.gradle.kts
  grpc-kotlin/src/main/kotlin/com/linecorp/armeria/server/grpc/kotlin/CoroutineServerInterceptor.kt
  grpc-kotlin/src/test/kotlin/com/linecorp/armeria/server/grpc/kotlin/CoroutineServerInterceptorTest.kt
  grpc-kotlin/src/test/proto/com/linecorp/armeria/grpc/testing/messages.proto
  grpc-kotlin/src/test/proto/com/linecorp/armeria/grpc/testing/test.proto
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/DeferredListener.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnaryServerCall.java
  settings.gradle
Labels: new feature

#4685 export open/closed connection metric for connection pool
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolMetrics.java
  core/src/main/java/com/linecorp/armeria/client/MetricCollectingConnectionPoolListener.java
  core/src/test/java/com/linecorp/armeria/client/ConnectionPoolCollectingMetricTest.java
Labels: new feature

#4589 Add an example for `thrift` tutorial
  examples/tutorials/thrift/build.gradle
  examples/tutorials/thrift/src/main/java/example/armeria/server/blog/thrift/BlogServiceExceptionHandler.java
  examples/tutorials/thrift/src/main/java/example/armeria/server/blog/thrift/BlogServiceImpl.java
  examples/tutorials/thrift/src/main/java/example/armeria/server/blog/thrift/Main.java
  examples/tutorials/thrift/src/main/thrift/blog.thrift
  examples/tutorials/thrift/src/test/java/example/armeria/server/blog/thrift/BlogServiceTest.java
  settings.gradle
Labels: documentation

#4765 Fix `#` character encoding in URIs
  core/src/main/java/com/linecorp/armeria/internal/common/PathAndQuery.java
  core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
Labels: defect

#4747 Fix javadocs for `WeightedRoundRobinSelector`
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
Labels: documentation

#4736 Return 400 Bad request when `absoluteUriTransformer` returns an empty…
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/server/AbsoluteRequestUriTest.java
Labels: cleanup

#4708 Provide a way to disconnect gracefully connection using `RequestContext`
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/AggregatedHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/Http1ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http1ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientKeepAliveHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/HttpRequestSubscriber.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/internal/client/DecodedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/client/HttpSession.java
  core/src/main/java/com/linecorp/armeria/internal/client/PooledChannel.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java
  core/src/test/java/com/linecorp/armeria/client/InitiateConnectionShutdownTest.java
Labels: new feature

#4748 Ensure `DnsResolver` is executed by `EventLoop`
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsServiceEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/dns/DnsTextEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolver.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsEndpointGroupBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolverTest.java
Labels: cleanup

#4758 Prevent self reference in addSuppressed
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
Labels: defect

#4768 Add ServiceRequestContextCaptor.isEmpty()
  junit5/src/main/java/com/linecorp/armeria/testing/server/ServiceRequestContextCaptor.java
Labels: new feature

#4770 Increase the JVM heap for Gradle to avoid OOME
  build.gradle
  gradle.properties
Labels: cleanup

#4771 Fix buffer leak with HEAD requests
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/server/HeadMethodLeakTest.java
Labels: defect

#4752 Allow configuring requestIdGenerator on per-service basis
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServerRequestIdTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilderTest.java
Labels: new feature

#4687 Add `ExceptionReportingServerErrorHandler` to log unhandled exceptions
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/ExceptionReportingServerErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingService.java
  core/src/test/java/com/linecorp/armeria/server/ExceptionReportingServerErrorHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRequestContextTest.java
Labels: new feature

#4688 Fix an intermittent deadlock when `DocService` is loaded for a Thrift service
  thrift/thrift0.12/build.gradle
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDescriptiveTypeInfoProvider.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePlugin.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftMetadataAccess.java
  thrift/thrift0.13/src/main/resources/com/linecorp/armeria/internal/common/thrift/thrift-options.properties
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftClassLoadingTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftMetadataAccessTest.java
  thrift/thrift0.15/build.gradle
  thrift/thrift0.15/src/main/resources/com/linecorp/armeria/internal/common/thrift/thrift-options.properties
  thrift/thrift0.16/build.gradle
  thrift/thrift0.16/src/main/resources/com/linecorp/armeria/internal/common/thrift/thrift-options.properties
  thrift/thrift0.17/build.gradle
  thrift/thrift0.17/src/main/resources/com/linecorp/armeria/internal/common/thrift/thrift-options.properties
Labels: defect

#4773 Fix flaky `HeadMethodLeakTest`
  core/src/main/java/com/linecorp/armeria/internal/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/test/java/com/linecorp/armeria/server/HeadMethodLeakTest.java
Labels: cleanup

#4697 Introduce internal headers for client side
  brave/src/main/java/com/linecorp/armeria/client/brave/ArmeriaHttpClientParser.java
  brave/src/main/java/com/linecorp/armeria/client/brave/ClientRequestContextAdapter.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientTest.java
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/cookie/CookieClient.java
  core/src/main/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/common/RequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/common/RequestHeadersBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientRequestContextExtension.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpHeadersUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/ClientRequestContextTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientAdditionalHeadersTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientAuthorityHeaderTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultRequestHeadersBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/DefaultClientRequestContextTest.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientAdditionalAuthorityTest.java
Labels: defect

#4778 Fix a bug where RetryConfigMapping is evaluated multiple times per req
  core/src/main/java/com/linecorp/armeria/client/retry/AbstractRetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingClient.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryingRpcClient.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryingClientTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: defect

#4750 Add barebones Netty event-loop metrics
  core/src/main/java/com/linecorp/armeria/common/CommonPools.java
  core/src/main/java/com/linecorp/armeria/common/metric/EventLoopMetrics.java
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeterBinders.java
  core/src/test/java/com/linecorp/armeria/common/metric/EventLoopMetricsTest.java
Labels: new feature

#4562 Replace synchronized under core/internal, core/server with ReentrantLock
  core/src/main/java/com/linecorp/armeria/internal/common/ReflectiveDependencyInjector.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/CaffeineMetricSupport.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/MinifiedBouncyCastleProvider.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedBeanFactoryRegistry.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckService.java
Labels: improvement

#4783 Update dependencies
  dependencies.toml
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlRequestIdManagerTest.java
Labels: dependencies

#4721 Server-side `RequestHeaders` uses the encoded path
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpHeaderUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/PathAndQueryTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpHeaderUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerRequestPathEncodingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRouteUtilTest.java
Labels: defect

#4563 Support address, base-path and `ssl.enabled` of ManagementServerProperties
  .github/workflows/actions_build.yml
  spring/boot3-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java
  spring/boot3-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationInternalServiceTest.java
  spring/boot3-actuator-autoconfigure/src/test/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfigurationSslTest.java
  spring/boot3-actuator-autoconfigure/src/test/resources/application-basePathSamePortTest.yml
  spring/boot3-actuator-autoconfigure/src/test/resources/application-basePathTest.yml
  spring/boot3-actuator-autoconfigure/src/test/resources/application-basePathWithoutPortTest.yml
  spring/boot3-actuator-autoconfigure/src/test/resources/application-managementLocalhostTest.yml
  spring/boot3-actuator-autoconfigure/src/test/resources/application-ssl.yml
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationNetUtil.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/InternalServices.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryAutoConfiguration.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java
Labels: new feature

#4516 Use monaco editor for Request Body in Query Editor
  docs-client/build.gradle
  docs-client/package-lock.json
  docs-client/package.json
  docs-client/src/containers/App/index.tsx
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/EndpointPath.tsx
  docs-client/src/containers/MethodPage/GraphqlRequestBody.tsx
  docs-client/src/containers/MethodPage/QueryEditor/app.css
  docs-client/src/containers/MethodPage/QueryEditor/index.css
  docs-client/src/containers/MethodPage/QueryEditor/index.tsx
  docs-client/src/containers/MethodPage/QueryEditor/lint.css
  docs-client/src/containers/MethodPage/RequestBody.tsx
  docs-client/src/containers/MethodPage/index.tsx
  docs-client/src/lib/specification.tsx
  docs-client/src/lib/transports/grpc-unframed.ts
  docs-client/src/lib/transports/thrift.ts
  docs-client/webpack.config.ts
  examples/graphql/src/main/java/example/armeria/server/graphql/Main.java
  examples/graphql/src/main/resources/graphql-playground.html
  licenses/web-licenses.txt
  site/build.gradle
  site/package-lock.json
Labels: new feature

#4716 Add ServiceErrorHandler
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolLoggingListener.java
  core/src/main/java/com/linecorp/armeria/common/util/TextFormatter.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/DefaultUnhandledExceptionsReporter.java
  core/src/main/java/com/linecorp/armeria/server/ExceptionReportingServiceErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServiceErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/UnhandledExceptionsReporter.java
  core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/common/util/TextFormatterTest.java
  core/src/test/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/CustomServerErrorHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ExceptionReportingServiceErrorHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerErrorHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceErrorHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
Labels: new feature
