Repository line/armeria, pull requests merged in 2023-12, with the labels that each got.

#5324 Try enabling PTS for non-CI builds
  build.gradle
Labels: miscellaneous

#5332 Newsletter vol. 6
  site/src/pages/news/20211029-newsletter-3.mdx
  site/src/pages/news/20231208-newsletter-6.mdx
  site/src/pages/release-notes/1.24.1.mdx
  site/src/pages/release-notes/1.25.0.mdx
  site/src/pages/release-notes/1.6.0.mdx
Labels: miscellaneous

#5307 Fix to send 400 from gRPC HTTP/JSON transcoding service when the request is invalid
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
Labels: defect

#5312 Fix a bug where `RequestLog` does not complete when `HttpResponse` is cancelled
  core/src/main/java/com/linecorp/armeria/common/stream/FilteredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/FuseableStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/stream/InternalStreamMessageUtil.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewerCancellationTest.java
Labels: defect

#5342 Introduce xDS module and SotW stream
  dependencies.toml
  settings.gradle
  testing-internal/src/main/resources/logback-test.xml
  xds/build.gradle
  xds/docs/DEVELOPER.md
  xds/docs/resources/duplicate_resource_nodes.plantuml
  xds/docs/resources/duplicate_resource_nodes.png
  xds/docs/resources/resource_tree.plantuml
  xds/docs/resources/resource_tree.png
  xds/src/main/java/com/linecorp/armeria/xds/ClusterResourceParser.java
  xds/src/main/java/com/linecorp/armeria/xds/EndpointResourceParser.java
  xds/src/main/java/com/linecorp/armeria/xds/ListenerResourceParser.java
  xds/src/main/java/com/linecorp/armeria/xds/ResourceParser.java
  xds/src/main/java/com/linecorp/armeria/xds/RouteResourceParser.java
  xds/src/main/java/com/linecorp/armeria/xds/SotwDiscoveryStub.java
  xds/src/main/java/com/linecorp/armeria/xds/SotwXdsStream.java
  xds/src/main/java/com/linecorp/armeria/xds/SubscriberStorage.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsResourceParserUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsResponseHandler.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsStream.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsStreamSubscriber.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsType.java
  xds/src/main/java/com/linecorp/armeria/xds/package-info.java
  xds/src/test/java/com/linecorp/armeria/xds/SotwXdsStreamTest.java
  xds/src/test/java/com/linecorp/armeria/xds/SubscriberStorageTest.java
Labels: new feature
