Repository line/armeria, pull requests merged in 2023-04, with the labels that each got.

#4552 Fix `FallbackService` not to raise `HttpStatusException`
  core/src/main/java/com/linecorp/armeria/server/FallbackService.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/FallbackServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerTest.java
Labels: defect

#4729 Fix concurrent modification exception from DeferredListener
  grpc/src/main/java/com/linecorp/armeria/server/grpc/DeferredListener.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/AsyncServerInterceptorTest.java
Labels: defect

#4787 Remove Spring Boot 1 integration modules
  dependencies.toml
  settings.gradle
  spring/boot1-autoconfigure/build.gradle
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaAutoConfiguration.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1BeanPostProcessor.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1BeanPostProcessorConfiguration.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1ConversionServiceConfiguration.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1FormatterRegistrar.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSpringBoot1MeterBindersConfiguration.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/DurationStyle.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/NumberToDurationConverter.java
  spring/boot1-autoconfigure/src/main/java/com/linecorp/armeria/spring/StringToDurationConverter.java
  spring/boot1-autoconfigure/src/main/resources/META-INF/spring.factories
  spring/boot1-autoconfigure/src/test/java/com/linecorp/armeria/spring/DurationStyleTests.java
  spring/boot1-starter/build.gradle
  spring/boot2-autoconfigure/src/test/java/com/linecorp/armeria/spring/DeprecatedIpTest.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaBeanPostProcessor.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/AssertjConfiguration.java
Labels: breaking change

#4809 Fix a wrong request path in `CustomServerErrorHandlerTest`
  core/src/test/java/com/linecorp/armeria/server/CustomServerErrorHandlerTest.java
Labels: cleanup

#4791 Ensure that request logs are completed for empty responses
  core/src/main/java/com/linecorp/armeria/common/EmptyHttpResponseException.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpMessageAggregator.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpResponseSubscriber.java
  core/src/test/java/com/linecorp/armeria/server/HttpServiceTest.java
  jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  jetty9/src/test/java/com/linecorp/armeria/server/jetty/JettyServiceTest.java
  jetty9/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  tomcat10/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
  tomcat10/src/test/java/com/linecorp/armeria/server/tomcat/ManagedTomcatServiceTest.java
  tomcat10/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: defect

#4808 Close a gRPC call when an invalid response is received.
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframer.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/InvalidGrpcResponseTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpDeframerTckTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerTest.java
Labels: defect

#4535 Add `AbstractRuleBuilder.onGrpcTrailers()`
  core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilder.java
  core/src/main/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/InternalGrpcWebTrailers.java
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/CircuitBreakerClientRuleTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryRuleWithContentBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/AbstractRuleBuilderTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/common/grpc/protocol/GrpcWebTrailers.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcWebTrailers.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientRetryTest.java
Labels: new feature

#4803 Bump Spring Boot 3 and Spring versions
  dependencies.toml
  it/spring/boot3-mixed-tomcat10/build.gradle
  it/spring/boot3-tomcat10/build.gradle
Labels: dependencies

#4793 Add the release note for 1.23.0
  core/src/main/java/com/linecorp/armeria/common/metric/EventLoopMetrics.java
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeterBinders.java
  dependencies.toml
  site/src/pages/release-notes/1.23.0.mdx
Labels: documentation

#4814 Publish Spring Boot 3 integration modules
  settings.gradle
Labels: cleanup

#4847 Update and fix Javadoc links in `dependencies.toml`
  dependencies.toml
Labels: cleanup
