Repository line/armeria, pull requests merged in 2024-07, with the labels that each got.

#5797 Fix `*ServiceBindingBuilder` to return the correct self type
  core/src/main/java/com/linecorp/armeria/server/AbstractContextPathAnnotatedServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/AbstractContextPathServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/server/contextpath/test/ServiceBuilderSelfTypeTest.java
Labels: defect

#5799 `WeightRampingUpStrategy` uses locks to avoid occasional selection failure for `XdsEndpointGroup`
  core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightedRoundRobinStrategy.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/ReentrantShortLock.java
Labels: defect

#5796 Fix handling of exceptions in `GrpcExceptionHandlerFunction`.
  examples/tutorials/grpc/src/main/java/example/armeria/server/blog/grpc/GrpcExceptionHandler.java
  grpc-kotlin/src/test/kotlin/com/linecorp/armeria/server/grpc/kotlin/CoroutineServerInterceptorTest.kt
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientBuilder.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/DefaultGrpcExceptionHandlerFunction.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GoogleGrpcExceptionHandlerFunction.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcExceptionHandlerFunction.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcExceptionHandlerFunctionUtil.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframer.java
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/ServerStatusAndMetadata.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HandlerRegistry.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/DefaultGrpcExceptionHandlerFunctionTest.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/GrpcExceptionHandlerFunctionBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/TestServiceImpl.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcExceptionHandlerAnnotationOnlyTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcExceptionHandlerFunctionUtilTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcExceptionHandlerTest.java
Labels: defect

#5804 Change conflicting meter names in `ServerMetrics`
  core/src/main/java/com/linecorp/armeria/server/ServerMetrics.java
  core/src/test/java/com/linecorp/armeria/server/ServerMetricsTest.java
Labels: defect

#5798 Add the release note for 1.29.2
  site/src/pages/release-notes/1.29.0.mdx
  site/src/pages/release-notes/1.29.2.mdx
Labels: documentation

#5806 Provide a way to set fallback file extensions for `FileService`
  core/src/main/java/com/linecorp/armeria/server/file/FileService.java
  core/src/main/java/com/linecorp/armeria/server/file/FileServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/file/FileServiceConfig.java
  core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
Labels: new feature

#5812 Fix flaky `ServerMetrics` tests
  core/src/test/java/com/linecorp/armeria/server/ServerMetricsTest.java
Labels: cleanup

#5811 Fix a bug where a protocol violation is not handled by `ServerErrorHandler`
  core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java
  core/src/test/java/com/linecorp/armeria/server/ProtocolViolationHandlingTest.java
Labels: defect

#5816 Handle a null ExecutionResult in `GraphqlService`
  graphql/src/main/java/com/linecorp/armeria/server/graphql/DefaultGraphqlService.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlErrorHandler.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlErrorHandlerTest.java
Labels: defect

#5817 Add release notes for 1.29.3
  site/src/pages/release-notes/1.29.3.mdx
Labels: documentation

#5805 Refactor `HaProxy` exception handling
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/HAProxyHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpSessionHandler.java
Labels: cleanup

#5802 Modify behavior of `Endpoint#withAttrs` to merge attributes
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
Labels: new feature, breaking change

#5822 Support thrift 0.19 and 0.20
  core/src/main/java/com/linecorp/armeria/common/util/Version.java
  dependencies.toml
  gradle/scripts/.github/CODEOWNERS
  gradle/scripts/.gitrepo
  gradle/scripts/lib/thrift/0.19/thrift.linux-aarch_64
  gradle/scripts/lib/thrift/0.19/thrift.linux-x86_64
  gradle/scripts/lib/thrift/0.19/thrift.osx-aarch_64
  gradle/scripts/lib/thrift/0.19/thrift.osx-x86_64
  gradle/scripts/lib/thrift/0.19/thrift.windows-x86_64.exe
  gradle/scripts/lib/thrift/0.20/thrift.linux-aarch_64
  gradle/scripts/lib/thrift/0.20/thrift.linux-x86_64
  gradle/scripts/lib/thrift/0.20/thrift.osx-aarch_64
  gradle/scripts/lib/thrift/0.20/thrift.osx-x86_64
  gradle/scripts/lib/thrift/0.20/thrift.windows-x86_64.exe
  settings.gradle
  thrift/thrift0.12/src/test/thrift/TTextProtocolTest.thrift
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ServletTestUtils.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftOverHttpClientTServletIntegrationTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/common/thrift/text/TTextProtocolTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/ApacheClientUtils.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServiceTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftVersionDetector.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/AbstractThriftOverHttpTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp1Test.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/ThriftOverHttp2Test.java
  thrift/thrift0.19/build.gradle
  thrift/thrift0.19/src/main/resources/com/linecorp/armeria/internal/common/thrift/thrift-options.properties
  thrift/thrift0.19/src/test/java/com/linecorp/armeria/client/thrift/ServletTestUtils.java
  thrift/thrift0.19/src/test/java/com/linecorp/armeria/internal/ApacheClientUtils.java
  thrift/thrift0.20/build.gradle
  thrift/thrift0.20/src/main/resources/com/linecorp/armeria/internal/common/thrift/thrift-options.properties
Labels: dependencies

#5400 Support google.api.HttpBody in gRPC/JSON transcoding
  grpc/src/main/java/com/linecorp/armeria/server/grpc/AbstractUnframedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcServiceTest.java
  grpc/src/test/proto/testing/grpc/transcoding.proto
Labels: new feature

#5829 fix: logger.warn instead of ISE on transcoding options for non-unary gRPC
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/proto/testing/grpc/transcoding.proto
Labels: defect

#5825 Exclude `java.security.Provider` SPI configuration from shaded jar
  gradle.properties
  gradle/scripts/README.md
  gradle/scripts/lib/java-shade.gradle
Labels: defect

#5824 Fix a bug where `INTERNAL_ERROR` is returned when gRPC message length is exceeded
  grpc/src/main/java/com/linecorp/armeria/common/grpc/DefaultGrpcExceptionHandlerFunction.java
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GrpcExceptionHandlerFunction.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcExceptionHandlerFunctionUtil.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframer.java
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/InternalGrpcExceptionHandler.java
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/AbstractServerCall.java
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/ServerStatusAndMetadata.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HandlerRegistry.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/StreamingServerCall.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnaryServerCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpStreamDeframerTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcMessageLengthTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/HandlerRegistryTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/InternalGrpcExceptionHandlerTest.java
Labels: defect

#5833 Fix `ClientFactory` leaks in `ResteasyClient`
  resteasy/src/main/java/com/linecorp/armeria/client/resteasy/ArmeriaJaxrsClientEngine.java
  resteasy/src/test/java/com/linecorp/armeria/server/resteasy/CalculatorServiceClientServerTest.java
Labels: defect

#5834 Update release notes for 1.29.3
  site/src/pages/release-notes/1.29.3.mdx
Labels: documentation

#5835 Revive java module related changes
  gradle/scripts/.gitrepo
  gradle/scripts/README.md
  gradle/scripts/lib/common-info.gradle
  gradle/scripts/lib/java-shade.gradle
  gradle/scripts/lib/java.gradle
  gradle/scripts/lib/prerequisite.gradle
  gradle/scripts/lib/thrift/dockerfile/Dockerfile.bionic
  gradle/scripts/lib/thrift/dockerfile/Dockerfile.centos7
  gradle/scripts/lib/thrift/dockerfile/Dockerfile.trusty
Labels: defect

#5836 Make CI run all branches on push
  .github/workflows/actions_build.yml
Labels: miscellaneous

#5840 Link the Wikipedia page instead of the LY corporation homepage
  site/src/pages/index.tsx
Labels: cleanup

#5844 Add the release note 1.29.4
  site/src/pages/release-notes/1.29.4.mdx
Labels: documentation

#5841 Do not convert `@Header` name when the name is specified
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedElementNameUtil.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
Labels: defect
