Repository line/armeria, pull requests merged in 2024-01, with the labels that each got.

#5339 Fix pts with testng
  build.gradle
  core/build.gradle
  dependencies.toml
  kotlin/build.gradle.kts
Labels: cleanup

#5363 Fix incorrect sample metrics YAML property in Spring Boot integration documentation page
  site/src/pages/docs/advanced-spring-boot-integration.mdx
Labels: documentation

#5350 Use `-deststoretype pkcs12` to remove warning
  examples/saml-service-provider/src/main/java/example/armeria/server/saml/sp/Main.java
  site/src/pages/docs/advanced-saml.mdx
Labels: documentation

#5338 Add the ability to run a testNg/testStreaming test on its own
  core/build.gradle
  kotlin/build.gradle.kts
Labels: cleanup

#5375 Fix flaky FixedStreamMessageTest
  core/src/test/java/com/linecorp/armeria/internal/common/stream/FixedStreamMessageTest.java
Labels: miscellaneous

#5356 Provide a way to decorate `THttpService` via annotation
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftServiceMetadata.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/DecoratingTHttpServiceTest.java
Labels: new feature

#5393 Properly convert implicit request object in the annotated doc service to type signature
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServicePlugin.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
Labels: defect

#5388 Fix illegal state of the ByteBuf if the CLOSE frame does not contain a reason
  core/src/main/java/com/linecorp/armeria/common/websocket/CloseByteBufWebSocketFrame.java
Labels: defect

#5351 Support gRPC exception handler for client-side
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientBuilder.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientOptions.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaChannel.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientExceptionHandlerTest.java
Labels: new feature

#5343 Fix a bug where all healthy endpoints are removed as `HealthCheckedEndpointGroup` is initialized
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupInitializationRaceTest.java
Labels: defect

#5391 Allow HttpFile to pass a Spring Boot 3 nested jar URL
  core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
  core/src/test/java/com/linecorp/armeria/server/file/HttpFileTest.java
Labels: improvement

#5361 Fixed a bug where logs produced by `Flags` were not appended to `RequestContextExportingAppender`
  logback/logback12/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java
Labels: defect

#5368 Make `WebSocketService` interface
  core/src/main/java/com/linecorp/armeria/client/websocket/WebSocketClientFrameDecoder.java
  core/src/main/java/com/linecorp/armeria/common/websocket/WebSocket.java
  core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketFrameDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/server/websocket/DefaultWebSocketService.java
  core/src/main/java/com/linecorp/armeria/internal/server/websocket/WebSocketServiceFrameDecoder.java
  core/src/main/java/com/linecorp/armeria/internal/server/websocket/package-info.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/websocket/WebSocketProtocolHandler.java
  core/src/main/java/com/linecorp/armeria/server/websocket/WebSocketService.java
  core/src/main/java/com/linecorp/armeria/server/websocket/WebSocketServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/websocket/WebSocketUpgradeResult.java
  core/src/test/java/com/linecorp/armeria/internal/common/websocket/WebSocketFrameEncoderAndDecoderTest.java
  core/src/test/java/com/linecorp/armeria/server/websocket/DelegatingWebSocketServiceTest.java
Labels: improvement, new feature

#5402 Use isolated self-hosted runners non-PR CI jobs
  .github/check-workflow-write-permission.sh
  .github/workflows/actions_build.yml
  .github/workflows/gradle-enterprise-postjob.yml
  .github/workflows/publish-release.yml
  .github/workflows/tag-new-release.yml
Labels: miscellaneous

#5371 Updates to Brave Jupiter tests
  brave/src/main/java/com/linecorp/armeria/common/brave/BraveBlockHoundIntegration.java
  brave/src/main/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextBuilder.java
  brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/client/brave/Http1BraveClientIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/client/brave/Http2BraveClientIntegrationTest.java
  brave/src/test/java/com/linecorp/armeria/server/brave/BraveServiceIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/observation/Http1ObservationClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/observation/Http2ObservationClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/client/observation/ObservationClientIntegrationTest.java
  dependencies.toml
  site/src/pages/docs/advanced-zipkin.mdx
Labels: cleanup, dependencies

#5369 eureka: allow overriding the healthCheckUrlPath
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/InstanceInfo.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/InstanceInfoBuilder.java
  eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
Labels: new feature

#5366 fix support json_name options
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
  grpc/src/test/proto/testing/grpc/transcoding.proto
Labels: new feature

#5353 Add `SessionProtocol` property to `RoutingContext`.
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  core/src/main/java/com/linecorp/armeria/server/DefaultRoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandlerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContextWrapper.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRouteUtil.java
  core/src/test/java/com/linecorp/armeria/server/CachingRoutingContextTest.java
  core/src/test/java/com/linecorp/armeria/server/RouteTest.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingContextSessionProtocolTest.java
  core/src/test/java/com/linecorp/armeria/server/RoutingContextTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceRouteUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
Labels: new feature

#5087 Add a build method to `ServerListener` responsible for graceful termination of an external `Executor`.
  core/src/main/java/com/linecorp/armeria/server/ServerListenerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ShutdownSupport.java
  core/src/main/java/com/linecorp/armeria/server/UnstoppableScheduledExecutorService.java
  core/src/test/java/com/linecorp/armeria/server/ServerListenerTest.java
Labels: new feature

#5288 Add metrics for active connections on the client side
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolMetrics.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/test/java/com/linecorp/armeria/client/ConnectionPoolCollectingMetricTest.java
Labels: new feature

#5319 Fix `StringMultimap.containsBoolean()` to check all entries
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderGetters.java
  core/src/main/java/com/linecorp/armeria/common/QueryParamGetters.java
  core/src/main/java/com/linecorp/armeria/common/StringMultimap.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/StringUtil.java
  core/src/test/java/com/linecorp/armeria/common/HttpHeadersBaseTest.java
  core/src/test/java/com/linecorp/armeria/common/QueryParamsBaseTest.java
Labels: defect

#5386 Support RxJava-wrapped `HttpResult` response in annotated services
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/CompositeResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/HttpResultUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/HttpResultUtilTest.java
  rxjava2/src/test/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunctionTest.java
  rxjava3/src/test/java/com/linecorp/armeria/server/rxjava3/ObservableResponseConverterFunctionTest.java
Labels: improvement

#5387 Enhance error reporting for failed gRPC client stub creation.
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/JavaGrpcClientStubFactory.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/KotlinGrpcClientStubFactory.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ReactorGrpcClientStubFactory.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ScalaPbGrpcClientStubFactory.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ServiceDescriptorResolutionException.java
Labels: improvement

#5280 Added websocket support to GraphQL using the graphql-ws protocol
  core/src/main/java/com/linecorp/armeria/common/websocket/WebSocketCloseStatus.java
  core/src/main/java/com/linecorp/armeria/internal/common/websocket/WebSocketUtil.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/DefaultGraphqlService.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/ExecutionResultSubscriber.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlExecutor.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlServiceBuilder.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlSubProtocol.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlWSSubProtocol.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlWebSocketService.java
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlWebSocketSubscriber.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceSubscriptionTest.java
Labels: new feature

#5233 Provide a way to run service code out of I/O event loops
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  brave/src/test/java/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContextTest.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/SubscribeOnStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/AbstractAnnotatedServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/AbstractServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ContextPathAnnotatedServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ContextPathServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostContextPathAnnotatedServiceConfigSetters.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostContextPathServiceBindingBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostServiceBindingBuilder.java
  core/src/test/java/com/linecorp/armeria/common/stream/SubscribeOnStreamMessageTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/ServiceWorkerGroupTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceNamingTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceTest.java
Labels: new feature

#5404 Try using testNg using junit engine
  core/build.gradle
  core/src/test/java/com/linecorp/armeria/client/Http2HeadersLimitTest.java
  core/src/test/java/com/linecorp/armeria/common/DefaultSplitHttpResponseTest.java
  dependencies.toml
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/HttpDeframerTckTest.java
  kotlin/build.gradle.kts
Labels: cleanup

#5412 Fix a leak when WebSocket client receives an invalid response
  core/src/main/java/com/linecorp/armeria/client/websocket/DefaultWebSocketClient.java
Labels: defect

#5422 Grant @dependabot write permission for workflow files.
  .github/check-workflow-write-permission.sh
Labels: miscellaneous

#5417 Handle flaky xds test
  xds/src/main/java/com/linecorp/armeria/xds/ClusterRoot.java
  xds/src/main/java/com/linecorp/armeria/xds/ListenerRoot.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsClientIntegrationTest.java
Labels: cleanup

#5188 Easily mask sensitive headers from request logs by adding `HeadersSanitizer`
  core/src/main/java/com/linecorp/armeria/common/logging/AbstractHeadersSanitizerBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/AbstractLogFormatterBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/HeaderMaskingFunction.java
  core/src/main/java/com/linecorp/armeria/common/logging/HeadersSanitizer.java
  core/src/main/java/com/linecorp/armeria/common/logging/JsonHeadersSanitizer.java
  core/src/main/java/com/linecorp/armeria/common/logging/JsonHeadersSanitizerBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/JsonLogFormatter.java
  core/src/main/java/com/linecorp/armeria/common/logging/JsonLogFormatterBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/TextHeadersSanitizer.java
  core/src/main/java/com/linecorp/armeria/common/logging/TextHeadersSanitizerBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/TextLogFormatter.java
  core/src/main/java/com/linecorp/armeria/common/logging/TextLogFormatterBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/JsonLogFormatterTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/TextLogFormatterTest.java
Labels: new feature

#5419 Release notes for 1.27.0
  dependencies.toml
  kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpClient.java
  site/src/pages/release-notes/1.27.0.mdx
Labels: documentation

#5426 Add `BlockHoundIntegration` for kubernetes integration moulde
  kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/KubernetesBlockHoundIntegration.java
  kubernetes/src/main/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
Labels: defect

#5427 Fix flaky `ByteStreamMessageOutputStreamTest.writeAfterStreamClosed()`
  core/src/test/java/com/linecorp/armeria/common/stream/ByteStreamMessageOutputStreamTest.java
Labels: cleanup

#5378 Add dependabot configuration for `npm` dependencies
  .github/dependabot.yml
Labels: cleanup

#5326 Retry test failure when publishing release
  .github/workflows/publish-release.yml
Labels: miscellaneous
