Repository line/armeria, pull requests merged in 2024-12, with the labels that each got.

#6012 Fix a bug where stale endpoints in `KubernetesEndpointGroup` aren't updated
  kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
Labels: defect

#6002 Expose the default `HealthCheckUpdateHandler`
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/healthcheck/HealthCheckUpdateHandler.java
Labels: improvement

#6013 Add the release note for 1.31.2
  site/src/pages/release-notes/1.31.2.mdx
Labels: documentation

#6022 Use `macos-latest` for CI builds
  .github/workflows/actions_build.yml
Labels: miscellaneous

#6025 `ResponseTimeoutMode.FROM_START` works correctly with `RetryingClient`
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java
  core/src/main/java/com/linecorp/armeria/client/WebSocketHttp1ClientChannelHandler.java
  core/src/main/java/com/linecorp/armeria/client/WebSocketHttp1ResponseWrapper.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientRequestContextExtension.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultCancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/NoopCancellationScheduler.java
  core/src/test/java/com/linecorp/armeria/client/retry/ResponseTimeoutFromStartTest.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/ArmeriaClientCall.java
Labels: defect

#6023 Automatically reconnect Kubernetes watcher when closed exceptionally
  kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpClientFactory.java
  kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/ArmeriaWebSocketClient.java
  kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupFaultToleranceTest.java
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/TestKubernetesClientBuilderCustomizer.java
Labels: defect

#6024 Periodically remove inactive connection pool metrics
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolListener.java
  core/src/main/java/com/linecorp/armeria/client/ConnectionPoolMetrics.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/test/java/com/linecorp/armeria/client/ConnectionPoolCollectingMetricTest.java
  core/src/test/java/com/linecorp/armeria/client/ConnectionPoolMetricsTest.java
  core/src/test/java/com/linecorp/armeria/client/Http1ResponseDecoderTest.java
Labels: defect

#6029 Bump Node.js version
  docs-client/build.gradle
  site/build.gradle
Labels: dependencies

#6030 Add release notes for 1.31.3
  site/src/pages/release-notes/1.31.3.mdx
Labels: documentation

#5941 Provide a way to terminate unfinished requests after graceful shutdown
  core/src/main/java/com/linecorp/armeria/common/ShuttingDownException.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DefaultGracefulShutdown.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/GracefulShutdown.java
  core/src/main/java/com/linecorp/armeria/server/GracefulShutdownBuilder.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
  core/src/test/java/com/linecorp/armeria/GracefulShutdownBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/CustomGracefulShutDownTest.java
  spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/server/GracefulShutdownIntegrationTest.java
Labels: new feature, deprecation
