Repository line/armeria, pull requests merged in 2024-03, with the labels that each got.

#5467 Suggestion: Set intellij project icon
  .gitignore
  .idea/icon.svg
Labels: miscellaneous

#5453 Remove armeria-brave module
  brave/brave/build.gradle
  brave/brave5/build.gradle
  brave/brave5/src/main/java/com/linecorp/armeria/client/brave/package-info.java
  brave/brave5/src/main/java/com/linecorp/armeria/common/brave/package-info.java
  brave/brave5/src/main/java/com/linecorp/armeria/internal/common/brave/package-info.java
  brave/brave5/src/main/java/com/linecorp/armeria/server/brave/package-info.java
  dependencies.toml
  settings.gradle
Labels: breaking change

#5444 Update the tutorial introduction
  site/src/pages/tutorials/index.mdx
Labels: documentation

#5456 Apply ktlint with `max_line_length` as 112
  .editorconfig
  benchmarks/jmh/src/jmh/kotlin/com/linecorp/armeria/internal/common/kotlin/AnnotatedServiceFlowBenchmark.kt
  examples/graphql-kotlin/src/test/kotlin/example/armeria/server/graphql/kotlin/GraphqlArmeriaClient.kt
  examples/grpc-kotlin/src/main/kotlin/example/armeria/grpc/kotlin/HelloServiceImpl.kt
  grpc-kotlin/src/main/kotlin/com/linecorp/armeria/server/grpc/kotlin/CoroutineServerInterceptor.kt
  grpc-kotlin/src/test/kotlin/com/linecorp/armeria/server/grpc/kotlin/CoroutineServerInterceptorTest.kt
  it/grpc/kotlin/src/test/kotlin/com/linecorp/armeria/grpc/kotlin/TestServiceImpl.kt
  it/kotlin/src/test/kotlin/com/linecorp/armeria/it/AnnotatedServiceErrorMessageTest.kt
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaRequestCoroutineContext.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/FlowAnnotatedServiceTest.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt
Labels: cleanup

#5437 Fix links on kotlin docs and fix service request context propagation example
  examples/context-propagation/kotlin/src/main/kotlin/example/armeria/contextpropagation/kotlin/MainService.kt
  site/src/pages/docs/advanced-kotlin.mdx
  site/src/pages/docs/client-grpc.mdx
  site/src/pages/docs/server-grpc.mdx
Labels: documentation

#5497 Fix to thread-safely load Thrift classes for old libthrift (< 0.9.3)
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/common/thrift/text/StructContext.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftMetadataAccess.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDescriptiveTypeInfoProvider.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServicePlugin.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/common/thrift/ThriftMetadataAccessTest.java
Labels: defect

#5495 Fix a possible `IllegalReferenceCountException` in WebSocket handshake
  core/src/main/java/com/linecorp/armeria/client/WebSocketHttp1ClientChannelHandler.java
Labels: defect

#5516 Streamline native image config generation / Update native image config
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/jni-config.json
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/predefined-classes-config.json
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/proxy-config.json
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/reflect-config.json
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/resource-config.json
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/serialization-config.json
  native-image-config/README.md
  native-image-config/build.gradle.kts
  native-image-config/src/base-config/resource-config.json
  native-image-config/src/trace-filters/caller-filter.json
Labels: cleanup

#5523 Close `InputStream` after marshalling gRPC messages
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcMessageMarshaller.java
Labels: defect

#5502 Migrate `XdsEndpointGroup` to `client.endpoint` (xDS-endpoint pt 2)
  xds/src/main/java/com/linecorp/armeria/xds/ClusterSnapshot.java
  xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceClient.java
  xds/src/main/java/com/linecorp/armeria/xds/EndpointSnapshot.java
  xds/src/main/java/com/linecorp/armeria/xds/ListenerSnapshot.java
  xds/src/main/java/com/linecorp/armeria/xds/RouteSnapshot.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsConverterUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsConstants.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointGroup.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/package-info.java
  xds/src/test/java/com/linecorp/armeria/xds/MostlyStaticWithDynamicEdsTest.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsEndpointGroupTest.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/XdsConverterUtilTest.java
Labels: cleanup, breaking change

#5370 Support for Spring 6 HTTP interface
  dependencies.toml
  settings.gradle
  spring/boot2-webflux-autoconfigure/build.gradle
  spring/boot3-webflux-autoconfigure/build.gradle
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientAutoConfiguration.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpConnector.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpHandlerAdapter.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequest.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/DataBufferFactoryWrapperConfiguration.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpRequestTest.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaClientHttpResponseTest.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpRequestTest.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponseTest.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/DataBufferFactoryWrapperTest.java
  spring/spring6/build.gradle.kts
  spring/spring6/src/main/java/com/linecorp/armeria/spring/client/ArmeriaHttpExchangeAdapter.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/client/ArmeriaHttpExchangeAdapterBuilder.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/client/RequestAttributeAccess.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/client/StatusHandler.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/client/package-info.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/internal/client/ArmeriaClientHttpRequest.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/internal/client/ArmeriaClientHttpResponse.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/internal/client/package-info.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/internal/common/DataBufferFactoryWrapper.java
  spring/spring6/src/main/java/com/linecorp/armeria/spring/internal/common/package-info.java
  spring/spring6/src/test/java/com/linecorp/armeria/spring/client/ArmeriaHttpExchangeAdapterTest.java
Labels: new feature

#5482 Ensure subscriptions are completed when a request is completed
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlWebSocketSubscriber.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceSubscriptionTest.java
  graphql/src/test/resources/testing/graphql/subscription.graphqls
Labels: defect

#5528 Add release notes for 1.27.3
  site/src/pages/release-notes/1.27.3.mdx
Labels: documentation

#5530 Update LINE Corporation to LY Corporation
  site/src/design/README.md
  site/src/layouts/footer.tsx
  site/src/pages/community/design-resources.mdx
  site/src/pages/community/developer-guide.mdx
  site/src/pages/community/index.mdx
  site/src/pages/community/toc.json
  site/src/pages/docs/index.mdx
  site/src/pages/index.tsx
Labels: documentation

#5499 Add authenticated user to mdc by default
  core/src/main/java/com/linecorp/armeria/common/logging/BuiltInProperty.java
  logback/logback12/src/test/java/com/linecorp/armeria/common/logback/RequestContextExportingAppenderTest.java
Labels: new feature

#5498 Support xDS grpc service initial metadata
  xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceClient.java
  xds/src/test/java/com/linecorp/armeria/xds/ConfigSourceGrpcServiceTest.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
Labels: defect

#5500 Access logs are written within the Request Context
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLoggerIntegrationTest.java
Labels: new feature

#5517 Guess `ExchangeType` if it is not set in `RequestOptions`
  core/src/main/java/com/linecorp/armeria/client/WebClient.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/WebClientExchangeTypeTest.java
Labels: defect

#5472 Use CircuitBreaker.tryRequest() instead of deprecated canRequest() in doc and test
  core/src/test/java/com/linecorp/armeria/client/circuitbreaker/NonBlockingCircuitBreakerTest.java
  site/src/pages/docs/client-circuit-breaker.mdx
Labels: documentation

#5532 Prevent open redirect by appending a trailing slash
  site/src/layouts/base.tsx
Labels: defect

#5074 FIX-5017 Add authorization metrics
  core/src/main/java/com/linecorp/armeria/server/auth/AuthService.java
  core/src/main/java/com/linecorp/armeria/server/auth/AuthServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/auth/AuthServiceTest.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcDecoratingService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/GrpcHttpJsonTranscodingServiceAnnotatedAuthServiceTest.java
Labels: improvement

#5533 Websocket bug: PING to server sends PING Frame instead of PONG Frame
  core/src/main/java/com/linecorp/armeria/common/websocket/WebSocketFrame.java
  it/websocket/src/test/java/com/linecorp/armeria/it/websocket/WebSocketServiceItTest.java
Labels: defect

#5544 Fix a bug where decorator's `serviceAdded` is not invoked
  core/src/main/java/com/linecorp/armeria/internal/server/RouteDecoratingService.java
  core/src/main/java/com/linecorp/armeria/internal/server/websocket/DefaultWebSocketService.java
  core/src/main/java/com/linecorp/armeria/server/DecoratingHttpServiceFunction.java
  core/src/main/java/com/linecorp/armeria/server/DecoratingService.java
  core/src/main/java/com/linecorp/armeria/server/FunctionalDecoratingHttpService.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/server/ServiceAddedTest.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/server/thrift/DecoratingTHttpServiceTest.java
Labels: defect

#5477 Relax the validation of `Location` header when redirecting
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeadersBase.java
  core/src/main/java/com/linecorp/armeria/common/RequestTarget.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
  core/src/main/java/com/linecorp/armeria/internal/common/NonWrappingRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
  core/src/test/java/com/linecorp/armeria/client/DomainSocketClientTest.java
  core/src/test/java/com/linecorp/armeria/client/RedirectingClientTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
Labels: defect
