Repository line/armeria, pull requests merged in 2024-08, with the labels that each got.

#5853 Upgrade Node.js to 22.3.0
  docs-client/build.gradle
  site/build.gradle
Labels: dependencies

#5852 Use cdn.jsdelivr.net for twemoji
  site/src/components/emoji.tsx
Labels: documentation

#5839 fix: doc service webpage sidebar should limit to 40% window width
  docs-client/src/containers/App/index.tsx
Labels: improvement

#5845 Allow some control characters in a request target
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
Labels: defect

#5801 Support priority and health based load balancing for `SubsetLoadBalancer`
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterEntry.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/LoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SubsetLoadBalancer.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
Labels: new feature

#5857 Update dependencies
  dependencies.toml
  gradle/scripts/lib/java-shade.gradle
  gradle/wrapper/gradle-wrapper.properties
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/InternalTestingBlockHoundIntegration.java
Labels: dependencies

#5785 Improve xDS health check
  core/src/main/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategy.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/AbstractHealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/EndpointAttributeKeys.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/RampingUpKeys.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/healthcheck/HttpHealthChecker.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/healthcheck/package-info.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/EndpointAttributeKeysTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/WeightRampingUpStrategyTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckContextGroupTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupTest.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/EndpointUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/EndpointsPool.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsAttributeAssigningEndpointGroup.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointGroup.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsHealthCheckedEndpointGroupBuilder.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/DynamicHealthCheckTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/HealthCheckedTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RampingUpTest.java
Labels: new feature

#5399 Fix blocking annotation not working on gRPC calls properly
  grpc-kotlin/src/test/kotlin/com/linecorp/armeria/server/grpc/kotlin/BlockingExecutorTest.kt
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaCoroutineContextInterceptor.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/FramedGrpcService.java
Labels: defect

#5854 Loosen the validation rule for URI authority
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
  core/src/main/java/com/linecorp/armeria/internal/common/SchemeAndAuthority.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/BitSetUtil.java
  core/src/test/java/com/linecorp/armeria/client/UnderscoredAuthorityTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/SchemeAndAuthorityTest.java
  core/src/test/java/com/linecorp/armeria/server/ServiceFinderTest.java
Labels: defect

#5862 Relax validation for responses with empty content status.
  core/src/main/java/com/linecorp/armeria/common/AggregatedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseUtil.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponseWriter.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/test/java/com/linecorp/armeria/common/DefaultAggregatedHttpResponseTest.java
Labels: improvement

#5800 `ClientRequestContext#cancel` cancels the associated request immediately
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java
  core/src/main/java/com/linecorp/armeria/common/RequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultCancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/NoopCancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/test/java/com/linecorp/armeria/client/ContextCancellationTest.java
  core/src/test/java/com/linecorp/armeria/client/CountingConnectionPoolListener.java
  core/src/test/java/com/linecorp/armeria/client/DelegatingHttpRequest.java
  core/src/test/java/com/linecorp/armeria/client/Http1ConnectionReuseTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientResponseTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/CancellationSchedulerTest.java
Labels: improvement

#5867 Fix flaky `StreamMessageCollectingTest.filteredStreamMessage_exception()`
  core/src/test/java/com/linecorp/armeria/common/stream/StreamMessageCollectingTest.java
Labels: cleanup

#5793 `ResponseTimeout` can be scheduled at an earlier timing
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/BlockingWebClientRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContextWrapper.java
  core/src/main/java/com/linecorp/armeria/client/DefaultRequestOptions.java
  core/src/main/java/com/linecorp/armeria/client/FutureTransformingRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java
  core/src/main/java/com/linecorp/armeria/client/RequestOptions.java
  core/src/main/java/com/linecorp/armeria/client/RequestOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/RequestOptionsSetters.java
  core/src/main/java/com/linecorp/armeria/client/ResponseTimeoutMode.java
  core/src/main/java/com/linecorp/armeria/client/RestClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/RestClientPreparation.java
  core/src/main/java/com/linecorp/armeria/client/TransformingRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/WebClientRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/client/websocket/WebSocketClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/test/java/com/linecorp/armeria/client/TimeoutModeTest.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientBuilder.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
  scala/scala_2.13/src/main/scala/com/linecorp/armeria/client/scala/ScalaRestClientPreparation.scala
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/client/thrift/ThriftClientBuilder.java
Labels: new feature

#5861 Add release notes for 1.30.0
  site/release-note.ts
  site/src/pages/release-notes/1.30.0.mdx
Labels: documentation

#5869 Fix flaky test `ContextCancellationTest`
  core/src/test/java/com/linecorp/armeria/client/ContextCancellationTest.java
Labels: cleanup
