Repository line/armeria, pull requests merged in 2024-04, with the labels that each got.

#5503 Support `STRICT_DNS`, `HealthCheck` for `XdsEndpointGroup` (xDS-endpoint pt 3)
  xds/src/main/java/com/linecorp/armeria/xds/AbstractRoot.java
  xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceClient.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterEntry.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterManager.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/LoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/MetadataUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/PrioritySet.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SubsetLoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsAttributeAssigningEndpointGroup.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsAttributesKeys.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointGroup.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointSelector.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointUtil.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/HealthCheckedTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/StrictDnsIntegrationTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/XdsConverterUtilTest.java
Labels: new feature

#5531 Enhance security of the Complete message for GraphQL over WebSocket protocol
  graphql/src/main/java/com/linecorp/armeria/server/graphql/GraphqlWSSubProtocol.java
  graphql/src/test/java/com/linecorp/armeria/server/graphql/GraphqlServiceSubscriptionTest.java
Labels: defect

#5524 Avoid addShutdownHook to JVM during its shutdown
  core/src/main/java/com/linecorp/armeria/client/DefaultClientFactory.java
Labels: defect

#5519 Fix a bug where the default `HeadersSanitizer` does not work in logging decorators
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/logging/LoggingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/AbstractLogFormatterBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultLogWriter.java
  core/src/main/java/com/linecorp/armeria/common/logging/LogWriterBuilder.java
  core/src/main/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilder.java
  core/src/main/java/com/linecorp/armeria/server/logging/LoggingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: defect, breaking change

#4829 Allow distribution config customization
  core/src/main/java/com/linecorp/armeria/client/metric/AbstractMetricCollectingClient.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClient.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingRpcClient.java
  core/src/main/java/com/linecorp/armeria/client/metric/MetricCollectingRpcClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/DistributionStatisticConfigUtil.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/metric/AbstractMetricCollectingBuilder.java
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeters.java
  core/src/main/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupport.java
  core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingService.java
  core/src/main/java/com/linecorp/armeria/server/metric/MetricCollectingServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/common/metric/AbstractMetricCollectingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/metric/RequestMetricSupportTest.java
  it/flags-provider/src/test/java/com/linecorp/armeria/common/FlagsProviderTest.java
Labels: new feature

#5535 Handle a leak when thrift requests are aborted early
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientDelegate.java
Labels: defect

#5449 Support for Kotlin value class in annotated services
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaCoroutineUtil.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/ValueClassTest.kt
Labels: defect

#5029 Add `TlsEngineType` enum
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/util/TlsEngineType.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/test/java/com/linecorp/armeria/common/FlagsTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/SslContextUtilTest.java
  it/flags-provider/src/test/java/com/linecorp/armeria/common/FlagsProviderTest.java
Labels: new feature

#5459 Add support for self config source
  xds/src/main/java/com/linecorp/armeria/xds/AbstractResourceNode.java
  xds/src/main/java/com/linecorp/armeria/xds/ClusterResourceNode.java
  xds/src/main/java/com/linecorp/armeria/xds/ClusterRoot.java
  xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceMapper.java
  xds/src/main/java/com/linecorp/armeria/xds/ListenerResourceNode.java
  xds/src/main/java/com/linecorp/armeria/xds/ListenerRoot.java
  xds/src/main/java/com/linecorp/armeria/xds/RouteResourceNode.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsBootstrapImpl.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsConverterUtil.java
  xds/src/test/java/com/linecorp/armeria/xds/MultiConfigSourceTest.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
Labels: new feature

#5445 Update REST and gRPC tutorials to use test code
  examples/tutorials/grpc/src/test/java/example/armeria/server/blog/grpc/BlogServiceTest.java
  examples/tutorials/thrift/src/test/java/example/armeria/server/blog/thrift/BlogServiceTest.java
  site/src/pages/tutorials/grpc/blog/add-docservice.mdx
  site/src/pages/tutorials/grpc/blog/define-service.mdx
  site/src/pages/tutorials/grpc/blog/implement-create.mdx
  site/src/pages/tutorials/grpc/blog/implement-delete.mdx
  site/src/pages/tutorials/grpc/blog/implement-read.mdx
  site/src/pages/tutorials/grpc/blog/implement-update.mdx
  site/src/pages/tutorials/grpc/blog/index.mdx
  site/src/pages/tutorials/grpc/blog/run-service.mdx
  site/src/pages/tutorials/rest/blog/add-services-to-server.mdx
  site/src/pages/tutorials/rest/blog/implement-create.mdx
  site/src/pages/tutorials/rest/blog/implement-delete.mdx
  site/src/pages/tutorials/rest/blog/implement-read.mdx
  site/src/pages/tutorials/rest/blog/implement-update.mdx
  site/src/pages/tutorials/rest/blog/index.mdx
  site/src/pages/tutorials/thrift/blog/create-service.mdx
  site/src/pages/tutorials/thrift/blog/define-service-methods.mdx
  site/src/pages/tutorials/thrift/blog/define-service.mdx
  site/src/pages/tutorials/thrift/blog/implement-create.mdx
  site/src/pages/tutorials/thrift/blog/implement-delete.mdx
  site/src/pages/tutorials/thrift/blog/implement-read.mdx
  site/src/pages/tutorials/thrift/blog/implement-update.mdx
  site/src/pages/tutorials/thrift/blog/index.mdx
  site/src/pages/tutorials/thrift/blog/run-server.mdx
  site/src/pages/tutorials/thrift/blog/run-service.mdx
  site/src/pages/tutorials/toc.json
Labels: documentation

#5560 Fix typo in document
  site/src/pages/docs/client-timeouts.mdx
Labels: documentation

#5534 Handle an empty query parameter with @Default
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java
  core/src/main/java/com/linecorp/armeria/server/annotation/Default.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolverTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/EmptyParameterWithDefaultAnnotationTest.java
Labels: defect

#5418 Reuse VirtualHostBuilder on the same hostnamePattern
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/server/HostnameBasedVirtualHostTest.java
  core/src/test/java/com/linecorp/armeria/server/PortBasedVirtualHostTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
Labels: defect

#4982 Add features to allow users specify regular expression or `Predicate` for CORS allowed origins
  core/src/main/java/com/linecorp/armeria/internal/server/websocket/DefaultWebSocketService.java
  core/src/main/java/com/linecorp/armeria/server/annotation/decorator/CorsDecorator.java
  core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/ChainedCorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsDecoratorFactoryFunction.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicy.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsPolicyBuilder.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsServiceBuilder.java
  core/src/main/java/com/linecorp/armeria/server/websocket/WebSocketServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
  core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceCorsTest.java
Labels: new feature

#5543 Introduce Java 9 module compatibility
  core/build.gradle
  gradle.properties
  gradle/scripts/README.md
  gradle/scripts/lib/common-info.gradle
  gradle/scripts/lib/java-shade.gradle
  gradle/scripts/lib/java.gradle
  gradle/scripts/lib/prerequisite.gradle
Labels: new feature

#5446 Add ServerErrorHandler to inject dependencies in annotations
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
  spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryTest.java
Labels: improvement

#5576 Update the project version to 1.28.0-SNAPSHOT
  gradle.properties
Labels: cleanup

#5381 Fix DocService to accept non JSON requests
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
  docs-client/src/containers/MethodPage/DebugPage.tsx
  docs-client/src/containers/MethodPage/GraphqlRequestBody.tsx
  docs-client/src/lib/json-util.ts
  docs-client/src/lib/transports/annotated-http.ts
  docs-client/src/lib/transports/grahpql-http.ts
  docs-client/src/lib/transports/grpc-unframed.ts
  docs-client/src/lib/transports/thrift.ts
  docs-client/src/lib/transports/transport.ts
Labels: defect

#5564 Add a stale bot
  .github/workflows/pr-stale.yml
Labels: miscellaneous

#5548 Improve incorrect cyclic redirect detection logic
  core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
  core/src/test/java/com/linecorp/armeria/client/RedirectSignatureTest.java
  core/src/test/java/com/linecorp/armeria/client/RedirectingClientTest.java
Labels: defect, sprint

#5554 Fix GrpcStatus for InvalidProtocolBufferException
  grpc/src/main/java/com/linecorp/armeria/internal/common/grpc/GrpcStatus.java
  grpc/src/test/java/com/linecorp/armeria/internal/common/grpc/GrpcStatusTest.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
  grpc/src/test/proto/testing/grpc/transcoding.proto
Labels: defect, sprint

#4227 Add flatMap method for collapsing streams into one
  core/src/main/java/com/linecorp/armeria/common/stream/FlatMapStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/FlatMapStreamMessageTest.java
Labels: new feature

#4863 Override `HttpRequestDecoder.createMessage()` for perfomance
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/server/ArmeriaHttpHeadersFactory.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerCodec.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerUpgradeHandler.java
  core/src/main/java/com/linecorp/armeria/server/NettyHttp1Headers.java
  core/src/main/java/com/linecorp/armeria/server/NettyHttp1Request.java
  core/src/main/java/com/linecorp/armeria/server/WebSocketServiceChannelHandler.java
  core/src/test/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/Http1ServerHeaderConvertTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerUpgradeHandlerTest.java
Labels: performance

#5584 Upgrade dependencies for 1.28.0
  build.gradle
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
  core/src/main/java/com/linecorp/armeria/internal/client/dns/DnsUtil.java
  core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
  dependencies.toml
  examples/grpc-krotodc/build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  sangria/sangria_2.13/src/main/scala/com/linecorp/armeria/server/sangria/SangriaGraphqlService.scala
  sangria/sangria_2.13/src/main/scala/com/linecorp/armeria/server/sangria/SangriaGraphqlServiceBuilder.scala
Labels: dependencies

#5573 Replace Optional with Spring's ObjectProvider to manage the optionali…
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/AbstractArmeriaAutoConfiguration.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactoryAutoConfiguration.java
Labels: improvement

#5002 Provide a way to automatically deserialize non-OK JSON response
  core/src/main/java/com/linecorp/armeria/client/AggregatedResponseAs.java
  core/src/main/java/com/linecorp/armeria/client/BlockingWebClientRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/client/JsonConditionalResponseAs.java
  core/src/main/java/com/linecorp/armeria/client/ResponseAs.java
  core/src/main/java/com/linecorp/armeria/client/ResponseAsUtil.java
  core/src/test/java/com/linecorp/armeria/client/AggregatedResponseAsTest.java
  core/src/test/java/com/linecorp/armeria/client/JsonConditionalResponseAsTest.java
Labels: new feature

#5469 Enhance route duplication detection by including param and header predicates
  core/src/main/java/com/linecorp/armeria/server/DefaultRoute.java
  core/src/main/java/com/linecorp/armeria/server/Route.java
  core/src/main/java/com/linecorp/armeria/server/Routers.java
  core/src/main/java/com/linecorp/armeria/server/RoutingPredicate.java
  core/src/test/java/com/linecorp/armeria/server/RouterTest.java
Labels: defect

#5591 Fix incorrect indentation in dependabot npm strategy
  .github/dependabot.yml
Labels: cleanup

#5588 Add release notes for 1.28.0
  site/src/pages/release-notes/1.28.0.mdx
Labels: documentation

#5172 Add a periodic check for cacheable task misses
  .github/workflows/gradle-cache-check.yml
Labels: cleanup

#5593 Close k8s client explicitly to avoid leak
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpHttpLoggingInterceptorTest.java
Labels: cleanup

#5598 Add lenient strictness to k8s test
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpHttpLoggingInterceptorTest.java
Labels: cleanup

#5602 CORS origin is checked in a case-insensitive manner
  core/src/main/java/com/linecorp/armeria/internal/server/websocket/DefaultWebSocketService.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsConfig.java
  core/src/main/java/com/linecorp/armeria/server/websocket/WebSocketServiceBuilder.java
  core/src/test/java/com/linecorp/armeria/server/cors/HttpServerCorsTest.java
  core/src/test/java/com/linecorp/armeria/server/websocket/WebSocketServiceCorsTest.java
Labels: defect

#5606 Bump brave from 6.0.2 to 6.0.3
  dependencies.toml
Labels: dependencies

#5609 Add release notes for 1.28.1
  site/src/pages/release-notes/1.28.1.mdx
Labels: documentation

#5555 Support custom json marshaller for unframed gRPC error
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandler.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlerBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlers.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorResponseType.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/ErrorDetailsMarshallerTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlerBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/UnframedGrpcErrorHandlerTest.java
Labels: new feature, sprint

#5614 Fixed bug where a request timeout is scheduled after receiving the entire body
  core/src/main/java/com/linecorp/armeria/internal/common/stream/AbstractFixedStreamMessage.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AggregatingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/EmptyContentDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
  core/src/test/java/com/linecorp/armeria/server/AggregatingRequestTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/server/ExceedingServiceMaxContentLengthTest.java
  jetty/jetty11/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  jetty/jetty12/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  jetty/jetty9/src/main/java/com/linecorp/armeria/server/jetty/JettyService.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlService.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/server/thrift/THttpService.java
  tomcat10/src/main/java/com/linecorp/armeria/server/tomcat/TomcatService.java
Labels: defect

#5615 Add the release note for 1.28.2
  site/src/pages/release-notes/1.28.2.mdx
Labels: documentation

#5600 Wait until buffers are released in `ExceedingServiceMaxContentLengthTest.maxContentLength`
  core/src/test/java/com/linecorp/armeria/server/ExceedingServiceMaxContentLengthTest.java
Labels: cleanup

#5586 Support `ResponseEntity` in annotated service instead of `HttpResult`
  core/src/main/java/com/linecorp/armeria/common/ResponseEntity.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedService.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/CompositeResponseConverterFunction.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/ResponseEntityUtil.java
  core/src/main/java/com/linecorp/armeria/server/annotation/HttpResult.java
  core/src/main/java/com/linecorp/armeria/server/annotation/ResponseConverterFunction.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceResponseConverterTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/ResponseEntityUtilTest.java
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/SuspendingAnnotatedServiceTest.kt
  rxjava2/src/test/java/com/linecorp/armeria/server/rxjava2/ObservableResponseConverterFunctionTest.java
  site/src/pages/docs/server-annotated-service.mdx
Labels: new feature, deprecation

#5562 Make @Description annotation at super class/interface work
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactory.java
  core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotationUtil.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceFactoryTest.java
Labels: defect

#5623 [Issue-5581] Change into transitive dependency(netty.transport.native.unix.common)
  core/build.gradle
Labels: defect, sprint

#5561 Add SchemeAndAuthority class which is in charge of authority normalization
  core/src/main/java/com/linecorp/armeria/client/Endpoint.java
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/ArmeriaHttpUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
  core/src/main/java/com/linecorp/armeria/internal/common/SchemeAndAuthority.java
  core/src/test/java/com/linecorp/armeria/client/EndpointTest.java
  core/src/test/java/com/linecorp/armeria/client/WebClientWithoutPortTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/SchemeAndAuthorityTest.java
Labels: cleanup

#5638 Ensure annotated service with Kotlin suspend function supports nullable parameters
  core/src/test/java/com/linecorp/armeria/common/logging/JsonLogFormatterTest.java
  kotlin/src/main/kotlin/com/linecorp/armeria/internal/common/kotlin/ArmeriaCoroutineUtil.kt
  kotlin/src/test/kotlin/com/linecorp/armeria/server/kotlin/NullableTypeSupportTest.kt
Labels: defect

#5640 Add the release note for 1.28.3
  site/src/pages/release-notes/1.28.3.mdx
Labels: documentation

#5643 Revert "Add Adrian Cole to the codeowners for the Brave module (#5458)"
  .github/CODEOWNERS
  .github/component_owners.yml
  .github/workflows/component-owners-action.yml
Labels: miscellaneous

#5649 Support LbSubsetFallbackPolicy.NO_FALLBACK
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterEntry.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterManager.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SubsetLoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointGroup.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/XdsConverterUtilTest.java
Labels: defect

#5650 Add the release note for 1.28.4
  site/src/pages/release-notes/1.28.4.mdx
Labels: documentation

#5648 Add recovery hook to outermost HttpResponse and fix DeferredStreamMessage
  core/src/main/java/com/linecorp/armeria/common/stream/CancellableStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/test/java/com/linecorp/armeria/server/RequestTimeoutTest.java
Labels: defect
