Repository line/armeria, pull requests merged in 2024-09, with the labels that each got.

#5896 Fix a bug where the parent's timeout is not cancelled in `RetryingClient`
  core/src/main/java/com/linecorp/armeria/internal/client/DefaultClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/internal/common/CancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultCancellationScheduler.java
  core/src/main/java/com/linecorp/armeria/internal/common/NoopCancellationScheduler.java
  core/src/test/java/com/linecorp/armeria/client/retry/RetryTimeoutCancellationTest.java
Labels: defect

#5899 Add release notes for 1.30.1
  site/src/pages/release-notes/1.30.1.mdx
Labels: documentation

#5865 chore: use markdown rather than HTML in README
  README.md
Labels: Stale

#5874 Use `DEBUG` to log `invalid authorization header` in `OAuth2TokenExtractor`
  core/src/main/java/com/linecorp/armeria/server/auth/OAuth2TokenExtractor.java
Labels: cleanup
