Repository line/armeria, pull requests merged in 2024-11, with the labels that each got.

#5954 Add missing static constructors to `ResponseEntity`
  core/src/main/java/com/linecorp/armeria/common/ResponseEntity.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceResponseConverterTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedServiceTest.java
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/ResponseEntityUtilTest.java
  rxjava3/src/test/java/com/linecorp/armeria/server/rxjava3/ObservableResponseConverterFunctionTest.java
Labels: breaking change

#5884 `ServerHttpResponse` sets the response `statusCode` correctly
  spring/boot2-webflux-autoconfigure/build.gradle
  spring/boot2-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/AbstractServerHttpResponseVersionSpecific.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/AbstractServerHttpResponse.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/AbstractServerHttpResponseVersionSpecific.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaHttpHandlerAdapter.java
  spring/boot3-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaServerHttpResponse.java
  spring/boot3-webflux-autoconfigure/src/test/java/com/linecorp/armeria/spring/web/reactive/ObservationTest.java
Labels: defect, Stale

#5946 Update GraalVM native image metadata
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/jni-config.json
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/reflect-config.json
  core/src/main/resources/META-INF/native-image/com.linecorp.armeria/armeria/resource-config.json
  native-image-config/build.gradle.kts
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftMetadataAccess.java
Labels: defect

#5938 Fixed `AsyncServerInterceptor` to be compatible with OpenTelmetry
  grpc/src/main/java/com/linecorp/armeria/server/grpc/ServerCallUtil.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/DeferredListenerTest.java
Labels: defect

#5761 Add StreamMessage.timeout()
  core/src/main/java/com/linecorp/armeria/client/RestClientPreparation.java
  core/src/main/java/com/linecorp/armeria/client/TransformingRequestPreparation.java
  core/src/main/java/com/linecorp/armeria/common/HttpRequest.java
  core/src/main/java/com/linecorp/armeria/common/HttpResponse.java
  core/src/main/java/com/linecorp/armeria/common/StreamTimeoutException.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/stream/StreamTimeoutMode.java
  core/src/main/java/com/linecorp/armeria/common/stream/TimeoutStreamMessage.java
  core/src/main/java/com/linecorp/armeria/common/websocket/WebSocket.java
  core/src/test/java/com/linecorp/armeria/common/stream/TimeoutStreamMessageTest.java
Labels: new feature

#5228 Provide a way to dynamically update TLS certificates
  benchmarks/jmh/src/jmh/java/com/linecorp/armeria/server/RoutersBenchmark.java
  build.gradle
  core/src/main/java/com/linecorp/armeria/client/AbstractClientOptionsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/Bootstraps.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/ClientTlsConfig.java
  core/src/main/java/com/linecorp/armeria/client/ClientTlsConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/client/HttpChannelPool.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/client/NullTlsProvider.java
  core/src/main/java/com/linecorp/armeria/common/AbstractTlsConfig.java
  core/src/main/java/com/linecorp/armeria/common/AbstractTlsConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/MappedTlsProvider.java
  core/src/main/java/com/linecorp/armeria/common/StaticTlsProvider.java
  core/src/main/java/com/linecorp/armeria/common/TlsKeyPair.java
  core/src/main/java/com/linecorp/armeria/common/TlsProvider.java
  core/src/main/java/com/linecorp/armeria/common/TlsProviderBuilder.java
  core/src/main/java/com/linecorp/armeria/common/TlsSetters.java
  core/src/main/java/com/linecorp/armeria/common/metric/AbstractCloseableMeterBinder.java
  core/src/main/java/com/linecorp/armeria/common/metric/CertificateMetrics.java
  core/src/main/java/com/linecorp/armeria/common/metric/CloseableMeterBinder.java
  core/src/main/java/com/linecorp/armeria/common/metric/EventLoopMetrics.java
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeterBinders.java
  core/src/main/java/com/linecorp/armeria/internal/common/IgnoreHostsTrustManager.java
  core/src/main/java/com/linecorp/armeria/internal/common/SslContextFactory.java
  core/src/main/java/com/linecorp/armeria/internal/common/TlsProviderUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/CertificateUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/KeyStoreUtil.java
  core/src/main/java/com/linecorp/armeria/internal/common/util/SslContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerSslContextUtil.java
  core/src/main/java/com/linecorp/armeria/server/ServerTlsConfig.java
  core/src/main/java/com/linecorp/armeria/server/ServerTlsConfigBuilder.java
  core/src/main/java/com/linecorp/armeria/server/TlsProviderMapping.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHost.java
  core/src/main/java/com/linecorp/armeria/server/VirtualHostBuilder.java
  core/src/test/java/com/linecorp/armeria/client/ClientTlsProviderBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientTlsProviderTest.java
  core/src/test/java/com/linecorp/armeria/client/IgnoreHostsTrustManagerTest.java
  core/src/test/java/com/linecorp/armeria/client/TlsProviderCacheTest.java
  core/src/test/java/com/linecorp/armeria/client/TlsProviderMTlsTest.java
  core/src/test/java/com/linecorp/armeria/client/TlsProviderTrustedCertificatesTest.java
  core/src/test/java/com/linecorp/armeria/client/proxy/ProxyClientIntegrationTest.java
  core/src/test/java/com/linecorp/armeria/internal/common/util/KeyStoreUtilTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTlsCertificateMetricsTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerTlsProviderTest.java
  core/src/test/java/com/linecorp/armeria/server/TlsProviderMappingTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostAnnotatedServiceBindingBuilderTest.java
  core/src/test/java/com/linecorp/armeria/server/VirtualHostBuilderTest.java
  it/builders/src/test/java/com/linecorp/armeria/OverriddenBuilderMethodsReturnTypeTest.java
  junit5/src/main/java/com/linecorp/armeria/internal/testing/SelfSignedCertificateRuleDelegate.java
  junit5/src/main/java/com/linecorp/armeria/testing/junit5/server/SelfSignedCertificateExtension.java
Labels: new feature

#5962 Avoid redundant fromObject(value) calls in addObject methods
  core/src/main/java/com/linecorp/armeria/common/StringMultimap.java
Labels: cleanup

#5939 Fix a bug where CORS headers are not injected when a `ServerErrorHandler` is set
  core/src/main/java/com/linecorp/armeria/internal/server/CorsHeaderUtil.java
  core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/cors/CorsService.java
  core/src/test/java/com/linecorp/armeria/server/cors/CorsServerErrorHandlerTest.java
  spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaSettingsConfigurationTest.java
Labels: defect

#5879 Allow `XdsEndpointGroup` to disable health checking per `Endpoint`
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/DefaultHealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckerContext.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/healthcheck/DefaultHttpHealthChecker.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/healthcheck/HttpHealthChecker.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/StaticHttpHealthChecker.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsHealthCheckedEndpointGroupBuilder.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/HealthCheckedTest.java
Labels: new feature

#5409 Add Nacos Support
  nacos/build.gradle.kts
  nacos/src/main/java/com/linecorp/armeria/client/nacos/NacosEndpointGroup.java
  nacos/src/main/java/com/linecorp/armeria/client/nacos/NacosEndpointGroupBuilder.java
  nacos/src/main/java/com/linecorp/armeria/client/nacos/package-info.java
  nacos/src/main/java/com/linecorp/armeria/common/nacos/NacosConfigSetters.java
  nacos/src/main/java/com/linecorp/armeria/common/nacos/package-info.java
  nacos/src/main/java/com/linecorp/armeria/internal/nacos/LoginClient.java
  nacos/src/main/java/com/linecorp/armeria/internal/nacos/NacosClient.java
  nacos/src/main/java/com/linecorp/armeria/internal/nacos/NacosClientBuilder.java
  nacos/src/main/java/com/linecorp/armeria/internal/nacos/NacosClientUtil.java
  nacos/src/main/java/com/linecorp/armeria/internal/nacos/QueryInstancesClient.java
  nacos/src/main/java/com/linecorp/armeria/internal/nacos/RegisterInstanceClient.java
  nacos/src/main/java/com/linecorp/armeria/internal/nacos/package-info.java
  nacos/src/main/java/com/linecorp/armeria/server/nacos/NacosUpdatingListener.java
  nacos/src/main/java/com/linecorp/armeria/server/nacos/NacosUpdatingListenerBuilder.java
  nacos/src/main/java/com/linecorp/armeria/server/nacos/package-info.java
  nacos/src/test/java/com/linecorp/armeria/client/nacos/NacosEndpointGroupBuilderTest.java
  nacos/src/test/java/com/linecorp/armeria/client/nacos/NacosEndpointGroupTest.java
  nacos/src/test/java/com/linecorp/armeria/internal/nacos/NacosClientBuilderTest.java
  nacos/src/test/java/com/linecorp/armeria/internal/nacos/NacosTestBase.java
  nacos/src/test/java/com/linecorp/armeria/server/nacos/NacosUpdatingListenerTest.java
  settings.gradle
Labels: new feature

#5963 Consider a trailing dot when resolve DNS with search domains
  core/src/main/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolver.java
  core/src/main/java/com/linecorp/armeria/internal/client/dns/DnsQuestionContext.java
  core/src/main/java/com/linecorp/armeria/internal/client/dns/SearchDomainDnsResolver.java
  core/src/test/java/com/linecorp/armeria/client/TrailingDotAddressResolverTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/dns/DefaultDnsResolverTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/dns/SearchDomainDnsResolverTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/dns/SearchDomainTest.java
Labels: defect

#5577 Support micrometer context-propagation
  dependencies.toml
  micrometer-context/build.gradle
  micrometer-context/src/main/java/com/linecorp/armeria/common/micrometer/context/RequestContextThreadLocalAccessor.java
  micrometer-context/src/main/java/com/linecorp/armeria/common/micrometer/context/package-info.java
  micrometer-context/src/test/java/com/linecorp/armeria/common/micrometer/context/RequestContextThreadLocalAccessorTest.java
  micrometer-context/src/test/java/com/linecorp/armeria/reactor3/RequestContextPropagationFluxTest.java
  micrometer-context/src/test/java/com/linecorp/armeria/reactor3/RequestContextPropagationMonoTest.java
  settings.gradle
Labels: new feature, sprint

#5967 Upgrade dependencies for 1.31.0
  .scalafmt.conf
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientExpect100HeaderTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerRequestPathEncodingTest.java
  dependencies.toml
  dropwizard2/src/test/java/com/linecorp/armeria/dropwizard/DropwizardArmeriaApplicationTest.java
  examples/dropwizard/src/test/java/example/dropwizard/DropwizardArmeriaApplicationTest.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  it/logback1.5/build.gradle
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpClientProxyTest.java
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpPostTest.java
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpPutTest.java
  scalapb/scalapb_3/src/main/scala/com/linecorp/armeria/common/scalapb/ScalaPbJsonMarshaller.scala
  scalapb/scalapb_3/src/main/scala/com/linecorp/armeria/server/scalapb/ScalaPbRequestConverterFunction.scala
  settings.gradle
  spring/boot3-autoconfigure/src/test/java/com/linecorp/armeria/spring/ArmeriaAutoConfigurationTest.java
  tomcat10/src/main/java/com/linecorp/armeria/server/tomcat/ArmeriaProcessor.java
  tomcat9/src/main/java/com/linecorp/armeria/server/tomcat/ArmeriaProcessor.java
  xds/src/test/java/com/linecorp/armeria/xds/MissingResourceTest.java
Labels: dependencies

#5932 Introduce rawPath in RequestTarget and ServiceRequestContext
  core/src/main/java/com/linecorp/armeria/common/AbstractRequestContextBuilder.java
  core/src/main/java/com/linecorp/armeria/common/RequestTarget.java
  core/src/main/java/com/linecorp/armeria/internal/common/DefaultRequestTarget.java
  core/src/main/java/com/linecorp/armeria/internal/server/DefaultServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/RoutingContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContext.java
  core/src/main/java/com/linecorp/armeria/server/ServiceRequestContextWrapper.java
  core/src/test/java/com/linecorp/armeria/internal/common/DefaultRequestTargetTest.java
  core/src/test/java/com/linecorp/armeria/server/RawPathTest.java
Labels: new feature

#5970 Add release note for 1.31.0
  dependencies.toml
  site/src/pages/release-notes/1.31.0.mdx
Labels: documentation

#5987 Fix failing nacos tests
  nacos/src/test/java/com/linecorp/armeria/internal/nacos/NacosClientBuilderTest.java
  nacos/src/test/java/com/linecorp/armeria/internal/nacos/NacosTestBase.java
Labels: cleanup

#5985 Introduce AccessLogWriterUtil and Remove Unnecessary RequestContext Push/Pop
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/AccessLogWriterUtil.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/logging/AccessLogWriter.java
  core/src/test/java/com/linecorp/armeria/server/logging/AccessLoggerIntegrationTest.java
Labels: improvement

#5986 Fix race condition where `log.whenComplete` may not complete
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultRequestLog.java
  core/src/main/java/com/linecorp/armeria/common/logging/RequestLogBuilder.java
  core/src/test/java/com/linecorp/armeria/common/logging/DefaultRequestLogTest.java
Labels: defect

#5994 Fix Jacoco failure
  settings.gradle
Labels: cleanup

#5992 Exclude protobuf 4.x from `armeria-grpc` module
  build.gradle
  gradle/scripts/.gitrepo
  gradle/scripts/lib/common-dependencies.gradle
  gradle/scripts/lib/java-shade.gradle
  grpc/build.gradle
Labels: defect

#5995 Release notes for 1.31.1
  dependencies.toml
  grpc/build.gradle
  site/src/pages/release-notes/1.31.1.mdx
Labels: documentation

#5998 Add the release note for 1.30.2
  site/src/pages/release-notes/1.30.2.mdx
Labels: documentation

#6000 Add manual button for publishing site
  .github/workflows/publish-site.yml
Labels: miscellaneous

#5916 Automatically register the metics of `PooledByteBufAllocator.DEFAULT`
  core/src/main/java/com/linecorp/armeria/common/metric/MoreMeterBinders.java
Labels: new feature

#5972 Fill the stack trace of `ResponseCompleteException` when sampled
  core/src/main/java/com/linecorp/armeria/common/ResponseCompleteException.java
Labels: defect
