Repository line/armeria, pull requests merged in 2025-07, with the labels that each got.

#6295 Developer guide: add clarification on copyright header
  site/src/pages/community/developer-guide.mdx
Labels: documentation

#6303 Add support for Thrift 0.22.0
  dependencies.toml
  settings.gradle
  thrift/thrift0.22/build.gradle
  thrift/thrift0.22/src/main/resources/com/linecorp/armeria/internal/common/thrift/thrift-options.properties
Labels: dependencies

#6310 (Thrift Field Masker Pt1) Remove redundant thrift files
  thrift/thrift0.12/build.gradle
  thrift/thrift0.12/src/test/thrift/RpcDebugTest.thrift
  thrift/thrift0.12/src/test/thrift/TTextProtocolTest.thrift
  thrift/thrift0.12/src/test/thrift/TreeStructTest.thrift
  thrift/thrift0.12/src/test/thrift/hbase.thrift
  thrift/thrift0.12/src/test/thrift/main.thrift
  thrift/thrift0.9/build.gradle
  thrift/thrift0.9/src/test/thrift/RpcDebugTest.thrift
  thrift/thrift0.9/src/test/thrift/TTextProtocolTest.thrift
  thrift/thrift0.9/src/test/thrift/TreeStructTest.thrift
  thrift/thrift0.9/src/test/thrift/hbase.thrift
  thrift/thrift0.9/src/test/thrift/main.thrift
Labels: cleanup

#6320 Fix bugs when validating xDS filter configuration
  dependencies.toml
  it/xds-client/build.gradle
  it/xds-client/src/test/java/com/linecorp/armeria/xds/it/EndpointCollectingDecorator.java
  it/xds-client/src/test/java/com/linecorp/armeria/xds/it/RoutingTest.java
  it/xds-client/src/test/java/com/linecorp/armeria/xds/it/XdsResourceReader.java
  settings.gradle
  xds/src/main/java/com/linecorp/armeria/xds/ParsedFilterConfig.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/FilterUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointUtil.java
Labels: defect

#6306 Migrate the ThankYou and Mailchimp components
  site-new/docs/index.mdx
  site-new/news/2020-07-03-newsletter-1.mdx
  site-new/news/2021-10-29-newsletter-3.mdx
  site-new/news/2022-07-14-newsletter-4.mdx
  site-new/news/2023-04-26-newsletter-5.mdx
  site-new/news/2023-12-08-newsletter-6.mdx
  site-new/package-lock.json
  site-new/package.json
  site-new/src/components/emoji.tsx
  site-new/src/components/mailchimp.module.css
  site-new/src/components/mailchimp.tsx
  site-new/src/components/thank-you.module.css
  site-new/src/components/thank-you.tsx
Labels: documentation

#6266 Ensure HTTP/2 flow control to work at the stream level
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/Http2ClientConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/common/DefaultFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  core/src/main/java/com/linecorp/armeria/common/FlagsProvider.java
  core/src/main/java/com/linecorp/armeria/common/SystemPropertyFlagsProvider.java
  core/src/main/java/com/linecorp/armeria/internal/client/DecodedHttpResponse.java
  core/src/main/java/com/linecorp/armeria/internal/common/InboundTrafficController.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2ServerConnectionHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/UpdatableServerConfig.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientFlowControlTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpResponseWrapperTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerFlowControlTest.java
  core/src/test/java/com/linecorp/armeria/server/HttpServerStreamingTest.java
  core/src/test/java/com/linecorp/armeria/server/StreamingDecodedHttpRequestTest.java
Labels: defect

#6325 feat: accept empty content body in HttpJsonTranscodingService
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
Labels: defect
