Repository line/armeria, pull requests merged in 2025-04, with the labels that each got.

#6166 Avoid leaking request contexts from server-side
  core/src/main/java/com/linecorp/armeria/client/AbstractHttpRequestHandler.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/Http2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/internal/common/HttpObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/AbstractHttpResponseSubscriber.java
  core/src/main/java/com/linecorp/armeria/server/AggregatedHttpResponseHandler.java
  core/src/main/java/com/linecorp/armeria/server/DecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp1ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/main/java/com/linecorp/armeria/server/StreamingDecodedHttpRequest.java
  core/src/main/java/com/linecorp/armeria/server/WebSocketServiceChannelHandler.java
  core/src/test/java/com/linecorp/armeria/server/RequestAbortLeakTest.java
Labels: defect

#6190 Fix duplicate endpoint handling in `HealthCheckedEndpointGroup`
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
Labels: defect

#6189 Add request context information to unexpected exception logs
  core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java
Labels: defect

#6192 Release notes for 1.32.4
  site/src/pages/release-notes/1.32.4.mdx
Labels: documentation

#6185 Exclude dependabot branches to avoid running the same tests twice.
  .github/workflows/actions_build.yml
Labels: cleanup

#6195 fix documents for client-thrift and client-entry
  site/src/pages/docs/client-retry.mdx
  site/src/pages/docs/client-thrift.mdx
Labels: cleanup

#6199 Improve URI comparison and validation in SAML components
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunction.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlEndpoint.java
  saml/src/main/java/com/linecorp/armeria/server/saml/SamlServiceProviderBuilder.java
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlAssertionConsumerFunctionTest.java
  saml/src/test/java/com/linecorp/armeria/server/saml/SamlEndpointTest.java
Labels: defect

#6202 Fixed a bug where the default setting for DNS over TCP was unintentionally disabled
  core/src/main/java/com/linecorp/armeria/client/AbstractDnsResolverBuilder.java
  core/src/test/java/com/linecorp/armeria/client/DnsOverTcpTest.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestTcpDnsServer.java
Labels: defect

#6205 Add the release note for 1.32.5
  site/src/pages/release-notes/1.32.5.mdx
Labels: documentation

#6060 Introduce `Preprocessor` based clients
  core/src/main/java/com/linecorp/armeria/client/AbstractWebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilderParams.java
  core/src/main/java/com/linecorp/armeria/client/ClientBuilderParamsBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/ClientPreprocessors.java
  core/src/main/java/com/linecorp/armeria/client/Clients.java
  core/src/main/java/com/linecorp/armeria/client/DecoratingClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/DefaultClientBuilderParams.java
  core/src/main/java/com/linecorp/armeria/client/DefaultWebClient.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientFactory.java
  core/src/main/java/com/linecorp/armeria/client/HttpPreprocessor.java
  core/src/main/java/com/linecorp/armeria/client/RedirectingClient.java
  core/src/main/java/com/linecorp/armeria/client/RestClient.java
  core/src/main/java/com/linecorp/armeria/client/RestClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/RpcPreprocessor.java
  core/src/main/java/com/linecorp/armeria/client/WebClient.java
  core/src/main/java/com/linecorp/armeria/client/WebClientBuilder.java
  core/src/main/java/com/linecorp/armeria/client/endpoint/EndpointGroup.java
  core/src/main/java/com/linecorp/armeria/client/websocket/WebSocketClientBuilder.java
  core/src/main/java/com/linecorp/armeria/common/Scheme.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientBuilderParamsUtil.java
  core/src/main/java/com/linecorp/armeria/internal/client/ClientUtil.java
  core/src/main/java/com/linecorp/armeria/internal/client/endpoint/UndefinedEndpointGroup.java
  core/src/test/java/com/linecorp/armeria/client/ClientBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/ClientFactoryBuilderTest.java
  core/src/test/java/com/linecorp/armeria/client/DefaultWebClientTest.java
  core/src/test/java/com/linecorp/armeria/client/DerivedClientTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpClientRequestPathTest.java
  core/src/test/java/com/linecorp/armeria/client/HttpPreprocessorTest.java
  core/src/test/java/com/linecorp/armeria/client/RestClientTest.java
  core/src/test/java/com/linecorp/armeria/client/WebClientAdditionalAuthorityTest.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupBuilder.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerBuilder.java
  eureka/src/test/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupTest.java
  eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
  grpc-protocol/src/main/java/com/linecorp/armeria/internal/client/grpc/protocol/UnaryGrpcClientFactory.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClientBuilder.java
  grpc/src/main/java/com/linecorp/armeria/client/grpc/GrpcClients.java
  grpc/src/main/java/com/linecorp/armeria/internal/client/grpc/GrpcClientFactory.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientBuilderTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcClientTest.java
  grpc/src/test/java/com/linecorp/armeria/client/grpc/GrpcServicePathTest.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofit.java
  retrofit2/src/main/java/com/linecorp/armeria/client/retrofit2/ArmeriaRetrofitBuilder.java
  retrofit2/src/test/java/com/linecorp/armeria/client/retrofit2/ArmeriaCallFactoryTest.java
  scala/scala_2.13/src/main/scala/com/linecorp/armeria/client/scala/ScalaRestClientFactory.scala
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/client/thrift/ThriftClientBuilder.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/client/thrift/ThriftClients.java
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/client/thrift/THttpClientFactory.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientBuilderTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientExchangeTypeTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/client/thrift/ThriftClientTest.java
Labels: new feature

#6206 Fix a memory leak in `DnsOverTcpTest`
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsMessageUtil.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TcpDnsQueryDecoder.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/TestTcpDnsServer.java
Labels: cleanup

#6210 Migrate components including TutorialSteps for the Documentation content
  site-new/docs/required-dependencies-test.mdx
  site-new/docs/server/decorator.mdx
  site-new/docs/setup.mdx
  site-new/docs/tutorials/rest/01-create-a-server.mdx
  site-new/docs/tutorials/rest/01-create-server.mdx
  site-new/docs/tutorials/rest/02-prepare-data-object.mdx
  site-new/docs/tutorials/rest/03-add-services-to-server.mdx
  site-new/docs/tutorials/rest/04-implement-create.mdx
  site-new/docs/tutorials/rest/05-implement-read.mdx
  site-new/docs/tutorials/rest/06-implement-update.mdx
  site-new/docs/tutorials/rest/07-implement-delete.mdx
  site-new/docusaurus.config.ts
  site-new/package-lock.json
  site-new/package.json
  site-new/sidebars.ts
  site-new/src/components/HomepageFeatures/index.tsx
  site-new/src/components/HomepageFeatures/styles.module.css
  site-new/src/components/api-link.module.css
  site-new/src/components/api-link.tsx
  site-new/src/components/aspect-ratio.module.css
  site-new/src/components/aspect-ratio.tsx
  site-new/src/components/max-width.tsx
  site-new/src/components/required-dependencies.tsx
  site-new/src/components/steps.tsx
  site-new/src/css/antd.css
  site-new/src/css/custom.css
  site-new/src/pages/index.module.css
  site-new/src/pages/index.tsx
  site-new/src/plugins/tutorial.ts
  site-new/src/theme/MDXComponents.ts
Labels: documentation

#6214 Rename LINE to LY in IDE settings
  settings/eclipse/cleanup.xml
  settings/eclipse/formatter.xml
  settings/intellij_idea/settings.jar
  site/src/pages/community/developer-guide.mdx
Labels: cleanup
