Repository line/armeria, pull requests merged in 2025-09, with the labels that each got.

#6366 Support retries for `XdsPreprocessor`
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/client/RefusedStreamException.java
  core/src/test/java/com/linecorp/armeria/client/Http2ClientRefusedStreamTest.java
  it/xds-client/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteEntryMatcherTest.java
  it/xds-client/src/test/java/com/linecorp/armeria/xds/it/RetryTest.java
  it/xds-client/src/test/java/com/linecorp/armeria/xds/it/RouteMatcherTest.java
  it/xds-client/src/test/java/com/linecorp/armeria/xds/it/TimeoutTest.java
  it/xds-client/src/test/java/com/linecorp/armeria/xds/it/VirtualHostRoutingTest.java
  xds/src/main/java/com/linecorp/armeria/xds/ListenerXdsResource.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ConfigSupplier.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/FilterUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/RetryStateFactory.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/RouteEntryMatcher.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/RouterFilter.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SelectedRoute.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsCommonUtil.java
Labels: new feature

#6382 Fix flaky `RetryingRpcClientTest.doNotRetryWhenResponseIsCancelled()`
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/it/client/retry/RetryingRpcClientTest.java
Labels: cleanup

#6395 `FileService` responds to `HEAD` range requests
  core/src/main/java/com/linecorp/armeria/server/file/FileService.java
  core/src/test/java/com/linecorp/armeria/server/file/FileServiceTest.java
Labels: defect

#6414 Fix race condition causing incomplete client logs on abort
  core/src/main/java/com/linecorp/armeria/client/HttpResponseWrapper.java
  core/src/test/java/com/linecorp/armeria/client/RequestLogCompleteTest.java
Labels: defect

#6413 Fix deadlock between Flags and RequestContextUtil static initialization
  core/src/main/java/com/linecorp/armeria/common/Flags.java
  it/flags-cyclic-dep/src/test/java/com/linecorp/armeria/common/FlagsCyclicDependencyTest.java
  it/flags-cyclic-dep/src/test/resources/logback-test.xml
Labels: defect

#6418 Add the release note for 1.33.4
  .github/workflows/publish-release.yml
  dependencies.toml
  site/src/pages/release-notes/1.33.4.mdx
Labels: documentation
