Repository line/armeria, pull requests merged in 2025-03, with the labels that each got.

#6082 Provide a way to ignore `json_name` in HTTP/JSON transcoding
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingOptionsBuilder.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingQueryParamMatchRule.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/java/com/linecorp/armeria/it/grpc/HttpJsonTranscodingTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcTranscodingJsonNameTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingOptionsBuilderTest.java
  grpc/src/test/proto/testing/grpc/transcoding.proto
  grpc/src/test/proto/testing/grpc/transcoding_json_name.proto
Labels: defect, breaking change

#6069 Set Eureka InstanceInfo to endpoint attribute
  eureka/src/main/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroup.java
  eureka/src/main/java/com/linecorp/armeria/common/eureka/DataCenterInfo.java
  eureka/src/main/java/com/linecorp/armeria/common/eureka/InstanceInfo.java
  eureka/src/main/java/com/linecorp/armeria/common/eureka/LeaseInfo.java
  eureka/src/main/java/com/linecorp/armeria/common/eureka/package-info.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/Application.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/DataCenterInfoSerializer.java
  eureka/src/main/java/com/linecorp/armeria/internal/common/eureka/EurekaWebClient.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListener.java
  eureka/src/main/java/com/linecorp/armeria/server/eureka/InstanceInfoBuilder.java
  eureka/src/test/java/com/linecorp/armeria/client/eureka/ArmeriaEurekaClientTest.java
  eureka/src/test/java/com/linecorp/armeria/client/eureka/EurekaEndpointGroupTest.java
  eureka/src/test/java/com/linecorp/armeria/common/eureka/InstanceInfoTest.java
  eureka/src/test/java/com/linecorp/armeria/server/eureka/EurekaUpdatingListenerTest.java
Labels: new feature

#6116 Add port tag to server metrics
  core/src/main/java/com/linecorp/armeria/server/ConnectionLimitingHandler.java
  core/src/main/java/com/linecorp/armeria/server/DefaultServerConfig.java
  core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerHandler.java
  core/src/main/java/com/linecorp/armeria/server/HttpServerPipelineConfigurator.java
  core/src/main/java/com/linecorp/armeria/server/Server.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerMetrics.java
  core/src/main/java/com/linecorp/armeria/server/ServerPort.java
  core/src/main/java/com/linecorp/armeria/server/ServerPortMetric.java
  core/src/test/java/com/linecorp/armeria/server/ConnectionLimitingHandlerTest.java
  core/src/test/java/com/linecorp/armeria/server/ServerMetricsTest.java
Labels: improvement

#6127 Expose experimental settings for dns
  core/src/main/java/com/linecorp/armeria/client/AbstractDnsResolverBuilder.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/dns/DnsAddressEndpointGroupTest.java
Labels: new feature

#6042 Fix Missing Use of `SuccessFunction` in Determining Response Success for Log Levels
  core/src/main/java/com/linecorp/armeria/common/logging/DefaultLogWriter.java
  core/src/main/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapper.java
  core/src/test/java/com/linecorp/armeria/client/logging/LoggingClientTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/LoggingDecoratorBuilderTest.java
  core/src/test/java/com/linecorp/armeria/common/logging/ResponseLogLevelMapperTest.java
  core/src/test/java/com/linecorp/armeria/server/healthcheck/HealthCheckServiceTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/LoggingServiceTest.java
Labels: defect, Stale

#6107 Include `ConnectTimeoutException` in timeout exceptions for rules
  core/src/main/java/com/linecorp/armeria/client/AbstractRuleBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientRequestContext.java
  core/src/main/java/com/linecorp/armeria/client/TimeoutExceptionPredicate.java
  core/src/test/java/com/linecorp/armeria/client/TimeoutExceptionPredicateTest.java
Labels: defect

#6121 Expose `CorsPolicyBuilder#build`
  core/src/main/java/com/linecorp/armeria/server/cors/AbstractCorsPolicyBuilder.java
  core/src/test/java/com/linecorp/armeria/server/cors/test/CorsBuilderTest.java
Labels: defect

#6111 Provide a way to reject IP addresses in the client side
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryBuilder.java
  core/src/main/java/com/linecorp/armeria/client/ClientFactoryOptions.java
  core/src/main/java/com/linecorp/armeria/client/HttpClientDelegate.java
  core/src/main/java/com/linecorp/armeria/common/IpAddressRejectedException.java
  core/src/test/java/com/linecorp/armeria/client/IpFilterTest.java
Labels: new feature

#6125 Update dependencies
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/common/MediaType.java
  core/src/main/java/com/linecorp/armeria/common/MediaTypeNames.java
  core/src/test/java/com/linecorp/armeria/common/multipart/MultipartDecoderTest.java
  dependencies.toml
  gradle/scripts/lib/java-rpc-proto.gradle
  grpc/src/main/java/com/linecorp/armeria/server/grpc/GrpcServiceBuilder.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/GrpcServiceServerTest.java
  retrofit2/build.gradle
  spring/spring6/src/test/java/com/linecorp/armeria/spring/client/ArmeriaHttpExchangeAdapterTest.java
Labels: dependencies

#6126 Add handling for cookies with the same name to `DefaultCookieJar`
  core/src/main/java/com/linecorp/armeria/client/cookie/DefaultCookieJar.java
  core/src/test/java/com/linecorp/armeria/client/cookie/DefaultCookieJarTest.java
Labels: defect

#6135 Improve compatibility with protobuf-java v4
  dependencies.toml
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  it/grpc/protobuf4/build.gradle
  it/grpc/protobuf4/src/test/proto/com/linecorp/armeria/grpc/testing/error.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/docservice_prefix.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/empty.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/flow.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/messages.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/metrics.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/options.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/proto2.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/proto3.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/proto3_importing_proto2.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/test.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/transcoding.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/transcoding_json_name.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/verb.proto
  settings.gradle
Labels: dependencies

#6138 Support SLF4J 2.0.17 MDC Adapter Field Change
  core/src/main/java/com/linecorp/armeria/common/logging/RequestScopedMdc.java
  dependencies.toml
  it/logback1.4/build.gradle.kts
Labels: defect, dependencies

#6155 Fix `:docs-client` devloop issues and update deps
  build.gradle
  core/src/test/java/com/linecorp/armeria/internal/server/annotation/AnnotatedDocServiceTest.java
  docs-client/package-lock.json
  docs-client/package.json
  docs-client/webpack.config.ts
  graphql/src/test/java/com/linecorp/armeria/internal/server/graphql/GraphqlDocServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServiceTest.java
  licenses/web-licenses.txt
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/DocServiceExtension.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServiceTest.java
Labels: cleanup

#6148 Register EventLoop as a Non-Blocking Thread in Reactor Scheduler 3.7.0+
  core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroup.java
  core/src/main/java/com/linecorp/armeria/common/CommonPools.java
Labels: defect

#6150 Fix Incorrect Calculation of Cumulative Demand in Duplicator
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessageDuplicator.java
  core/src/main/java/com/linecorp/armeria/common/stream/DeferredStreamMessage.java
  core/src/main/java/com/linecorp/armeria/internal/common/SplitHttpMessageSubscriber.java
  core/src/test/java/com/linecorp/armeria/common/stream/DuplicatorCumulativeDemandTest.java
  core/src/test/java/com/linecorp/armeria/server/GracefulShutdownBuilderTest.java
Labels: defect

#6157 Do not send RST_STREAM when UnprocessedRequestException is raised
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/test/java/com/linecorp/armeria/client/HeaderListSizeExceptionTest.java
Labels: defect

#6147 Prioritize Binding of Services with Custom Verbs in HttpJsonTranscodi…
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingRouteAndPathVariables.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingServiceTest.java
  grpc/src/test/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingVerbServiceBindingTest.java
  grpc/src/test/proto/testing/grpc/transcoding_custom_verb.proto
  it/grpc/protobuf4/src/test/proto/testing/grpc/transcoding_custom_verb.proto
Labels: defect

#6153 Add optional info for google.proto types
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePlugin.java
  grpc/src/main/java/com/linecorp/armeria/internal/server/grpc/HttpEndpointSpecification.java
  grpc/src/main/java/com/linecorp/armeria/server/grpc/HttpJsonTranscodingService.java
  grpc/src/test/java/com/linecorp/armeria/internal/server/grpc/GrpcDocServicePluginTest.java
  grpc/src/test/proto/testing/grpc/transcoding.proto
Labels: defect

#6151 Add the release note for 1.32.1
  site/src/pages/release-notes/1.32.1.mdx
Labels: documentation

#6144 Define the structure of the Documentation content
  site-new/community/articles.mdx
  site-new/community/code-of-conduct.mdx
  site-new/community/design-resources.mdx
  site-new/community/developer-guide.mdx
  site-new/community/index.mdx
  site-new/docs/advanced/logging.mdx
  site-new/docs/api-link-test.mdx
  site-new/docs/client/http.mdx
  site-new/docs/index.mdx
  site-new/docs/server/basics.mdx
  site-new/docs/server/decorator.mdx
  site-new/docs/tutorials/grpc/01-define-a-service.mdx
  site-new/docs/tutorials/grpc/index.mdx
  site-new/docs/tutorials/index.mdx
  site-new/docs/tutorials/rest/01-create-a-server.mdx
  site-new/docs/tutorials/rest/index.mdx
  site-new/docs/tutorials/thrift/01-define-a-service.mdx
  site-new/docs/tutorials/thrift/index.mdx
  site-new/docusaurus.config.ts
  site-new/sidebars.ts
  site-new/sidebarsCommunity.ts
  site-new/src/components/api-link.module.less
  site-new/src/css/custom.less
Labels: documentation

#6159 Use namespace when retreiving k8s services
  kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
Labels: defect

#6160 Add the release note for 1.32.2
  site/src/pages/release-notes/1.32.2.mdx
Labels: documentation

#6161 Prevent the old `Watcher`s from updating endpoints in `KubernetesEndointGroup`
  kubernetes/src/main/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroup.java
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/endpoints/KubernetesEndpointGroupMockServerTest.java
Labels: defect

#6164 Add the release note for 1.32.3
  site/src/pages/release-notes/1.32.3.mdx
Labels: documentation

#6146 fixes customizer logic in the GsonGrpcJsonMarshallerBuilder
  grpc/src/main/java/com/linecorp/armeria/common/grpc/GsonGrpcJsonMarshallerBuilder.java
  grpc/src/test/java/com/linecorp/armeria/common/grpc/GsonGrpcJsonMarshallerBuilderTest.java
Labels: new feature, deprecation

#6171 Fix flaky tests using `Awaitility.await().untilAsserted()`
  core/src/test/java/com/linecorp/armeria/common/multipart/MultipartDecoderTest.java
Labels: cleanup

#6097 Introduce `AbstractAsyncSelector`
  core/src/main/java/com/linecorp/armeria/client/endpoint/AbstractEndpointSelector.java
  core/src/main/java/com/linecorp/armeria/internal/client/AbstractAsyncSelector.java
  core/src/test/java/com/linecorp/armeria/client/endpoint/SelectionTimeoutTest.java
  core/src/test/java/com/linecorp/armeria/internal/client/AbstractAsyncSelectorTest.java
Labels: improvement, Stale

#6174 Remove DnsCacheListener from DnsCache when resolver is closed
  core/src/main/java/com/linecorp/armeria/client/DefaultDnsCache.java
  core/src/main/java/com/linecorp/armeria/client/DnsCache.java
  core/src/main/java/com/linecorp/armeria/client/RefreshingAddressResolver.java
  core/src/test/java/com/linecorp/armeria/client/NoopDnsCache.java
  core/src/test/java/com/linecorp/armeria/client/RefreshingAddressResolverTest.java
Labels: defect

#6105 Introduce virtual host snapshots
  xds/src/main/java/com/linecorp/armeria/xds/ClusterResourceNode.java
  xds/src/main/java/com/linecorp/armeria/xds/ClusterRoot.java
  xds/src/main/java/com/linecorp/armeria/xds/ClusterSnapshot.java
  xds/src/main/java/com/linecorp/armeria/xds/CompositeXdsStream.java
  xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceMapper.java
  xds/src/main/java/com/linecorp/armeria/xds/ListenerRoot.java
  xds/src/main/java/com/linecorp/armeria/xds/RouteEntry.java
  xds/src/main/java/com/linecorp/armeria/xds/RouteResourceNode.java
  xds/src/main/java/com/linecorp/armeria/xds/RouteSnapshot.java
  xds/src/main/java/com/linecorp/armeria/xds/SotwXdsStream.java
  xds/src/main/java/com/linecorp/armeria/xds/StaticResourceUtils.java
  xds/src/main/java/com/linecorp/armeria/xds/VirtualHostResourceNode.java
  xds/src/main/java/com/linecorp/armeria/xds/VirtualHostSnapshot.java
  xds/src/main/java/com/linecorp/armeria/xds/VirtualHostXdsResource.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsType.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterEntry.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterManager.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/DefaultLoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/MetadataUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SubsetLoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsAttributeKeys.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsLoadBalancer.java
  xds/src/test/java/com/linecorp/armeria/xds/AggregatingNodeTest.java
  xds/src/test/java/com/linecorp/armeria/xds/DynamicResourcesTest.java
  xds/src/test/java/com/linecorp/armeria/xds/MostlyStaticWithDynamicEdsTest.java
  xds/src/test/java/com/linecorp/armeria/xds/MultiConfigSourceTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/ZoneAwareTest.java
Labels: improvement

#6168 Handle a race condition where `onSubscribe` may be emitted downstream after `onError`
  core/src/main/java/com/linecorp/armeria/common/stream/DefaultStreamMessage.java
  core/src/test/java/com/linecorp/armeria/common/stream/DefaultStreamMessageTest.java
Labels: defect
