Repository line/armeria, pull requests merged in 2025-06, with the labels that each got.

#6248 Remove assumption that namespace always exists for thrift docs
  thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/server/thrift/ThriftDocStringExtractor.java
Labels: defect

#6254 Add support for Thrift 0.21.0
  dependencies.toml
  gradle/scripts/.gitrepo
  gradle/scripts/README.md
  gradle/scripts/lib/common-git.gradle
  gradle/scripts/lib/kotlin.gradle
  gradle/scripts/lib/thrift/0.21/thrift.linux-aarch_64
  gradle/scripts/lib/thrift/0.21/thrift.linux-x86_64
  gradle/scripts/lib/thrift/0.21/thrift.osx-aarch_64
  gradle/scripts/lib/thrift/0.21/thrift.osx-x86_64
  gradle/scripts/lib/thrift/0.21/thrift.windows-x86_64.exe
  gradle/scripts/lib/thrift/0.22/thrift.linux-aarch_64
  gradle/scripts/lib/thrift/0.22/thrift.linux-x86_64
  gradle/scripts/lib/thrift/0.22/thrift.osx-aarch_64
  gradle/scripts/lib/thrift/0.22/thrift.osx-x86_64
  gradle/scripts/lib/thrift/0.22/thrift.windows-x86_64.exe
  gradle/scripts/lib/thrift/dockerfile/Dockerfile.bionic
  gradle/scripts/lib/thrift/dockerfile/Dockerfile.centos7
  gradle/scripts/lib/thrift/dockerfile/Dockerfile.trusty
  it/thrift0.9.1/src/test/thrift/cassandra.thrift
  settings.gradle
  thrift/thrift0.12/src/test/thrift/cassandra.thrift
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocServiceTest.java
  thrift/thrift0.13/src/test/java/com/linecorp/armeria/internal/server/thrift/ThriftDocStringExtractorTest.java
  thrift/thrift0.13/src/test/resources/META-INF/armeria/thrift/cassandra.json
  thrift/thrift0.13/src/test/thrift/cassandra.thrift
  thrift/thrift0.21/build.gradle
  thrift/thrift0.21/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java
  thrift/thrift0.21/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftServiceMetadata.java
  thrift/thrift0.21/src/main/java/com/linecorp/armeria/internal/common/thrift/package-info.java
  thrift/thrift0.21/src/main/java/com/linecorp/armeria/server/thrift/ThriftCallService.java
  thrift/thrift0.21/src/main/java/com/linecorp/armeria/server/thrift/package-info.java
  thrift/thrift0.21/src/main/resources/com/linecorp/armeria/internal/common/thrift/thrift-options.properties
  thrift/thrift0.9/src/test/thrift/cassandra.thrift
Labels: dependencies

#6271 Bump up kubernetes-client version to 7.3.1 and use Java 11 on kubernetes module
  dependencies.toml
  it/kubernetes-chaos-tests/build.gradle
  kubernetes/src/test/java/com/linecorp/armeria/client/kubernetes/ArmeriaHttpClientProxyTest.java
  settings.gradle
Labels: defect, dependencies

#6279 Server doesn't send a `RST_STREAM` frame after `endStream` is sent
  core/src/main/java/com/linecorp/armeria/client/Http2ResponseDecoder.java
  core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java
  core/src/test/java/com/linecorp/armeria/server/Http2ResetStreamTest.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/NettyServerExtension.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/netty/Http2ClientFrameInitializer.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/netty/HttpFrameAggregator.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/netty/SimpleHttp2Connection.java
  testing-internal/src/main/java/com/linecorp/armeria/internal/testing/netty/package-info.java
Labels: defect

#6288 `XdsLoadBalancer` is managed by `XdsClusterManager`
  xds/src/main/java/com/linecorp/armeria/xds/AbstractRoot.java
  xds/src/main/java/com/linecorp/armeria/xds/BootstrapClusters.java
  xds/src/main/java/com/linecorp/armeria/xds/ClusterResourceNode.java
  xds/src/main/java/com/linecorp/armeria/xds/ClusterSnapshot.java
  xds/src/main/java/com/linecorp/armeria/xds/ClusterXdsResource.java
  xds/src/main/java/com/linecorp/armeria/xds/ConfigSourceClient.java
  xds/src/main/java/com/linecorp/armeria/xds/GrpcServicesPreprocessor.java
  xds/src/main/java/com/linecorp/armeria/xds/StaticResourceUtils.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsBootstrapImpl.java
  xds/src/main/java/com/linecorp/armeria/xds/XdsClusterManager.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/AttributesPool.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterEntry.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/ClusterManager.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/DefaultLoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/DefaultXdsLoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/EndpointsPool.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/LoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/LocalCluster.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/MetadataUtil.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/SubsetLoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/UpdatableXdsLoadBalancer.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsAttributeKeys.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointGroup.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsEndpointSelector.java
  xds/src/main/java/com/linecorp/armeria/xds/client/endpoint/XdsLoadBalancer.java
  xds/src/test/java/com/linecorp/armeria/xds/MostlyStaticWithDynamicEdsTest.java
  xds/src/test/java/com/linecorp/armeria/xds/MultiConfigSourceTest.java
  xds/src/test/java/com/linecorp/armeria/xds/ResourceWatcherTest.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestResources.java
  xds/src/test/java/com/linecorp/armeria/xds/XdsTestUtil.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/DynamicHealthCheckTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/HealthCheckedTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/LocalityTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/PriorityTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RampingUpTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/RouteMetadataSubsetTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/StrictDnsIntegrationTest.java
  xds/src/test/java/com/linecorp/armeria/xds/client/endpoint/ZoneAwareTest.java
Labels: improvement
