Repository line/armeria, pull requests merged in 2025-08, with the labels that each got.

#6328 Add option to force reload values in `AsyncLoader`
  core/src/main/java/com/linecorp/armeria/common/util/AsyncLoader.java
  core/src/main/java/com/linecorp/armeria/common/util/AsyncLoaderBuilder.java
  core/src/main/java/com/linecorp/armeria/common/util/DefaultAsyncLoader.java
  core/src/test/java/com/linecorp/armeria/common/util/DefaultAsyncLoaderTest.java
  nacos/src/main/java/com/linecorp/armeria/internal/nacos/LoginClient.java
Labels: new feature

#6338 Exclude `SslContext.buildKeyStore()` from BlockHound reports
  core/src/main/java/com/linecorp/armeria/common/CoreBlockHoundIntegration.java
Labels: cleanup

#6269 Set response content preview after recovering failed responses
  core/src/main/java/com/linecorp/armeria/internal/logging/ContentPreviewingUtil.java
  core/src/main/java/com/linecorp/armeria/server/ContentPreviewServerErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/CorsServerErrorHandler.java
  core/src/main/java/com/linecorp/armeria/server/DecoratingServerErrorHandlerFunction.java
  core/src/main/java/com/linecorp/armeria/server/ServerBuilder.java
  core/src/main/java/com/linecorp/armeria/server/ServerErrorHandlerDecorators.java
  core/src/main/java/com/linecorp/armeria/server/logging/ContentPreviewingService.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingErrorResponseTest.java
  core/src/test/java/com/linecorp/armeria/server/logging/ContentPreviewingServiceTest.java
Labels: new feature

#6342 Use OSSRH Staging API to publish artifacts
  gradle.properties
Labels: miscellaneous

#6341 Support `Athenz-Role-Auth` header in Athenz module
  athenz/src/main/java/com/linecorp/armeria/client/athenz/AthenzClient.java
  athenz/src/main/java/com/linecorp/armeria/common/athenz/TokenType.java
  athenz/src/main/java/com/linecorp/armeria/internal/common/athenz/AthenzHeaderNames.java
  athenz/src/main/java/com/linecorp/armeria/server/athenz/RequiresAthenzRole.java
  athenz/src/test/java/com/linecorp/armeria/common/athenz/TokenTypeTest.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzAnnotatedServiceTest.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzIntegrationTest.java
Labels: defect

#6347 Add Athenz documentation and example
  athenz/src/test/java/com/linecorp/armeria/client/athenz/AccessTokenClientTest.java
  athenz/src/test/java/com/linecorp/armeria/client/athenz/RoleTokenClientTest.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzAnnotatedServiceTest.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzDocker.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzExtension.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzIntegrationTest.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzInvalidPolicyDataTest.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzPolicyLoaderTest.java
  core/src/test/java12/com/linecorp/armeria/server/JavaHttpClientUpgradeTest.java
  dependencies.toml
  examples/athenz/build.gradle
  examples/athenz/src/main/java/example/armeria/athenz/GrpcServiceImpl.java
  examples/athenz/src/main/java/example/armeria/athenz/Main.java
  examples/athenz/src/main/java/example/armeria/athenz/RestServiceImpl.java
  examples/athenz/src/main/proto/hello.proto
  examples/athenz/src/test/java/example/armeria/athenz/AthenzTest.java
  gradle.properties
  settings.gradle
  site/src/pages/docs/advanced-athenz.mdx
  site/src/pages/docs/toc.json
  site/src/pages/release-notes/1.33.0.mdx
Labels: documentation

#6353 Bump Netty to 4.2.4 from 4.2.3
  dependencies.toml
Labels: dependencies

#6348 Integrate Athenz with Spring Boot auto-configuration
  athenz/src/main/java/com/linecorp/armeria/common/athenz/TokenType.java
  athenz/src/main/java/com/linecorp/armeria/internal/common/athenz/package-info.java
  athenz/src/main/java/com/linecorp/armeria/internal/server/athenz/AthenzServiceDecoratorFactoryProvider.java
  athenz/src/main/java/com/linecorp/armeria/internal/server/athenz/package-info.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzExtension.java
  athenz/src/test/java/com/linecorp/armeria/server/athenz/AthenzIntegrationTest.java
  core/src/main/java/com/linecorp/armeria/common/HttpHeaderNames.java
  core/src/main/java/com/linecorp/armeria/common/logging/AbstractHeadersSanitizerBuilder.java
  examples/athenz/src/test/java/example/armeria/athenz/AthenzTest.java
  it/spring/boot3-athenz/build.gradle
  it/spring/boot3-athenz/src/main/java/com/linecorp/armeria/spring/athenz/SimpleFileService.java
  it/spring/boot3-athenz/src/main/java/com/linecorp/armeria/spring/athenz/SpringAthenzMain.java
  it/spring/boot3-athenz/src/main/java/com/linecorp/armeria/spring/athenz/TestDecorator.java
  it/spring/boot3-athenz/src/test/java/com/linecorp/armeria/spring/athenz/AthenzSpringBootTest.java
  it/spring/boot3-athenz/src/test/resources/config/application-athenzTest.yml
  settings.gradle
  site/src/pages/docs/advanced-athenz.mdx
  spring/boot2-webflux-autoconfigure/build.gradle
  spring/boot3-actuator-autoconfigure/build.gradle
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/ArmeriaConfigurationUtil.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/internal/spring/AthenzSupport.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/ArmeriaSettings.java
  spring/boot3-autoconfigure/src/main/java/com/linecorp/armeria/spring/AthenzConfig.java
  spring/boot3-webflux-autoconfigure/build.gradle
Labels: new feature

#6350 Add release notes for 1.33.1
  site/src/pages/release-notes/1.33.0.mdx
  site/src/pages/release-notes/1.33.1.mdx
Labels: documentation

#6358 Update the athenz test certificates for admin role
  athenz/src/test/resources/docker/certs/domain-admin/cert.pem
  athenz/src/test/resources/docker/certs/domain-admin/key.pem
Labels: cleanup

#6374 Add release notes for 1.33.2
  site/src/pages/release-notes/1.33.1.mdx
  site/src/pages/release-notes/1.33.2.mdx
Labels: documentation
